// ReSharper disable All
using Moonfish.Model;
using Moonfish.Tags.BlamExtension;
using Moonfish.Tags;
using OpenTK;
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

namespace Moonfish.Tags
{
    public partial struct TagClass
    {
        public static readonly TagClass Whip = (TagClass)"whip";
    };
};

namespace Moonfish.Guerilla.Tags
{
    [TagClassAttribute("whip")]
    public partial class CellularAutomata2dBlock : CellularAutomata2dBlockBase
    {
        public CellularAutomata2dBlock() : base()
        {
        }
    };
    [LayoutAttribute(Size = 544, Alignment = 4)]
    public class CellularAutomata2dBlockBase : GuerillaBlock
    {
        internal short updatesPerSecondHz;
        internal byte[] invalidName_;
        internal float deadCellPenalty;
        internal float liveCellBonus;
        internal byte[] invalidName_0;
        internal short widthCells;
        internal short heightCells;
        internal float cellWidthWorldUnits;
        internal float heightWorldUnits;
        internal OpenTK.Vector2 velocityCellsUpdate;
        internal byte[] invalidName_1;
        internal Moonfish.Tags.StringIdent marker;
        internal InterpolationFlags interpolationFlags;
        internal Moonfish.Tags.ColourR8G8B8 baseColor;
        internal Moonfish.Tags.ColourR8G8B8 peakColor;
        internal byte[] invalidName_2;
        internal short widthCells0;
        internal short heightCells0;
        internal float cellWidthWorldUnits0;
        internal OpenTK.Vector2 velocityCellsUpdate0;
        internal byte[] invalidName_3;
        internal Moonfish.Tags.StringIdent marker0;
        internal short textureWidthCells;
        internal byte[] invalidName_4;
        internal byte[] invalidName_5;
        [TagReference("bitm")]
        internal Moonfish.Tags.TagReference texture;
        internal byte[] invalidName_6;
        internal RulesBlock[] rules;
        public override int SerializedSize { get { return 544; } }
        public override int Alignment { get { return 4; } }
        public CellularAutomata2dBlockBase() : base()
        {
        }
        public override Queue<BlamPointer> ReadFields(BinaryReader binaryReader)
        {
            var blamPointers = new Queue<BlamPointer>(base.ReadFields(binaryReader));
            updatesPerSecondHz = binaryReader.ReadInt16();
            invalidName_ = binaryReader.ReadBytes(2);
            deadCellPenalty = binaryReader.ReadSingle();
            liveCellBonus = binaryReader.ReadSingle();
            invalidName_0 = binaryReader.ReadBytes(80);
            widthCells = binaryReader.ReadInt16();
            heightCells = binaryReader.ReadInt16();
            cellWidthWorldUnits = binaryReader.ReadSingle();
            heightWorldUnits = binaryReader.ReadSingle();
            velocityCellsUpdate = binaryReader.ReadVector2();
            invalidName_1 = binaryReader.ReadBytes(28);
            marker = binaryReader.ReadStringID();
            interpolationFlags = (InterpolationFlags)binaryReader.ReadInt32();
            baseColor = binaryReader.ReadColorR8G8B8();
            peakColor = binaryReader.ReadColorR8G8B8();
            invalidName_2 = binaryReader.ReadBytes(76);
            widthCells0 = binaryReader.ReadInt16();
            heightCells0 = binaryReader.ReadInt16();
            cellWidthWorldUnits0 = binaryReader.ReadSingle();
            velocityCellsUpdate0 = binaryReader.ReadVector2();
            invalidName_3 = binaryReader.ReadBytes(48);
            marker0 = binaryReader.ReadStringID();
            textureWidthCells = binaryReader.ReadInt16();
            invalidName_4 = binaryReader.ReadBytes(2);
            invalidName_5 = binaryReader.ReadBytes(48);
            texture = binaryReader.ReadTagReference();
            invalidName_6 = binaryReader.ReadBytes(160);
            blamPointers.Enqueue(ReadBlockArrayPointer<RulesBlock>(binaryReader));
            return blamPointers;
        }
        public override void ReadPointers(BinaryReader binaryReader, Queue<BlamPointer> blamPointers)
        {
            base.ReadPointers(binaryReader, blamPointers);
            invalidName_[0].ReadPointers(binaryReader, blamPointers);
            invalidName_[1].ReadPointers(binaryReader, blamPointers);
            invalidName_0[0].ReadPointers(binaryReader, blamPointers);
            invalidName_0[1].ReadPointers(binaryReader, blamPointers);
            invalidName_0[2].ReadPointers(binaryReader, blamPointers);
            invalidName_0[3].ReadPointers(binaryReader, blamPointers);
            invalidName_0[4].ReadPointers(binaryReader, blamPointers);
            invalidName_0[5].ReadPointers(binaryReader, blamPointers);
            invalidName_0[6].ReadPointers(binaryReader, blamPointers);
            invalidName_0[7].ReadPointers(binaryReader, blamPointers);
            invalidName_0[8].ReadPointers(binaryReader, blamPointers);
            invalidName_0[9].ReadPointers(binaryReader, blamPointers);
            invalidName_0[10].ReadPointers(binaryReader, blamPointers);
            invalidName_0[11].ReadPointers(binaryReader, blamPointers);
            invalidName_0[12].ReadPointers(binaryReader, blamPointers);
            invalidName_0[13].ReadPointers(binaryReader, blamPointers);
            invalidName_0[14].ReadPointers(binaryReader, blamPointers);
            invalidName_0[15].ReadPointers(binaryReader, blamPointers);
            invalidName_0[16].ReadPointers(binaryReader, blamPointers);
            invalidName_0[17].ReadPointers(binaryReader, blamPointers);
            invalidName_0[18].ReadPointers(binaryReader, blamPointers);
            invalidName_0[19].ReadPointers(binaryReader, blamPointers);
            invalidName_0[20].ReadPointers(binaryReader, blamPointers);
            invalidName_0[21].ReadPointers(binaryReader, blamPointers);
            invalidName_0[22].ReadPointers(binaryReader, blamPointers);
            invalidName_0[23].ReadPointers(binaryReader, blamPointers);
            invalidName_0[24].ReadPointers(binaryReader, blamPointers);
            invalidName_0[25].ReadPointers(binaryReader, blamPointers);
            invalidName_0[26].ReadPointers(binaryReader, blamPointers);
            invalidName_0[27].ReadPointers(binaryReader, blamPointers);
            invalidName_0[28].ReadPointers(binaryReader, blamPointers);
            invalidName_0[29].ReadPointers(binaryReader, blamPointers);
            invalidName_0[30].ReadPointers(binaryReader, blamPointers);
            invalidName_0[31].ReadPointers(binaryReader, blamPointers);
            invalidName_0[32].ReadPointers(binaryReader, blamPointers);
            invalidName_0[33].ReadPointers(binaryReader, blamPointers);
            invalidName_0[34].ReadPointers(binaryReader, blamPointers);
            invalidName_0[35].ReadPointers(binaryReader, blamPointers);
            invalidName_0[36].ReadPointers(binaryReader, blamPointers);
            invalidName_0[37].ReadPointers(binaryReader, blamPointers);
            invalidName_0[38].ReadPointers(binaryReader, blamPointers);
            invalidName_0[39].ReadPointers(binaryReader, blamPointers);
            invalidName_0[40].ReadPointers(binaryReader, blamPointers);
            invalidName_0[41].ReadPointers(binaryReader, blamPointers);
            invalidName_0[42].ReadPointers(binaryReader, blamPointers);
            invalidName_0[43].ReadPointers(binaryReader, blamPointers);
            invalidName_0[44].ReadPointers(binaryReader, blamPointers);
            invalidName_0[45].ReadPointers(binaryReader, blamPointers);
            invalidName_0[46].ReadPointers(binaryReader, blamPointers);
            invalidName_0[47].ReadPointers(binaryReader, blamPointers);
            invalidName_0[48].ReadPointers(binaryReader, blamPointers);
            invalidName_0[49].ReadPointers(binaryReader, blamPointers);
            invalidName_0[50].ReadPointers(binaryReader, blamPointers);
            invalidName_0[51].ReadPointers(binaryReader, blamPointers);
            invalidName_0[52].ReadPointers(binaryReader, blamPointers);
            invalidName_0[53].ReadPointers(binaryReader, blamPointers);
            invalidName_0[54].ReadPointers(binaryReader, blamPointers);
            invalidName_0[55].ReadPointers(binaryReader, blamPointers);
            invalidName_0[56].ReadPointers(binaryReader, blamPointers);
            invalidName_0[57].ReadPointers(binaryReader, blamPointers);
            invalidName_0[58].ReadPointers(binaryReader, blamPointers);
            invalidName_0[59].ReadPointers(binaryReader, blamPointers);
            invalidName_0[60].ReadPointers(binaryReader, blamPointers);
            invalidName_0[61].ReadPointers(binaryReader, blamPointers);
            invalidName_0[62].ReadPointers(binaryReader, blamPointers);
            invalidName_0[63].ReadPointers(binaryReader, blamPointers);
            invalidName_0[64].ReadPointers(binaryReader, blamPointers);
            invalidName_0[65].ReadPointers(binaryReader, blamPointers);
            invalidName_0[66].ReadPointers(binaryReader, blamPointers);
            invalidName_0[67].ReadPointers(binaryReader, blamPointers);
            invalidName_0[68].ReadPointers(binaryReader, blamPointers);
            invalidName_0[69].ReadPointers(binaryReader, blamPointers);
            invalidName_0[70].ReadPointers(binaryReader, blamPointers);
            invalidName_0[71].ReadPointers(binaryReader, blamPointers);
            invalidName_0[72].ReadPointers(binaryReader, blamPointers);
            invalidName_0[73].ReadPointers(binaryReader, blamPointers);
            invalidName_0[74].ReadPointers(binaryReader, blamPointers);
            invalidName_0[75].ReadPointers(binaryReader, blamPointers);
            invalidName_0[76].ReadPointers(binaryReader, blamPointers);
            invalidName_0[77].ReadPointers(binaryReader, blamPointers);
            invalidName_0[78].ReadPointers(binaryReader, blamPointers);
            invalidName_0[79].ReadPointers(binaryReader, blamPointers);
            invalidName_1[0].ReadPointers(binaryReader, blamPointers);
            invalidName_1[1].ReadPointers(binaryReader, blamPointers);
            invalidName_1[2].ReadPointers(binaryReader, blamPointers);
            invalidName_1[3].ReadPointers(binaryReader, blamPointers);
            invalidName_1[4].ReadPointers(binaryReader, blamPointers);
            invalidName_1[5].ReadPointers(binaryReader, blamPointers);
            invalidName_1[6].ReadPointers(binaryReader, blamPointers);
            invalidName_1[7].ReadPointers(binaryReader, blamPointers);
            invalidName_1[8].ReadPointers(binaryReader, blamPointers);
            invalidName_1[9].ReadPointers(binaryReader, blamPointers);
            invalidName_1[10].ReadPointers(binaryReader, blamPointers);
            invalidName_1[11].ReadPointers(binaryReader, blamPointers);
            invalidName_1[12].ReadPointers(binaryReader, blamPointers);
            invalidName_1[13].ReadPointers(binaryReader, blamPointers);
            invalidName_1[14].ReadPointers(binaryReader, blamPointers);
            invalidName_1[15].ReadPointers(binaryReader, blamPointers);
            invalidName_1[16].ReadPointers(binaryReader, blamPointers);
            invalidName_1[17].ReadPointers(binaryReader, blamPointers);
            invalidName_1[18].ReadPointers(binaryReader, blamPointers);
            invalidName_1[19].ReadPointers(binaryReader, blamPointers);
            invalidName_1[20].ReadPointers(binaryReader, blamPointers);
            invalidName_1[21].ReadPointers(binaryReader, blamPointers);
            invalidName_1[22].ReadPointers(binaryReader, blamPointers);
            invalidName_1[23].ReadPointers(binaryReader, blamPointers);
            invalidName_1[24].ReadPointers(binaryReader, blamPointers);
            invalidName_1[25].ReadPointers(binaryReader, blamPointers);
            invalidName_1[26].ReadPointers(binaryReader, blamPointers);
            invalidName_1[27].ReadPointers(binaryReader, blamPointers);
            invalidName_2[0].ReadPointers(binaryReader, blamPointers);
            invalidName_2[1].ReadPointers(binaryReader, blamPointers);
            invalidName_2[2].ReadPointers(binaryReader, blamPointers);
            invalidName_2[3].ReadPointers(binaryReader, blamPointers);
            invalidName_2[4].ReadPointers(binaryReader, blamPointers);
            invalidName_2[5].ReadPointers(binaryReader, blamPointers);
            invalidName_2[6].ReadPointers(binaryReader, blamPointers);
            invalidName_2[7].ReadPointers(binaryReader, blamPointers);
            invalidName_2[8].ReadPointers(binaryReader, blamPointers);
            invalidName_2[9].ReadPointers(binaryReader, blamPointers);
            invalidName_2[10].ReadPointers(binaryReader, blamPointers);
            invalidName_2[11].ReadPointers(binaryReader, blamPointers);
            invalidName_2[12].ReadPointers(binaryReader, blamPointers);
            invalidName_2[13].ReadPointers(binaryReader, blamPointers);
            invalidName_2[14].ReadPointers(binaryReader, blamPointers);
            invalidName_2[15].ReadPointers(binaryReader, blamPointers);
            invalidName_2[16].ReadPointers(binaryReader, blamPointers);
            invalidName_2[17].ReadPointers(binaryReader, blamPointers);
            invalidName_2[18].ReadPointers(binaryReader, blamPointers);
            invalidName_2[19].ReadPointers(binaryReader, blamPointers);
            invalidName_2[20].ReadPointers(binaryReader, blamPointers);
            invalidName_2[21].ReadPointers(binaryReader, blamPointers);
            invalidName_2[22].ReadPointers(binaryReader, blamPointers);
            invalidName_2[23].ReadPointers(binaryReader, blamPointers);
            invalidName_2[24].ReadPointers(binaryReader, blamPointers);
            invalidName_2[25].ReadPointers(binaryReader, blamPointers);
            invalidName_2[26].ReadPointers(binaryReader, blamPointers);
            invalidName_2[27].ReadPointers(binaryReader, blamPointers);
            invalidName_2[28].ReadPointers(binaryReader, blamPointers);
            invalidName_2[29].ReadPointers(binaryReader, blamPointers);
            invalidName_2[30].ReadPointers(binaryReader, blamPointers);
            invalidName_2[31].ReadPointers(binaryReader, blamPointers);
            invalidName_2[32].ReadPointers(binaryReader, blamPointers);
            invalidName_2[33].ReadPointers(binaryReader, blamPointers);
            invalidName_2[34].ReadPointers(binaryReader, blamPointers);
            invalidName_2[35].ReadPointers(binaryReader, blamPointers);
            invalidName_2[36].ReadPointers(binaryReader, blamPointers);
            invalidName_2[37].ReadPointers(binaryReader, blamPointers);
            invalidName_2[38].ReadPointers(binaryReader, blamPointers);
            invalidName_2[39].ReadPointers(binaryReader, blamPointers);
            invalidName_2[40].ReadPointers(binaryReader, blamPointers);
            invalidName_2[41].ReadPointers(binaryReader, blamPointers);
            invalidName_2[42].ReadPointers(binaryReader, blamPointers);
            invalidName_2[43].ReadPointers(binaryReader, blamPointers);
            invalidName_2[44].ReadPointers(binaryReader, blamPointers);
            invalidName_2[45].ReadPointers(binaryReader, blamPointers);
            invalidName_2[46].ReadPointers(binaryReader, blamPointers);
            invalidName_2[47].ReadPointers(binaryReader, blamPointers);
            invalidName_2[48].ReadPointers(binaryReader, blamPointers);
            invalidName_2[49].ReadPointers(binaryReader, blamPointers);
            invalidName_2[50].ReadPointers(binaryReader, blamPointers);
            invalidName_2[51].ReadPointers(binaryReader, blamPointers);
            invalidName_2[52].ReadPointers(binaryReader, blamPointers);
            invalidName_2[53].ReadPointers(binaryReader, blamPointers);
            invalidName_2[54].ReadPointers(binaryReader, blamPointers);
            invalidName_2[55].ReadPointers(binaryReader, blamPointers);
            invalidName_2[56].ReadPointers(binaryReader, blamPointers);
            invalidName_2[57].ReadPointers(binaryReader, blamPointers);
            invalidName_2[58].ReadPointers(binaryReader, blamPointers);
            invalidName_2[59].ReadPointers(binaryReader, blamPointers);
            invalidName_2[60].ReadPointers(binaryReader, blamPointers);
            invalidName_2[61].ReadPointers(binaryReader, blamPointers);
            invalidName_2[62].ReadPointers(binaryReader, blamPointers);
            invalidName_2[63].ReadPointers(binaryReader, blamPointers);
            invalidName_2[64].ReadPointers(binaryReader, blamPointers);
            invalidName_2[65].ReadPointers(binaryReader, blamPointers);
            invalidName_2[66].ReadPointers(binaryReader, blamPointers);
            invalidName_2[67].ReadPointers(binaryReader, blamPointers);
            invalidName_2[68].ReadPointers(binaryReader, blamPointers);
            invalidName_2[69].ReadPointers(binaryReader, blamPointers);
            invalidName_2[70].ReadPointers(binaryReader, blamPointers);
            invalidName_2[71].ReadPointers(binaryReader, blamPointers);
            invalidName_2[72].ReadPointers(binaryReader, blamPointers);
            invalidName_2[73].ReadPointers(binaryReader, blamPointers);
            invalidName_2[74].ReadPointers(binaryReader, blamPointers);
            invalidName_2[75].ReadPointers(binaryReader, blamPointers);
            invalidName_3[0].ReadPointers(binaryReader, blamPointers);
            invalidName_3[1].ReadPointers(binaryReader, blamPointers);
            invalidName_3[2].ReadPointers(binaryReader, blamPointers);
            invalidName_3[3].ReadPointers(binaryReader, blamPointers);
            invalidName_3[4].ReadPointers(binaryReader, blamPointers);
            invalidName_3[5].ReadPointers(binaryReader, blamPointers);
            invalidName_3[6].ReadPointers(binaryReader, blamPointers);
            invalidName_3[7].ReadPointers(binaryReader, blamPointers);
            invalidName_3[8].ReadPointers(binaryReader, blamPointers);
            invalidName_3[9].ReadPointers(binaryReader, blamPointers);
            invalidName_3[10].ReadPointers(binaryReader, blamPointers);
            invalidName_3[11].ReadPointers(binaryReader, blamPointers);
            invalidName_3[12].ReadPointers(binaryReader, blamPointers);
            invalidName_3[13].ReadPointers(binaryReader, blamPointers);
            invalidName_3[14].ReadPointers(binaryReader, blamPointers);
            invalidName_3[15].ReadPointers(binaryReader, blamPointers);
            invalidName_3[16].ReadPointers(binaryReader, blamPointers);
            invalidName_3[17].ReadPointers(binaryReader, blamPointers);
            invalidName_3[18].ReadPointers(binaryReader, blamPointers);
            invalidName_3[19].ReadPointers(binaryReader, blamPointers);
            invalidName_3[20].ReadPointers(binaryReader, blamPointers);
            invalidName_3[21].ReadPointers(binaryReader, blamPointers);
            invalidName_3[22].ReadPointers(binaryReader, blamPointers);
            invalidName_3[23].ReadPointers(binaryReader, blamPointers);
            invalidName_3[24].ReadPointers(binaryReader, blamPointers);
            invalidName_3[25].ReadPointers(binaryReader, blamPointers);
            invalidName_3[26].ReadPointers(binaryReader, blamPointers);
            invalidName_3[27].ReadPointers(binaryReader, blamPointers);
            invalidName_3[28].ReadPointers(binaryReader, blamPointers);
            invalidName_3[29].ReadPointers(binaryReader, blamPointers);
            invalidName_3[30].ReadPointers(binaryReader, blamPointers);
            invalidName_3[31].ReadPointers(binaryReader, blamPointers);
            invalidName_3[32].ReadPointers(binaryReader, blamPointers);
            invalidName_3[33].ReadPointers(binaryReader, blamPointers);
            invalidName_3[34].ReadPointers(binaryReader, blamPointers);
            invalidName_3[35].ReadPointers(binaryReader, blamPointers);
            invalidName_3[36].ReadPointers(binaryReader, blamPointers);
            invalidName_3[37].ReadPointers(binaryReader, blamPointers);
            invalidName_3[38].ReadPointers(binaryReader, blamPointers);
            invalidName_3[39].ReadPointers(binaryReader, blamPointers);
            invalidName_3[40].ReadPointers(binaryReader, blamPointers);
            invalidName_3[41].ReadPointers(binaryReader, blamPointers);
            invalidName_3[42].ReadPointers(binaryReader, blamPointers);
            invalidName_3[43].ReadPointers(binaryReader, blamPointers);
            invalidName_3[44].ReadPointers(binaryReader, blamPointers);
            invalidName_3[45].ReadPointers(binaryReader, blamPointers);
            invalidName_3[46].ReadPointers(binaryReader, blamPointers);
            invalidName_3[47].ReadPointers(binaryReader, blamPointers);
            invalidName_4[0].ReadPointers(binaryReader, blamPointers);
            invalidName_4[1].ReadPointers(binaryReader, blamPointers);
            invalidName_5[0].ReadPointers(binaryReader, blamPointers);
            invalidName_5[1].ReadPointers(binaryReader, blamPointers);
            invalidName_5[2].ReadPointers(binaryReader, blamPointers);
            invalidName_5[3].ReadPointers(binaryReader, blamPointers);
            invalidName_5[4].ReadPointers(binaryReader, blamPointers);
            invalidName_5[5].ReadPointers(binaryReader, blamPointers);
            invalidName_5[6].ReadPointers(binaryReader, blamPointers);
            invalidName_5[7].ReadPointers(binaryReader, blamPointers);
            invalidName_5[8].ReadPointers(binaryReader, blamPointers);
            invalidName_5[9].ReadPointers(binaryReader, blamPointers);
            invalidName_5[10].ReadPointers(binaryReader, blamPointers);
            invalidName_5[11].ReadPointers(binaryReader, blamPointers);
            invalidName_5[12].ReadPointers(binaryReader, blamPointers);
            invalidName_5[13].ReadPointers(binaryReader, blamPointers);
            invalidName_5[14].ReadPointers(binaryReader, blamPointers);
            invalidName_5[15].ReadPointers(binaryReader, blamPointers);
            invalidName_5[16].ReadPointers(binaryReader, blamPointers);
            invalidName_5[17].ReadPointers(binaryReader, blamPointers);
            invalidName_5[18].ReadPointers(binaryReader, blamPointers);
            invalidName_5[19].ReadPointers(binaryReader, blamPointers);
            invalidName_5[20].ReadPointers(binaryReader, blamPointers);
            invalidName_5[21].ReadPointers(binaryReader, blamPointers);
            invalidName_5[22].ReadPointers(binaryReader, blamPointers);
            invalidName_5[23].ReadPointers(binaryReader, blamPointers);
            invalidName_5[24].ReadPointers(binaryReader, blamPointers);
            invalidName_5[25].ReadPointers(binaryReader, blamPointers);
            invalidName_5[26].ReadPointers(binaryReader, blamPointers);
            invalidName_5[27].ReadPointers(binaryReader, blamPointers);
            invalidName_5[28].ReadPointers(binaryReader, blamPointers);
            invalidName_5[29].ReadPointers(binaryReader, blamPointers);
            invalidName_5[30].ReadPointers(binaryReader, blamPointers);
            invalidName_5[31].ReadPointers(binaryReader, blamPointers);
            invalidName_5[32].ReadPointers(binaryReader, blamPointers);
            invalidName_5[33].ReadPointers(binaryReader, blamPointers);
            invalidName_5[34].ReadPointers(binaryReader, blamPointers);
            invalidName_5[35].ReadPointers(binaryReader, blamPointers);
            invalidName_5[36].ReadPointers(binaryReader, blamPointers);
            invalidName_5[37].ReadPointers(binaryReader, blamPointers);
            invalidName_5[38].ReadPointers(binaryReader, blamPointers);
            invalidName_5[39].ReadPointers(binaryReader, blamPointers);
            invalidName_5[40].ReadPointers(binaryReader, blamPointers);
            invalidName_5[41].ReadPointers(binaryReader, blamPointers);
            invalidName_5[42].ReadPointers(binaryReader, blamPointers);
            invalidName_5[43].ReadPointers(binaryReader, blamPointers);
            invalidName_5[44].ReadPointers(binaryReader, blamPointers);
            invalidName_5[45].ReadPointers(binaryReader, blamPointers);
            invalidName_5[46].ReadPointers(binaryReader, blamPointers);
            invalidName_5[47].ReadPointers(binaryReader, blamPointers);
            invalidName_6[0].ReadPointers(binaryReader, blamPointers);
            invalidName_6[1].ReadPointers(binaryReader, blamPointers);
            invalidName_6[2].ReadPointers(binaryReader, blamPointers);
            invalidName_6[3].ReadPointers(binaryReader, blamPointers);
            invalidName_6[4].ReadPointers(binaryReader, blamPointers);
            invalidName_6[5].ReadPointers(binaryReader, blamPointers);
            invalidName_6[6].ReadPointers(binaryReader, blamPointers);
            invalidName_6[7].ReadPointers(binaryReader, blamPointers);
            invalidName_6[8].ReadPointers(binaryReader, blamPointers);
            invalidName_6[9].ReadPointers(binaryReader, blamPointers);
            invalidName_6[10].ReadPointers(binaryReader, blamPointers);
            invalidName_6[11].ReadPointers(binaryReader, blamPointers);
            invalidName_6[12].ReadPointers(binaryReader, blamPointers);
            invalidName_6[13].ReadPointers(binaryReader, blamPointers);
            invalidName_6[14].ReadPointers(binaryReader, blamPointers);
            invalidName_6[15].ReadPointers(binaryReader, blamPointers);
            invalidName_6[16].ReadPointers(binaryReader, blamPointers);
            invalidName_6[17].ReadPointers(binaryReader, blamPointers);
            invalidName_6[18].ReadPointers(binaryReader, blamPointers);
            invalidName_6[19].ReadPointers(binaryReader, blamPointers);
            invalidName_6[20].ReadPointers(binaryReader, blamPointers);
            invalidName_6[21].ReadPointers(binaryReader, blamPointers);
            invalidName_6[22].ReadPointers(binaryReader, blamPointers);
            invalidName_6[23].ReadPointers(binaryReader, blamPointers);
            invalidName_6[24].ReadPointers(binaryReader, blamPointers);
            invalidName_6[25].ReadPointers(binaryReader, blamPointers);
            invalidName_6[26].ReadPointers(binaryReader, blamPointers);
            invalidName_6[27].ReadPointers(binaryReader, blamPointers);
            invalidName_6[28].ReadPointers(binaryReader, blamPointers);
            invalidName_6[29].ReadPointers(binaryReader, blamPointers);
            invalidName_6[30].ReadPointers(binaryReader, blamPointers);
            invalidName_6[31].ReadPointers(binaryReader, blamPointers);
            invalidName_6[32].ReadPointers(binaryReader, blamPointers);
            invalidName_6[33].ReadPointers(binaryReader, blamPointers);
            invalidName_6[34].ReadPointers(binaryReader, blamPointers);
            invalidName_6[35].ReadPointers(binaryReader, blamPointers);
            invalidName_6[36].ReadPointers(binaryReader, blamPointers);
            invalidName_6[37].ReadPointers(binaryReader, blamPointers);
            invalidName_6[38].ReadPointers(binaryReader, blamPointers);
            invalidName_6[39].ReadPointers(binaryReader, blamPointers);
            invalidName_6[40].ReadPointers(binaryReader, blamPointers);
            invalidName_6[41].ReadPointers(binaryReader, blamPointers);
            invalidName_6[42].ReadPointers(binaryReader, blamPointers);
            invalidName_6[43].ReadPointers(binaryReader, blamPointers);
            invalidName_6[44].ReadPointers(binaryReader, blamPointers);
            invalidName_6[45].ReadPointers(binaryReader, blamPointers);
            invalidName_6[46].ReadPointers(binaryReader, blamPointers);
            invalidName_6[47].ReadPointers(binaryReader, blamPointers);
            invalidName_6[48].ReadPointers(binaryReader, blamPointers);
            invalidName_6[49].ReadPointers(binaryReader, blamPointers);
            invalidName_6[50].ReadPointers(binaryReader, blamPointers);
            invalidName_6[51].ReadPointers(binaryReader, blamPointers);
            invalidName_6[52].ReadPointers(binaryReader, blamPointers);
            invalidName_6[53].ReadPointers(binaryReader, blamPointers);
            invalidName_6[54].ReadPointers(binaryReader, blamPointers);
            invalidName_6[55].ReadPointers(binaryReader, blamPointers);
            invalidName_6[56].ReadPointers(binaryReader, blamPointers);
            invalidName_6[57].ReadPointers(binaryReader, blamPointers);
            invalidName_6[58].ReadPointers(binaryReader, blamPointers);
            invalidName_6[59].ReadPointers(binaryReader, blamPointers);
            invalidName_6[60].ReadPointers(binaryReader, blamPointers);
            invalidName_6[61].ReadPointers(binaryReader, blamPointers);
            invalidName_6[62].ReadPointers(binaryReader, blamPointers);
            invalidName_6[63].ReadPointers(binaryReader, blamPointers);
            invalidName_6[64].ReadPointers(binaryReader, blamPointers);
            invalidName_6[65].ReadPointers(binaryReader, blamPointers);
            invalidName_6[66].ReadPointers(binaryReader, blamPointers);
            invalidName_6[67].ReadPointers(binaryReader, blamPointers);
            invalidName_6[68].ReadPointers(binaryReader, blamPointers);
            invalidName_6[69].ReadPointers(binaryReader, blamPointers);
            invalidName_6[70].ReadPointers(binaryReader, blamPointers);
            invalidName_6[71].ReadPointers(binaryReader, blamPointers);
            invalidName_6[72].ReadPointers(binaryReader, blamPointers);
            invalidName_6[73].ReadPointers(binaryReader, blamPointers);
            invalidName_6[74].ReadPointers(binaryReader, blamPointers);
            invalidName_6[75].ReadPointers(binaryReader, blamPointers);
            invalidName_6[76].ReadPointers(binaryReader, blamPointers);
            invalidName_6[77].ReadPointers(binaryReader, blamPointers);
            invalidName_6[78].ReadPointers(binaryReader, blamPointers);
            invalidName_6[79].ReadPointers(binaryReader, blamPointers);
            invalidName_6[80].ReadPointers(binaryReader, blamPointers);
            invalidName_6[81].ReadPointers(binaryReader, blamPointers);
            invalidName_6[82].ReadPointers(binaryReader, blamPointers);
            invalidName_6[83].ReadPointers(binaryReader, blamPointers);
            invalidName_6[84].ReadPointers(binaryReader, blamPointers);
            invalidName_6[85].ReadPointers(binaryReader, blamPointers);
            invalidName_6[86].ReadPointers(binaryReader, blamPointers);
            invalidName_6[87].ReadPointers(binaryReader, blamPointers);
            invalidName_6[88].ReadPointers(binaryReader, blamPointers);
            invalidName_6[89].ReadPointers(binaryReader, blamPointers);
            invalidName_6[90].ReadPointers(binaryReader, blamPointers);
            invalidName_6[91].ReadPointers(binaryReader, blamPointers);
            invalidName_6[92].ReadPointers(binaryReader, blamPointers);
            invalidName_6[93].ReadPointers(binaryReader, blamPointers);
            invalidName_6[94].ReadPointers(binaryReader, blamPointers);
            invalidName_6[95].ReadPointers(binaryReader, blamPointers);
            invalidName_6[96].ReadPointers(binaryReader, blamPointers);
            invalidName_6[97].ReadPointers(binaryReader, blamPointers);
            invalidName_6[98].ReadPointers(binaryReader, blamPointers);
            invalidName_6[99].ReadPointers(binaryReader, blamPointers);
            invalidName_6[100].ReadPointers(binaryReader, blamPointers);
            invalidName_6[101].ReadPointers(binaryReader, blamPointers);
            invalidName_6[102].ReadPointers(binaryReader, blamPointers);
            invalidName_6[103].ReadPointers(binaryReader, blamPointers);
            invalidName_6[104].ReadPointers(binaryReader, blamPointers);
            invalidName_6[105].ReadPointers(binaryReader, blamPointers);
            invalidName_6[106].ReadPointers(binaryReader, blamPointers);
            invalidName_6[107].ReadPointers(binaryReader, blamPointers);
            invalidName_6[108].ReadPointers(binaryReader, blamPointers);
            invalidName_6[109].ReadPointers(binaryReader, blamPointers);
            invalidName_6[110].ReadPointers(binaryReader, blamPointers);
            invalidName_6[111].ReadPointers(binaryReader, blamPointers);
            invalidName_6[112].ReadPointers(binaryReader, blamPointers);
            invalidName_6[113].ReadPointers(binaryReader, blamPointers);
            invalidName_6[114].ReadPointers(binaryReader, blamPointers);
            invalidName_6[115].ReadPointers(binaryReader, blamPointers);
            invalidName_6[116].ReadPointers(binaryReader, blamPointers);
            invalidName_6[117].ReadPointers(binaryReader, blamPointers);
            invalidName_6[118].ReadPointers(binaryReader, blamPointers);
            invalidName_6[119].ReadPointers(binaryReader, blamPointers);
            invalidName_6[120].ReadPointers(binaryReader, blamPointers);
            invalidName_6[121].ReadPointers(binaryReader, blamPointers);
            invalidName_6[122].ReadPointers(binaryReader, blamPointers);
            invalidName_6[123].ReadPointers(binaryReader, blamPointers);
            invalidName_6[124].ReadPointers(binaryReader, blamPointers);
            invalidName_6[125].ReadPointers(binaryReader, blamPointers);
            invalidName_6[126].ReadPointers(binaryReader, blamPointers);
            invalidName_6[127].ReadPointers(binaryReader, blamPointers);
            invalidName_6[128].ReadPointers(binaryReader, blamPointers);
            invalidName_6[129].ReadPointers(binaryReader, blamPointers);
            invalidName_6[130].ReadPointers(binaryReader, blamPointers);
            invalidName_6[131].ReadPointers(binaryReader, blamPointers);
            invalidName_6[132].ReadPointers(binaryReader, blamPointers);
            invalidName_6[133].ReadPointers(binaryReader, blamPointers);
            invalidName_6[134].ReadPointers(binaryReader, blamPointers);
            invalidName_6[135].ReadPointers(binaryReader, blamPointers);
            invalidName_6[136].ReadPointers(binaryReader, blamPointers);
            invalidName_6[137].ReadPointers(binaryReader, blamPointers);
            invalidName_6[138].ReadPointers(binaryReader, blamPointers);
            invalidName_6[139].ReadPointers(binaryReader, blamPointers);
            invalidName_6[140].ReadPointers(binaryReader, blamPointers);
            invalidName_6[141].ReadPointers(binaryReader, blamPointers);
            invalidName_6[142].ReadPointers(binaryReader, blamPointers);
            invalidName_6[143].ReadPointers(binaryReader, blamPointers);
            invalidName_6[144].ReadPointers(binaryReader, blamPointers);
            invalidName_6[145].ReadPointers(binaryReader, blamPointers);
            invalidName_6[146].ReadPointers(binaryReader, blamPointers);
            invalidName_6[147].ReadPointers(binaryReader, blamPointers);
            invalidName_6[148].ReadPointers(binaryReader, blamPointers);
            invalidName_6[149].ReadPointers(binaryReader, blamPointers);
            invalidName_6[150].ReadPointers(binaryReader, blamPointers);
            invalidName_6[151].ReadPointers(binaryReader, blamPointers);
            invalidName_6[152].ReadPointers(binaryReader, blamPointers);
            invalidName_6[153].ReadPointers(binaryReader, blamPointers);
            invalidName_6[154].ReadPointers(binaryReader, blamPointers);
            invalidName_6[155].ReadPointers(binaryReader, blamPointers);
            invalidName_6[156].ReadPointers(binaryReader, blamPointers);
            invalidName_6[157].ReadPointers(binaryReader, blamPointers);
            invalidName_6[158].ReadPointers(binaryReader, blamPointers);
            invalidName_6[159].ReadPointers(binaryReader, blamPointers);
            rules = ReadBlockArrayData<RulesBlock>(binaryReader, blamPointers.Dequeue());
        }
        public override int Write(BinaryWriter binaryWriter, int nextAddress)
        {
            base.Write(binaryWriter, nextAddress);
using(binaryWriter.BaseStream.Pin())
            {
                binaryWriter.Write(updatesPerSecondHz);
                binaryWriter.Write(invalidName_, 0, 2);
                binaryWriter.Write(deadCellPenalty);
                binaryWriter.Write(liveCellBonus);
                binaryWriter.Write(invalidName_0, 0, 80);
                binaryWriter.Write(widthCells);
                binaryWriter.Write(heightCells);
                binaryWriter.Write(cellWidthWorldUnits);
                binaryWriter.Write(heightWorldUnits);
                binaryWriter.Write(velocityCellsUpdate);
                binaryWriter.Write(invalidName_1, 0, 28);
                binaryWriter.Write(marker);
                binaryWriter.Write((Int32)interpolationFlags);
                binaryWriter.Write(baseColor);
                binaryWriter.Write(peakColor);
                binaryWriter.Write(invalidName_2, 0, 76);
                binaryWriter.Write(widthCells0);
                binaryWriter.Write(heightCells0);
                binaryWriter.Write(cellWidthWorldUnits0);
                binaryWriter.Write(velocityCellsUpdate0);
                binaryWriter.Write(invalidName_3, 0, 48);
                binaryWriter.Write(marker0);
                binaryWriter.Write(textureWidthCells);
                binaryWriter.Write(invalidName_4, 0, 2);
                binaryWriter.Write(invalidName_5, 0, 48);
                binaryWriter.Write(texture);
                binaryWriter.Write(invalidName_6, 0, 160);
                nextAddress = Guerilla.WriteBlockArray<RulesBlock>(binaryWriter, rules, nextAddress);
                return nextAddress;
            }
        }
        [FlagsAttribute]
        internal enum InterpolationFlags : int
        {
            BlendInHsvBlendsColorsInHsvRatherThanRgbSpace = 1,
            MoreColorsBlendsColorsThroughMoreHuesGoesTheLongWayAroundTheColorWheel = 2,
        };
    };
}
