// ReSharper disable All
using Moonfish.Model;
using Moonfish.Tags.BlamExtension;
using Moonfish.Tags;
using OpenTK;
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

namespace Moonfish.Tags
{
    public partial struct TagClass
    {
        public static readonly TagClass Devo = (TagClass)"devo";
    };
};

namespace Moonfish.Guerilla.Tags
{
    [TagClassAttribute("devo")]
    public partial class CellularAutomataBlock : CellularAutomataBlockBase
    {
        public CellularAutomataBlock() : base()
        {
        }
    };
    [LayoutAttribute(Size = 548, Alignment = 4)]
    public class CellularAutomataBlockBase : GuerillaBlock
    {
        internal short updatesPerSecondHz;
        internal short xWidthCells;
        internal short yDepthCells;
        internal short zHeightCells;
        internal float xWidthWorldUnits;
        internal float yDepthWorldUnits;
        internal float zHeightWorldUnits;
        internal byte[] invalidName_;
        internal Moonfish.Tags.StringIdent marker;
        internal float cellBirthChance01;
        internal byte[] invalidName_0;
        internal int cellGeneMutates1InTimes;
        internal int virusGeneMutations1InTimes;
        internal byte[] invalidName_1;
        /// <summary>
        /// the lifespan of a cell once infected
        /// </summary>
        internal int infectedCellLifespanUpdates;
        /// <summary>
        /// no cell can be infected before it has been alive this number of updates
        /// </summary>
        internal short minimumInfectionAgeUpdates;
        internal byte[] invalidName_2;
        internal float cellInfectionChance01;
        /// <summary>
        /// 0.0 is most difficult for the virus, 1.0 means any virus can infect any cell
        /// </summary>
        internal float infectionThreshold01;
        internal byte[] invalidName_3;
        internal float newCellFilledChance01;
        internal float newCellInfectedChance01;
        internal byte[] invalidName_4;
        internal float detailTextureChangeChance01;
        internal byte[] invalidName_5;
        /// <summary>
        /// the number of cells repeating across the detail texture in both dimensions
        /// </summary>
        internal short detailTextureWidthCells;
        internal byte[] invalidName_6;
        [TagReference("bitm")]
        internal Moonfish.Tags.TagReference detailTexture;
        internal byte[] invalidName_7;
        [TagReference("bitm")]
        internal Moonfish.Tags.TagReference maskBitmap;
        internal byte[] invalidName_8;
        public override int SerializedSize { get { return 548; } }
        public override int Alignment { get { return 4; } }
        public CellularAutomataBlockBase() : base()
        {
        }
        public override Queue<BlamPointer> ReadFields(BinaryReader binaryReader)
        {
            var blamPointers = new Queue<BlamPointer>(base.ReadFields(binaryReader));
            updatesPerSecondHz = binaryReader.ReadInt16();
            xWidthCells = binaryReader.ReadInt16();
            yDepthCells = binaryReader.ReadInt16();
            zHeightCells = binaryReader.ReadInt16();
            xWidthWorldUnits = binaryReader.ReadSingle();
            yDepthWorldUnits = binaryReader.ReadSingle();
            zHeightWorldUnits = binaryReader.ReadSingle();
            invalidName_ = binaryReader.ReadBytes(32);
            marker = binaryReader.ReadStringID();
            cellBirthChance01 = binaryReader.ReadSingle();
            invalidName_0 = binaryReader.ReadBytes(32);
            cellGeneMutates1InTimes = binaryReader.ReadInt32();
            virusGeneMutations1InTimes = binaryReader.ReadInt32();
            invalidName_1 = binaryReader.ReadBytes(32);
            infectedCellLifespanUpdates = binaryReader.ReadInt32();
            minimumInfectionAgeUpdates = binaryReader.ReadInt16();
            invalidName_2 = binaryReader.ReadBytes(2);
            cellInfectionChance01 = binaryReader.ReadSingle();
            infectionThreshold01 = binaryReader.ReadSingle();
            invalidName_3 = binaryReader.ReadBytes(32);
            newCellFilledChance01 = binaryReader.ReadSingle();
            newCellInfectedChance01 = binaryReader.ReadSingle();
            invalidName_4 = binaryReader.ReadBytes(32);
            detailTextureChangeChance01 = binaryReader.ReadSingle();
            invalidName_5 = binaryReader.ReadBytes(32);
            detailTextureWidthCells = binaryReader.ReadInt16();
            invalidName_6 = binaryReader.ReadBytes(2);
            detailTexture = binaryReader.ReadTagReference();
            invalidName_7 = binaryReader.ReadBytes(32);
            maskBitmap = binaryReader.ReadTagReference();
            invalidName_8 = binaryReader.ReadBytes(240);
            return blamPointers;
        }
        public override void ReadPointers(BinaryReader binaryReader, Queue<BlamPointer> blamPointers)
        {
            base.ReadPointers(binaryReader, blamPointers);
            invalidName_[0].ReadPointers(binaryReader, blamPointers);
            invalidName_[1].ReadPointers(binaryReader, blamPointers);
            invalidName_[2].ReadPointers(binaryReader, blamPointers);
            invalidName_[3].ReadPointers(binaryReader, blamPointers);
            invalidName_[4].ReadPointers(binaryReader, blamPointers);
            invalidName_[5].ReadPointers(binaryReader, blamPointers);
            invalidName_[6].ReadPointers(binaryReader, blamPointers);
            invalidName_[7].ReadPointers(binaryReader, blamPointers);
            invalidName_[8].ReadPointers(binaryReader, blamPointers);
            invalidName_[9].ReadPointers(binaryReader, blamPointers);
            invalidName_[10].ReadPointers(binaryReader, blamPointers);
            invalidName_[11].ReadPointers(binaryReader, blamPointers);
            invalidName_[12].ReadPointers(binaryReader, blamPointers);
            invalidName_[13].ReadPointers(binaryReader, blamPointers);
            invalidName_[14].ReadPointers(binaryReader, blamPointers);
            invalidName_[15].ReadPointers(binaryReader, blamPointers);
            invalidName_[16].ReadPointers(binaryReader, blamPointers);
            invalidName_[17].ReadPointers(binaryReader, blamPointers);
            invalidName_[18].ReadPointers(binaryReader, blamPointers);
            invalidName_[19].ReadPointers(binaryReader, blamPointers);
            invalidName_[20].ReadPointers(binaryReader, blamPointers);
            invalidName_[21].ReadPointers(binaryReader, blamPointers);
            invalidName_[22].ReadPointers(binaryReader, blamPointers);
            invalidName_[23].ReadPointers(binaryReader, blamPointers);
            invalidName_[24].ReadPointers(binaryReader, blamPointers);
            invalidName_[25].ReadPointers(binaryReader, blamPointers);
            invalidName_[26].ReadPointers(binaryReader, blamPointers);
            invalidName_[27].ReadPointers(binaryReader, blamPointers);
            invalidName_[28].ReadPointers(binaryReader, blamPointers);
            invalidName_[29].ReadPointers(binaryReader, blamPointers);
            invalidName_[30].ReadPointers(binaryReader, blamPointers);
            invalidName_[31].ReadPointers(binaryReader, blamPointers);
            invalidName_0[0].ReadPointers(binaryReader, blamPointers);
            invalidName_0[1].ReadPointers(binaryReader, blamPointers);
            invalidName_0[2].ReadPointers(binaryReader, blamPointers);
            invalidName_0[3].ReadPointers(binaryReader, blamPointers);
            invalidName_0[4].ReadPointers(binaryReader, blamPointers);
            invalidName_0[5].ReadPointers(binaryReader, blamPointers);
            invalidName_0[6].ReadPointers(binaryReader, blamPointers);
            invalidName_0[7].ReadPointers(binaryReader, blamPointers);
            invalidName_0[8].ReadPointers(binaryReader, blamPointers);
            invalidName_0[9].ReadPointers(binaryReader, blamPointers);
            invalidName_0[10].ReadPointers(binaryReader, blamPointers);
            invalidName_0[11].ReadPointers(binaryReader, blamPointers);
            invalidName_0[12].ReadPointers(binaryReader, blamPointers);
            invalidName_0[13].ReadPointers(binaryReader, blamPointers);
            invalidName_0[14].ReadPointers(binaryReader, blamPointers);
            invalidName_0[15].ReadPointers(binaryReader, blamPointers);
            invalidName_0[16].ReadPointers(binaryReader, blamPointers);
            invalidName_0[17].ReadPointers(binaryReader, blamPointers);
            invalidName_0[18].ReadPointers(binaryReader, blamPointers);
            invalidName_0[19].ReadPointers(binaryReader, blamPointers);
            invalidName_0[20].ReadPointers(binaryReader, blamPointers);
            invalidName_0[21].ReadPointers(binaryReader, blamPointers);
            invalidName_0[22].ReadPointers(binaryReader, blamPointers);
            invalidName_0[23].ReadPointers(binaryReader, blamPointers);
            invalidName_0[24].ReadPointers(binaryReader, blamPointers);
            invalidName_0[25].ReadPointers(binaryReader, blamPointers);
            invalidName_0[26].ReadPointers(binaryReader, blamPointers);
            invalidName_0[27].ReadPointers(binaryReader, blamPointers);
            invalidName_0[28].ReadPointers(binaryReader, blamPointers);
            invalidName_0[29].ReadPointers(binaryReader, blamPointers);
            invalidName_0[30].ReadPointers(binaryReader, blamPointers);
            invalidName_0[31].ReadPointers(binaryReader, blamPointers);
            invalidName_1[0].ReadPointers(binaryReader, blamPointers);
            invalidName_1[1].ReadPointers(binaryReader, blamPointers);
            invalidName_1[2].ReadPointers(binaryReader, blamPointers);
            invalidName_1[3].ReadPointers(binaryReader, blamPointers);
            invalidName_1[4].ReadPointers(binaryReader, blamPointers);
            invalidName_1[5].ReadPointers(binaryReader, blamPointers);
            invalidName_1[6].ReadPointers(binaryReader, blamPointers);
            invalidName_1[7].ReadPointers(binaryReader, blamPointers);
            invalidName_1[8].ReadPointers(binaryReader, blamPointers);
            invalidName_1[9].ReadPointers(binaryReader, blamPointers);
            invalidName_1[10].ReadPointers(binaryReader, blamPointers);
            invalidName_1[11].ReadPointers(binaryReader, blamPointers);
            invalidName_1[12].ReadPointers(binaryReader, blamPointers);
            invalidName_1[13].ReadPointers(binaryReader, blamPointers);
            invalidName_1[14].ReadPointers(binaryReader, blamPointers);
            invalidName_1[15].ReadPointers(binaryReader, blamPointers);
            invalidName_1[16].ReadPointers(binaryReader, blamPointers);
            invalidName_1[17].ReadPointers(binaryReader, blamPointers);
            invalidName_1[18].ReadPointers(binaryReader, blamPointers);
            invalidName_1[19].ReadPointers(binaryReader, blamPointers);
            invalidName_1[20].ReadPointers(binaryReader, blamPointers);
            invalidName_1[21].ReadPointers(binaryReader, blamPointers);
            invalidName_1[22].ReadPointers(binaryReader, blamPointers);
            invalidName_1[23].ReadPointers(binaryReader, blamPointers);
            invalidName_1[24].ReadPointers(binaryReader, blamPointers);
            invalidName_1[25].ReadPointers(binaryReader, blamPointers);
            invalidName_1[26].ReadPointers(binaryReader, blamPointers);
            invalidName_1[27].ReadPointers(binaryReader, blamPointers);
            invalidName_1[28].ReadPointers(binaryReader, blamPointers);
            invalidName_1[29].ReadPointers(binaryReader, blamPointers);
            invalidName_1[30].ReadPointers(binaryReader, blamPointers);
            invalidName_1[31].ReadPointers(binaryReader, blamPointers);
            invalidName_2[0].ReadPointers(binaryReader, blamPointers);
            invalidName_2[1].ReadPointers(binaryReader, blamPointers);
            invalidName_3[0].ReadPointers(binaryReader, blamPointers);
            invalidName_3[1].ReadPointers(binaryReader, blamPointers);
            invalidName_3[2].ReadPointers(binaryReader, blamPointers);
            invalidName_3[3].ReadPointers(binaryReader, blamPointers);
            invalidName_3[4].ReadPointers(binaryReader, blamPointers);
            invalidName_3[5].ReadPointers(binaryReader, blamPointers);
            invalidName_3[6].ReadPointers(binaryReader, blamPointers);
            invalidName_3[7].ReadPointers(binaryReader, blamPointers);
            invalidName_3[8].ReadPointers(binaryReader, blamPointers);
            invalidName_3[9].ReadPointers(binaryReader, blamPointers);
            invalidName_3[10].ReadPointers(binaryReader, blamPointers);
            invalidName_3[11].ReadPointers(binaryReader, blamPointers);
            invalidName_3[12].ReadPointers(binaryReader, blamPointers);
            invalidName_3[13].ReadPointers(binaryReader, blamPointers);
            invalidName_3[14].ReadPointers(binaryReader, blamPointers);
            invalidName_3[15].ReadPointers(binaryReader, blamPointers);
            invalidName_3[16].ReadPointers(binaryReader, blamPointers);
            invalidName_3[17].ReadPointers(binaryReader, blamPointers);
            invalidName_3[18].ReadPointers(binaryReader, blamPointers);
            invalidName_3[19].ReadPointers(binaryReader, blamPointers);
            invalidName_3[20].ReadPointers(binaryReader, blamPointers);
            invalidName_3[21].ReadPointers(binaryReader, blamPointers);
            invalidName_3[22].ReadPointers(binaryReader, blamPointers);
            invalidName_3[23].ReadPointers(binaryReader, blamPointers);
            invalidName_3[24].ReadPointers(binaryReader, blamPointers);
            invalidName_3[25].ReadPointers(binaryReader, blamPointers);
            invalidName_3[26].ReadPointers(binaryReader, blamPointers);
            invalidName_3[27].ReadPointers(binaryReader, blamPointers);
            invalidName_3[28].ReadPointers(binaryReader, blamPointers);
            invalidName_3[29].ReadPointers(binaryReader, blamPointers);
            invalidName_3[30].ReadPointers(binaryReader, blamPointers);
            invalidName_3[31].ReadPointers(binaryReader, blamPointers);
            invalidName_4[0].ReadPointers(binaryReader, blamPointers);
            invalidName_4[1].ReadPointers(binaryReader, blamPointers);
            invalidName_4[2].ReadPointers(binaryReader, blamPointers);
            invalidName_4[3].ReadPointers(binaryReader, blamPointers);
            invalidName_4[4].ReadPointers(binaryReader, blamPointers);
            invalidName_4[5].ReadPointers(binaryReader, blamPointers);
            invalidName_4[6].ReadPointers(binaryReader, blamPointers);
            invalidName_4[7].ReadPointers(binaryReader, blamPointers);
            invalidName_4[8].ReadPointers(binaryReader, blamPointers);
            invalidName_4[9].ReadPointers(binaryReader, blamPointers);
            invalidName_4[10].ReadPointers(binaryReader, blamPointers);
            invalidName_4[11].ReadPointers(binaryReader, blamPointers);
            invalidName_4[12].ReadPointers(binaryReader, blamPointers);
            invalidName_4[13].ReadPointers(binaryReader, blamPointers);
            invalidName_4[14].ReadPointers(binaryReader, blamPointers);
            invalidName_4[15].ReadPointers(binaryReader, blamPointers);
            invalidName_4[16].ReadPointers(binaryReader, blamPointers);
            invalidName_4[17].ReadPointers(binaryReader, blamPointers);
            invalidName_4[18].ReadPointers(binaryReader, blamPointers);
            invalidName_4[19].ReadPointers(binaryReader, blamPointers);
            invalidName_4[20].ReadPointers(binaryReader, blamPointers);
            invalidName_4[21].ReadPointers(binaryReader, blamPointers);
            invalidName_4[22].ReadPointers(binaryReader, blamPointers);
            invalidName_4[23].ReadPointers(binaryReader, blamPointers);
            invalidName_4[24].ReadPointers(binaryReader, blamPointers);
            invalidName_4[25].ReadPointers(binaryReader, blamPointers);
            invalidName_4[26].ReadPointers(binaryReader, blamPointers);
            invalidName_4[27].ReadPointers(binaryReader, blamPointers);
            invalidName_4[28].ReadPointers(binaryReader, blamPointers);
            invalidName_4[29].ReadPointers(binaryReader, blamPointers);
            invalidName_4[30].ReadPointers(binaryReader, blamPointers);
            invalidName_4[31].ReadPointers(binaryReader, blamPointers);
            invalidName_5[0].ReadPointers(binaryReader, blamPointers);
            invalidName_5[1].ReadPointers(binaryReader, blamPointers);
            invalidName_5[2].ReadPointers(binaryReader, blamPointers);
            invalidName_5[3].ReadPointers(binaryReader, blamPointers);
            invalidName_5[4].ReadPointers(binaryReader, blamPointers);
            invalidName_5[5].ReadPointers(binaryReader, blamPointers);
            invalidName_5[6].ReadPointers(binaryReader, blamPointers);
            invalidName_5[7].ReadPointers(binaryReader, blamPointers);
            invalidName_5[8].ReadPointers(binaryReader, blamPointers);
            invalidName_5[9].ReadPointers(binaryReader, blamPointers);
            invalidName_5[10].ReadPointers(binaryReader, blamPointers);
            invalidName_5[11].ReadPointers(binaryReader, blamPointers);
            invalidName_5[12].ReadPointers(binaryReader, blamPointers);
            invalidName_5[13].ReadPointers(binaryReader, blamPointers);
            invalidName_5[14].ReadPointers(binaryReader, blamPointers);
            invalidName_5[15].ReadPointers(binaryReader, blamPointers);
            invalidName_5[16].ReadPointers(binaryReader, blamPointers);
            invalidName_5[17].ReadPointers(binaryReader, blamPointers);
            invalidName_5[18].ReadPointers(binaryReader, blamPointers);
            invalidName_5[19].ReadPointers(binaryReader, blamPointers);
            invalidName_5[20].ReadPointers(binaryReader, blamPointers);
            invalidName_5[21].ReadPointers(binaryReader, blamPointers);
            invalidName_5[22].ReadPointers(binaryReader, blamPointers);
            invalidName_5[23].ReadPointers(binaryReader, blamPointers);
            invalidName_5[24].ReadPointers(binaryReader, blamPointers);
            invalidName_5[25].ReadPointers(binaryReader, blamPointers);
            invalidName_5[26].ReadPointers(binaryReader, blamPointers);
            invalidName_5[27].ReadPointers(binaryReader, blamPointers);
            invalidName_5[28].ReadPointers(binaryReader, blamPointers);
            invalidName_5[29].ReadPointers(binaryReader, blamPointers);
            invalidName_5[30].ReadPointers(binaryReader, blamPointers);
            invalidName_5[31].ReadPointers(binaryReader, blamPointers);
            invalidName_6[0].ReadPointers(binaryReader, blamPointers);
            invalidName_6[1].ReadPointers(binaryReader, blamPointers);
            invalidName_7[0].ReadPointers(binaryReader, blamPointers);
            invalidName_7[1].ReadPointers(binaryReader, blamPointers);
            invalidName_7[2].ReadPointers(binaryReader, blamPointers);
            invalidName_7[3].ReadPointers(binaryReader, blamPointers);
            invalidName_7[4].ReadPointers(binaryReader, blamPointers);
            invalidName_7[5].ReadPointers(binaryReader, blamPointers);
            invalidName_7[6].ReadPointers(binaryReader, blamPointers);
            invalidName_7[7].ReadPointers(binaryReader, blamPointers);
            invalidName_7[8].ReadPointers(binaryReader, blamPointers);
            invalidName_7[9].ReadPointers(binaryReader, blamPointers);
            invalidName_7[10].ReadPointers(binaryReader, blamPointers);
            invalidName_7[11].ReadPointers(binaryReader, blamPointers);
            invalidName_7[12].ReadPointers(binaryReader, blamPointers);
            invalidName_7[13].ReadPointers(binaryReader, blamPointers);
            invalidName_7[14].ReadPointers(binaryReader, blamPointers);
            invalidName_7[15].ReadPointers(binaryReader, blamPointers);
            invalidName_7[16].ReadPointers(binaryReader, blamPointers);
            invalidName_7[17].ReadPointers(binaryReader, blamPointers);
            invalidName_7[18].ReadPointers(binaryReader, blamPointers);
            invalidName_7[19].ReadPointers(binaryReader, blamPointers);
            invalidName_7[20].ReadPointers(binaryReader, blamPointers);
            invalidName_7[21].ReadPointers(binaryReader, blamPointers);
            invalidName_7[22].ReadPointers(binaryReader, blamPointers);
            invalidName_7[23].ReadPointers(binaryReader, blamPointers);
            invalidName_7[24].ReadPointers(binaryReader, blamPointers);
            invalidName_7[25].ReadPointers(binaryReader, blamPointers);
            invalidName_7[26].ReadPointers(binaryReader, blamPointers);
            invalidName_7[27].ReadPointers(binaryReader, blamPointers);
            invalidName_7[28].ReadPointers(binaryReader, blamPointers);
            invalidName_7[29].ReadPointers(binaryReader, blamPointers);
            invalidName_7[30].ReadPointers(binaryReader, blamPointers);
            invalidName_7[31].ReadPointers(binaryReader, blamPointers);
            invalidName_8[0].ReadPointers(binaryReader, blamPointers);
            invalidName_8[1].ReadPointers(binaryReader, blamPointers);
            invalidName_8[2].ReadPointers(binaryReader, blamPointers);
            invalidName_8[3].ReadPointers(binaryReader, blamPointers);
            invalidName_8[4].ReadPointers(binaryReader, blamPointers);
            invalidName_8[5].ReadPointers(binaryReader, blamPointers);
            invalidName_8[6].ReadPointers(binaryReader, blamPointers);
            invalidName_8[7].ReadPointers(binaryReader, blamPointers);
            invalidName_8[8].ReadPointers(binaryReader, blamPointers);
            invalidName_8[9].ReadPointers(binaryReader, blamPointers);
            invalidName_8[10].ReadPointers(binaryReader, blamPointers);
            invalidName_8[11].ReadPointers(binaryReader, blamPointers);
            invalidName_8[12].ReadPointers(binaryReader, blamPointers);
            invalidName_8[13].ReadPointers(binaryReader, blamPointers);
            invalidName_8[14].ReadPointers(binaryReader, blamPointers);
            invalidName_8[15].ReadPointers(binaryReader, blamPointers);
            invalidName_8[16].ReadPointers(binaryReader, blamPointers);
            invalidName_8[17].ReadPointers(binaryReader, blamPointers);
            invalidName_8[18].ReadPointers(binaryReader, blamPointers);
            invalidName_8[19].ReadPointers(binaryReader, blamPointers);
            invalidName_8[20].ReadPointers(binaryReader, blamPointers);
            invalidName_8[21].ReadPointers(binaryReader, blamPointers);
            invalidName_8[22].ReadPointers(binaryReader, blamPointers);
            invalidName_8[23].ReadPointers(binaryReader, blamPointers);
            invalidName_8[24].ReadPointers(binaryReader, blamPointers);
            invalidName_8[25].ReadPointers(binaryReader, blamPointers);
            invalidName_8[26].ReadPointers(binaryReader, blamPointers);
            invalidName_8[27].ReadPointers(binaryReader, blamPointers);
            invalidName_8[28].ReadPointers(binaryReader, blamPointers);
            invalidName_8[29].ReadPointers(binaryReader, blamPointers);
            invalidName_8[30].ReadPointers(binaryReader, blamPointers);
            invalidName_8[31].ReadPointers(binaryReader, blamPointers);
            invalidName_8[32].ReadPointers(binaryReader, blamPointers);
            invalidName_8[33].ReadPointers(binaryReader, blamPointers);
            invalidName_8[34].ReadPointers(binaryReader, blamPointers);
            invalidName_8[35].ReadPointers(binaryReader, blamPointers);
            invalidName_8[36].ReadPointers(binaryReader, blamPointers);
            invalidName_8[37].ReadPointers(binaryReader, blamPointers);
            invalidName_8[38].ReadPointers(binaryReader, blamPointers);
            invalidName_8[39].ReadPointers(binaryReader, blamPointers);
            invalidName_8[40].ReadPointers(binaryReader, blamPointers);
            invalidName_8[41].ReadPointers(binaryReader, blamPointers);
            invalidName_8[42].ReadPointers(binaryReader, blamPointers);
            invalidName_8[43].ReadPointers(binaryReader, blamPointers);
            invalidName_8[44].ReadPointers(binaryReader, blamPointers);
            invalidName_8[45].ReadPointers(binaryReader, blamPointers);
            invalidName_8[46].ReadPointers(binaryReader, blamPointers);
            invalidName_8[47].ReadPointers(binaryReader, blamPointers);
            invalidName_8[48].ReadPointers(binaryReader, blamPointers);
            invalidName_8[49].ReadPointers(binaryReader, blamPointers);
            invalidName_8[50].ReadPointers(binaryReader, blamPointers);
            invalidName_8[51].ReadPointers(binaryReader, blamPointers);
            invalidName_8[52].ReadPointers(binaryReader, blamPointers);
            invalidName_8[53].ReadPointers(binaryReader, blamPointers);
            invalidName_8[54].ReadPointers(binaryReader, blamPointers);
            invalidName_8[55].ReadPointers(binaryReader, blamPointers);
            invalidName_8[56].ReadPointers(binaryReader, blamPointers);
            invalidName_8[57].ReadPointers(binaryReader, blamPointers);
            invalidName_8[58].ReadPointers(binaryReader, blamPointers);
            invalidName_8[59].ReadPointers(binaryReader, blamPointers);
            invalidName_8[60].ReadPointers(binaryReader, blamPointers);
            invalidName_8[61].ReadPointers(binaryReader, blamPointers);
            invalidName_8[62].ReadPointers(binaryReader, blamPointers);
            invalidName_8[63].ReadPointers(binaryReader, blamPointers);
            invalidName_8[64].ReadPointers(binaryReader, blamPointers);
            invalidName_8[65].ReadPointers(binaryReader, blamPointers);
            invalidName_8[66].ReadPointers(binaryReader, blamPointers);
            invalidName_8[67].ReadPointers(binaryReader, blamPointers);
            invalidName_8[68].ReadPointers(binaryReader, blamPointers);
            invalidName_8[69].ReadPointers(binaryReader, blamPointers);
            invalidName_8[70].ReadPointers(binaryReader, blamPointers);
            invalidName_8[71].ReadPointers(binaryReader, blamPointers);
            invalidName_8[72].ReadPointers(binaryReader, blamPointers);
            invalidName_8[73].ReadPointers(binaryReader, blamPointers);
            invalidName_8[74].ReadPointers(binaryReader, blamPointers);
            invalidName_8[75].ReadPointers(binaryReader, blamPointers);
            invalidName_8[76].ReadPointers(binaryReader, blamPointers);
            invalidName_8[77].ReadPointers(binaryReader, blamPointers);
            invalidName_8[78].ReadPointers(binaryReader, blamPointers);
            invalidName_8[79].ReadPointers(binaryReader, blamPointers);
            invalidName_8[80].ReadPointers(binaryReader, blamPointers);
            invalidName_8[81].ReadPointers(binaryReader, blamPointers);
            invalidName_8[82].ReadPointers(binaryReader, blamPointers);
            invalidName_8[83].ReadPointers(binaryReader, blamPointers);
            invalidName_8[84].ReadPointers(binaryReader, blamPointers);
            invalidName_8[85].ReadPointers(binaryReader, blamPointers);
            invalidName_8[86].ReadPointers(binaryReader, blamPointers);
            invalidName_8[87].ReadPointers(binaryReader, blamPointers);
            invalidName_8[88].ReadPointers(binaryReader, blamPointers);
            invalidName_8[89].ReadPointers(binaryReader, blamPointers);
            invalidName_8[90].ReadPointers(binaryReader, blamPointers);
            invalidName_8[91].ReadPointers(binaryReader, blamPointers);
            invalidName_8[92].ReadPointers(binaryReader, blamPointers);
            invalidName_8[93].ReadPointers(binaryReader, blamPointers);
            invalidName_8[94].ReadPointers(binaryReader, blamPointers);
            invalidName_8[95].ReadPointers(binaryReader, blamPointers);
            invalidName_8[96].ReadPointers(binaryReader, blamPointers);
            invalidName_8[97].ReadPointers(binaryReader, blamPointers);
            invalidName_8[98].ReadPointers(binaryReader, blamPointers);
            invalidName_8[99].ReadPointers(binaryReader, blamPointers);
            invalidName_8[100].ReadPointers(binaryReader, blamPointers);
            invalidName_8[101].ReadPointers(binaryReader, blamPointers);
            invalidName_8[102].ReadPointers(binaryReader, blamPointers);
            invalidName_8[103].ReadPointers(binaryReader, blamPointers);
            invalidName_8[104].ReadPointers(binaryReader, blamPointers);
            invalidName_8[105].ReadPointers(binaryReader, blamPointers);
            invalidName_8[106].ReadPointers(binaryReader, blamPointers);
            invalidName_8[107].ReadPointers(binaryReader, blamPointers);
            invalidName_8[108].ReadPointers(binaryReader, blamPointers);
            invalidName_8[109].ReadPointers(binaryReader, blamPointers);
            invalidName_8[110].ReadPointers(binaryReader, blamPointers);
            invalidName_8[111].ReadPointers(binaryReader, blamPointers);
            invalidName_8[112].ReadPointers(binaryReader, blamPointers);
            invalidName_8[113].ReadPointers(binaryReader, blamPointers);
            invalidName_8[114].ReadPointers(binaryReader, blamPointers);
            invalidName_8[115].ReadPointers(binaryReader, blamPointers);
            invalidName_8[116].ReadPointers(binaryReader, blamPointers);
            invalidName_8[117].ReadPointers(binaryReader, blamPointers);
            invalidName_8[118].ReadPointers(binaryReader, blamPointers);
            invalidName_8[119].ReadPointers(binaryReader, blamPointers);
            invalidName_8[120].ReadPointers(binaryReader, blamPointers);
            invalidName_8[121].ReadPointers(binaryReader, blamPointers);
            invalidName_8[122].ReadPointers(binaryReader, blamPointers);
            invalidName_8[123].ReadPointers(binaryReader, blamPointers);
            invalidName_8[124].ReadPointers(binaryReader, blamPointers);
            invalidName_8[125].ReadPointers(binaryReader, blamPointers);
            invalidName_8[126].ReadPointers(binaryReader, blamPointers);
            invalidName_8[127].ReadPointers(binaryReader, blamPointers);
            invalidName_8[128].ReadPointers(binaryReader, blamPointers);
            invalidName_8[129].ReadPointers(binaryReader, blamPointers);
            invalidName_8[130].ReadPointers(binaryReader, blamPointers);
            invalidName_8[131].ReadPointers(binaryReader, blamPointers);
            invalidName_8[132].ReadPointers(binaryReader, blamPointers);
            invalidName_8[133].ReadPointers(binaryReader, blamPointers);
            invalidName_8[134].ReadPointers(binaryReader, blamPointers);
            invalidName_8[135].ReadPointers(binaryReader, blamPointers);
            invalidName_8[136].ReadPointers(binaryReader, blamPointers);
            invalidName_8[137].ReadPointers(binaryReader, blamPointers);
            invalidName_8[138].ReadPointers(binaryReader, blamPointers);
            invalidName_8[139].ReadPointers(binaryReader, blamPointers);
            invalidName_8[140].ReadPointers(binaryReader, blamPointers);
            invalidName_8[141].ReadPointers(binaryReader, blamPointers);
            invalidName_8[142].ReadPointers(binaryReader, blamPointers);
            invalidName_8[143].ReadPointers(binaryReader, blamPointers);
            invalidName_8[144].ReadPointers(binaryReader, blamPointers);
            invalidName_8[145].ReadPointers(binaryReader, blamPointers);
            invalidName_8[146].ReadPointers(binaryReader, blamPointers);
            invalidName_8[147].ReadPointers(binaryReader, blamPointers);
            invalidName_8[148].ReadPointers(binaryReader, blamPointers);
            invalidName_8[149].ReadPointers(binaryReader, blamPointers);
            invalidName_8[150].ReadPointers(binaryReader, blamPointers);
            invalidName_8[151].ReadPointers(binaryReader, blamPointers);
            invalidName_8[152].ReadPointers(binaryReader, blamPointers);
            invalidName_8[153].ReadPointers(binaryReader, blamPointers);
            invalidName_8[154].ReadPointers(binaryReader, blamPointers);
            invalidName_8[155].ReadPointers(binaryReader, blamPointers);
            invalidName_8[156].ReadPointers(binaryReader, blamPointers);
            invalidName_8[157].ReadPointers(binaryReader, blamPointers);
            invalidName_8[158].ReadPointers(binaryReader, blamPointers);
            invalidName_8[159].ReadPointers(binaryReader, blamPointers);
            invalidName_8[160].ReadPointers(binaryReader, blamPointers);
            invalidName_8[161].ReadPointers(binaryReader, blamPointers);
            invalidName_8[162].ReadPointers(binaryReader, blamPointers);
            invalidName_8[163].ReadPointers(binaryReader, blamPointers);
            invalidName_8[164].ReadPointers(binaryReader, blamPointers);
            invalidName_8[165].ReadPointers(binaryReader, blamPointers);
            invalidName_8[166].ReadPointers(binaryReader, blamPointers);
            invalidName_8[167].ReadPointers(binaryReader, blamPointers);
            invalidName_8[168].ReadPointers(binaryReader, blamPointers);
            invalidName_8[169].ReadPointers(binaryReader, blamPointers);
            invalidName_8[170].ReadPointers(binaryReader, blamPointers);
            invalidName_8[171].ReadPointers(binaryReader, blamPointers);
            invalidName_8[172].ReadPointers(binaryReader, blamPointers);
            invalidName_8[173].ReadPointers(binaryReader, blamPointers);
            invalidName_8[174].ReadPointers(binaryReader, blamPointers);
            invalidName_8[175].ReadPointers(binaryReader, blamPointers);
            invalidName_8[176].ReadPointers(binaryReader, blamPointers);
            invalidName_8[177].ReadPointers(binaryReader, blamPointers);
            invalidName_8[178].ReadPointers(binaryReader, blamPointers);
            invalidName_8[179].ReadPointers(binaryReader, blamPointers);
            invalidName_8[180].ReadPointers(binaryReader, blamPointers);
            invalidName_8[181].ReadPointers(binaryReader, blamPointers);
            invalidName_8[182].ReadPointers(binaryReader, blamPointers);
            invalidName_8[183].ReadPointers(binaryReader, blamPointers);
            invalidName_8[184].ReadPointers(binaryReader, blamPointers);
            invalidName_8[185].ReadPointers(binaryReader, blamPointers);
            invalidName_8[186].ReadPointers(binaryReader, blamPointers);
            invalidName_8[187].ReadPointers(binaryReader, blamPointers);
            invalidName_8[188].ReadPointers(binaryReader, blamPointers);
            invalidName_8[189].ReadPointers(binaryReader, blamPointers);
            invalidName_8[190].ReadPointers(binaryReader, blamPointers);
            invalidName_8[191].ReadPointers(binaryReader, blamPointers);
            invalidName_8[192].ReadPointers(binaryReader, blamPointers);
            invalidName_8[193].ReadPointers(binaryReader, blamPointers);
            invalidName_8[194].ReadPointers(binaryReader, blamPointers);
            invalidName_8[195].ReadPointers(binaryReader, blamPointers);
            invalidName_8[196].ReadPointers(binaryReader, blamPointers);
            invalidName_8[197].ReadPointers(binaryReader, blamPointers);
            invalidName_8[198].ReadPointers(binaryReader, blamPointers);
            invalidName_8[199].ReadPointers(binaryReader, blamPointers);
            invalidName_8[200].ReadPointers(binaryReader, blamPointers);
            invalidName_8[201].ReadPointers(binaryReader, blamPointers);
            invalidName_8[202].ReadPointers(binaryReader, blamPointers);
            invalidName_8[203].ReadPointers(binaryReader, blamPointers);
            invalidName_8[204].ReadPointers(binaryReader, blamPointers);
            invalidName_8[205].ReadPointers(binaryReader, blamPointers);
            invalidName_8[206].ReadPointers(binaryReader, blamPointers);
            invalidName_8[207].ReadPointers(binaryReader, blamPointers);
            invalidName_8[208].ReadPointers(binaryReader, blamPointers);
            invalidName_8[209].ReadPointers(binaryReader, blamPointers);
            invalidName_8[210].ReadPointers(binaryReader, blamPointers);
            invalidName_8[211].ReadPointers(binaryReader, blamPointers);
            invalidName_8[212].ReadPointers(binaryReader, blamPointers);
            invalidName_8[213].ReadPointers(binaryReader, blamPointers);
            invalidName_8[214].ReadPointers(binaryReader, blamPointers);
            invalidName_8[215].ReadPointers(binaryReader, blamPointers);
            invalidName_8[216].ReadPointers(binaryReader, blamPointers);
            invalidName_8[217].ReadPointers(binaryReader, blamPointers);
            invalidName_8[218].ReadPointers(binaryReader, blamPointers);
            invalidName_8[219].ReadPointers(binaryReader, blamPointers);
            invalidName_8[220].ReadPointers(binaryReader, blamPointers);
            invalidName_8[221].ReadPointers(binaryReader, blamPointers);
            invalidName_8[222].ReadPointers(binaryReader, blamPointers);
            invalidName_8[223].ReadPointers(binaryReader, blamPointers);
            invalidName_8[224].ReadPointers(binaryReader, blamPointers);
            invalidName_8[225].ReadPointers(binaryReader, blamPointers);
            invalidName_8[226].ReadPointers(binaryReader, blamPointers);
            invalidName_8[227].ReadPointers(binaryReader, blamPointers);
            invalidName_8[228].ReadPointers(binaryReader, blamPointers);
            invalidName_8[229].ReadPointers(binaryReader, blamPointers);
            invalidName_8[230].ReadPointers(binaryReader, blamPointers);
            invalidName_8[231].ReadPointers(binaryReader, blamPointers);
            invalidName_8[232].ReadPointers(binaryReader, blamPointers);
            invalidName_8[233].ReadPointers(binaryReader, blamPointers);
            invalidName_8[234].ReadPointers(binaryReader, blamPointers);
            invalidName_8[235].ReadPointers(binaryReader, blamPointers);
            invalidName_8[236].ReadPointers(binaryReader, blamPointers);
            invalidName_8[237].ReadPointers(binaryReader, blamPointers);
            invalidName_8[238].ReadPointers(binaryReader, blamPointers);
            invalidName_8[239].ReadPointers(binaryReader, blamPointers);
        }
        public override int Write(BinaryWriter binaryWriter, int nextAddress)
        {
            base.Write(binaryWriter, nextAddress);
using(binaryWriter.BaseStream.Pin())
            {
                binaryWriter.Write(updatesPerSecondHz);
                binaryWriter.Write(xWidthCells);
                binaryWriter.Write(yDepthCells);
                binaryWriter.Write(zHeightCells);
                binaryWriter.Write(xWidthWorldUnits);
                binaryWriter.Write(yDepthWorldUnits);
                binaryWriter.Write(zHeightWorldUnits);
                binaryWriter.Write(invalidName_, 0, 32);
                binaryWriter.Write(marker);
                binaryWriter.Write(cellBirthChance01);
                binaryWriter.Write(invalidName_0, 0, 32);
                binaryWriter.Write(cellGeneMutates1InTimes);
                binaryWriter.Write(virusGeneMutations1InTimes);
                binaryWriter.Write(invalidName_1, 0, 32);
                binaryWriter.Write(infectedCellLifespanUpdates);
                binaryWriter.Write(minimumInfectionAgeUpdates);
                binaryWriter.Write(invalidName_2, 0, 2);
                binaryWriter.Write(cellInfectionChance01);
                binaryWriter.Write(infectionThreshold01);
                binaryWriter.Write(invalidName_3, 0, 32);
                binaryWriter.Write(newCellFilledChance01);
                binaryWriter.Write(newCellInfectedChance01);
                binaryWriter.Write(invalidName_4, 0, 32);
                binaryWriter.Write(detailTextureChangeChance01);
                binaryWriter.Write(invalidName_5, 0, 32);
                binaryWriter.Write(detailTextureWidthCells);
                binaryWriter.Write(invalidName_6, 0, 2);
                binaryWriter.Write(detailTexture);
                binaryWriter.Write(invalidName_7, 0, 32);
                binaryWriter.Write(maskBitmap);
                binaryWriter.Write(invalidName_8, 0, 240);
                return nextAddress;
            }
        }
    };
}
