// ReSharper disable All
using Moonfish.Model;
using Moonfish.Tags.BlamExtension;
using Moonfish.Tags;
using OpenTK;
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

namespace Moonfish.Guerilla.Tags
{
    public partial class ErrorReportsBlock : ErrorReportsBlockBase
    {
        public ErrorReportsBlock() : base()
        {
        }
    };
    [LayoutAttribute(Size = 608, Alignment = 4)]
    public class ErrorReportsBlockBase : GuerillaBlock
    {
        internal Type type;
        internal Flags flags;
        internal byte[] text;
        internal Moonfish.Tags.String32 sourceFilename;
        internal int sourceLineNumber;
        internal ErrorReportVerticesBlock[] vertices;
        internal ErrorReportVectorsBlock[] vectors;
        internal ErrorReportLinesBlock[] lines;
        internal ErrorReportTrianglesBlock[] triangles;
        internal ErrorReportQuadsBlock[] quads;
        internal ErrorReportCommentsBlock[] comments;
        internal byte[] invalidName_;
        internal int reportKey;
        internal int nodeIndex;
        internal Moonfish.Model.Range boundsX;
        internal Moonfish.Model.Range boundsY;
        internal Moonfish.Model.Range boundsZ;
        internal OpenTK.Vector4 color;
        internal byte[] invalidName_0;
        public override int SerializedSize { get { return 608; } }
        public override int Alignment { get { return 4; } }
        public ErrorReportsBlockBase() : base()
        {
        }
        public override Queue<BlamPointer> ReadFields(BinaryReader binaryReader)
        {
            var blamPointers = new Queue<BlamPointer>(base.ReadFields(binaryReader));
            type = (Type)binaryReader.ReadInt16();
            flags = (Flags)binaryReader.ReadInt16();
            blamPointers.Enqueue(ReadBlockArrayPointer(binaryReader, 1));
            sourceFilename = binaryReader.ReadString32();
            sourceLineNumber = binaryReader.ReadInt32();
            blamPointers.Enqueue(ReadBlockArrayPointer<ErrorReportVerticesBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<ErrorReportVectorsBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<ErrorReportLinesBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<ErrorReportTrianglesBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<ErrorReportQuadsBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<ErrorReportCommentsBlock>(binaryReader));
            invalidName_ = binaryReader.ReadBytes(380);
            reportKey = binaryReader.ReadInt32();
            nodeIndex = binaryReader.ReadInt32();
            boundsX = binaryReader.ReadRange();
            boundsY = binaryReader.ReadRange();
            boundsZ = binaryReader.ReadRange();
            color = binaryReader.ReadVector4();
            invalidName_0 = binaryReader.ReadBytes(84);
            return blamPointers;
        }
        public override void ReadPointers(BinaryReader binaryReader, Queue<BlamPointer> blamPointers)
        {
            base.ReadPointers(binaryReader, blamPointers);
            text = ReadDataByteArray(binaryReader, blamPointers.Dequeue());
            vertices = ReadBlockArrayData<ErrorReportVerticesBlock>(binaryReader, blamPointers.Dequeue());
            vectors = ReadBlockArrayData<ErrorReportVectorsBlock>(binaryReader, blamPointers.Dequeue());
            lines = ReadBlockArrayData<ErrorReportLinesBlock>(binaryReader, blamPointers.Dequeue());
            triangles = ReadBlockArrayData<ErrorReportTrianglesBlock>(binaryReader, blamPointers.Dequeue());
            quads = ReadBlockArrayData<ErrorReportQuadsBlock>(binaryReader, blamPointers.Dequeue());
            comments = ReadBlockArrayData<ErrorReportCommentsBlock>(binaryReader, blamPointers.Dequeue());
            invalidName_[0].ReadPointers(binaryReader, blamPointers);
            invalidName_[1].ReadPointers(binaryReader, blamPointers);
            invalidName_[2].ReadPointers(binaryReader, blamPointers);
            invalidName_[3].ReadPointers(binaryReader, blamPointers);
            invalidName_[4].ReadPointers(binaryReader, blamPointers);
            invalidName_[5].ReadPointers(binaryReader, blamPointers);
            invalidName_[6].ReadPointers(binaryReader, blamPointers);
            invalidName_[7].ReadPointers(binaryReader, blamPointers);
            invalidName_[8].ReadPointers(binaryReader, blamPointers);
            invalidName_[9].ReadPointers(binaryReader, blamPointers);
            invalidName_[10].ReadPointers(binaryReader, blamPointers);
            invalidName_[11].ReadPointers(binaryReader, blamPointers);
            invalidName_[12].ReadPointers(binaryReader, blamPointers);
            invalidName_[13].ReadPointers(binaryReader, blamPointers);
            invalidName_[14].ReadPointers(binaryReader, blamPointers);
            invalidName_[15].ReadPointers(binaryReader, blamPointers);
            invalidName_[16].ReadPointers(binaryReader, blamPointers);
            invalidName_[17].ReadPointers(binaryReader, blamPointers);
            invalidName_[18].ReadPointers(binaryReader, blamPointers);
            invalidName_[19].ReadPointers(binaryReader, blamPointers);
            invalidName_[20].ReadPointers(binaryReader, blamPointers);
            invalidName_[21].ReadPointers(binaryReader, blamPointers);
            invalidName_[22].ReadPointers(binaryReader, blamPointers);
            invalidName_[23].ReadPointers(binaryReader, blamPointers);
            invalidName_[24].ReadPointers(binaryReader, blamPointers);
            invalidName_[25].ReadPointers(binaryReader, blamPointers);
            invalidName_[26].ReadPointers(binaryReader, blamPointers);
            invalidName_[27].ReadPointers(binaryReader, blamPointers);
            invalidName_[28].ReadPointers(binaryReader, blamPointers);
            invalidName_[29].ReadPointers(binaryReader, blamPointers);
            invalidName_[30].ReadPointers(binaryReader, blamPointers);
            invalidName_[31].ReadPointers(binaryReader, blamPointers);
            invalidName_[32].ReadPointers(binaryReader, blamPointers);
            invalidName_[33].ReadPointers(binaryReader, blamPointers);
            invalidName_[34].ReadPointers(binaryReader, blamPointers);
            invalidName_[35].ReadPointers(binaryReader, blamPointers);
            invalidName_[36].ReadPointers(binaryReader, blamPointers);
            invalidName_[37].ReadPointers(binaryReader, blamPointers);
            invalidName_[38].ReadPointers(binaryReader, blamPointers);
            invalidName_[39].ReadPointers(binaryReader, blamPointers);
            invalidName_[40].ReadPointers(binaryReader, blamPointers);
            invalidName_[41].ReadPointers(binaryReader, blamPointers);
            invalidName_[42].ReadPointers(binaryReader, blamPointers);
            invalidName_[43].ReadPointers(binaryReader, blamPointers);
            invalidName_[44].ReadPointers(binaryReader, blamPointers);
            invalidName_[45].ReadPointers(binaryReader, blamPointers);
            invalidName_[46].ReadPointers(binaryReader, blamPointers);
            invalidName_[47].ReadPointers(binaryReader, blamPointers);
            invalidName_[48].ReadPointers(binaryReader, blamPointers);
            invalidName_[49].ReadPointers(binaryReader, blamPointers);
            invalidName_[50].ReadPointers(binaryReader, blamPointers);
            invalidName_[51].ReadPointers(binaryReader, blamPointers);
            invalidName_[52].ReadPointers(binaryReader, blamPointers);
            invalidName_[53].ReadPointers(binaryReader, blamPointers);
            invalidName_[54].ReadPointers(binaryReader, blamPointers);
            invalidName_[55].ReadPointers(binaryReader, blamPointers);
            invalidName_[56].ReadPointers(binaryReader, blamPointers);
            invalidName_[57].ReadPointers(binaryReader, blamPointers);
            invalidName_[58].ReadPointers(binaryReader, blamPointers);
            invalidName_[59].ReadPointers(binaryReader, blamPointers);
            invalidName_[60].ReadPointers(binaryReader, blamPointers);
            invalidName_[61].ReadPointers(binaryReader, blamPointers);
            invalidName_[62].ReadPointers(binaryReader, blamPointers);
            invalidName_[63].ReadPointers(binaryReader, blamPointers);
            invalidName_[64].ReadPointers(binaryReader, blamPointers);
            invalidName_[65].ReadPointers(binaryReader, blamPointers);
            invalidName_[66].ReadPointers(binaryReader, blamPointers);
            invalidName_[67].ReadPointers(binaryReader, blamPointers);
            invalidName_[68].ReadPointers(binaryReader, blamPointers);
            invalidName_[69].ReadPointers(binaryReader, blamPointers);
            invalidName_[70].ReadPointers(binaryReader, blamPointers);
            invalidName_[71].ReadPointers(binaryReader, blamPointers);
            invalidName_[72].ReadPointers(binaryReader, blamPointers);
            invalidName_[73].ReadPointers(binaryReader, blamPointers);
            invalidName_[74].ReadPointers(binaryReader, blamPointers);
            invalidName_[75].ReadPointers(binaryReader, blamPointers);
            invalidName_[76].ReadPointers(binaryReader, blamPointers);
            invalidName_[77].ReadPointers(binaryReader, blamPointers);
            invalidName_[78].ReadPointers(binaryReader, blamPointers);
            invalidName_[79].ReadPointers(binaryReader, blamPointers);
            invalidName_[80].ReadPointers(binaryReader, blamPointers);
            invalidName_[81].ReadPointers(binaryReader, blamPointers);
            invalidName_[82].ReadPointers(binaryReader, blamPointers);
            invalidName_[83].ReadPointers(binaryReader, blamPointers);
            invalidName_[84].ReadPointers(binaryReader, blamPointers);
            invalidName_[85].ReadPointers(binaryReader, blamPointers);
            invalidName_[86].ReadPointers(binaryReader, blamPointers);
            invalidName_[87].ReadPointers(binaryReader, blamPointers);
            invalidName_[88].ReadPointers(binaryReader, blamPointers);
            invalidName_[89].ReadPointers(binaryReader, blamPointers);
            invalidName_[90].ReadPointers(binaryReader, blamPointers);
            invalidName_[91].ReadPointers(binaryReader, blamPointers);
            invalidName_[92].ReadPointers(binaryReader, blamPointers);
            invalidName_[93].ReadPointers(binaryReader, blamPointers);
            invalidName_[94].ReadPointers(binaryReader, blamPointers);
            invalidName_[95].ReadPointers(binaryReader, blamPointers);
            invalidName_[96].ReadPointers(binaryReader, blamPointers);
            invalidName_[97].ReadPointers(binaryReader, blamPointers);
            invalidName_[98].ReadPointers(binaryReader, blamPointers);
            invalidName_[99].ReadPointers(binaryReader, blamPointers);
            invalidName_[100].ReadPointers(binaryReader, blamPointers);
            invalidName_[101].ReadPointers(binaryReader, blamPointers);
            invalidName_[102].ReadPointers(binaryReader, blamPointers);
            invalidName_[103].ReadPointers(binaryReader, blamPointers);
            invalidName_[104].ReadPointers(binaryReader, blamPointers);
            invalidName_[105].ReadPointers(binaryReader, blamPointers);
            invalidName_[106].ReadPointers(binaryReader, blamPointers);
            invalidName_[107].ReadPointers(binaryReader, blamPointers);
            invalidName_[108].ReadPointers(binaryReader, blamPointers);
            invalidName_[109].ReadPointers(binaryReader, blamPointers);
            invalidName_[110].ReadPointers(binaryReader, blamPointers);
            invalidName_[111].ReadPointers(binaryReader, blamPointers);
            invalidName_[112].ReadPointers(binaryReader, blamPointers);
            invalidName_[113].ReadPointers(binaryReader, blamPointers);
            invalidName_[114].ReadPointers(binaryReader, blamPointers);
            invalidName_[115].ReadPointers(binaryReader, blamPointers);
            invalidName_[116].ReadPointers(binaryReader, blamPointers);
            invalidName_[117].ReadPointers(binaryReader, blamPointers);
            invalidName_[118].ReadPointers(binaryReader, blamPointers);
            invalidName_[119].ReadPointers(binaryReader, blamPointers);
            invalidName_[120].ReadPointers(binaryReader, blamPointers);
            invalidName_[121].ReadPointers(binaryReader, blamPointers);
            invalidName_[122].ReadPointers(binaryReader, blamPointers);
            invalidName_[123].ReadPointers(binaryReader, blamPointers);
            invalidName_[124].ReadPointers(binaryReader, blamPointers);
            invalidName_[125].ReadPointers(binaryReader, blamPointers);
            invalidName_[126].ReadPointers(binaryReader, blamPointers);
            invalidName_[127].ReadPointers(binaryReader, blamPointers);
            invalidName_[128].ReadPointers(binaryReader, blamPointers);
            invalidName_[129].ReadPointers(binaryReader, blamPointers);
            invalidName_[130].ReadPointers(binaryReader, blamPointers);
            invalidName_[131].ReadPointers(binaryReader, blamPointers);
            invalidName_[132].ReadPointers(binaryReader, blamPointers);
            invalidName_[133].ReadPointers(binaryReader, blamPointers);
            invalidName_[134].ReadPointers(binaryReader, blamPointers);
            invalidName_[135].ReadPointers(binaryReader, blamPointers);
            invalidName_[136].ReadPointers(binaryReader, blamPointers);
            invalidName_[137].ReadPointers(binaryReader, blamPointers);
            invalidName_[138].ReadPointers(binaryReader, blamPointers);
            invalidName_[139].ReadPointers(binaryReader, blamPointers);
            invalidName_[140].ReadPointers(binaryReader, blamPointers);
            invalidName_[141].ReadPointers(binaryReader, blamPointers);
            invalidName_[142].ReadPointers(binaryReader, blamPointers);
            invalidName_[143].ReadPointers(binaryReader, blamPointers);
            invalidName_[144].ReadPointers(binaryReader, blamPointers);
            invalidName_[145].ReadPointers(binaryReader, blamPointers);
            invalidName_[146].ReadPointers(binaryReader, blamPointers);
            invalidName_[147].ReadPointers(binaryReader, blamPointers);
            invalidName_[148].ReadPointers(binaryReader, blamPointers);
            invalidName_[149].ReadPointers(binaryReader, blamPointers);
            invalidName_[150].ReadPointers(binaryReader, blamPointers);
            invalidName_[151].ReadPointers(binaryReader, blamPointers);
            invalidName_[152].ReadPointers(binaryReader, blamPointers);
            invalidName_[153].ReadPointers(binaryReader, blamPointers);
            invalidName_[154].ReadPointers(binaryReader, blamPointers);
            invalidName_[155].ReadPointers(binaryReader, blamPointers);
            invalidName_[156].ReadPointers(binaryReader, blamPointers);
            invalidName_[157].ReadPointers(binaryReader, blamPointers);
            invalidName_[158].ReadPointers(binaryReader, blamPointers);
            invalidName_[159].ReadPointers(binaryReader, blamPointers);
            invalidName_[160].ReadPointers(binaryReader, blamPointers);
            invalidName_[161].ReadPointers(binaryReader, blamPointers);
            invalidName_[162].ReadPointers(binaryReader, blamPointers);
            invalidName_[163].ReadPointers(binaryReader, blamPointers);
            invalidName_[164].ReadPointers(binaryReader, blamPointers);
            invalidName_[165].ReadPointers(binaryReader, blamPointers);
            invalidName_[166].ReadPointers(binaryReader, blamPointers);
            invalidName_[167].ReadPointers(binaryReader, blamPointers);
            invalidName_[168].ReadPointers(binaryReader, blamPointers);
            invalidName_[169].ReadPointers(binaryReader, blamPointers);
            invalidName_[170].ReadPointers(binaryReader, blamPointers);
            invalidName_[171].ReadPointers(binaryReader, blamPointers);
            invalidName_[172].ReadPointers(binaryReader, blamPointers);
            invalidName_[173].ReadPointers(binaryReader, blamPointers);
            invalidName_[174].ReadPointers(binaryReader, blamPointers);
            invalidName_[175].ReadPointers(binaryReader, blamPointers);
            invalidName_[176].ReadPointers(binaryReader, blamPointers);
            invalidName_[177].ReadPointers(binaryReader, blamPointers);
            invalidName_[178].ReadPointers(binaryReader, blamPointers);
            invalidName_[179].ReadPointers(binaryReader, blamPointers);
            invalidName_[180].ReadPointers(binaryReader, blamPointers);
            invalidName_[181].ReadPointers(binaryReader, blamPointers);
            invalidName_[182].ReadPointers(binaryReader, blamPointers);
            invalidName_[183].ReadPointers(binaryReader, blamPointers);
            invalidName_[184].ReadPointers(binaryReader, blamPointers);
            invalidName_[185].ReadPointers(binaryReader, blamPointers);
            invalidName_[186].ReadPointers(binaryReader, blamPointers);
            invalidName_[187].ReadPointers(binaryReader, blamPointers);
            invalidName_[188].ReadPointers(binaryReader, blamPointers);
            invalidName_[189].ReadPointers(binaryReader, blamPointers);
            invalidName_[190].ReadPointers(binaryReader, blamPointers);
            invalidName_[191].ReadPointers(binaryReader, blamPointers);
            invalidName_[192].ReadPointers(binaryReader, blamPointers);
            invalidName_[193].ReadPointers(binaryReader, blamPointers);
            invalidName_[194].ReadPointers(binaryReader, blamPointers);
            invalidName_[195].ReadPointers(binaryReader, blamPointers);
            invalidName_[196].ReadPointers(binaryReader, blamPointers);
            invalidName_[197].ReadPointers(binaryReader, blamPointers);
            invalidName_[198].ReadPointers(binaryReader, blamPointers);
            invalidName_[199].ReadPointers(binaryReader, blamPointers);
            invalidName_[200].ReadPointers(binaryReader, blamPointers);
            invalidName_[201].ReadPointers(binaryReader, blamPointers);
            invalidName_[202].ReadPointers(binaryReader, blamPointers);
            invalidName_[203].ReadPointers(binaryReader, blamPointers);
            invalidName_[204].ReadPointers(binaryReader, blamPointers);
            invalidName_[205].ReadPointers(binaryReader, blamPointers);
            invalidName_[206].ReadPointers(binaryReader, blamPointers);
            invalidName_[207].ReadPointers(binaryReader, blamPointers);
            invalidName_[208].ReadPointers(binaryReader, blamPointers);
            invalidName_[209].ReadPointers(binaryReader, blamPointers);
            invalidName_[210].ReadPointers(binaryReader, blamPointers);
            invalidName_[211].ReadPointers(binaryReader, blamPointers);
            invalidName_[212].ReadPointers(binaryReader, blamPointers);
            invalidName_[213].ReadPointers(binaryReader, blamPointers);
            invalidName_[214].ReadPointers(binaryReader, blamPointers);
            invalidName_[215].ReadPointers(binaryReader, blamPointers);
            invalidName_[216].ReadPointers(binaryReader, blamPointers);
            invalidName_[217].ReadPointers(binaryReader, blamPointers);
            invalidName_[218].ReadPointers(binaryReader, blamPointers);
            invalidName_[219].ReadPointers(binaryReader, blamPointers);
            invalidName_[220].ReadPointers(binaryReader, blamPointers);
            invalidName_[221].ReadPointers(binaryReader, blamPointers);
            invalidName_[222].ReadPointers(binaryReader, blamPointers);
            invalidName_[223].ReadPointers(binaryReader, blamPointers);
            invalidName_[224].ReadPointers(binaryReader, blamPointers);
            invalidName_[225].ReadPointers(binaryReader, blamPointers);
            invalidName_[226].ReadPointers(binaryReader, blamPointers);
            invalidName_[227].ReadPointers(binaryReader, blamPointers);
            invalidName_[228].ReadPointers(binaryReader, blamPointers);
            invalidName_[229].ReadPointers(binaryReader, blamPointers);
            invalidName_[230].ReadPointers(binaryReader, blamPointers);
            invalidName_[231].ReadPointers(binaryReader, blamPointers);
            invalidName_[232].ReadPointers(binaryReader, blamPointers);
            invalidName_[233].ReadPointers(binaryReader, blamPointers);
            invalidName_[234].ReadPointers(binaryReader, blamPointers);
            invalidName_[235].ReadPointers(binaryReader, blamPointers);
            invalidName_[236].ReadPointers(binaryReader, blamPointers);
            invalidName_[237].ReadPointers(binaryReader, blamPointers);
            invalidName_[238].ReadPointers(binaryReader, blamPointers);
            invalidName_[239].ReadPointers(binaryReader, blamPointers);
            invalidName_[240].ReadPointers(binaryReader, blamPointers);
            invalidName_[241].ReadPointers(binaryReader, blamPointers);
            invalidName_[242].ReadPointers(binaryReader, blamPointers);
            invalidName_[243].ReadPointers(binaryReader, blamPointers);
            invalidName_[244].ReadPointers(binaryReader, blamPointers);
            invalidName_[245].ReadPointers(binaryReader, blamPointers);
            invalidName_[246].ReadPointers(binaryReader, blamPointers);
            invalidName_[247].ReadPointers(binaryReader, blamPointers);
            invalidName_[248].ReadPointers(binaryReader, blamPointers);
            invalidName_[249].ReadPointers(binaryReader, blamPointers);
            invalidName_[250].ReadPointers(binaryReader, blamPointers);
            invalidName_[251].ReadPointers(binaryReader, blamPointers);
            invalidName_[252].ReadPointers(binaryReader, blamPointers);
            invalidName_[253].ReadPointers(binaryReader, blamPointers);
            invalidName_[254].ReadPointers(binaryReader, blamPointers);
            invalidName_[255].ReadPointers(binaryReader, blamPointers);
            invalidName_[256].ReadPointers(binaryReader, blamPointers);
            invalidName_[257].ReadPointers(binaryReader, blamPointers);
            invalidName_[258].ReadPointers(binaryReader, blamPointers);
            invalidName_[259].ReadPointers(binaryReader, blamPointers);
            invalidName_[260].ReadPointers(binaryReader, blamPointers);
            invalidName_[261].ReadPointers(binaryReader, blamPointers);
            invalidName_[262].ReadPointers(binaryReader, blamPointers);
            invalidName_[263].ReadPointers(binaryReader, blamPointers);
            invalidName_[264].ReadPointers(binaryReader, blamPointers);
            invalidName_[265].ReadPointers(binaryReader, blamPointers);
            invalidName_[266].ReadPointers(binaryReader, blamPointers);
            invalidName_[267].ReadPointers(binaryReader, blamPointers);
            invalidName_[268].ReadPointers(binaryReader, blamPointers);
            invalidName_[269].ReadPointers(binaryReader, blamPointers);
            invalidName_[270].ReadPointers(binaryReader, blamPointers);
            invalidName_[271].ReadPointers(binaryReader, blamPointers);
            invalidName_[272].ReadPointers(binaryReader, blamPointers);
            invalidName_[273].ReadPointers(binaryReader, blamPointers);
            invalidName_[274].ReadPointers(binaryReader, blamPointers);
            invalidName_[275].ReadPointers(binaryReader, blamPointers);
            invalidName_[276].ReadPointers(binaryReader, blamPointers);
            invalidName_[277].ReadPointers(binaryReader, blamPointers);
            invalidName_[278].ReadPointers(binaryReader, blamPointers);
            invalidName_[279].ReadPointers(binaryReader, blamPointers);
            invalidName_[280].ReadPointers(binaryReader, blamPointers);
            invalidName_[281].ReadPointers(binaryReader, blamPointers);
            invalidName_[282].ReadPointers(binaryReader, blamPointers);
            invalidName_[283].ReadPointers(binaryReader, blamPointers);
            invalidName_[284].ReadPointers(binaryReader, blamPointers);
            invalidName_[285].ReadPointers(binaryReader, blamPointers);
            invalidName_[286].ReadPointers(binaryReader, blamPointers);
            invalidName_[287].ReadPointers(binaryReader, blamPointers);
            invalidName_[288].ReadPointers(binaryReader, blamPointers);
            invalidName_[289].ReadPointers(binaryReader, blamPointers);
            invalidName_[290].ReadPointers(binaryReader, blamPointers);
            invalidName_[291].ReadPointers(binaryReader, blamPointers);
            invalidName_[292].ReadPointers(binaryReader, blamPointers);
            invalidName_[293].ReadPointers(binaryReader, blamPointers);
            invalidName_[294].ReadPointers(binaryReader, blamPointers);
            invalidName_[295].ReadPointers(binaryReader, blamPointers);
            invalidName_[296].ReadPointers(binaryReader, blamPointers);
            invalidName_[297].ReadPointers(binaryReader, blamPointers);
            invalidName_[298].ReadPointers(binaryReader, blamPointers);
            invalidName_[299].ReadPointers(binaryReader, blamPointers);
            invalidName_[300].ReadPointers(binaryReader, blamPointers);
            invalidName_[301].ReadPointers(binaryReader, blamPointers);
            invalidName_[302].ReadPointers(binaryReader, blamPointers);
            invalidName_[303].ReadPointers(binaryReader, blamPointers);
            invalidName_[304].ReadPointers(binaryReader, blamPointers);
            invalidName_[305].ReadPointers(binaryReader, blamPointers);
            invalidName_[306].ReadPointers(binaryReader, blamPointers);
            invalidName_[307].ReadPointers(binaryReader, blamPointers);
            invalidName_[308].ReadPointers(binaryReader, blamPointers);
            invalidName_[309].ReadPointers(binaryReader, blamPointers);
            invalidName_[310].ReadPointers(binaryReader, blamPointers);
            invalidName_[311].ReadPointers(binaryReader, blamPointers);
            invalidName_[312].ReadPointers(binaryReader, blamPointers);
            invalidName_[313].ReadPointers(binaryReader, blamPointers);
            invalidName_[314].ReadPointers(binaryReader, blamPointers);
            invalidName_[315].ReadPointers(binaryReader, blamPointers);
            invalidName_[316].ReadPointers(binaryReader, blamPointers);
            invalidName_[317].ReadPointers(binaryReader, blamPointers);
            invalidName_[318].ReadPointers(binaryReader, blamPointers);
            invalidName_[319].ReadPointers(binaryReader, blamPointers);
            invalidName_[320].ReadPointers(binaryReader, blamPointers);
            invalidName_[321].ReadPointers(binaryReader, blamPointers);
            invalidName_[322].ReadPointers(binaryReader, blamPointers);
            invalidName_[323].ReadPointers(binaryReader, blamPointers);
            invalidName_[324].ReadPointers(binaryReader, blamPointers);
            invalidName_[325].ReadPointers(binaryReader, blamPointers);
            invalidName_[326].ReadPointers(binaryReader, blamPointers);
            invalidName_[327].ReadPointers(binaryReader, blamPointers);
            invalidName_[328].ReadPointers(binaryReader, blamPointers);
            invalidName_[329].ReadPointers(binaryReader, blamPointers);
            invalidName_[330].ReadPointers(binaryReader, blamPointers);
            invalidName_[331].ReadPointers(binaryReader, blamPointers);
            invalidName_[332].ReadPointers(binaryReader, blamPointers);
            invalidName_[333].ReadPointers(binaryReader, blamPointers);
            invalidName_[334].ReadPointers(binaryReader, blamPointers);
            invalidName_[335].ReadPointers(binaryReader, blamPointers);
            invalidName_[336].ReadPointers(binaryReader, blamPointers);
            invalidName_[337].ReadPointers(binaryReader, blamPointers);
            invalidName_[338].ReadPointers(binaryReader, blamPointers);
            invalidName_[339].ReadPointers(binaryReader, blamPointers);
            invalidName_[340].ReadPointers(binaryReader, blamPointers);
            invalidName_[341].ReadPointers(binaryReader, blamPointers);
            invalidName_[342].ReadPointers(binaryReader, blamPointers);
            invalidName_[343].ReadPointers(binaryReader, blamPointers);
            invalidName_[344].ReadPointers(binaryReader, blamPointers);
            invalidName_[345].ReadPointers(binaryReader, blamPointers);
            invalidName_[346].ReadPointers(binaryReader, blamPointers);
            invalidName_[347].ReadPointers(binaryReader, blamPointers);
            invalidName_[348].ReadPointers(binaryReader, blamPointers);
            invalidName_[349].ReadPointers(binaryReader, blamPointers);
            invalidName_[350].ReadPointers(binaryReader, blamPointers);
            invalidName_[351].ReadPointers(binaryReader, blamPointers);
            invalidName_[352].ReadPointers(binaryReader, blamPointers);
            invalidName_[353].ReadPointers(binaryReader, blamPointers);
            invalidName_[354].ReadPointers(binaryReader, blamPointers);
            invalidName_[355].ReadPointers(binaryReader, blamPointers);
            invalidName_[356].ReadPointers(binaryReader, blamPointers);
            invalidName_[357].ReadPointers(binaryReader, blamPointers);
            invalidName_[358].ReadPointers(binaryReader, blamPointers);
            invalidName_[359].ReadPointers(binaryReader, blamPointers);
            invalidName_[360].ReadPointers(binaryReader, blamPointers);
            invalidName_[361].ReadPointers(binaryReader, blamPointers);
            invalidName_[362].ReadPointers(binaryReader, blamPointers);
            invalidName_[363].ReadPointers(binaryReader, blamPointers);
            invalidName_[364].ReadPointers(binaryReader, blamPointers);
            invalidName_[365].ReadPointers(binaryReader, blamPointers);
            invalidName_[366].ReadPointers(binaryReader, blamPointers);
            invalidName_[367].ReadPointers(binaryReader, blamPointers);
            invalidName_[368].ReadPointers(binaryReader, blamPointers);
            invalidName_[369].ReadPointers(binaryReader, blamPointers);
            invalidName_[370].ReadPointers(binaryReader, blamPointers);
            invalidName_[371].ReadPointers(binaryReader, blamPointers);
            invalidName_[372].ReadPointers(binaryReader, blamPointers);
            invalidName_[373].ReadPointers(binaryReader, blamPointers);
            invalidName_[374].ReadPointers(binaryReader, blamPointers);
            invalidName_[375].ReadPointers(binaryReader, blamPointers);
            invalidName_[376].ReadPointers(binaryReader, blamPointers);
            invalidName_[377].ReadPointers(binaryReader, blamPointers);
            invalidName_[378].ReadPointers(binaryReader, blamPointers);
            invalidName_[379].ReadPointers(binaryReader, blamPointers);
            invalidName_0[0].ReadPointers(binaryReader, blamPointers);
            invalidName_0[1].ReadPointers(binaryReader, blamPointers);
            invalidName_0[2].ReadPointers(binaryReader, blamPointers);
            invalidName_0[3].ReadPointers(binaryReader, blamPointers);
            invalidName_0[4].ReadPointers(binaryReader, blamPointers);
            invalidName_0[5].ReadPointers(binaryReader, blamPointers);
            invalidName_0[6].ReadPointers(binaryReader, blamPointers);
            invalidName_0[7].ReadPointers(binaryReader, blamPointers);
            invalidName_0[8].ReadPointers(binaryReader, blamPointers);
            invalidName_0[9].ReadPointers(binaryReader, blamPointers);
            invalidName_0[10].ReadPointers(binaryReader, blamPointers);
            invalidName_0[11].ReadPointers(binaryReader, blamPointers);
            invalidName_0[12].ReadPointers(binaryReader, blamPointers);
            invalidName_0[13].ReadPointers(binaryReader, blamPointers);
            invalidName_0[14].ReadPointers(binaryReader, blamPointers);
            invalidName_0[15].ReadPointers(binaryReader, blamPointers);
            invalidName_0[16].ReadPointers(binaryReader, blamPointers);
            invalidName_0[17].ReadPointers(binaryReader, blamPointers);
            invalidName_0[18].ReadPointers(binaryReader, blamPointers);
            invalidName_0[19].ReadPointers(binaryReader, blamPointers);
            invalidName_0[20].ReadPointers(binaryReader, blamPointers);
            invalidName_0[21].ReadPointers(binaryReader, blamPointers);
            invalidName_0[22].ReadPointers(binaryReader, blamPointers);
            invalidName_0[23].ReadPointers(binaryReader, blamPointers);
            invalidName_0[24].ReadPointers(binaryReader, blamPointers);
            invalidName_0[25].ReadPointers(binaryReader, blamPointers);
            invalidName_0[26].ReadPointers(binaryReader, blamPointers);
            invalidName_0[27].ReadPointers(binaryReader, blamPointers);
            invalidName_0[28].ReadPointers(binaryReader, blamPointers);
            invalidName_0[29].ReadPointers(binaryReader, blamPointers);
            invalidName_0[30].ReadPointers(binaryReader, blamPointers);
            invalidName_0[31].ReadPointers(binaryReader, blamPointers);
            invalidName_0[32].ReadPointers(binaryReader, blamPointers);
            invalidName_0[33].ReadPointers(binaryReader, blamPointers);
            invalidName_0[34].ReadPointers(binaryReader, blamPointers);
            invalidName_0[35].ReadPointers(binaryReader, blamPointers);
            invalidName_0[36].ReadPointers(binaryReader, blamPointers);
            invalidName_0[37].ReadPointers(binaryReader, blamPointers);
            invalidName_0[38].ReadPointers(binaryReader, blamPointers);
            invalidName_0[39].ReadPointers(binaryReader, blamPointers);
            invalidName_0[40].ReadPointers(binaryReader, blamPointers);
            invalidName_0[41].ReadPointers(binaryReader, blamPointers);
            invalidName_0[42].ReadPointers(binaryReader, blamPointers);
            invalidName_0[43].ReadPointers(binaryReader, blamPointers);
            invalidName_0[44].ReadPointers(binaryReader, blamPointers);
            invalidName_0[45].ReadPointers(binaryReader, blamPointers);
            invalidName_0[46].ReadPointers(binaryReader, blamPointers);
            invalidName_0[47].ReadPointers(binaryReader, blamPointers);
            invalidName_0[48].ReadPointers(binaryReader, blamPointers);
            invalidName_0[49].ReadPointers(binaryReader, blamPointers);
            invalidName_0[50].ReadPointers(binaryReader, blamPointers);
            invalidName_0[51].ReadPointers(binaryReader, blamPointers);
            invalidName_0[52].ReadPointers(binaryReader, blamPointers);
            invalidName_0[53].ReadPointers(binaryReader, blamPointers);
            invalidName_0[54].ReadPointers(binaryReader, blamPointers);
            invalidName_0[55].ReadPointers(binaryReader, blamPointers);
            invalidName_0[56].ReadPointers(binaryReader, blamPointers);
            invalidName_0[57].ReadPointers(binaryReader, blamPointers);
            invalidName_0[58].ReadPointers(binaryReader, blamPointers);
            invalidName_0[59].ReadPointers(binaryReader, blamPointers);
            invalidName_0[60].ReadPointers(binaryReader, blamPointers);
            invalidName_0[61].ReadPointers(binaryReader, blamPointers);
            invalidName_0[62].ReadPointers(binaryReader, blamPointers);
            invalidName_0[63].ReadPointers(binaryReader, blamPointers);
            invalidName_0[64].ReadPointers(binaryReader, blamPointers);
            invalidName_0[65].ReadPointers(binaryReader, blamPointers);
            invalidName_0[66].ReadPointers(binaryReader, blamPointers);
            invalidName_0[67].ReadPointers(binaryReader, blamPointers);
            invalidName_0[68].ReadPointers(binaryReader, blamPointers);
            invalidName_0[69].ReadPointers(binaryReader, blamPointers);
            invalidName_0[70].ReadPointers(binaryReader, blamPointers);
            invalidName_0[71].ReadPointers(binaryReader, blamPointers);
            invalidName_0[72].ReadPointers(binaryReader, blamPointers);
            invalidName_0[73].ReadPointers(binaryReader, blamPointers);
            invalidName_0[74].ReadPointers(binaryReader, blamPointers);
            invalidName_0[75].ReadPointers(binaryReader, blamPointers);
            invalidName_0[76].ReadPointers(binaryReader, blamPointers);
            invalidName_0[77].ReadPointers(binaryReader, blamPointers);
            invalidName_0[78].ReadPointers(binaryReader, blamPointers);
            invalidName_0[79].ReadPointers(binaryReader, blamPointers);
            invalidName_0[80].ReadPointers(binaryReader, blamPointers);
            invalidName_0[81].ReadPointers(binaryReader, blamPointers);
            invalidName_0[82].ReadPointers(binaryReader, blamPointers);
            invalidName_0[83].ReadPointers(binaryReader, blamPointers);
        }
        public override int Write(BinaryWriter binaryWriter, int nextAddress)
        {
            base.Write(binaryWriter, nextAddress);
using(binaryWriter.BaseStream.Pin())
            {
                binaryWriter.Write((Int16)type);
                binaryWriter.Write((Int16)flags);
                nextAddress = Guerilla.WriteData(binaryWriter, text, nextAddress);
                binaryWriter.Write(sourceFilename);
                binaryWriter.Write(sourceLineNumber);
                nextAddress = Guerilla.WriteBlockArray<ErrorReportVerticesBlock>(binaryWriter, vertices, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<ErrorReportVectorsBlock>(binaryWriter, vectors, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<ErrorReportLinesBlock>(binaryWriter, lines, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<ErrorReportTrianglesBlock>(binaryWriter, triangles, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<ErrorReportQuadsBlock>(binaryWriter, quads, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<ErrorReportCommentsBlock>(binaryWriter, comments, nextAddress);
                binaryWriter.Write(invalidName_, 0, 380);
                binaryWriter.Write(reportKey);
                binaryWriter.Write(nodeIndex);
                binaryWriter.Write(boundsX);
                binaryWriter.Write(boundsY);
                binaryWriter.Write(boundsZ);
                binaryWriter.Write(color);
                binaryWriter.Write(invalidName_0, 0, 84);
                return nextAddress;
            }
        }
        internal enum Type : short
        {
            Silent = 0,
            Comment = 1,
            Warning = 2,
            Error = 3,
        };
        [FlagsAttribute]
        internal enum Flags : short
        {
            Rendered = 1,
            TangentSpace = 2,
            Noncritical = 4,
            LightmapLight = 8,
            ReportKeyIsValid = 16,
        };
    };
}
