// ReSharper disable All
using Moonfish.Model;
using Moonfish.Tags.BlamExtension;
using Moonfish.Tags;
using OpenTK;
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

namespace Moonfish.Guerilla.Tags
{
    public partial class GlobalWeatherBackgroundPlateBlock : GlobalWeatherBackgroundPlateBlockBase
    {
        public GlobalWeatherBackgroundPlateBlock() : base()
        {
        }
    };
    [LayoutAttribute(Size = 936, Alignment = 4)]
    public class GlobalWeatherBackgroundPlateBlockBase : GuerillaBlock
    {
        [TagReference("bitm")]
        internal Moonfish.Tags.TagReference texture0;
        [TagReference("bitm")]
        internal Moonfish.Tags.TagReference texture1;
        [TagReference("bitm")]
        internal Moonfish.Tags.TagReference texture2;
        internal float platePositions0;
        internal float platePositions1;
        internal float platePositions2;
        internal OpenTK.Vector3 moveSpeed0;
        internal OpenTK.Vector3 moveSpeed1;
        internal OpenTK.Vector3 moveSpeed2;
        internal float textureScale0;
        internal float textureScale1;
        internal float textureScale2;
        internal OpenTK.Vector3 jitter0;
        internal OpenTK.Vector3 jitter1;
        internal OpenTK.Vector3 jitter2;
        internal float plateZNear;
        internal float plateZFar;
        internal float depthBlendZNear;
        internal float depthBlendZFar;
        internal float opacity0;
        internal float opacity1;
        internal float opacity2;
        internal Flags flags;
        internal Moonfish.Tags.ColourR8G8B8 tintColor0;
        internal Moonfish.Tags.ColourR8G8B8 tintColor1;
        internal Moonfish.Tags.ColourR8G8B8 tintColor2;
        internal float mass1;
        internal float mass2;
        internal float mass3;
        internal byte[] invalidName_;
        public override int SerializedSize { get { return 936; } }
        public override int Alignment { get { return 4; } }
        public GlobalWeatherBackgroundPlateBlockBase() : base()
        {
        }
        public override Queue<BlamPointer> ReadFields(BinaryReader binaryReader)
        {
            var blamPointers = new Queue<BlamPointer>(base.ReadFields(binaryReader));
            texture0 = binaryReader.ReadTagReference();
            texture1 = binaryReader.ReadTagReference();
            texture2 = binaryReader.ReadTagReference();
            platePositions0 = binaryReader.ReadSingle();
            platePositions1 = binaryReader.ReadSingle();
            platePositions2 = binaryReader.ReadSingle();
            moveSpeed0 = binaryReader.ReadVector3();
            moveSpeed1 = binaryReader.ReadVector3();
            moveSpeed2 = binaryReader.ReadVector3();
            textureScale0 = binaryReader.ReadSingle();
            textureScale1 = binaryReader.ReadSingle();
            textureScale2 = binaryReader.ReadSingle();
            jitter0 = binaryReader.ReadVector3();
            jitter1 = binaryReader.ReadVector3();
            jitter2 = binaryReader.ReadVector3();
            plateZNear = binaryReader.ReadSingle();
            plateZFar = binaryReader.ReadSingle();
            depthBlendZNear = binaryReader.ReadSingle();
            depthBlendZFar = binaryReader.ReadSingle();
            opacity0 = binaryReader.ReadSingle();
            opacity1 = binaryReader.ReadSingle();
            opacity2 = binaryReader.ReadSingle();
            flags = (Flags)binaryReader.ReadInt32();
            tintColor0 = binaryReader.ReadColorR8G8B8();
            tintColor1 = binaryReader.ReadColorR8G8B8();
            tintColor2 = binaryReader.ReadColorR8G8B8();
            mass1 = binaryReader.ReadSingle();
            mass2 = binaryReader.ReadSingle();
            mass3 = binaryReader.ReadSingle();
            invalidName_ = binaryReader.ReadBytes(736);
            return blamPointers;
        }
        public override void ReadPointers(BinaryReader binaryReader, Queue<BlamPointer> blamPointers)
        {
            base.ReadPointers(binaryReader, blamPointers);
            invalidName_[0].ReadPointers(binaryReader, blamPointers);
            invalidName_[1].ReadPointers(binaryReader, blamPointers);
            invalidName_[2].ReadPointers(binaryReader, blamPointers);
            invalidName_[3].ReadPointers(binaryReader, blamPointers);
            invalidName_[4].ReadPointers(binaryReader, blamPointers);
            invalidName_[5].ReadPointers(binaryReader, blamPointers);
            invalidName_[6].ReadPointers(binaryReader, blamPointers);
            invalidName_[7].ReadPointers(binaryReader, blamPointers);
            invalidName_[8].ReadPointers(binaryReader, blamPointers);
            invalidName_[9].ReadPointers(binaryReader, blamPointers);
            invalidName_[10].ReadPointers(binaryReader, blamPointers);
            invalidName_[11].ReadPointers(binaryReader, blamPointers);
            invalidName_[12].ReadPointers(binaryReader, blamPointers);
            invalidName_[13].ReadPointers(binaryReader, blamPointers);
            invalidName_[14].ReadPointers(binaryReader, blamPointers);
            invalidName_[15].ReadPointers(binaryReader, blamPointers);
            invalidName_[16].ReadPointers(binaryReader, blamPointers);
            invalidName_[17].ReadPointers(binaryReader, blamPointers);
            invalidName_[18].ReadPointers(binaryReader, blamPointers);
            invalidName_[19].ReadPointers(binaryReader, blamPointers);
            invalidName_[20].ReadPointers(binaryReader, blamPointers);
            invalidName_[21].ReadPointers(binaryReader, blamPointers);
            invalidName_[22].ReadPointers(binaryReader, blamPointers);
            invalidName_[23].ReadPointers(binaryReader, blamPointers);
            invalidName_[24].ReadPointers(binaryReader, blamPointers);
            invalidName_[25].ReadPointers(binaryReader, blamPointers);
            invalidName_[26].ReadPointers(binaryReader, blamPointers);
            invalidName_[27].ReadPointers(binaryReader, blamPointers);
            invalidName_[28].ReadPointers(binaryReader, blamPointers);
            invalidName_[29].ReadPointers(binaryReader, blamPointers);
            invalidName_[30].ReadPointers(binaryReader, blamPointers);
            invalidName_[31].ReadPointers(binaryReader, blamPointers);
            invalidName_[32].ReadPointers(binaryReader, blamPointers);
            invalidName_[33].ReadPointers(binaryReader, blamPointers);
            invalidName_[34].ReadPointers(binaryReader, blamPointers);
            invalidName_[35].ReadPointers(binaryReader, blamPointers);
            invalidName_[36].ReadPointers(binaryReader, blamPointers);
            invalidName_[37].ReadPointers(binaryReader, blamPointers);
            invalidName_[38].ReadPointers(binaryReader, blamPointers);
            invalidName_[39].ReadPointers(binaryReader, blamPointers);
            invalidName_[40].ReadPointers(binaryReader, blamPointers);
            invalidName_[41].ReadPointers(binaryReader, blamPointers);
            invalidName_[42].ReadPointers(binaryReader, blamPointers);
            invalidName_[43].ReadPointers(binaryReader, blamPointers);
            invalidName_[44].ReadPointers(binaryReader, blamPointers);
            invalidName_[45].ReadPointers(binaryReader, blamPointers);
            invalidName_[46].ReadPointers(binaryReader, blamPointers);
            invalidName_[47].ReadPointers(binaryReader, blamPointers);
            invalidName_[48].ReadPointers(binaryReader, blamPointers);
            invalidName_[49].ReadPointers(binaryReader, blamPointers);
            invalidName_[50].ReadPointers(binaryReader, blamPointers);
            invalidName_[51].ReadPointers(binaryReader, blamPointers);
            invalidName_[52].ReadPointers(binaryReader, blamPointers);
            invalidName_[53].ReadPointers(binaryReader, blamPointers);
            invalidName_[54].ReadPointers(binaryReader, blamPointers);
            invalidName_[55].ReadPointers(binaryReader, blamPointers);
            invalidName_[56].ReadPointers(binaryReader, blamPointers);
            invalidName_[57].ReadPointers(binaryReader, blamPointers);
            invalidName_[58].ReadPointers(binaryReader, blamPointers);
            invalidName_[59].ReadPointers(binaryReader, blamPointers);
            invalidName_[60].ReadPointers(binaryReader, blamPointers);
            invalidName_[61].ReadPointers(binaryReader, blamPointers);
            invalidName_[62].ReadPointers(binaryReader, blamPointers);
            invalidName_[63].ReadPointers(binaryReader, blamPointers);
            invalidName_[64].ReadPointers(binaryReader, blamPointers);
            invalidName_[65].ReadPointers(binaryReader, blamPointers);
            invalidName_[66].ReadPointers(binaryReader, blamPointers);
            invalidName_[67].ReadPointers(binaryReader, blamPointers);
            invalidName_[68].ReadPointers(binaryReader, blamPointers);
            invalidName_[69].ReadPointers(binaryReader, blamPointers);
            invalidName_[70].ReadPointers(binaryReader, blamPointers);
            invalidName_[71].ReadPointers(binaryReader, blamPointers);
            invalidName_[72].ReadPointers(binaryReader, blamPointers);
            invalidName_[73].ReadPointers(binaryReader, blamPointers);
            invalidName_[74].ReadPointers(binaryReader, blamPointers);
            invalidName_[75].ReadPointers(binaryReader, blamPointers);
            invalidName_[76].ReadPointers(binaryReader, blamPointers);
            invalidName_[77].ReadPointers(binaryReader, blamPointers);
            invalidName_[78].ReadPointers(binaryReader, blamPointers);
            invalidName_[79].ReadPointers(binaryReader, blamPointers);
            invalidName_[80].ReadPointers(binaryReader, blamPointers);
            invalidName_[81].ReadPointers(binaryReader, blamPointers);
            invalidName_[82].ReadPointers(binaryReader, blamPointers);
            invalidName_[83].ReadPointers(binaryReader, blamPointers);
            invalidName_[84].ReadPointers(binaryReader, blamPointers);
            invalidName_[85].ReadPointers(binaryReader, blamPointers);
            invalidName_[86].ReadPointers(binaryReader, blamPointers);
            invalidName_[87].ReadPointers(binaryReader, blamPointers);
            invalidName_[88].ReadPointers(binaryReader, blamPointers);
            invalidName_[89].ReadPointers(binaryReader, blamPointers);
            invalidName_[90].ReadPointers(binaryReader, blamPointers);
            invalidName_[91].ReadPointers(binaryReader, blamPointers);
            invalidName_[92].ReadPointers(binaryReader, blamPointers);
            invalidName_[93].ReadPointers(binaryReader, blamPointers);
            invalidName_[94].ReadPointers(binaryReader, blamPointers);
            invalidName_[95].ReadPointers(binaryReader, blamPointers);
            invalidName_[96].ReadPointers(binaryReader, blamPointers);
            invalidName_[97].ReadPointers(binaryReader, blamPointers);
            invalidName_[98].ReadPointers(binaryReader, blamPointers);
            invalidName_[99].ReadPointers(binaryReader, blamPointers);
            invalidName_[100].ReadPointers(binaryReader, blamPointers);
            invalidName_[101].ReadPointers(binaryReader, blamPointers);
            invalidName_[102].ReadPointers(binaryReader, blamPointers);
            invalidName_[103].ReadPointers(binaryReader, blamPointers);
            invalidName_[104].ReadPointers(binaryReader, blamPointers);
            invalidName_[105].ReadPointers(binaryReader, blamPointers);
            invalidName_[106].ReadPointers(binaryReader, blamPointers);
            invalidName_[107].ReadPointers(binaryReader, blamPointers);
            invalidName_[108].ReadPointers(binaryReader, blamPointers);
            invalidName_[109].ReadPointers(binaryReader, blamPointers);
            invalidName_[110].ReadPointers(binaryReader, blamPointers);
            invalidName_[111].ReadPointers(binaryReader, blamPointers);
            invalidName_[112].ReadPointers(binaryReader, blamPointers);
            invalidName_[113].ReadPointers(binaryReader, blamPointers);
            invalidName_[114].ReadPointers(binaryReader, blamPointers);
            invalidName_[115].ReadPointers(binaryReader, blamPointers);
            invalidName_[116].ReadPointers(binaryReader, blamPointers);
            invalidName_[117].ReadPointers(binaryReader, blamPointers);
            invalidName_[118].ReadPointers(binaryReader, blamPointers);
            invalidName_[119].ReadPointers(binaryReader, blamPointers);
            invalidName_[120].ReadPointers(binaryReader, blamPointers);
            invalidName_[121].ReadPointers(binaryReader, blamPointers);
            invalidName_[122].ReadPointers(binaryReader, blamPointers);
            invalidName_[123].ReadPointers(binaryReader, blamPointers);
            invalidName_[124].ReadPointers(binaryReader, blamPointers);
            invalidName_[125].ReadPointers(binaryReader, blamPointers);
            invalidName_[126].ReadPointers(binaryReader, blamPointers);
            invalidName_[127].ReadPointers(binaryReader, blamPointers);
            invalidName_[128].ReadPointers(binaryReader, blamPointers);
            invalidName_[129].ReadPointers(binaryReader, blamPointers);
            invalidName_[130].ReadPointers(binaryReader, blamPointers);
            invalidName_[131].ReadPointers(binaryReader, blamPointers);
            invalidName_[132].ReadPointers(binaryReader, blamPointers);
            invalidName_[133].ReadPointers(binaryReader, blamPointers);
            invalidName_[134].ReadPointers(binaryReader, blamPointers);
            invalidName_[135].ReadPointers(binaryReader, blamPointers);
            invalidName_[136].ReadPointers(binaryReader, blamPointers);
            invalidName_[137].ReadPointers(binaryReader, blamPointers);
            invalidName_[138].ReadPointers(binaryReader, blamPointers);
            invalidName_[139].ReadPointers(binaryReader, blamPointers);
            invalidName_[140].ReadPointers(binaryReader, blamPointers);
            invalidName_[141].ReadPointers(binaryReader, blamPointers);
            invalidName_[142].ReadPointers(binaryReader, blamPointers);
            invalidName_[143].ReadPointers(binaryReader, blamPointers);
            invalidName_[144].ReadPointers(binaryReader, blamPointers);
            invalidName_[145].ReadPointers(binaryReader, blamPointers);
            invalidName_[146].ReadPointers(binaryReader, blamPointers);
            invalidName_[147].ReadPointers(binaryReader, blamPointers);
            invalidName_[148].ReadPointers(binaryReader, blamPointers);
            invalidName_[149].ReadPointers(binaryReader, blamPointers);
            invalidName_[150].ReadPointers(binaryReader, blamPointers);
            invalidName_[151].ReadPointers(binaryReader, blamPointers);
            invalidName_[152].ReadPointers(binaryReader, blamPointers);
            invalidName_[153].ReadPointers(binaryReader, blamPointers);
            invalidName_[154].ReadPointers(binaryReader, blamPointers);
            invalidName_[155].ReadPointers(binaryReader, blamPointers);
            invalidName_[156].ReadPointers(binaryReader, blamPointers);
            invalidName_[157].ReadPointers(binaryReader, blamPointers);
            invalidName_[158].ReadPointers(binaryReader, blamPointers);
            invalidName_[159].ReadPointers(binaryReader, blamPointers);
            invalidName_[160].ReadPointers(binaryReader, blamPointers);
            invalidName_[161].ReadPointers(binaryReader, blamPointers);
            invalidName_[162].ReadPointers(binaryReader, blamPointers);
            invalidName_[163].ReadPointers(binaryReader, blamPointers);
            invalidName_[164].ReadPointers(binaryReader, blamPointers);
            invalidName_[165].ReadPointers(binaryReader, blamPointers);
            invalidName_[166].ReadPointers(binaryReader, blamPointers);
            invalidName_[167].ReadPointers(binaryReader, blamPointers);
            invalidName_[168].ReadPointers(binaryReader, blamPointers);
            invalidName_[169].ReadPointers(binaryReader, blamPointers);
            invalidName_[170].ReadPointers(binaryReader, blamPointers);
            invalidName_[171].ReadPointers(binaryReader, blamPointers);
            invalidName_[172].ReadPointers(binaryReader, blamPointers);
            invalidName_[173].ReadPointers(binaryReader, blamPointers);
            invalidName_[174].ReadPointers(binaryReader, blamPointers);
            invalidName_[175].ReadPointers(binaryReader, blamPointers);
            invalidName_[176].ReadPointers(binaryReader, blamPointers);
            invalidName_[177].ReadPointers(binaryReader, blamPointers);
            invalidName_[178].ReadPointers(binaryReader, blamPointers);
            invalidName_[179].ReadPointers(binaryReader, blamPointers);
            invalidName_[180].ReadPointers(binaryReader, blamPointers);
            invalidName_[181].ReadPointers(binaryReader, blamPointers);
            invalidName_[182].ReadPointers(binaryReader, blamPointers);
            invalidName_[183].ReadPointers(binaryReader, blamPointers);
            invalidName_[184].ReadPointers(binaryReader, blamPointers);
            invalidName_[185].ReadPointers(binaryReader, blamPointers);
            invalidName_[186].ReadPointers(binaryReader, blamPointers);
            invalidName_[187].ReadPointers(binaryReader, blamPointers);
            invalidName_[188].ReadPointers(binaryReader, blamPointers);
            invalidName_[189].ReadPointers(binaryReader, blamPointers);
            invalidName_[190].ReadPointers(binaryReader, blamPointers);
            invalidName_[191].ReadPointers(binaryReader, blamPointers);
            invalidName_[192].ReadPointers(binaryReader, blamPointers);
            invalidName_[193].ReadPointers(binaryReader, blamPointers);
            invalidName_[194].ReadPointers(binaryReader, blamPointers);
            invalidName_[195].ReadPointers(binaryReader, blamPointers);
            invalidName_[196].ReadPointers(binaryReader, blamPointers);
            invalidName_[197].ReadPointers(binaryReader, blamPointers);
            invalidName_[198].ReadPointers(binaryReader, blamPointers);
            invalidName_[199].ReadPointers(binaryReader, blamPointers);
            invalidName_[200].ReadPointers(binaryReader, blamPointers);
            invalidName_[201].ReadPointers(binaryReader, blamPointers);
            invalidName_[202].ReadPointers(binaryReader, blamPointers);
            invalidName_[203].ReadPointers(binaryReader, blamPointers);
            invalidName_[204].ReadPointers(binaryReader, blamPointers);
            invalidName_[205].ReadPointers(binaryReader, blamPointers);
            invalidName_[206].ReadPointers(binaryReader, blamPointers);
            invalidName_[207].ReadPointers(binaryReader, blamPointers);
            invalidName_[208].ReadPointers(binaryReader, blamPointers);
            invalidName_[209].ReadPointers(binaryReader, blamPointers);
            invalidName_[210].ReadPointers(binaryReader, blamPointers);
            invalidName_[211].ReadPointers(binaryReader, blamPointers);
            invalidName_[212].ReadPointers(binaryReader, blamPointers);
            invalidName_[213].ReadPointers(binaryReader, blamPointers);
            invalidName_[214].ReadPointers(binaryReader, blamPointers);
            invalidName_[215].ReadPointers(binaryReader, blamPointers);
            invalidName_[216].ReadPointers(binaryReader, blamPointers);
            invalidName_[217].ReadPointers(binaryReader, blamPointers);
            invalidName_[218].ReadPointers(binaryReader, blamPointers);
            invalidName_[219].ReadPointers(binaryReader, blamPointers);
            invalidName_[220].ReadPointers(binaryReader, blamPointers);
            invalidName_[221].ReadPointers(binaryReader, blamPointers);
            invalidName_[222].ReadPointers(binaryReader, blamPointers);
            invalidName_[223].ReadPointers(binaryReader, blamPointers);
            invalidName_[224].ReadPointers(binaryReader, blamPointers);
            invalidName_[225].ReadPointers(binaryReader, blamPointers);
            invalidName_[226].ReadPointers(binaryReader, blamPointers);
            invalidName_[227].ReadPointers(binaryReader, blamPointers);
            invalidName_[228].ReadPointers(binaryReader, blamPointers);
            invalidName_[229].ReadPointers(binaryReader, blamPointers);
            invalidName_[230].ReadPointers(binaryReader, blamPointers);
            invalidName_[231].ReadPointers(binaryReader, blamPointers);
            invalidName_[232].ReadPointers(binaryReader, blamPointers);
            invalidName_[233].ReadPointers(binaryReader, blamPointers);
            invalidName_[234].ReadPointers(binaryReader, blamPointers);
            invalidName_[235].ReadPointers(binaryReader, blamPointers);
            invalidName_[236].ReadPointers(binaryReader, blamPointers);
            invalidName_[237].ReadPointers(binaryReader, blamPointers);
            invalidName_[238].ReadPointers(binaryReader, blamPointers);
            invalidName_[239].ReadPointers(binaryReader, blamPointers);
            invalidName_[240].ReadPointers(binaryReader, blamPointers);
            invalidName_[241].ReadPointers(binaryReader, blamPointers);
            invalidName_[242].ReadPointers(binaryReader, blamPointers);
            invalidName_[243].ReadPointers(binaryReader, blamPointers);
            invalidName_[244].ReadPointers(binaryReader, blamPointers);
            invalidName_[245].ReadPointers(binaryReader, blamPointers);
            invalidName_[246].ReadPointers(binaryReader, blamPointers);
            invalidName_[247].ReadPointers(binaryReader, blamPointers);
            invalidName_[248].ReadPointers(binaryReader, blamPointers);
            invalidName_[249].ReadPointers(binaryReader, blamPointers);
            invalidName_[250].ReadPointers(binaryReader, blamPointers);
            invalidName_[251].ReadPointers(binaryReader, blamPointers);
            invalidName_[252].ReadPointers(binaryReader, blamPointers);
            invalidName_[253].ReadPointers(binaryReader, blamPointers);
            invalidName_[254].ReadPointers(binaryReader, blamPointers);
            invalidName_[255].ReadPointers(binaryReader, blamPointers);
            invalidName_[256].ReadPointers(binaryReader, blamPointers);
            invalidName_[257].ReadPointers(binaryReader, blamPointers);
            invalidName_[258].ReadPointers(binaryReader, blamPointers);
            invalidName_[259].ReadPointers(binaryReader, blamPointers);
            invalidName_[260].ReadPointers(binaryReader, blamPointers);
            invalidName_[261].ReadPointers(binaryReader, blamPointers);
            invalidName_[262].ReadPointers(binaryReader, blamPointers);
            invalidName_[263].ReadPointers(binaryReader, blamPointers);
            invalidName_[264].ReadPointers(binaryReader, blamPointers);
            invalidName_[265].ReadPointers(binaryReader, blamPointers);
            invalidName_[266].ReadPointers(binaryReader, blamPointers);
            invalidName_[267].ReadPointers(binaryReader, blamPointers);
            invalidName_[268].ReadPointers(binaryReader, blamPointers);
            invalidName_[269].ReadPointers(binaryReader, blamPointers);
            invalidName_[270].ReadPointers(binaryReader, blamPointers);
            invalidName_[271].ReadPointers(binaryReader, blamPointers);
            invalidName_[272].ReadPointers(binaryReader, blamPointers);
            invalidName_[273].ReadPointers(binaryReader, blamPointers);
            invalidName_[274].ReadPointers(binaryReader, blamPointers);
            invalidName_[275].ReadPointers(binaryReader, blamPointers);
            invalidName_[276].ReadPointers(binaryReader, blamPointers);
            invalidName_[277].ReadPointers(binaryReader, blamPointers);
            invalidName_[278].ReadPointers(binaryReader, blamPointers);
            invalidName_[279].ReadPointers(binaryReader, blamPointers);
            invalidName_[280].ReadPointers(binaryReader, blamPointers);
            invalidName_[281].ReadPointers(binaryReader, blamPointers);
            invalidName_[282].ReadPointers(binaryReader, blamPointers);
            invalidName_[283].ReadPointers(binaryReader, blamPointers);
            invalidName_[284].ReadPointers(binaryReader, blamPointers);
            invalidName_[285].ReadPointers(binaryReader, blamPointers);
            invalidName_[286].ReadPointers(binaryReader, blamPointers);
            invalidName_[287].ReadPointers(binaryReader, blamPointers);
            invalidName_[288].ReadPointers(binaryReader, blamPointers);
            invalidName_[289].ReadPointers(binaryReader, blamPointers);
            invalidName_[290].ReadPointers(binaryReader, blamPointers);
            invalidName_[291].ReadPointers(binaryReader, blamPointers);
            invalidName_[292].ReadPointers(binaryReader, blamPointers);
            invalidName_[293].ReadPointers(binaryReader, blamPointers);
            invalidName_[294].ReadPointers(binaryReader, blamPointers);
            invalidName_[295].ReadPointers(binaryReader, blamPointers);
            invalidName_[296].ReadPointers(binaryReader, blamPointers);
            invalidName_[297].ReadPointers(binaryReader, blamPointers);
            invalidName_[298].ReadPointers(binaryReader, blamPointers);
            invalidName_[299].ReadPointers(binaryReader, blamPointers);
            invalidName_[300].ReadPointers(binaryReader, blamPointers);
            invalidName_[301].ReadPointers(binaryReader, blamPointers);
            invalidName_[302].ReadPointers(binaryReader, blamPointers);
            invalidName_[303].ReadPointers(binaryReader, blamPointers);
            invalidName_[304].ReadPointers(binaryReader, blamPointers);
            invalidName_[305].ReadPointers(binaryReader, blamPointers);
            invalidName_[306].ReadPointers(binaryReader, blamPointers);
            invalidName_[307].ReadPointers(binaryReader, blamPointers);
            invalidName_[308].ReadPointers(binaryReader, blamPointers);
            invalidName_[309].ReadPointers(binaryReader, blamPointers);
            invalidName_[310].ReadPointers(binaryReader, blamPointers);
            invalidName_[311].ReadPointers(binaryReader, blamPointers);
            invalidName_[312].ReadPointers(binaryReader, blamPointers);
            invalidName_[313].ReadPointers(binaryReader, blamPointers);
            invalidName_[314].ReadPointers(binaryReader, blamPointers);
            invalidName_[315].ReadPointers(binaryReader, blamPointers);
            invalidName_[316].ReadPointers(binaryReader, blamPointers);
            invalidName_[317].ReadPointers(binaryReader, blamPointers);
            invalidName_[318].ReadPointers(binaryReader, blamPointers);
            invalidName_[319].ReadPointers(binaryReader, blamPointers);
            invalidName_[320].ReadPointers(binaryReader, blamPointers);
            invalidName_[321].ReadPointers(binaryReader, blamPointers);
            invalidName_[322].ReadPointers(binaryReader, blamPointers);
            invalidName_[323].ReadPointers(binaryReader, blamPointers);
            invalidName_[324].ReadPointers(binaryReader, blamPointers);
            invalidName_[325].ReadPointers(binaryReader, blamPointers);
            invalidName_[326].ReadPointers(binaryReader, blamPointers);
            invalidName_[327].ReadPointers(binaryReader, blamPointers);
            invalidName_[328].ReadPointers(binaryReader, blamPointers);
            invalidName_[329].ReadPointers(binaryReader, blamPointers);
            invalidName_[330].ReadPointers(binaryReader, blamPointers);
            invalidName_[331].ReadPointers(binaryReader, blamPointers);
            invalidName_[332].ReadPointers(binaryReader, blamPointers);
            invalidName_[333].ReadPointers(binaryReader, blamPointers);
            invalidName_[334].ReadPointers(binaryReader, blamPointers);
            invalidName_[335].ReadPointers(binaryReader, blamPointers);
            invalidName_[336].ReadPointers(binaryReader, blamPointers);
            invalidName_[337].ReadPointers(binaryReader, blamPointers);
            invalidName_[338].ReadPointers(binaryReader, blamPointers);
            invalidName_[339].ReadPointers(binaryReader, blamPointers);
            invalidName_[340].ReadPointers(binaryReader, blamPointers);
            invalidName_[341].ReadPointers(binaryReader, blamPointers);
            invalidName_[342].ReadPointers(binaryReader, blamPointers);
            invalidName_[343].ReadPointers(binaryReader, blamPointers);
            invalidName_[344].ReadPointers(binaryReader, blamPointers);
            invalidName_[345].ReadPointers(binaryReader, blamPointers);
            invalidName_[346].ReadPointers(binaryReader, blamPointers);
            invalidName_[347].ReadPointers(binaryReader, blamPointers);
            invalidName_[348].ReadPointers(binaryReader, blamPointers);
            invalidName_[349].ReadPointers(binaryReader, blamPointers);
            invalidName_[350].ReadPointers(binaryReader, blamPointers);
            invalidName_[351].ReadPointers(binaryReader, blamPointers);
            invalidName_[352].ReadPointers(binaryReader, blamPointers);
            invalidName_[353].ReadPointers(binaryReader, blamPointers);
            invalidName_[354].ReadPointers(binaryReader, blamPointers);
            invalidName_[355].ReadPointers(binaryReader, blamPointers);
            invalidName_[356].ReadPointers(binaryReader, blamPointers);
            invalidName_[357].ReadPointers(binaryReader, blamPointers);
            invalidName_[358].ReadPointers(binaryReader, blamPointers);
            invalidName_[359].ReadPointers(binaryReader, blamPointers);
            invalidName_[360].ReadPointers(binaryReader, blamPointers);
            invalidName_[361].ReadPointers(binaryReader, blamPointers);
            invalidName_[362].ReadPointers(binaryReader, blamPointers);
            invalidName_[363].ReadPointers(binaryReader, blamPointers);
            invalidName_[364].ReadPointers(binaryReader, blamPointers);
            invalidName_[365].ReadPointers(binaryReader, blamPointers);
            invalidName_[366].ReadPointers(binaryReader, blamPointers);
            invalidName_[367].ReadPointers(binaryReader, blamPointers);
            invalidName_[368].ReadPointers(binaryReader, blamPointers);
            invalidName_[369].ReadPointers(binaryReader, blamPointers);
            invalidName_[370].ReadPointers(binaryReader, blamPointers);
            invalidName_[371].ReadPointers(binaryReader, blamPointers);
            invalidName_[372].ReadPointers(binaryReader, blamPointers);
            invalidName_[373].ReadPointers(binaryReader, blamPointers);
            invalidName_[374].ReadPointers(binaryReader, blamPointers);
            invalidName_[375].ReadPointers(binaryReader, blamPointers);
            invalidName_[376].ReadPointers(binaryReader, blamPointers);
            invalidName_[377].ReadPointers(binaryReader, blamPointers);
            invalidName_[378].ReadPointers(binaryReader, blamPointers);
            invalidName_[379].ReadPointers(binaryReader, blamPointers);
            invalidName_[380].ReadPointers(binaryReader, blamPointers);
            invalidName_[381].ReadPointers(binaryReader, blamPointers);
            invalidName_[382].ReadPointers(binaryReader, blamPointers);
            invalidName_[383].ReadPointers(binaryReader, blamPointers);
            invalidName_[384].ReadPointers(binaryReader, blamPointers);
            invalidName_[385].ReadPointers(binaryReader, blamPointers);
            invalidName_[386].ReadPointers(binaryReader, blamPointers);
            invalidName_[387].ReadPointers(binaryReader, blamPointers);
            invalidName_[388].ReadPointers(binaryReader, blamPointers);
            invalidName_[389].ReadPointers(binaryReader, blamPointers);
            invalidName_[390].ReadPointers(binaryReader, blamPointers);
            invalidName_[391].ReadPointers(binaryReader, blamPointers);
            invalidName_[392].ReadPointers(binaryReader, blamPointers);
            invalidName_[393].ReadPointers(binaryReader, blamPointers);
            invalidName_[394].ReadPointers(binaryReader, blamPointers);
            invalidName_[395].ReadPointers(binaryReader, blamPointers);
            invalidName_[396].ReadPointers(binaryReader, blamPointers);
            invalidName_[397].ReadPointers(binaryReader, blamPointers);
            invalidName_[398].ReadPointers(binaryReader, blamPointers);
            invalidName_[399].ReadPointers(binaryReader, blamPointers);
            invalidName_[400].ReadPointers(binaryReader, blamPointers);
            invalidName_[401].ReadPointers(binaryReader, blamPointers);
            invalidName_[402].ReadPointers(binaryReader, blamPointers);
            invalidName_[403].ReadPointers(binaryReader, blamPointers);
            invalidName_[404].ReadPointers(binaryReader, blamPointers);
            invalidName_[405].ReadPointers(binaryReader, blamPointers);
            invalidName_[406].ReadPointers(binaryReader, blamPointers);
            invalidName_[407].ReadPointers(binaryReader, blamPointers);
            invalidName_[408].ReadPointers(binaryReader, blamPointers);
            invalidName_[409].ReadPointers(binaryReader, blamPointers);
            invalidName_[410].ReadPointers(binaryReader, blamPointers);
            invalidName_[411].ReadPointers(binaryReader, blamPointers);
            invalidName_[412].ReadPointers(binaryReader, blamPointers);
            invalidName_[413].ReadPointers(binaryReader, blamPointers);
            invalidName_[414].ReadPointers(binaryReader, blamPointers);
            invalidName_[415].ReadPointers(binaryReader, blamPointers);
            invalidName_[416].ReadPointers(binaryReader, blamPointers);
            invalidName_[417].ReadPointers(binaryReader, blamPointers);
            invalidName_[418].ReadPointers(binaryReader, blamPointers);
            invalidName_[419].ReadPointers(binaryReader, blamPointers);
            invalidName_[420].ReadPointers(binaryReader, blamPointers);
            invalidName_[421].ReadPointers(binaryReader, blamPointers);
            invalidName_[422].ReadPointers(binaryReader, blamPointers);
            invalidName_[423].ReadPointers(binaryReader, blamPointers);
            invalidName_[424].ReadPointers(binaryReader, blamPointers);
            invalidName_[425].ReadPointers(binaryReader, blamPointers);
            invalidName_[426].ReadPointers(binaryReader, blamPointers);
            invalidName_[427].ReadPointers(binaryReader, blamPointers);
            invalidName_[428].ReadPointers(binaryReader, blamPointers);
            invalidName_[429].ReadPointers(binaryReader, blamPointers);
            invalidName_[430].ReadPointers(binaryReader, blamPointers);
            invalidName_[431].ReadPointers(binaryReader, blamPointers);
            invalidName_[432].ReadPointers(binaryReader, blamPointers);
            invalidName_[433].ReadPointers(binaryReader, blamPointers);
            invalidName_[434].ReadPointers(binaryReader, blamPointers);
            invalidName_[435].ReadPointers(binaryReader, blamPointers);
            invalidName_[436].ReadPointers(binaryReader, blamPointers);
            invalidName_[437].ReadPointers(binaryReader, blamPointers);
            invalidName_[438].ReadPointers(binaryReader, blamPointers);
            invalidName_[439].ReadPointers(binaryReader, blamPointers);
            invalidName_[440].ReadPointers(binaryReader, blamPointers);
            invalidName_[441].ReadPointers(binaryReader, blamPointers);
            invalidName_[442].ReadPointers(binaryReader, blamPointers);
            invalidName_[443].ReadPointers(binaryReader, blamPointers);
            invalidName_[444].ReadPointers(binaryReader, blamPointers);
            invalidName_[445].ReadPointers(binaryReader, blamPointers);
            invalidName_[446].ReadPointers(binaryReader, blamPointers);
            invalidName_[447].ReadPointers(binaryReader, blamPointers);
            invalidName_[448].ReadPointers(binaryReader, blamPointers);
            invalidName_[449].ReadPointers(binaryReader, blamPointers);
            invalidName_[450].ReadPointers(binaryReader, blamPointers);
            invalidName_[451].ReadPointers(binaryReader, blamPointers);
            invalidName_[452].ReadPointers(binaryReader, blamPointers);
            invalidName_[453].ReadPointers(binaryReader, blamPointers);
            invalidName_[454].ReadPointers(binaryReader, blamPointers);
            invalidName_[455].ReadPointers(binaryReader, blamPointers);
            invalidName_[456].ReadPointers(binaryReader, blamPointers);
            invalidName_[457].ReadPointers(binaryReader, blamPointers);
            invalidName_[458].ReadPointers(binaryReader, blamPointers);
            invalidName_[459].ReadPointers(binaryReader, blamPointers);
            invalidName_[460].ReadPointers(binaryReader, blamPointers);
            invalidName_[461].ReadPointers(binaryReader, blamPointers);
            invalidName_[462].ReadPointers(binaryReader, blamPointers);
            invalidName_[463].ReadPointers(binaryReader, blamPointers);
            invalidName_[464].ReadPointers(binaryReader, blamPointers);
            invalidName_[465].ReadPointers(binaryReader, blamPointers);
            invalidName_[466].ReadPointers(binaryReader, blamPointers);
            invalidName_[467].ReadPointers(binaryReader, blamPointers);
            invalidName_[468].ReadPointers(binaryReader, blamPointers);
            invalidName_[469].ReadPointers(binaryReader, blamPointers);
            invalidName_[470].ReadPointers(binaryReader, blamPointers);
            invalidName_[471].ReadPointers(binaryReader, blamPointers);
            invalidName_[472].ReadPointers(binaryReader, blamPointers);
            invalidName_[473].ReadPointers(binaryReader, blamPointers);
            invalidName_[474].ReadPointers(binaryReader, blamPointers);
            invalidName_[475].ReadPointers(binaryReader, blamPointers);
            invalidName_[476].ReadPointers(binaryReader, blamPointers);
            invalidName_[477].ReadPointers(binaryReader, blamPointers);
            invalidName_[478].ReadPointers(binaryReader, blamPointers);
            invalidName_[479].ReadPointers(binaryReader, blamPointers);
            invalidName_[480].ReadPointers(binaryReader, blamPointers);
            invalidName_[481].ReadPointers(binaryReader, blamPointers);
            invalidName_[482].ReadPointers(binaryReader, blamPointers);
            invalidName_[483].ReadPointers(binaryReader, blamPointers);
            invalidName_[484].ReadPointers(binaryReader, blamPointers);
            invalidName_[485].ReadPointers(binaryReader, blamPointers);
            invalidName_[486].ReadPointers(binaryReader, blamPointers);
            invalidName_[487].ReadPointers(binaryReader, blamPointers);
            invalidName_[488].ReadPointers(binaryReader, blamPointers);
            invalidName_[489].ReadPointers(binaryReader, blamPointers);
            invalidName_[490].ReadPointers(binaryReader, blamPointers);
            invalidName_[491].ReadPointers(binaryReader, blamPointers);
            invalidName_[492].ReadPointers(binaryReader, blamPointers);
            invalidName_[493].ReadPointers(binaryReader, blamPointers);
            invalidName_[494].ReadPointers(binaryReader, blamPointers);
            invalidName_[495].ReadPointers(binaryReader, blamPointers);
            invalidName_[496].ReadPointers(binaryReader, blamPointers);
            invalidName_[497].ReadPointers(binaryReader, blamPointers);
            invalidName_[498].ReadPointers(binaryReader, blamPointers);
            invalidName_[499].ReadPointers(binaryReader, blamPointers);
            invalidName_[500].ReadPointers(binaryReader, blamPointers);
            invalidName_[501].ReadPointers(binaryReader, blamPointers);
            invalidName_[502].ReadPointers(binaryReader, blamPointers);
            invalidName_[503].ReadPointers(binaryReader, blamPointers);
            invalidName_[504].ReadPointers(binaryReader, blamPointers);
            invalidName_[505].ReadPointers(binaryReader, blamPointers);
            invalidName_[506].ReadPointers(binaryReader, blamPointers);
            invalidName_[507].ReadPointers(binaryReader, blamPointers);
            invalidName_[508].ReadPointers(binaryReader, blamPointers);
            invalidName_[509].ReadPointers(binaryReader, blamPointers);
            invalidName_[510].ReadPointers(binaryReader, blamPointers);
            invalidName_[511].ReadPointers(binaryReader, blamPointers);
            invalidName_[512].ReadPointers(binaryReader, blamPointers);
            invalidName_[513].ReadPointers(binaryReader, blamPointers);
            invalidName_[514].ReadPointers(binaryReader, blamPointers);
            invalidName_[515].ReadPointers(binaryReader, blamPointers);
            invalidName_[516].ReadPointers(binaryReader, blamPointers);
            invalidName_[517].ReadPointers(binaryReader, blamPointers);
            invalidName_[518].ReadPointers(binaryReader, blamPointers);
            invalidName_[519].ReadPointers(binaryReader, blamPointers);
            invalidName_[520].ReadPointers(binaryReader, blamPointers);
            invalidName_[521].ReadPointers(binaryReader, blamPointers);
            invalidName_[522].ReadPointers(binaryReader, blamPointers);
            invalidName_[523].ReadPointers(binaryReader, blamPointers);
            invalidName_[524].ReadPointers(binaryReader, blamPointers);
            invalidName_[525].ReadPointers(binaryReader, blamPointers);
            invalidName_[526].ReadPointers(binaryReader, blamPointers);
            invalidName_[527].ReadPointers(binaryReader, blamPointers);
            invalidName_[528].ReadPointers(binaryReader, blamPointers);
            invalidName_[529].ReadPointers(binaryReader, blamPointers);
            invalidName_[530].ReadPointers(binaryReader, blamPointers);
            invalidName_[531].ReadPointers(binaryReader, blamPointers);
            invalidName_[532].ReadPointers(binaryReader, blamPointers);
            invalidName_[533].ReadPointers(binaryReader, blamPointers);
            invalidName_[534].ReadPointers(binaryReader, blamPointers);
            invalidName_[535].ReadPointers(binaryReader, blamPointers);
            invalidName_[536].ReadPointers(binaryReader, blamPointers);
            invalidName_[537].ReadPointers(binaryReader, blamPointers);
            invalidName_[538].ReadPointers(binaryReader, blamPointers);
            invalidName_[539].ReadPointers(binaryReader, blamPointers);
            invalidName_[540].ReadPointers(binaryReader, blamPointers);
            invalidName_[541].ReadPointers(binaryReader, blamPointers);
            invalidName_[542].ReadPointers(binaryReader, blamPointers);
            invalidName_[543].ReadPointers(binaryReader, blamPointers);
            invalidName_[544].ReadPointers(binaryReader, blamPointers);
            invalidName_[545].ReadPointers(binaryReader, blamPointers);
            invalidName_[546].ReadPointers(binaryReader, blamPointers);
            invalidName_[547].ReadPointers(binaryReader, blamPointers);
            invalidName_[548].ReadPointers(binaryReader, blamPointers);
            invalidName_[549].ReadPointers(binaryReader, blamPointers);
            invalidName_[550].ReadPointers(binaryReader, blamPointers);
            invalidName_[551].ReadPointers(binaryReader, blamPointers);
            invalidName_[552].ReadPointers(binaryReader, blamPointers);
            invalidName_[553].ReadPointers(binaryReader, blamPointers);
            invalidName_[554].ReadPointers(binaryReader, blamPointers);
            invalidName_[555].ReadPointers(binaryReader, blamPointers);
            invalidName_[556].ReadPointers(binaryReader, blamPointers);
            invalidName_[557].ReadPointers(binaryReader, blamPointers);
            invalidName_[558].ReadPointers(binaryReader, blamPointers);
            invalidName_[559].ReadPointers(binaryReader, blamPointers);
            invalidName_[560].ReadPointers(binaryReader, blamPointers);
            invalidName_[561].ReadPointers(binaryReader, blamPointers);
            invalidName_[562].ReadPointers(binaryReader, blamPointers);
            invalidName_[563].ReadPointers(binaryReader, blamPointers);
            invalidName_[564].ReadPointers(binaryReader, blamPointers);
            invalidName_[565].ReadPointers(binaryReader, blamPointers);
            invalidName_[566].ReadPointers(binaryReader, blamPointers);
            invalidName_[567].ReadPointers(binaryReader, blamPointers);
            invalidName_[568].ReadPointers(binaryReader, blamPointers);
            invalidName_[569].ReadPointers(binaryReader, blamPointers);
            invalidName_[570].ReadPointers(binaryReader, blamPointers);
            invalidName_[571].ReadPointers(binaryReader, blamPointers);
            invalidName_[572].ReadPointers(binaryReader, blamPointers);
            invalidName_[573].ReadPointers(binaryReader, blamPointers);
            invalidName_[574].ReadPointers(binaryReader, blamPointers);
            invalidName_[575].ReadPointers(binaryReader, blamPointers);
            invalidName_[576].ReadPointers(binaryReader, blamPointers);
            invalidName_[577].ReadPointers(binaryReader, blamPointers);
            invalidName_[578].ReadPointers(binaryReader, blamPointers);
            invalidName_[579].ReadPointers(binaryReader, blamPointers);
            invalidName_[580].ReadPointers(binaryReader, blamPointers);
            invalidName_[581].ReadPointers(binaryReader, blamPointers);
            invalidName_[582].ReadPointers(binaryReader, blamPointers);
            invalidName_[583].ReadPointers(binaryReader, blamPointers);
            invalidName_[584].ReadPointers(binaryReader, blamPointers);
            invalidName_[585].ReadPointers(binaryReader, blamPointers);
            invalidName_[586].ReadPointers(binaryReader, blamPointers);
            invalidName_[587].ReadPointers(binaryReader, blamPointers);
            invalidName_[588].ReadPointers(binaryReader, blamPointers);
            invalidName_[589].ReadPointers(binaryReader, blamPointers);
            invalidName_[590].ReadPointers(binaryReader, blamPointers);
            invalidName_[591].ReadPointers(binaryReader, blamPointers);
            invalidName_[592].ReadPointers(binaryReader, blamPointers);
            invalidName_[593].ReadPointers(binaryReader, blamPointers);
            invalidName_[594].ReadPointers(binaryReader, blamPointers);
            invalidName_[595].ReadPointers(binaryReader, blamPointers);
            invalidName_[596].ReadPointers(binaryReader, blamPointers);
            invalidName_[597].ReadPointers(binaryReader, blamPointers);
            invalidName_[598].ReadPointers(binaryReader, blamPointers);
            invalidName_[599].ReadPointers(binaryReader, blamPointers);
            invalidName_[600].ReadPointers(binaryReader, blamPointers);
            invalidName_[601].ReadPointers(binaryReader, blamPointers);
            invalidName_[602].ReadPointers(binaryReader, blamPointers);
            invalidName_[603].ReadPointers(binaryReader, blamPointers);
            invalidName_[604].ReadPointers(binaryReader, blamPointers);
            invalidName_[605].ReadPointers(binaryReader, blamPointers);
            invalidName_[606].ReadPointers(binaryReader, blamPointers);
            invalidName_[607].ReadPointers(binaryReader, blamPointers);
            invalidName_[608].ReadPointers(binaryReader, blamPointers);
            invalidName_[609].ReadPointers(binaryReader, blamPointers);
            invalidName_[610].ReadPointers(binaryReader, blamPointers);
            invalidName_[611].ReadPointers(binaryReader, blamPointers);
            invalidName_[612].ReadPointers(binaryReader, blamPointers);
            invalidName_[613].ReadPointers(binaryReader, blamPointers);
            invalidName_[614].ReadPointers(binaryReader, blamPointers);
            invalidName_[615].ReadPointers(binaryReader, blamPointers);
            invalidName_[616].ReadPointers(binaryReader, blamPointers);
            invalidName_[617].ReadPointers(binaryReader, blamPointers);
            invalidName_[618].ReadPointers(binaryReader, blamPointers);
            invalidName_[619].ReadPointers(binaryReader, blamPointers);
            invalidName_[620].ReadPointers(binaryReader, blamPointers);
            invalidName_[621].ReadPointers(binaryReader, blamPointers);
            invalidName_[622].ReadPointers(binaryReader, blamPointers);
            invalidName_[623].ReadPointers(binaryReader, blamPointers);
            invalidName_[624].ReadPointers(binaryReader, blamPointers);
            invalidName_[625].ReadPointers(binaryReader, blamPointers);
            invalidName_[626].ReadPointers(binaryReader, blamPointers);
            invalidName_[627].ReadPointers(binaryReader, blamPointers);
            invalidName_[628].ReadPointers(binaryReader, blamPointers);
            invalidName_[629].ReadPointers(binaryReader, blamPointers);
            invalidName_[630].ReadPointers(binaryReader, blamPointers);
            invalidName_[631].ReadPointers(binaryReader, blamPointers);
            invalidName_[632].ReadPointers(binaryReader, blamPointers);
            invalidName_[633].ReadPointers(binaryReader, blamPointers);
            invalidName_[634].ReadPointers(binaryReader, blamPointers);
            invalidName_[635].ReadPointers(binaryReader, blamPointers);
            invalidName_[636].ReadPointers(binaryReader, blamPointers);
            invalidName_[637].ReadPointers(binaryReader, blamPointers);
            invalidName_[638].ReadPointers(binaryReader, blamPointers);
            invalidName_[639].ReadPointers(binaryReader, blamPointers);
            invalidName_[640].ReadPointers(binaryReader, blamPointers);
            invalidName_[641].ReadPointers(binaryReader, blamPointers);
            invalidName_[642].ReadPointers(binaryReader, blamPointers);
            invalidName_[643].ReadPointers(binaryReader, blamPointers);
            invalidName_[644].ReadPointers(binaryReader, blamPointers);
            invalidName_[645].ReadPointers(binaryReader, blamPointers);
            invalidName_[646].ReadPointers(binaryReader, blamPointers);
            invalidName_[647].ReadPointers(binaryReader, blamPointers);
            invalidName_[648].ReadPointers(binaryReader, blamPointers);
            invalidName_[649].ReadPointers(binaryReader, blamPointers);
            invalidName_[650].ReadPointers(binaryReader, blamPointers);
            invalidName_[651].ReadPointers(binaryReader, blamPointers);
            invalidName_[652].ReadPointers(binaryReader, blamPointers);
            invalidName_[653].ReadPointers(binaryReader, blamPointers);
            invalidName_[654].ReadPointers(binaryReader, blamPointers);
            invalidName_[655].ReadPointers(binaryReader, blamPointers);
            invalidName_[656].ReadPointers(binaryReader, blamPointers);
            invalidName_[657].ReadPointers(binaryReader, blamPointers);
            invalidName_[658].ReadPointers(binaryReader, blamPointers);
            invalidName_[659].ReadPointers(binaryReader, blamPointers);
            invalidName_[660].ReadPointers(binaryReader, blamPointers);
            invalidName_[661].ReadPointers(binaryReader, blamPointers);
            invalidName_[662].ReadPointers(binaryReader, blamPointers);
            invalidName_[663].ReadPointers(binaryReader, blamPointers);
            invalidName_[664].ReadPointers(binaryReader, blamPointers);
            invalidName_[665].ReadPointers(binaryReader, blamPointers);
            invalidName_[666].ReadPointers(binaryReader, blamPointers);
            invalidName_[667].ReadPointers(binaryReader, blamPointers);
            invalidName_[668].ReadPointers(binaryReader, blamPointers);
            invalidName_[669].ReadPointers(binaryReader, blamPointers);
            invalidName_[670].ReadPointers(binaryReader, blamPointers);
            invalidName_[671].ReadPointers(binaryReader, blamPointers);
            invalidName_[672].ReadPointers(binaryReader, blamPointers);
            invalidName_[673].ReadPointers(binaryReader, blamPointers);
            invalidName_[674].ReadPointers(binaryReader, blamPointers);
            invalidName_[675].ReadPointers(binaryReader, blamPointers);
            invalidName_[676].ReadPointers(binaryReader, blamPointers);
            invalidName_[677].ReadPointers(binaryReader, blamPointers);
            invalidName_[678].ReadPointers(binaryReader, blamPointers);
            invalidName_[679].ReadPointers(binaryReader, blamPointers);
            invalidName_[680].ReadPointers(binaryReader, blamPointers);
            invalidName_[681].ReadPointers(binaryReader, blamPointers);
            invalidName_[682].ReadPointers(binaryReader, blamPointers);
            invalidName_[683].ReadPointers(binaryReader, blamPointers);
            invalidName_[684].ReadPointers(binaryReader, blamPointers);
            invalidName_[685].ReadPointers(binaryReader, blamPointers);
            invalidName_[686].ReadPointers(binaryReader, blamPointers);
            invalidName_[687].ReadPointers(binaryReader, blamPointers);
            invalidName_[688].ReadPointers(binaryReader, blamPointers);
            invalidName_[689].ReadPointers(binaryReader, blamPointers);
            invalidName_[690].ReadPointers(binaryReader, blamPointers);
            invalidName_[691].ReadPointers(binaryReader, blamPointers);
            invalidName_[692].ReadPointers(binaryReader, blamPointers);
            invalidName_[693].ReadPointers(binaryReader, blamPointers);
            invalidName_[694].ReadPointers(binaryReader, blamPointers);
            invalidName_[695].ReadPointers(binaryReader, blamPointers);
            invalidName_[696].ReadPointers(binaryReader, blamPointers);
            invalidName_[697].ReadPointers(binaryReader, blamPointers);
            invalidName_[698].ReadPointers(binaryReader, blamPointers);
            invalidName_[699].ReadPointers(binaryReader, blamPointers);
            invalidName_[700].ReadPointers(binaryReader, blamPointers);
            invalidName_[701].ReadPointers(binaryReader, blamPointers);
            invalidName_[702].ReadPointers(binaryReader, blamPointers);
            invalidName_[703].ReadPointers(binaryReader, blamPointers);
            invalidName_[704].ReadPointers(binaryReader, blamPointers);
            invalidName_[705].ReadPointers(binaryReader, blamPointers);
            invalidName_[706].ReadPointers(binaryReader, blamPointers);
            invalidName_[707].ReadPointers(binaryReader, blamPointers);
            invalidName_[708].ReadPointers(binaryReader, blamPointers);
            invalidName_[709].ReadPointers(binaryReader, blamPointers);
            invalidName_[710].ReadPointers(binaryReader, blamPointers);
            invalidName_[711].ReadPointers(binaryReader, blamPointers);
            invalidName_[712].ReadPointers(binaryReader, blamPointers);
            invalidName_[713].ReadPointers(binaryReader, blamPointers);
            invalidName_[714].ReadPointers(binaryReader, blamPointers);
            invalidName_[715].ReadPointers(binaryReader, blamPointers);
            invalidName_[716].ReadPointers(binaryReader, blamPointers);
            invalidName_[717].ReadPointers(binaryReader, blamPointers);
            invalidName_[718].ReadPointers(binaryReader, blamPointers);
            invalidName_[719].ReadPointers(binaryReader, blamPointers);
            invalidName_[720].ReadPointers(binaryReader, blamPointers);
            invalidName_[721].ReadPointers(binaryReader, blamPointers);
            invalidName_[722].ReadPointers(binaryReader, blamPointers);
            invalidName_[723].ReadPointers(binaryReader, blamPointers);
            invalidName_[724].ReadPointers(binaryReader, blamPointers);
            invalidName_[725].ReadPointers(binaryReader, blamPointers);
            invalidName_[726].ReadPointers(binaryReader, blamPointers);
            invalidName_[727].ReadPointers(binaryReader, blamPointers);
            invalidName_[728].ReadPointers(binaryReader, blamPointers);
            invalidName_[729].ReadPointers(binaryReader, blamPointers);
            invalidName_[730].ReadPointers(binaryReader, blamPointers);
            invalidName_[731].ReadPointers(binaryReader, blamPointers);
            invalidName_[732].ReadPointers(binaryReader, blamPointers);
            invalidName_[733].ReadPointers(binaryReader, blamPointers);
            invalidName_[734].ReadPointers(binaryReader, blamPointers);
            invalidName_[735].ReadPointers(binaryReader, blamPointers);
        }
        public override int Write(BinaryWriter binaryWriter, int nextAddress)
        {
            base.Write(binaryWriter, nextAddress);
using(binaryWriter.BaseStream.Pin())
            {
                binaryWriter.Write(texture0);
                binaryWriter.Write(texture1);
                binaryWriter.Write(texture2);
                binaryWriter.Write(platePositions0);
                binaryWriter.Write(platePositions1);
                binaryWriter.Write(platePositions2);
                binaryWriter.Write(moveSpeed0);
                binaryWriter.Write(moveSpeed1);
                binaryWriter.Write(moveSpeed2);
                binaryWriter.Write(textureScale0);
                binaryWriter.Write(textureScale1);
                binaryWriter.Write(textureScale2);
                binaryWriter.Write(jitter0);
                binaryWriter.Write(jitter1);
                binaryWriter.Write(jitter2);
                binaryWriter.Write(plateZNear);
                binaryWriter.Write(plateZFar);
                binaryWriter.Write(depthBlendZNear);
                binaryWriter.Write(depthBlendZFar);
                binaryWriter.Write(opacity0);
                binaryWriter.Write(opacity1);
                binaryWriter.Write(opacity2);
                binaryWriter.Write((Int32)flags);
                binaryWriter.Write(tintColor0);
                binaryWriter.Write(tintColor1);
                binaryWriter.Write(tintColor2);
                binaryWriter.Write(mass1);
                binaryWriter.Write(mass2);
                binaryWriter.Write(mass3);
                binaryWriter.Write(invalidName_, 0, 736);
                return nextAddress;
            }
        }
        [FlagsAttribute]
        internal enum Flags : int
        {
            ForwardMotion = 1,
            AutoPositionPlanes = 2,
            AutoScalePlanesautoUpdateSpeed = 4,
        };
    };
}
