// ReSharper disable All
using Moonfish.Model;
using Moonfish.Tags.BlamExtension;
using Moonfish.Tags;
using OpenTK;
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

namespace Moonfish.Tags
{
    public partial struct TagClass
    {
        public static readonly TagClass Matg = (TagClass)"matg";
    };
};

namespace Moonfish.Guerilla.Tags
{
    [TagClassAttribute("matg")]
    public partial class GlobalsBlock : GlobalsBlockBase
    {
        public GlobalsBlock() : base()
        {
        }
    };
    [LayoutAttribute(Size = 644, Alignment = 4)]
    public class GlobalsBlockBase : GuerillaBlock
    {
        internal byte[] invalidName_;
        internal Language language;
        internal HavokCleanupResourcesBlock[] havokCleanupResources;
        internal CollisionDamageBlock[] collisionDamage;
        internal SoundGlobalsBlock[] soundGlobals;
        internal AiGlobalsBlock[] aiGlobals;
        internal GameGlobalsDamageBlock[] damageTable;
        internal GNullBlock[] gNullBlock;
        internal MoonfishSoundReferencesBlock[] sounds;
        internal CameraBlock[] camera;
        internal PlayerControlBlock[] playerControl;
        internal DifficultyBlock[] difficulty;
        internal GrenadesBlock[] grenades;
        internal RasterizerDataBlock[] rasterizerData;
        internal InterfaceTagReferences[] interfaceTags;
        internal CheatWeaponsBlock[] weaponListUpdateWeaponListEnumInGameGlobalsH;
        internal CheatPowerupsBlock[] cheatPowerups;
        internal MultiplayerInformationBlock[] multiplayerInformation;
        internal PlayerInformationBlock[] playerInformation;
        internal PlayerRepresentationBlock[] playerRepresentation;
        internal FallingDamageBlock[] fallingDamage;
        internal OldMaterialsBlock[] oldMaterials;
        internal MaterialsBlock[] materials;
        internal MultiplayerUiBlock[] multiplayerUI;
        internal MultiplayerColorBlock[] profileColors;
        [TagReference("mulg")]
        internal Moonfish.Tags.TagReference multiplayerGlobals;
        internal RuntimeLevelsDefinitionBlock[] runtimeLevelData;
        internal UiLevelsDefinitionBlock[] uiLevelData;
        [TagReference("gldf")]
        internal Moonfish.Tags.TagReference defaultGlobalLighting;
        internal byte[] invalidName_0;
        public override int SerializedSize { get { return 644; } }
        public override int Alignment { get { return 4; } }
        public GlobalsBlockBase() : base()
        {
        }
        public override Queue<BlamPointer> ReadFields(BinaryReader binaryReader)
        {
            var blamPointers = new Queue<BlamPointer>(base.ReadFields(binaryReader));
            invalidName_ = binaryReader.ReadBytes(172);
            language = (Language)binaryReader.ReadInt32();
            blamPointers.Enqueue(ReadBlockArrayPointer<HavokCleanupResourcesBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<CollisionDamageBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<SoundGlobalsBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<AiGlobalsBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<GameGlobalsDamageBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<GNullBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<MoonfishSoundReferencesBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<CameraBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<PlayerControlBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<DifficultyBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<GrenadesBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<RasterizerDataBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<InterfaceTagReferences>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<CheatWeaponsBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<CheatPowerupsBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<MultiplayerInformationBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<PlayerInformationBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<PlayerRepresentationBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<FallingDamageBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<OldMaterialsBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<MaterialsBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<MultiplayerUiBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<MultiplayerColorBlock>(binaryReader));
            multiplayerGlobals = binaryReader.ReadTagReference();
            blamPointers.Enqueue(ReadBlockArrayPointer<RuntimeLevelsDefinitionBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<UiLevelsDefinitionBlock>(binaryReader));
            defaultGlobalLighting = binaryReader.ReadTagReference();
            invalidName_0 = binaryReader.ReadBytes(252);
            return blamPointers;
        }
        public override void ReadPointers(BinaryReader binaryReader, Queue<BlamPointer> blamPointers)
        {
            base.ReadPointers(binaryReader, blamPointers);
            invalidName_[0].ReadPointers(binaryReader, blamPointers);
            invalidName_[1].ReadPointers(binaryReader, blamPointers);
            invalidName_[2].ReadPointers(binaryReader, blamPointers);
            invalidName_[3].ReadPointers(binaryReader, blamPointers);
            invalidName_[4].ReadPointers(binaryReader, blamPointers);
            invalidName_[5].ReadPointers(binaryReader, blamPointers);
            invalidName_[6].ReadPointers(binaryReader, blamPointers);
            invalidName_[7].ReadPointers(binaryReader, blamPointers);
            invalidName_[8].ReadPointers(binaryReader, blamPointers);
            invalidName_[9].ReadPointers(binaryReader, blamPointers);
            invalidName_[10].ReadPointers(binaryReader, blamPointers);
            invalidName_[11].ReadPointers(binaryReader, blamPointers);
            invalidName_[12].ReadPointers(binaryReader, blamPointers);
            invalidName_[13].ReadPointers(binaryReader, blamPointers);
            invalidName_[14].ReadPointers(binaryReader, blamPointers);
            invalidName_[15].ReadPointers(binaryReader, blamPointers);
            invalidName_[16].ReadPointers(binaryReader, blamPointers);
            invalidName_[17].ReadPointers(binaryReader, blamPointers);
            invalidName_[18].ReadPointers(binaryReader, blamPointers);
            invalidName_[19].ReadPointers(binaryReader, blamPointers);
            invalidName_[20].ReadPointers(binaryReader, blamPointers);
            invalidName_[21].ReadPointers(binaryReader, blamPointers);
            invalidName_[22].ReadPointers(binaryReader, blamPointers);
            invalidName_[23].ReadPointers(binaryReader, blamPointers);
            invalidName_[24].ReadPointers(binaryReader, blamPointers);
            invalidName_[25].ReadPointers(binaryReader, blamPointers);
            invalidName_[26].ReadPointers(binaryReader, blamPointers);
            invalidName_[27].ReadPointers(binaryReader, blamPointers);
            invalidName_[28].ReadPointers(binaryReader, blamPointers);
            invalidName_[29].ReadPointers(binaryReader, blamPointers);
            invalidName_[30].ReadPointers(binaryReader, blamPointers);
            invalidName_[31].ReadPointers(binaryReader, blamPointers);
            invalidName_[32].ReadPointers(binaryReader, blamPointers);
            invalidName_[33].ReadPointers(binaryReader, blamPointers);
            invalidName_[34].ReadPointers(binaryReader, blamPointers);
            invalidName_[35].ReadPointers(binaryReader, blamPointers);
            invalidName_[36].ReadPointers(binaryReader, blamPointers);
            invalidName_[37].ReadPointers(binaryReader, blamPointers);
            invalidName_[38].ReadPointers(binaryReader, blamPointers);
            invalidName_[39].ReadPointers(binaryReader, blamPointers);
            invalidName_[40].ReadPointers(binaryReader, blamPointers);
            invalidName_[41].ReadPointers(binaryReader, blamPointers);
            invalidName_[42].ReadPointers(binaryReader, blamPointers);
            invalidName_[43].ReadPointers(binaryReader, blamPointers);
            invalidName_[44].ReadPointers(binaryReader, blamPointers);
            invalidName_[45].ReadPointers(binaryReader, blamPointers);
            invalidName_[46].ReadPointers(binaryReader, blamPointers);
            invalidName_[47].ReadPointers(binaryReader, blamPointers);
            invalidName_[48].ReadPointers(binaryReader, blamPointers);
            invalidName_[49].ReadPointers(binaryReader, blamPointers);
            invalidName_[50].ReadPointers(binaryReader, blamPointers);
            invalidName_[51].ReadPointers(binaryReader, blamPointers);
            invalidName_[52].ReadPointers(binaryReader, blamPointers);
            invalidName_[53].ReadPointers(binaryReader, blamPointers);
            invalidName_[54].ReadPointers(binaryReader, blamPointers);
            invalidName_[55].ReadPointers(binaryReader, blamPointers);
            invalidName_[56].ReadPointers(binaryReader, blamPointers);
            invalidName_[57].ReadPointers(binaryReader, blamPointers);
            invalidName_[58].ReadPointers(binaryReader, blamPointers);
            invalidName_[59].ReadPointers(binaryReader, blamPointers);
            invalidName_[60].ReadPointers(binaryReader, blamPointers);
            invalidName_[61].ReadPointers(binaryReader, blamPointers);
            invalidName_[62].ReadPointers(binaryReader, blamPointers);
            invalidName_[63].ReadPointers(binaryReader, blamPointers);
            invalidName_[64].ReadPointers(binaryReader, blamPointers);
            invalidName_[65].ReadPointers(binaryReader, blamPointers);
            invalidName_[66].ReadPointers(binaryReader, blamPointers);
            invalidName_[67].ReadPointers(binaryReader, blamPointers);
            invalidName_[68].ReadPointers(binaryReader, blamPointers);
            invalidName_[69].ReadPointers(binaryReader, blamPointers);
            invalidName_[70].ReadPointers(binaryReader, blamPointers);
            invalidName_[71].ReadPointers(binaryReader, blamPointers);
            invalidName_[72].ReadPointers(binaryReader, blamPointers);
            invalidName_[73].ReadPointers(binaryReader, blamPointers);
            invalidName_[74].ReadPointers(binaryReader, blamPointers);
            invalidName_[75].ReadPointers(binaryReader, blamPointers);
            invalidName_[76].ReadPointers(binaryReader, blamPointers);
            invalidName_[77].ReadPointers(binaryReader, blamPointers);
            invalidName_[78].ReadPointers(binaryReader, blamPointers);
            invalidName_[79].ReadPointers(binaryReader, blamPointers);
            invalidName_[80].ReadPointers(binaryReader, blamPointers);
            invalidName_[81].ReadPointers(binaryReader, blamPointers);
            invalidName_[82].ReadPointers(binaryReader, blamPointers);
            invalidName_[83].ReadPointers(binaryReader, blamPointers);
            invalidName_[84].ReadPointers(binaryReader, blamPointers);
            invalidName_[85].ReadPointers(binaryReader, blamPointers);
            invalidName_[86].ReadPointers(binaryReader, blamPointers);
            invalidName_[87].ReadPointers(binaryReader, blamPointers);
            invalidName_[88].ReadPointers(binaryReader, blamPointers);
            invalidName_[89].ReadPointers(binaryReader, blamPointers);
            invalidName_[90].ReadPointers(binaryReader, blamPointers);
            invalidName_[91].ReadPointers(binaryReader, blamPointers);
            invalidName_[92].ReadPointers(binaryReader, blamPointers);
            invalidName_[93].ReadPointers(binaryReader, blamPointers);
            invalidName_[94].ReadPointers(binaryReader, blamPointers);
            invalidName_[95].ReadPointers(binaryReader, blamPointers);
            invalidName_[96].ReadPointers(binaryReader, blamPointers);
            invalidName_[97].ReadPointers(binaryReader, blamPointers);
            invalidName_[98].ReadPointers(binaryReader, blamPointers);
            invalidName_[99].ReadPointers(binaryReader, blamPointers);
            invalidName_[100].ReadPointers(binaryReader, blamPointers);
            invalidName_[101].ReadPointers(binaryReader, blamPointers);
            invalidName_[102].ReadPointers(binaryReader, blamPointers);
            invalidName_[103].ReadPointers(binaryReader, blamPointers);
            invalidName_[104].ReadPointers(binaryReader, blamPointers);
            invalidName_[105].ReadPointers(binaryReader, blamPointers);
            invalidName_[106].ReadPointers(binaryReader, blamPointers);
            invalidName_[107].ReadPointers(binaryReader, blamPointers);
            invalidName_[108].ReadPointers(binaryReader, blamPointers);
            invalidName_[109].ReadPointers(binaryReader, blamPointers);
            invalidName_[110].ReadPointers(binaryReader, blamPointers);
            invalidName_[111].ReadPointers(binaryReader, blamPointers);
            invalidName_[112].ReadPointers(binaryReader, blamPointers);
            invalidName_[113].ReadPointers(binaryReader, blamPointers);
            invalidName_[114].ReadPointers(binaryReader, blamPointers);
            invalidName_[115].ReadPointers(binaryReader, blamPointers);
            invalidName_[116].ReadPointers(binaryReader, blamPointers);
            invalidName_[117].ReadPointers(binaryReader, blamPointers);
            invalidName_[118].ReadPointers(binaryReader, blamPointers);
            invalidName_[119].ReadPointers(binaryReader, blamPointers);
            invalidName_[120].ReadPointers(binaryReader, blamPointers);
            invalidName_[121].ReadPointers(binaryReader, blamPointers);
            invalidName_[122].ReadPointers(binaryReader, blamPointers);
            invalidName_[123].ReadPointers(binaryReader, blamPointers);
            invalidName_[124].ReadPointers(binaryReader, blamPointers);
            invalidName_[125].ReadPointers(binaryReader, blamPointers);
            invalidName_[126].ReadPointers(binaryReader, blamPointers);
            invalidName_[127].ReadPointers(binaryReader, blamPointers);
            invalidName_[128].ReadPointers(binaryReader, blamPointers);
            invalidName_[129].ReadPointers(binaryReader, blamPointers);
            invalidName_[130].ReadPointers(binaryReader, blamPointers);
            invalidName_[131].ReadPointers(binaryReader, blamPointers);
            invalidName_[132].ReadPointers(binaryReader, blamPointers);
            invalidName_[133].ReadPointers(binaryReader, blamPointers);
            invalidName_[134].ReadPointers(binaryReader, blamPointers);
            invalidName_[135].ReadPointers(binaryReader, blamPointers);
            invalidName_[136].ReadPointers(binaryReader, blamPointers);
            invalidName_[137].ReadPointers(binaryReader, blamPointers);
            invalidName_[138].ReadPointers(binaryReader, blamPointers);
            invalidName_[139].ReadPointers(binaryReader, blamPointers);
            invalidName_[140].ReadPointers(binaryReader, blamPointers);
            invalidName_[141].ReadPointers(binaryReader, blamPointers);
            invalidName_[142].ReadPointers(binaryReader, blamPointers);
            invalidName_[143].ReadPointers(binaryReader, blamPointers);
            invalidName_[144].ReadPointers(binaryReader, blamPointers);
            invalidName_[145].ReadPointers(binaryReader, blamPointers);
            invalidName_[146].ReadPointers(binaryReader, blamPointers);
            invalidName_[147].ReadPointers(binaryReader, blamPointers);
            invalidName_[148].ReadPointers(binaryReader, blamPointers);
            invalidName_[149].ReadPointers(binaryReader, blamPointers);
            invalidName_[150].ReadPointers(binaryReader, blamPointers);
            invalidName_[151].ReadPointers(binaryReader, blamPointers);
            invalidName_[152].ReadPointers(binaryReader, blamPointers);
            invalidName_[153].ReadPointers(binaryReader, blamPointers);
            invalidName_[154].ReadPointers(binaryReader, blamPointers);
            invalidName_[155].ReadPointers(binaryReader, blamPointers);
            invalidName_[156].ReadPointers(binaryReader, blamPointers);
            invalidName_[157].ReadPointers(binaryReader, blamPointers);
            invalidName_[158].ReadPointers(binaryReader, blamPointers);
            invalidName_[159].ReadPointers(binaryReader, blamPointers);
            invalidName_[160].ReadPointers(binaryReader, blamPointers);
            invalidName_[161].ReadPointers(binaryReader, blamPointers);
            invalidName_[162].ReadPointers(binaryReader, blamPointers);
            invalidName_[163].ReadPointers(binaryReader, blamPointers);
            invalidName_[164].ReadPointers(binaryReader, blamPointers);
            invalidName_[165].ReadPointers(binaryReader, blamPointers);
            invalidName_[166].ReadPointers(binaryReader, blamPointers);
            invalidName_[167].ReadPointers(binaryReader, blamPointers);
            invalidName_[168].ReadPointers(binaryReader, blamPointers);
            invalidName_[169].ReadPointers(binaryReader, blamPointers);
            invalidName_[170].ReadPointers(binaryReader, blamPointers);
            invalidName_[171].ReadPointers(binaryReader, blamPointers);
            havokCleanupResources = ReadBlockArrayData<HavokCleanupResourcesBlock>(binaryReader, blamPointers.Dequeue());
            collisionDamage = ReadBlockArrayData<CollisionDamageBlock>(binaryReader, blamPointers.Dequeue());
            soundGlobals = ReadBlockArrayData<SoundGlobalsBlock>(binaryReader, blamPointers.Dequeue());
            aiGlobals = ReadBlockArrayData<AiGlobalsBlock>(binaryReader, blamPointers.Dequeue());
            damageTable = ReadBlockArrayData<GameGlobalsDamageBlock>(binaryReader, blamPointers.Dequeue());
            gNullBlock = ReadBlockArrayData<GNullBlock>(binaryReader, blamPointers.Dequeue());
            sounds = ReadBlockArrayData<MoonfishSoundReferencesBlock>(binaryReader, blamPointers.Dequeue());
            camera = ReadBlockArrayData<CameraBlock>(binaryReader, blamPointers.Dequeue());
            playerControl = ReadBlockArrayData<PlayerControlBlock>(binaryReader, blamPointers.Dequeue());
            difficulty = ReadBlockArrayData<DifficultyBlock>(binaryReader, blamPointers.Dequeue());
            grenades = ReadBlockArrayData<GrenadesBlock>(binaryReader, blamPointers.Dequeue());
            rasterizerData = ReadBlockArrayData<RasterizerDataBlock>(binaryReader, blamPointers.Dequeue());
            interfaceTags = ReadBlockArrayData<InterfaceTagReferences>(binaryReader, blamPointers.Dequeue());
            weaponListUpdateWeaponListEnumInGameGlobalsH = ReadBlockArrayData<CheatWeaponsBlock>(binaryReader, blamPointers.Dequeue());
            cheatPowerups = ReadBlockArrayData<CheatPowerupsBlock>(binaryReader, blamPointers.Dequeue());
            multiplayerInformation = ReadBlockArrayData<MultiplayerInformationBlock>(binaryReader, blamPointers.Dequeue());
            playerInformation = ReadBlockArrayData<PlayerInformationBlock>(binaryReader, blamPointers.Dequeue());
            playerRepresentation = ReadBlockArrayData<PlayerRepresentationBlock>(binaryReader, blamPointers.Dequeue());
            fallingDamage = ReadBlockArrayData<FallingDamageBlock>(binaryReader, blamPointers.Dequeue());
            oldMaterials = ReadBlockArrayData<OldMaterialsBlock>(binaryReader, blamPointers.Dequeue());
            materials = ReadBlockArrayData<MaterialsBlock>(binaryReader, blamPointers.Dequeue());
            multiplayerUI = ReadBlockArrayData<MultiplayerUiBlock>(binaryReader, blamPointers.Dequeue());
            profileColors = ReadBlockArrayData<MultiplayerColorBlock>(binaryReader, blamPointers.Dequeue());
            runtimeLevelData = ReadBlockArrayData<RuntimeLevelsDefinitionBlock>(binaryReader, blamPointers.Dequeue());
            uiLevelData = ReadBlockArrayData<UiLevelsDefinitionBlock>(binaryReader, blamPointers.Dequeue());
            invalidName_0[0].ReadPointers(binaryReader, blamPointers);
            invalidName_0[1].ReadPointers(binaryReader, blamPointers);
            invalidName_0[2].ReadPointers(binaryReader, blamPointers);
            invalidName_0[3].ReadPointers(binaryReader, blamPointers);
            invalidName_0[4].ReadPointers(binaryReader, blamPointers);
            invalidName_0[5].ReadPointers(binaryReader, blamPointers);
            invalidName_0[6].ReadPointers(binaryReader, blamPointers);
            invalidName_0[7].ReadPointers(binaryReader, blamPointers);
            invalidName_0[8].ReadPointers(binaryReader, blamPointers);
            invalidName_0[9].ReadPointers(binaryReader, blamPointers);
            invalidName_0[10].ReadPointers(binaryReader, blamPointers);
            invalidName_0[11].ReadPointers(binaryReader, blamPointers);
            invalidName_0[12].ReadPointers(binaryReader, blamPointers);
            invalidName_0[13].ReadPointers(binaryReader, blamPointers);
            invalidName_0[14].ReadPointers(binaryReader, blamPointers);
            invalidName_0[15].ReadPointers(binaryReader, blamPointers);
            invalidName_0[16].ReadPointers(binaryReader, blamPointers);
            invalidName_0[17].ReadPointers(binaryReader, blamPointers);
            invalidName_0[18].ReadPointers(binaryReader, blamPointers);
            invalidName_0[19].ReadPointers(binaryReader, blamPointers);
            invalidName_0[20].ReadPointers(binaryReader, blamPointers);
            invalidName_0[21].ReadPointers(binaryReader, blamPointers);
            invalidName_0[22].ReadPointers(binaryReader, blamPointers);
            invalidName_0[23].ReadPointers(binaryReader, blamPointers);
            invalidName_0[24].ReadPointers(binaryReader, blamPointers);
            invalidName_0[25].ReadPointers(binaryReader, blamPointers);
            invalidName_0[26].ReadPointers(binaryReader, blamPointers);
            invalidName_0[27].ReadPointers(binaryReader, blamPointers);
            invalidName_0[28].ReadPointers(binaryReader, blamPointers);
            invalidName_0[29].ReadPointers(binaryReader, blamPointers);
            invalidName_0[30].ReadPointers(binaryReader, blamPointers);
            invalidName_0[31].ReadPointers(binaryReader, blamPointers);
            invalidName_0[32].ReadPointers(binaryReader, blamPointers);
            invalidName_0[33].ReadPointers(binaryReader, blamPointers);
            invalidName_0[34].ReadPointers(binaryReader, blamPointers);
            invalidName_0[35].ReadPointers(binaryReader, blamPointers);
            invalidName_0[36].ReadPointers(binaryReader, blamPointers);
            invalidName_0[37].ReadPointers(binaryReader, blamPointers);
            invalidName_0[38].ReadPointers(binaryReader, blamPointers);
            invalidName_0[39].ReadPointers(binaryReader, blamPointers);
            invalidName_0[40].ReadPointers(binaryReader, blamPointers);
            invalidName_0[41].ReadPointers(binaryReader, blamPointers);
            invalidName_0[42].ReadPointers(binaryReader, blamPointers);
            invalidName_0[43].ReadPointers(binaryReader, blamPointers);
            invalidName_0[44].ReadPointers(binaryReader, blamPointers);
            invalidName_0[45].ReadPointers(binaryReader, blamPointers);
            invalidName_0[46].ReadPointers(binaryReader, blamPointers);
            invalidName_0[47].ReadPointers(binaryReader, blamPointers);
            invalidName_0[48].ReadPointers(binaryReader, blamPointers);
            invalidName_0[49].ReadPointers(binaryReader, blamPointers);
            invalidName_0[50].ReadPointers(binaryReader, blamPointers);
            invalidName_0[51].ReadPointers(binaryReader, blamPointers);
            invalidName_0[52].ReadPointers(binaryReader, blamPointers);
            invalidName_0[53].ReadPointers(binaryReader, blamPointers);
            invalidName_0[54].ReadPointers(binaryReader, blamPointers);
            invalidName_0[55].ReadPointers(binaryReader, blamPointers);
            invalidName_0[56].ReadPointers(binaryReader, blamPointers);
            invalidName_0[57].ReadPointers(binaryReader, blamPointers);
            invalidName_0[58].ReadPointers(binaryReader, blamPointers);
            invalidName_0[59].ReadPointers(binaryReader, blamPointers);
            invalidName_0[60].ReadPointers(binaryReader, blamPointers);
            invalidName_0[61].ReadPointers(binaryReader, blamPointers);
            invalidName_0[62].ReadPointers(binaryReader, blamPointers);
            invalidName_0[63].ReadPointers(binaryReader, blamPointers);
            invalidName_0[64].ReadPointers(binaryReader, blamPointers);
            invalidName_0[65].ReadPointers(binaryReader, blamPointers);
            invalidName_0[66].ReadPointers(binaryReader, blamPointers);
            invalidName_0[67].ReadPointers(binaryReader, blamPointers);
            invalidName_0[68].ReadPointers(binaryReader, blamPointers);
            invalidName_0[69].ReadPointers(binaryReader, blamPointers);
            invalidName_0[70].ReadPointers(binaryReader, blamPointers);
            invalidName_0[71].ReadPointers(binaryReader, blamPointers);
            invalidName_0[72].ReadPointers(binaryReader, blamPointers);
            invalidName_0[73].ReadPointers(binaryReader, blamPointers);
            invalidName_0[74].ReadPointers(binaryReader, blamPointers);
            invalidName_0[75].ReadPointers(binaryReader, blamPointers);
            invalidName_0[76].ReadPointers(binaryReader, blamPointers);
            invalidName_0[77].ReadPointers(binaryReader, blamPointers);
            invalidName_0[78].ReadPointers(binaryReader, blamPointers);
            invalidName_0[79].ReadPointers(binaryReader, blamPointers);
            invalidName_0[80].ReadPointers(binaryReader, blamPointers);
            invalidName_0[81].ReadPointers(binaryReader, blamPointers);
            invalidName_0[82].ReadPointers(binaryReader, blamPointers);
            invalidName_0[83].ReadPointers(binaryReader, blamPointers);
            invalidName_0[84].ReadPointers(binaryReader, blamPointers);
            invalidName_0[85].ReadPointers(binaryReader, blamPointers);
            invalidName_0[86].ReadPointers(binaryReader, blamPointers);
            invalidName_0[87].ReadPointers(binaryReader, blamPointers);
            invalidName_0[88].ReadPointers(binaryReader, blamPointers);
            invalidName_0[89].ReadPointers(binaryReader, blamPointers);
            invalidName_0[90].ReadPointers(binaryReader, blamPointers);
            invalidName_0[91].ReadPointers(binaryReader, blamPointers);
            invalidName_0[92].ReadPointers(binaryReader, blamPointers);
            invalidName_0[93].ReadPointers(binaryReader, blamPointers);
            invalidName_0[94].ReadPointers(binaryReader, blamPointers);
            invalidName_0[95].ReadPointers(binaryReader, blamPointers);
            invalidName_0[96].ReadPointers(binaryReader, blamPointers);
            invalidName_0[97].ReadPointers(binaryReader, blamPointers);
            invalidName_0[98].ReadPointers(binaryReader, blamPointers);
            invalidName_0[99].ReadPointers(binaryReader, blamPointers);
            invalidName_0[100].ReadPointers(binaryReader, blamPointers);
            invalidName_0[101].ReadPointers(binaryReader, blamPointers);
            invalidName_0[102].ReadPointers(binaryReader, blamPointers);
            invalidName_0[103].ReadPointers(binaryReader, blamPointers);
            invalidName_0[104].ReadPointers(binaryReader, blamPointers);
            invalidName_0[105].ReadPointers(binaryReader, blamPointers);
            invalidName_0[106].ReadPointers(binaryReader, blamPointers);
            invalidName_0[107].ReadPointers(binaryReader, blamPointers);
            invalidName_0[108].ReadPointers(binaryReader, blamPointers);
            invalidName_0[109].ReadPointers(binaryReader, blamPointers);
            invalidName_0[110].ReadPointers(binaryReader, blamPointers);
            invalidName_0[111].ReadPointers(binaryReader, blamPointers);
            invalidName_0[112].ReadPointers(binaryReader, blamPointers);
            invalidName_0[113].ReadPointers(binaryReader, blamPointers);
            invalidName_0[114].ReadPointers(binaryReader, blamPointers);
            invalidName_0[115].ReadPointers(binaryReader, blamPointers);
            invalidName_0[116].ReadPointers(binaryReader, blamPointers);
            invalidName_0[117].ReadPointers(binaryReader, blamPointers);
            invalidName_0[118].ReadPointers(binaryReader, blamPointers);
            invalidName_0[119].ReadPointers(binaryReader, blamPointers);
            invalidName_0[120].ReadPointers(binaryReader, blamPointers);
            invalidName_0[121].ReadPointers(binaryReader, blamPointers);
            invalidName_0[122].ReadPointers(binaryReader, blamPointers);
            invalidName_0[123].ReadPointers(binaryReader, blamPointers);
            invalidName_0[124].ReadPointers(binaryReader, blamPointers);
            invalidName_0[125].ReadPointers(binaryReader, blamPointers);
            invalidName_0[126].ReadPointers(binaryReader, blamPointers);
            invalidName_0[127].ReadPointers(binaryReader, blamPointers);
            invalidName_0[128].ReadPointers(binaryReader, blamPointers);
            invalidName_0[129].ReadPointers(binaryReader, blamPointers);
            invalidName_0[130].ReadPointers(binaryReader, blamPointers);
            invalidName_0[131].ReadPointers(binaryReader, blamPointers);
            invalidName_0[132].ReadPointers(binaryReader, blamPointers);
            invalidName_0[133].ReadPointers(binaryReader, blamPointers);
            invalidName_0[134].ReadPointers(binaryReader, blamPointers);
            invalidName_0[135].ReadPointers(binaryReader, blamPointers);
            invalidName_0[136].ReadPointers(binaryReader, blamPointers);
            invalidName_0[137].ReadPointers(binaryReader, blamPointers);
            invalidName_0[138].ReadPointers(binaryReader, blamPointers);
            invalidName_0[139].ReadPointers(binaryReader, blamPointers);
            invalidName_0[140].ReadPointers(binaryReader, blamPointers);
            invalidName_0[141].ReadPointers(binaryReader, blamPointers);
            invalidName_0[142].ReadPointers(binaryReader, blamPointers);
            invalidName_0[143].ReadPointers(binaryReader, blamPointers);
            invalidName_0[144].ReadPointers(binaryReader, blamPointers);
            invalidName_0[145].ReadPointers(binaryReader, blamPointers);
            invalidName_0[146].ReadPointers(binaryReader, blamPointers);
            invalidName_0[147].ReadPointers(binaryReader, blamPointers);
            invalidName_0[148].ReadPointers(binaryReader, blamPointers);
            invalidName_0[149].ReadPointers(binaryReader, blamPointers);
            invalidName_0[150].ReadPointers(binaryReader, blamPointers);
            invalidName_0[151].ReadPointers(binaryReader, blamPointers);
            invalidName_0[152].ReadPointers(binaryReader, blamPointers);
            invalidName_0[153].ReadPointers(binaryReader, blamPointers);
            invalidName_0[154].ReadPointers(binaryReader, blamPointers);
            invalidName_0[155].ReadPointers(binaryReader, blamPointers);
            invalidName_0[156].ReadPointers(binaryReader, blamPointers);
            invalidName_0[157].ReadPointers(binaryReader, blamPointers);
            invalidName_0[158].ReadPointers(binaryReader, blamPointers);
            invalidName_0[159].ReadPointers(binaryReader, blamPointers);
            invalidName_0[160].ReadPointers(binaryReader, blamPointers);
            invalidName_0[161].ReadPointers(binaryReader, blamPointers);
            invalidName_0[162].ReadPointers(binaryReader, blamPointers);
            invalidName_0[163].ReadPointers(binaryReader, blamPointers);
            invalidName_0[164].ReadPointers(binaryReader, blamPointers);
            invalidName_0[165].ReadPointers(binaryReader, blamPointers);
            invalidName_0[166].ReadPointers(binaryReader, blamPointers);
            invalidName_0[167].ReadPointers(binaryReader, blamPointers);
            invalidName_0[168].ReadPointers(binaryReader, blamPointers);
            invalidName_0[169].ReadPointers(binaryReader, blamPointers);
            invalidName_0[170].ReadPointers(binaryReader, blamPointers);
            invalidName_0[171].ReadPointers(binaryReader, blamPointers);
            invalidName_0[172].ReadPointers(binaryReader, blamPointers);
            invalidName_0[173].ReadPointers(binaryReader, blamPointers);
            invalidName_0[174].ReadPointers(binaryReader, blamPointers);
            invalidName_0[175].ReadPointers(binaryReader, blamPointers);
            invalidName_0[176].ReadPointers(binaryReader, blamPointers);
            invalidName_0[177].ReadPointers(binaryReader, blamPointers);
            invalidName_0[178].ReadPointers(binaryReader, blamPointers);
            invalidName_0[179].ReadPointers(binaryReader, blamPointers);
            invalidName_0[180].ReadPointers(binaryReader, blamPointers);
            invalidName_0[181].ReadPointers(binaryReader, blamPointers);
            invalidName_0[182].ReadPointers(binaryReader, blamPointers);
            invalidName_0[183].ReadPointers(binaryReader, blamPointers);
            invalidName_0[184].ReadPointers(binaryReader, blamPointers);
            invalidName_0[185].ReadPointers(binaryReader, blamPointers);
            invalidName_0[186].ReadPointers(binaryReader, blamPointers);
            invalidName_0[187].ReadPointers(binaryReader, blamPointers);
            invalidName_0[188].ReadPointers(binaryReader, blamPointers);
            invalidName_0[189].ReadPointers(binaryReader, blamPointers);
            invalidName_0[190].ReadPointers(binaryReader, blamPointers);
            invalidName_0[191].ReadPointers(binaryReader, blamPointers);
            invalidName_0[192].ReadPointers(binaryReader, blamPointers);
            invalidName_0[193].ReadPointers(binaryReader, blamPointers);
            invalidName_0[194].ReadPointers(binaryReader, blamPointers);
            invalidName_0[195].ReadPointers(binaryReader, blamPointers);
            invalidName_0[196].ReadPointers(binaryReader, blamPointers);
            invalidName_0[197].ReadPointers(binaryReader, blamPointers);
            invalidName_0[198].ReadPointers(binaryReader, blamPointers);
            invalidName_0[199].ReadPointers(binaryReader, blamPointers);
            invalidName_0[200].ReadPointers(binaryReader, blamPointers);
            invalidName_0[201].ReadPointers(binaryReader, blamPointers);
            invalidName_0[202].ReadPointers(binaryReader, blamPointers);
            invalidName_0[203].ReadPointers(binaryReader, blamPointers);
            invalidName_0[204].ReadPointers(binaryReader, blamPointers);
            invalidName_0[205].ReadPointers(binaryReader, blamPointers);
            invalidName_0[206].ReadPointers(binaryReader, blamPointers);
            invalidName_0[207].ReadPointers(binaryReader, blamPointers);
            invalidName_0[208].ReadPointers(binaryReader, blamPointers);
            invalidName_0[209].ReadPointers(binaryReader, blamPointers);
            invalidName_0[210].ReadPointers(binaryReader, blamPointers);
            invalidName_0[211].ReadPointers(binaryReader, blamPointers);
            invalidName_0[212].ReadPointers(binaryReader, blamPointers);
            invalidName_0[213].ReadPointers(binaryReader, blamPointers);
            invalidName_0[214].ReadPointers(binaryReader, blamPointers);
            invalidName_0[215].ReadPointers(binaryReader, blamPointers);
            invalidName_0[216].ReadPointers(binaryReader, blamPointers);
            invalidName_0[217].ReadPointers(binaryReader, blamPointers);
            invalidName_0[218].ReadPointers(binaryReader, blamPointers);
            invalidName_0[219].ReadPointers(binaryReader, blamPointers);
            invalidName_0[220].ReadPointers(binaryReader, blamPointers);
            invalidName_0[221].ReadPointers(binaryReader, blamPointers);
            invalidName_0[222].ReadPointers(binaryReader, blamPointers);
            invalidName_0[223].ReadPointers(binaryReader, blamPointers);
            invalidName_0[224].ReadPointers(binaryReader, blamPointers);
            invalidName_0[225].ReadPointers(binaryReader, blamPointers);
            invalidName_0[226].ReadPointers(binaryReader, blamPointers);
            invalidName_0[227].ReadPointers(binaryReader, blamPointers);
            invalidName_0[228].ReadPointers(binaryReader, blamPointers);
            invalidName_0[229].ReadPointers(binaryReader, blamPointers);
            invalidName_0[230].ReadPointers(binaryReader, blamPointers);
            invalidName_0[231].ReadPointers(binaryReader, blamPointers);
            invalidName_0[232].ReadPointers(binaryReader, blamPointers);
            invalidName_0[233].ReadPointers(binaryReader, blamPointers);
            invalidName_0[234].ReadPointers(binaryReader, blamPointers);
            invalidName_0[235].ReadPointers(binaryReader, blamPointers);
            invalidName_0[236].ReadPointers(binaryReader, blamPointers);
            invalidName_0[237].ReadPointers(binaryReader, blamPointers);
            invalidName_0[238].ReadPointers(binaryReader, blamPointers);
            invalidName_0[239].ReadPointers(binaryReader, blamPointers);
            invalidName_0[240].ReadPointers(binaryReader, blamPointers);
            invalidName_0[241].ReadPointers(binaryReader, blamPointers);
            invalidName_0[242].ReadPointers(binaryReader, blamPointers);
            invalidName_0[243].ReadPointers(binaryReader, blamPointers);
            invalidName_0[244].ReadPointers(binaryReader, blamPointers);
            invalidName_0[245].ReadPointers(binaryReader, blamPointers);
            invalidName_0[246].ReadPointers(binaryReader, blamPointers);
            invalidName_0[247].ReadPointers(binaryReader, blamPointers);
            invalidName_0[248].ReadPointers(binaryReader, blamPointers);
            invalidName_0[249].ReadPointers(binaryReader, blamPointers);
            invalidName_0[250].ReadPointers(binaryReader, blamPointers);
            invalidName_0[251].ReadPointers(binaryReader, blamPointers);
        }
        public override int Write(BinaryWriter binaryWriter, int nextAddress)
        {
            base.Write(binaryWriter, nextAddress);
using(binaryWriter.BaseStream.Pin())
            {
                binaryWriter.Write(invalidName_, 0, 172);
                binaryWriter.Write((Int32)language);
                nextAddress = Guerilla.WriteBlockArray<HavokCleanupResourcesBlock>(binaryWriter, havokCleanupResources, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<CollisionDamageBlock>(binaryWriter, collisionDamage, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<SoundGlobalsBlock>(binaryWriter, soundGlobals, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<AiGlobalsBlock>(binaryWriter, aiGlobals, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<GameGlobalsDamageBlock>(binaryWriter, damageTable, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<GNullBlock>(binaryWriter, gNullBlock, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<MoonfishSoundReferencesBlock>(binaryWriter, sounds, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<CameraBlock>(binaryWriter, camera, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<PlayerControlBlock>(binaryWriter, playerControl, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<DifficultyBlock>(binaryWriter, difficulty, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<GrenadesBlock>(binaryWriter, grenades, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<RasterizerDataBlock>(binaryWriter, rasterizerData, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<InterfaceTagReferences>(binaryWriter, interfaceTags, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<CheatWeaponsBlock>(binaryWriter, weaponListUpdateWeaponListEnumInGameGlobalsH, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<CheatPowerupsBlock>(binaryWriter, cheatPowerups, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<MultiplayerInformationBlock>(binaryWriter, multiplayerInformation, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<PlayerInformationBlock>(binaryWriter, playerInformation, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<PlayerRepresentationBlock>(binaryWriter, playerRepresentation, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<FallingDamageBlock>(binaryWriter, fallingDamage, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<OldMaterialsBlock>(binaryWriter, oldMaterials, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<MaterialsBlock>(binaryWriter, materials, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<MultiplayerUiBlock>(binaryWriter, multiplayerUI, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<MultiplayerColorBlock>(binaryWriter, profileColors, nextAddress);
                binaryWriter.Write(multiplayerGlobals);
                nextAddress = Guerilla.WriteBlockArray<RuntimeLevelsDefinitionBlock>(binaryWriter, runtimeLevelData, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<UiLevelsDefinitionBlock>(binaryWriter, uiLevelData, nextAddress);
                binaryWriter.Write(defaultGlobalLighting);
                binaryWriter.Write(invalidName_0, 0, 252);
                return nextAddress;
            }
        }
        internal enum Language : int
        {
            English = 0,
            Japanese = 1,
            German = 2,
            French = 3,
            Spanish = 4,
            Italian = 5,
            Korean = 6,
            Chinese = 7,
            Portuguese = 8,
        };
    };
}
