// ReSharper disable All
using Moonfish.Model;
using Moonfish.Tags.BlamExtension;
using Moonfish.Tags;
using OpenTK;
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

namespace Moonfish.Guerilla.Tags
{
    public partial class GlobalErrorReportCategoriesBlock : GlobalErrorReportCategoriesBlockBase
    {
        public GlobalErrorReportCategoriesBlock() : base()
        {
        }
    };
    [LayoutAttribute(Size = 676, Alignment = 4)]
    public class GlobalErrorReportCategoriesBlockBase : GuerillaBlock
    {
        internal Moonfish.Tags.String256 name;
        internal ReportType reportType;
        internal Flags flags;
        internal byte[] invalidName_;
        internal byte[] invalidName_0;
        internal byte[] invalidName_1;
        internal ErrorReportsBlock[] reports;
        public override int SerializedSize { get { return 676; } }
        public override int Alignment { get { return 4; } }
        public GlobalErrorReportCategoriesBlockBase() : base()
        {
        }
        public override Queue<BlamPointer> ReadFields(BinaryReader binaryReader)
        {
            var blamPointers = new Queue<BlamPointer>(base.ReadFields(binaryReader));
            name = binaryReader.ReadString256();
            reportType = (ReportType)binaryReader.ReadInt16();
            flags = (Flags)binaryReader.ReadInt16();
            invalidName_ = binaryReader.ReadBytes(2);
            invalidName_0 = binaryReader.ReadBytes(2);
            invalidName_1 = binaryReader.ReadBytes(404);
            blamPointers.Enqueue(ReadBlockArrayPointer<ErrorReportsBlock>(binaryReader));
            return blamPointers;
        }
        public override void ReadPointers(BinaryReader binaryReader, Queue<BlamPointer> blamPointers)
        {
            base.ReadPointers(binaryReader, blamPointers);
            invalidName_[0].ReadPointers(binaryReader, blamPointers);
            invalidName_[1].ReadPointers(binaryReader, blamPointers);
            invalidName_0[0].ReadPointers(binaryReader, blamPointers);
            invalidName_0[1].ReadPointers(binaryReader, blamPointers);
            invalidName_1[0].ReadPointers(binaryReader, blamPointers);
            invalidName_1[1].ReadPointers(binaryReader, blamPointers);
            invalidName_1[2].ReadPointers(binaryReader, blamPointers);
            invalidName_1[3].ReadPointers(binaryReader, blamPointers);
            invalidName_1[4].ReadPointers(binaryReader, blamPointers);
            invalidName_1[5].ReadPointers(binaryReader, blamPointers);
            invalidName_1[6].ReadPointers(binaryReader, blamPointers);
            invalidName_1[7].ReadPointers(binaryReader, blamPointers);
            invalidName_1[8].ReadPointers(binaryReader, blamPointers);
            invalidName_1[9].ReadPointers(binaryReader, blamPointers);
            invalidName_1[10].ReadPointers(binaryReader, blamPointers);
            invalidName_1[11].ReadPointers(binaryReader, blamPointers);
            invalidName_1[12].ReadPointers(binaryReader, blamPointers);
            invalidName_1[13].ReadPointers(binaryReader, blamPointers);
            invalidName_1[14].ReadPointers(binaryReader, blamPointers);
            invalidName_1[15].ReadPointers(binaryReader, blamPointers);
            invalidName_1[16].ReadPointers(binaryReader, blamPointers);
            invalidName_1[17].ReadPointers(binaryReader, blamPointers);
            invalidName_1[18].ReadPointers(binaryReader, blamPointers);
            invalidName_1[19].ReadPointers(binaryReader, blamPointers);
            invalidName_1[20].ReadPointers(binaryReader, blamPointers);
            invalidName_1[21].ReadPointers(binaryReader, blamPointers);
            invalidName_1[22].ReadPointers(binaryReader, blamPointers);
            invalidName_1[23].ReadPointers(binaryReader, blamPointers);
            invalidName_1[24].ReadPointers(binaryReader, blamPointers);
            invalidName_1[25].ReadPointers(binaryReader, blamPointers);
            invalidName_1[26].ReadPointers(binaryReader, blamPointers);
            invalidName_1[27].ReadPointers(binaryReader, blamPointers);
            invalidName_1[28].ReadPointers(binaryReader, blamPointers);
            invalidName_1[29].ReadPointers(binaryReader, blamPointers);
            invalidName_1[30].ReadPointers(binaryReader, blamPointers);
            invalidName_1[31].ReadPointers(binaryReader, blamPointers);
            invalidName_1[32].ReadPointers(binaryReader, blamPointers);
            invalidName_1[33].ReadPointers(binaryReader, blamPointers);
            invalidName_1[34].ReadPointers(binaryReader, blamPointers);
            invalidName_1[35].ReadPointers(binaryReader, blamPointers);
            invalidName_1[36].ReadPointers(binaryReader, blamPointers);
            invalidName_1[37].ReadPointers(binaryReader, blamPointers);
            invalidName_1[38].ReadPointers(binaryReader, blamPointers);
            invalidName_1[39].ReadPointers(binaryReader, blamPointers);
            invalidName_1[40].ReadPointers(binaryReader, blamPointers);
            invalidName_1[41].ReadPointers(binaryReader, blamPointers);
            invalidName_1[42].ReadPointers(binaryReader, blamPointers);
            invalidName_1[43].ReadPointers(binaryReader, blamPointers);
            invalidName_1[44].ReadPointers(binaryReader, blamPointers);
            invalidName_1[45].ReadPointers(binaryReader, blamPointers);
            invalidName_1[46].ReadPointers(binaryReader, blamPointers);
            invalidName_1[47].ReadPointers(binaryReader, blamPointers);
            invalidName_1[48].ReadPointers(binaryReader, blamPointers);
            invalidName_1[49].ReadPointers(binaryReader, blamPointers);
            invalidName_1[50].ReadPointers(binaryReader, blamPointers);
            invalidName_1[51].ReadPointers(binaryReader, blamPointers);
            invalidName_1[52].ReadPointers(binaryReader, blamPointers);
            invalidName_1[53].ReadPointers(binaryReader, blamPointers);
            invalidName_1[54].ReadPointers(binaryReader, blamPointers);
            invalidName_1[55].ReadPointers(binaryReader, blamPointers);
            invalidName_1[56].ReadPointers(binaryReader, blamPointers);
            invalidName_1[57].ReadPointers(binaryReader, blamPointers);
            invalidName_1[58].ReadPointers(binaryReader, blamPointers);
            invalidName_1[59].ReadPointers(binaryReader, blamPointers);
            invalidName_1[60].ReadPointers(binaryReader, blamPointers);
            invalidName_1[61].ReadPointers(binaryReader, blamPointers);
            invalidName_1[62].ReadPointers(binaryReader, blamPointers);
            invalidName_1[63].ReadPointers(binaryReader, blamPointers);
            invalidName_1[64].ReadPointers(binaryReader, blamPointers);
            invalidName_1[65].ReadPointers(binaryReader, blamPointers);
            invalidName_1[66].ReadPointers(binaryReader, blamPointers);
            invalidName_1[67].ReadPointers(binaryReader, blamPointers);
            invalidName_1[68].ReadPointers(binaryReader, blamPointers);
            invalidName_1[69].ReadPointers(binaryReader, blamPointers);
            invalidName_1[70].ReadPointers(binaryReader, blamPointers);
            invalidName_1[71].ReadPointers(binaryReader, blamPointers);
            invalidName_1[72].ReadPointers(binaryReader, blamPointers);
            invalidName_1[73].ReadPointers(binaryReader, blamPointers);
            invalidName_1[74].ReadPointers(binaryReader, blamPointers);
            invalidName_1[75].ReadPointers(binaryReader, blamPointers);
            invalidName_1[76].ReadPointers(binaryReader, blamPointers);
            invalidName_1[77].ReadPointers(binaryReader, blamPointers);
            invalidName_1[78].ReadPointers(binaryReader, blamPointers);
            invalidName_1[79].ReadPointers(binaryReader, blamPointers);
            invalidName_1[80].ReadPointers(binaryReader, blamPointers);
            invalidName_1[81].ReadPointers(binaryReader, blamPointers);
            invalidName_1[82].ReadPointers(binaryReader, blamPointers);
            invalidName_1[83].ReadPointers(binaryReader, blamPointers);
            invalidName_1[84].ReadPointers(binaryReader, blamPointers);
            invalidName_1[85].ReadPointers(binaryReader, blamPointers);
            invalidName_1[86].ReadPointers(binaryReader, blamPointers);
            invalidName_1[87].ReadPointers(binaryReader, blamPointers);
            invalidName_1[88].ReadPointers(binaryReader, blamPointers);
            invalidName_1[89].ReadPointers(binaryReader, blamPointers);
            invalidName_1[90].ReadPointers(binaryReader, blamPointers);
            invalidName_1[91].ReadPointers(binaryReader, blamPointers);
            invalidName_1[92].ReadPointers(binaryReader, blamPointers);
            invalidName_1[93].ReadPointers(binaryReader, blamPointers);
            invalidName_1[94].ReadPointers(binaryReader, blamPointers);
            invalidName_1[95].ReadPointers(binaryReader, blamPointers);
            invalidName_1[96].ReadPointers(binaryReader, blamPointers);
            invalidName_1[97].ReadPointers(binaryReader, blamPointers);
            invalidName_1[98].ReadPointers(binaryReader, blamPointers);
            invalidName_1[99].ReadPointers(binaryReader, blamPointers);
            invalidName_1[100].ReadPointers(binaryReader, blamPointers);
            invalidName_1[101].ReadPointers(binaryReader, blamPointers);
            invalidName_1[102].ReadPointers(binaryReader, blamPointers);
            invalidName_1[103].ReadPointers(binaryReader, blamPointers);
            invalidName_1[104].ReadPointers(binaryReader, blamPointers);
            invalidName_1[105].ReadPointers(binaryReader, blamPointers);
            invalidName_1[106].ReadPointers(binaryReader, blamPointers);
            invalidName_1[107].ReadPointers(binaryReader, blamPointers);
            invalidName_1[108].ReadPointers(binaryReader, blamPointers);
            invalidName_1[109].ReadPointers(binaryReader, blamPointers);
            invalidName_1[110].ReadPointers(binaryReader, blamPointers);
            invalidName_1[111].ReadPointers(binaryReader, blamPointers);
            invalidName_1[112].ReadPointers(binaryReader, blamPointers);
            invalidName_1[113].ReadPointers(binaryReader, blamPointers);
            invalidName_1[114].ReadPointers(binaryReader, blamPointers);
            invalidName_1[115].ReadPointers(binaryReader, blamPointers);
            invalidName_1[116].ReadPointers(binaryReader, blamPointers);
            invalidName_1[117].ReadPointers(binaryReader, blamPointers);
            invalidName_1[118].ReadPointers(binaryReader, blamPointers);
            invalidName_1[119].ReadPointers(binaryReader, blamPointers);
            invalidName_1[120].ReadPointers(binaryReader, blamPointers);
            invalidName_1[121].ReadPointers(binaryReader, blamPointers);
            invalidName_1[122].ReadPointers(binaryReader, blamPointers);
            invalidName_1[123].ReadPointers(binaryReader, blamPointers);
            invalidName_1[124].ReadPointers(binaryReader, blamPointers);
            invalidName_1[125].ReadPointers(binaryReader, blamPointers);
            invalidName_1[126].ReadPointers(binaryReader, blamPointers);
            invalidName_1[127].ReadPointers(binaryReader, blamPointers);
            invalidName_1[128].ReadPointers(binaryReader, blamPointers);
            invalidName_1[129].ReadPointers(binaryReader, blamPointers);
            invalidName_1[130].ReadPointers(binaryReader, blamPointers);
            invalidName_1[131].ReadPointers(binaryReader, blamPointers);
            invalidName_1[132].ReadPointers(binaryReader, blamPointers);
            invalidName_1[133].ReadPointers(binaryReader, blamPointers);
            invalidName_1[134].ReadPointers(binaryReader, blamPointers);
            invalidName_1[135].ReadPointers(binaryReader, blamPointers);
            invalidName_1[136].ReadPointers(binaryReader, blamPointers);
            invalidName_1[137].ReadPointers(binaryReader, blamPointers);
            invalidName_1[138].ReadPointers(binaryReader, blamPointers);
            invalidName_1[139].ReadPointers(binaryReader, blamPointers);
            invalidName_1[140].ReadPointers(binaryReader, blamPointers);
            invalidName_1[141].ReadPointers(binaryReader, blamPointers);
            invalidName_1[142].ReadPointers(binaryReader, blamPointers);
            invalidName_1[143].ReadPointers(binaryReader, blamPointers);
            invalidName_1[144].ReadPointers(binaryReader, blamPointers);
            invalidName_1[145].ReadPointers(binaryReader, blamPointers);
            invalidName_1[146].ReadPointers(binaryReader, blamPointers);
            invalidName_1[147].ReadPointers(binaryReader, blamPointers);
            invalidName_1[148].ReadPointers(binaryReader, blamPointers);
            invalidName_1[149].ReadPointers(binaryReader, blamPointers);
            invalidName_1[150].ReadPointers(binaryReader, blamPointers);
            invalidName_1[151].ReadPointers(binaryReader, blamPointers);
            invalidName_1[152].ReadPointers(binaryReader, blamPointers);
            invalidName_1[153].ReadPointers(binaryReader, blamPointers);
            invalidName_1[154].ReadPointers(binaryReader, blamPointers);
            invalidName_1[155].ReadPointers(binaryReader, blamPointers);
            invalidName_1[156].ReadPointers(binaryReader, blamPointers);
            invalidName_1[157].ReadPointers(binaryReader, blamPointers);
            invalidName_1[158].ReadPointers(binaryReader, blamPointers);
            invalidName_1[159].ReadPointers(binaryReader, blamPointers);
            invalidName_1[160].ReadPointers(binaryReader, blamPointers);
            invalidName_1[161].ReadPointers(binaryReader, blamPointers);
            invalidName_1[162].ReadPointers(binaryReader, blamPointers);
            invalidName_1[163].ReadPointers(binaryReader, blamPointers);
            invalidName_1[164].ReadPointers(binaryReader, blamPointers);
            invalidName_1[165].ReadPointers(binaryReader, blamPointers);
            invalidName_1[166].ReadPointers(binaryReader, blamPointers);
            invalidName_1[167].ReadPointers(binaryReader, blamPointers);
            invalidName_1[168].ReadPointers(binaryReader, blamPointers);
            invalidName_1[169].ReadPointers(binaryReader, blamPointers);
            invalidName_1[170].ReadPointers(binaryReader, blamPointers);
            invalidName_1[171].ReadPointers(binaryReader, blamPointers);
            invalidName_1[172].ReadPointers(binaryReader, blamPointers);
            invalidName_1[173].ReadPointers(binaryReader, blamPointers);
            invalidName_1[174].ReadPointers(binaryReader, blamPointers);
            invalidName_1[175].ReadPointers(binaryReader, blamPointers);
            invalidName_1[176].ReadPointers(binaryReader, blamPointers);
            invalidName_1[177].ReadPointers(binaryReader, blamPointers);
            invalidName_1[178].ReadPointers(binaryReader, blamPointers);
            invalidName_1[179].ReadPointers(binaryReader, blamPointers);
            invalidName_1[180].ReadPointers(binaryReader, blamPointers);
            invalidName_1[181].ReadPointers(binaryReader, blamPointers);
            invalidName_1[182].ReadPointers(binaryReader, blamPointers);
            invalidName_1[183].ReadPointers(binaryReader, blamPointers);
            invalidName_1[184].ReadPointers(binaryReader, blamPointers);
            invalidName_1[185].ReadPointers(binaryReader, blamPointers);
            invalidName_1[186].ReadPointers(binaryReader, blamPointers);
            invalidName_1[187].ReadPointers(binaryReader, blamPointers);
            invalidName_1[188].ReadPointers(binaryReader, blamPointers);
            invalidName_1[189].ReadPointers(binaryReader, blamPointers);
            invalidName_1[190].ReadPointers(binaryReader, blamPointers);
            invalidName_1[191].ReadPointers(binaryReader, blamPointers);
            invalidName_1[192].ReadPointers(binaryReader, blamPointers);
            invalidName_1[193].ReadPointers(binaryReader, blamPointers);
            invalidName_1[194].ReadPointers(binaryReader, blamPointers);
            invalidName_1[195].ReadPointers(binaryReader, blamPointers);
            invalidName_1[196].ReadPointers(binaryReader, blamPointers);
            invalidName_1[197].ReadPointers(binaryReader, blamPointers);
            invalidName_1[198].ReadPointers(binaryReader, blamPointers);
            invalidName_1[199].ReadPointers(binaryReader, blamPointers);
            invalidName_1[200].ReadPointers(binaryReader, blamPointers);
            invalidName_1[201].ReadPointers(binaryReader, blamPointers);
            invalidName_1[202].ReadPointers(binaryReader, blamPointers);
            invalidName_1[203].ReadPointers(binaryReader, blamPointers);
            invalidName_1[204].ReadPointers(binaryReader, blamPointers);
            invalidName_1[205].ReadPointers(binaryReader, blamPointers);
            invalidName_1[206].ReadPointers(binaryReader, blamPointers);
            invalidName_1[207].ReadPointers(binaryReader, blamPointers);
            invalidName_1[208].ReadPointers(binaryReader, blamPointers);
            invalidName_1[209].ReadPointers(binaryReader, blamPointers);
            invalidName_1[210].ReadPointers(binaryReader, blamPointers);
            invalidName_1[211].ReadPointers(binaryReader, blamPointers);
            invalidName_1[212].ReadPointers(binaryReader, blamPointers);
            invalidName_1[213].ReadPointers(binaryReader, blamPointers);
            invalidName_1[214].ReadPointers(binaryReader, blamPointers);
            invalidName_1[215].ReadPointers(binaryReader, blamPointers);
            invalidName_1[216].ReadPointers(binaryReader, blamPointers);
            invalidName_1[217].ReadPointers(binaryReader, blamPointers);
            invalidName_1[218].ReadPointers(binaryReader, blamPointers);
            invalidName_1[219].ReadPointers(binaryReader, blamPointers);
            invalidName_1[220].ReadPointers(binaryReader, blamPointers);
            invalidName_1[221].ReadPointers(binaryReader, blamPointers);
            invalidName_1[222].ReadPointers(binaryReader, blamPointers);
            invalidName_1[223].ReadPointers(binaryReader, blamPointers);
            invalidName_1[224].ReadPointers(binaryReader, blamPointers);
            invalidName_1[225].ReadPointers(binaryReader, blamPointers);
            invalidName_1[226].ReadPointers(binaryReader, blamPointers);
            invalidName_1[227].ReadPointers(binaryReader, blamPointers);
            invalidName_1[228].ReadPointers(binaryReader, blamPointers);
            invalidName_1[229].ReadPointers(binaryReader, blamPointers);
            invalidName_1[230].ReadPointers(binaryReader, blamPointers);
            invalidName_1[231].ReadPointers(binaryReader, blamPointers);
            invalidName_1[232].ReadPointers(binaryReader, blamPointers);
            invalidName_1[233].ReadPointers(binaryReader, blamPointers);
            invalidName_1[234].ReadPointers(binaryReader, blamPointers);
            invalidName_1[235].ReadPointers(binaryReader, blamPointers);
            invalidName_1[236].ReadPointers(binaryReader, blamPointers);
            invalidName_1[237].ReadPointers(binaryReader, blamPointers);
            invalidName_1[238].ReadPointers(binaryReader, blamPointers);
            invalidName_1[239].ReadPointers(binaryReader, blamPointers);
            invalidName_1[240].ReadPointers(binaryReader, blamPointers);
            invalidName_1[241].ReadPointers(binaryReader, blamPointers);
            invalidName_1[242].ReadPointers(binaryReader, blamPointers);
            invalidName_1[243].ReadPointers(binaryReader, blamPointers);
            invalidName_1[244].ReadPointers(binaryReader, blamPointers);
            invalidName_1[245].ReadPointers(binaryReader, blamPointers);
            invalidName_1[246].ReadPointers(binaryReader, blamPointers);
            invalidName_1[247].ReadPointers(binaryReader, blamPointers);
            invalidName_1[248].ReadPointers(binaryReader, blamPointers);
            invalidName_1[249].ReadPointers(binaryReader, blamPointers);
            invalidName_1[250].ReadPointers(binaryReader, blamPointers);
            invalidName_1[251].ReadPointers(binaryReader, blamPointers);
            invalidName_1[252].ReadPointers(binaryReader, blamPointers);
            invalidName_1[253].ReadPointers(binaryReader, blamPointers);
            invalidName_1[254].ReadPointers(binaryReader, blamPointers);
            invalidName_1[255].ReadPointers(binaryReader, blamPointers);
            invalidName_1[256].ReadPointers(binaryReader, blamPointers);
            invalidName_1[257].ReadPointers(binaryReader, blamPointers);
            invalidName_1[258].ReadPointers(binaryReader, blamPointers);
            invalidName_1[259].ReadPointers(binaryReader, blamPointers);
            invalidName_1[260].ReadPointers(binaryReader, blamPointers);
            invalidName_1[261].ReadPointers(binaryReader, blamPointers);
            invalidName_1[262].ReadPointers(binaryReader, blamPointers);
            invalidName_1[263].ReadPointers(binaryReader, blamPointers);
            invalidName_1[264].ReadPointers(binaryReader, blamPointers);
            invalidName_1[265].ReadPointers(binaryReader, blamPointers);
            invalidName_1[266].ReadPointers(binaryReader, blamPointers);
            invalidName_1[267].ReadPointers(binaryReader, blamPointers);
            invalidName_1[268].ReadPointers(binaryReader, blamPointers);
            invalidName_1[269].ReadPointers(binaryReader, blamPointers);
            invalidName_1[270].ReadPointers(binaryReader, blamPointers);
            invalidName_1[271].ReadPointers(binaryReader, blamPointers);
            invalidName_1[272].ReadPointers(binaryReader, blamPointers);
            invalidName_1[273].ReadPointers(binaryReader, blamPointers);
            invalidName_1[274].ReadPointers(binaryReader, blamPointers);
            invalidName_1[275].ReadPointers(binaryReader, blamPointers);
            invalidName_1[276].ReadPointers(binaryReader, blamPointers);
            invalidName_1[277].ReadPointers(binaryReader, blamPointers);
            invalidName_1[278].ReadPointers(binaryReader, blamPointers);
            invalidName_1[279].ReadPointers(binaryReader, blamPointers);
            invalidName_1[280].ReadPointers(binaryReader, blamPointers);
            invalidName_1[281].ReadPointers(binaryReader, blamPointers);
            invalidName_1[282].ReadPointers(binaryReader, blamPointers);
            invalidName_1[283].ReadPointers(binaryReader, blamPointers);
            invalidName_1[284].ReadPointers(binaryReader, blamPointers);
            invalidName_1[285].ReadPointers(binaryReader, blamPointers);
            invalidName_1[286].ReadPointers(binaryReader, blamPointers);
            invalidName_1[287].ReadPointers(binaryReader, blamPointers);
            invalidName_1[288].ReadPointers(binaryReader, blamPointers);
            invalidName_1[289].ReadPointers(binaryReader, blamPointers);
            invalidName_1[290].ReadPointers(binaryReader, blamPointers);
            invalidName_1[291].ReadPointers(binaryReader, blamPointers);
            invalidName_1[292].ReadPointers(binaryReader, blamPointers);
            invalidName_1[293].ReadPointers(binaryReader, blamPointers);
            invalidName_1[294].ReadPointers(binaryReader, blamPointers);
            invalidName_1[295].ReadPointers(binaryReader, blamPointers);
            invalidName_1[296].ReadPointers(binaryReader, blamPointers);
            invalidName_1[297].ReadPointers(binaryReader, blamPointers);
            invalidName_1[298].ReadPointers(binaryReader, blamPointers);
            invalidName_1[299].ReadPointers(binaryReader, blamPointers);
            invalidName_1[300].ReadPointers(binaryReader, blamPointers);
            invalidName_1[301].ReadPointers(binaryReader, blamPointers);
            invalidName_1[302].ReadPointers(binaryReader, blamPointers);
            invalidName_1[303].ReadPointers(binaryReader, blamPointers);
            invalidName_1[304].ReadPointers(binaryReader, blamPointers);
            invalidName_1[305].ReadPointers(binaryReader, blamPointers);
            invalidName_1[306].ReadPointers(binaryReader, blamPointers);
            invalidName_1[307].ReadPointers(binaryReader, blamPointers);
            invalidName_1[308].ReadPointers(binaryReader, blamPointers);
            invalidName_1[309].ReadPointers(binaryReader, blamPointers);
            invalidName_1[310].ReadPointers(binaryReader, blamPointers);
            invalidName_1[311].ReadPointers(binaryReader, blamPointers);
            invalidName_1[312].ReadPointers(binaryReader, blamPointers);
            invalidName_1[313].ReadPointers(binaryReader, blamPointers);
            invalidName_1[314].ReadPointers(binaryReader, blamPointers);
            invalidName_1[315].ReadPointers(binaryReader, blamPointers);
            invalidName_1[316].ReadPointers(binaryReader, blamPointers);
            invalidName_1[317].ReadPointers(binaryReader, blamPointers);
            invalidName_1[318].ReadPointers(binaryReader, blamPointers);
            invalidName_1[319].ReadPointers(binaryReader, blamPointers);
            invalidName_1[320].ReadPointers(binaryReader, blamPointers);
            invalidName_1[321].ReadPointers(binaryReader, blamPointers);
            invalidName_1[322].ReadPointers(binaryReader, blamPointers);
            invalidName_1[323].ReadPointers(binaryReader, blamPointers);
            invalidName_1[324].ReadPointers(binaryReader, blamPointers);
            invalidName_1[325].ReadPointers(binaryReader, blamPointers);
            invalidName_1[326].ReadPointers(binaryReader, blamPointers);
            invalidName_1[327].ReadPointers(binaryReader, blamPointers);
            invalidName_1[328].ReadPointers(binaryReader, blamPointers);
            invalidName_1[329].ReadPointers(binaryReader, blamPointers);
            invalidName_1[330].ReadPointers(binaryReader, blamPointers);
            invalidName_1[331].ReadPointers(binaryReader, blamPointers);
            invalidName_1[332].ReadPointers(binaryReader, blamPointers);
            invalidName_1[333].ReadPointers(binaryReader, blamPointers);
            invalidName_1[334].ReadPointers(binaryReader, blamPointers);
            invalidName_1[335].ReadPointers(binaryReader, blamPointers);
            invalidName_1[336].ReadPointers(binaryReader, blamPointers);
            invalidName_1[337].ReadPointers(binaryReader, blamPointers);
            invalidName_1[338].ReadPointers(binaryReader, blamPointers);
            invalidName_1[339].ReadPointers(binaryReader, blamPointers);
            invalidName_1[340].ReadPointers(binaryReader, blamPointers);
            invalidName_1[341].ReadPointers(binaryReader, blamPointers);
            invalidName_1[342].ReadPointers(binaryReader, blamPointers);
            invalidName_1[343].ReadPointers(binaryReader, blamPointers);
            invalidName_1[344].ReadPointers(binaryReader, blamPointers);
            invalidName_1[345].ReadPointers(binaryReader, blamPointers);
            invalidName_1[346].ReadPointers(binaryReader, blamPointers);
            invalidName_1[347].ReadPointers(binaryReader, blamPointers);
            invalidName_1[348].ReadPointers(binaryReader, blamPointers);
            invalidName_1[349].ReadPointers(binaryReader, blamPointers);
            invalidName_1[350].ReadPointers(binaryReader, blamPointers);
            invalidName_1[351].ReadPointers(binaryReader, blamPointers);
            invalidName_1[352].ReadPointers(binaryReader, blamPointers);
            invalidName_1[353].ReadPointers(binaryReader, blamPointers);
            invalidName_1[354].ReadPointers(binaryReader, blamPointers);
            invalidName_1[355].ReadPointers(binaryReader, blamPointers);
            invalidName_1[356].ReadPointers(binaryReader, blamPointers);
            invalidName_1[357].ReadPointers(binaryReader, blamPointers);
            invalidName_1[358].ReadPointers(binaryReader, blamPointers);
            invalidName_1[359].ReadPointers(binaryReader, blamPointers);
            invalidName_1[360].ReadPointers(binaryReader, blamPointers);
            invalidName_1[361].ReadPointers(binaryReader, blamPointers);
            invalidName_1[362].ReadPointers(binaryReader, blamPointers);
            invalidName_1[363].ReadPointers(binaryReader, blamPointers);
            invalidName_1[364].ReadPointers(binaryReader, blamPointers);
            invalidName_1[365].ReadPointers(binaryReader, blamPointers);
            invalidName_1[366].ReadPointers(binaryReader, blamPointers);
            invalidName_1[367].ReadPointers(binaryReader, blamPointers);
            invalidName_1[368].ReadPointers(binaryReader, blamPointers);
            invalidName_1[369].ReadPointers(binaryReader, blamPointers);
            invalidName_1[370].ReadPointers(binaryReader, blamPointers);
            invalidName_1[371].ReadPointers(binaryReader, blamPointers);
            invalidName_1[372].ReadPointers(binaryReader, blamPointers);
            invalidName_1[373].ReadPointers(binaryReader, blamPointers);
            invalidName_1[374].ReadPointers(binaryReader, blamPointers);
            invalidName_1[375].ReadPointers(binaryReader, blamPointers);
            invalidName_1[376].ReadPointers(binaryReader, blamPointers);
            invalidName_1[377].ReadPointers(binaryReader, blamPointers);
            invalidName_1[378].ReadPointers(binaryReader, blamPointers);
            invalidName_1[379].ReadPointers(binaryReader, blamPointers);
            invalidName_1[380].ReadPointers(binaryReader, blamPointers);
            invalidName_1[381].ReadPointers(binaryReader, blamPointers);
            invalidName_1[382].ReadPointers(binaryReader, blamPointers);
            invalidName_1[383].ReadPointers(binaryReader, blamPointers);
            invalidName_1[384].ReadPointers(binaryReader, blamPointers);
            invalidName_1[385].ReadPointers(binaryReader, blamPointers);
            invalidName_1[386].ReadPointers(binaryReader, blamPointers);
            invalidName_1[387].ReadPointers(binaryReader, blamPointers);
            invalidName_1[388].ReadPointers(binaryReader, blamPointers);
            invalidName_1[389].ReadPointers(binaryReader, blamPointers);
            invalidName_1[390].ReadPointers(binaryReader, blamPointers);
            invalidName_1[391].ReadPointers(binaryReader, blamPointers);
            invalidName_1[392].ReadPointers(binaryReader, blamPointers);
            invalidName_1[393].ReadPointers(binaryReader, blamPointers);
            invalidName_1[394].ReadPointers(binaryReader, blamPointers);
            invalidName_1[395].ReadPointers(binaryReader, blamPointers);
            invalidName_1[396].ReadPointers(binaryReader, blamPointers);
            invalidName_1[397].ReadPointers(binaryReader, blamPointers);
            invalidName_1[398].ReadPointers(binaryReader, blamPointers);
            invalidName_1[399].ReadPointers(binaryReader, blamPointers);
            invalidName_1[400].ReadPointers(binaryReader, blamPointers);
            invalidName_1[401].ReadPointers(binaryReader, blamPointers);
            invalidName_1[402].ReadPointers(binaryReader, blamPointers);
            invalidName_1[403].ReadPointers(binaryReader, blamPointers);
            reports = ReadBlockArrayData<ErrorReportsBlock>(binaryReader, blamPointers.Dequeue());
        }
        public override int Write(BinaryWriter binaryWriter, int nextAddress)
        {
            base.Write(binaryWriter, nextAddress);
using(binaryWriter.BaseStream.Pin())
            {
                binaryWriter.Write(name);
                binaryWriter.Write((Int16)reportType);
                binaryWriter.Write((Int16)flags);
                binaryWriter.Write(invalidName_, 0, 2);
                binaryWriter.Write(invalidName_0, 0, 2);
                binaryWriter.Write(invalidName_1, 0, 404);
                nextAddress = Guerilla.WriteBlockArray<ErrorReportsBlock>(binaryWriter, reports, nextAddress);
                return nextAddress;
            }
        }
        internal enum ReportType : short
        {
            Silent = 0,
            Comment = 1,
            Warning = 2,
            Error = 3,
        };
        [FlagsAttribute]
        internal enum Flags : short
        {
            Rendered = 1,
            TangentSpace = 2,
            Noncritical = 4,
            LightmapLight = 8,
            ReportKeyIsValid = 16,
        };
    };
}
