// ReSharper disable All
using Moonfish.Model;
using Moonfish.Tags.BlamExtension;
using Moonfish.Tags;
using OpenTK;
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

namespace Moonfish.Tags
{
    public partial struct TagClass
    {
        public static readonly TagClass Hudg = (TagClass)"hudg";
    };
};

namespace Moonfish.Guerilla.Tags
{
    [TagClassAttribute("hudg")]
    public partial class HudGlobalsBlock : HudGlobalsBlockBase
    {
        public HudGlobalsBlock() : base()
        {
        }
    };
    [LayoutAttribute(Size = 1160, Alignment = 4)]
    public class HudGlobalsBlockBase : GuerillaBlock
    {
        internal Anchor anchor;
        internal byte[] invalidName_;
        internal byte[] invalidName_0;
        internal Moonfish.Tags.Point anchorOffset;
        internal float widthScale;
        internal float heightScale;
        internal ScalingFlags scalingFlags;
        internal byte[] invalidName_1;
        internal byte[] invalidName_2;
        [TagReference("bitm")]
        internal Moonfish.Tags.TagReference obsolete1;
        [TagReference("bitm")]
        internal Moonfish.Tags.TagReference obsolete2;
        internal float upTime;
        internal float fadeTime;
        internal OpenTK.Vector4 iconColor;
        internal OpenTK.Vector4 textColor;
        internal float textSpacing;
        [TagReference("unic")]
        internal Moonfish.Tags.TagReference itemMessageText;
        [TagReference("bitm")]
        internal Moonfish.Tags.TagReference iconBitmap;
        [TagReference("unic")]
        internal Moonfish.Tags.TagReference alternateIconText;
        internal HudButtonIconBlock[] buttonIcons;
        internal Moonfish.Tags.ColourA1R1G1B1 defaultColor;
        internal Moonfish.Tags.ColourA1R1G1B1 flashingColor;
        internal float flashPeriod;
        /// <summary>
        /// time between flashes
        /// </summary>
        internal float flashDelay;
        internal short numberOfFlashes;
        internal FlashFlags flashFlags;
        /// <summary>
        /// time of each flash
        /// </summary>
        internal float flashLength;
        internal Moonfish.Tags.ColourA1R1G1B1 disabledColor;
        internal byte[] invalidName_3;
        [TagReference("hmt ")]
        internal Moonfish.Tags.TagReference hudMessages;
        internal Moonfish.Tags.ColourA1R1G1B1 defaultColor0;
        internal Moonfish.Tags.ColourA1R1G1B1 flashingColor0;
        internal float flashPeriod0;
        /// <summary>
        /// time between flashes
        /// </summary>
        internal float flashDelay0;
        internal short numberOfFlashes0;
        internal FlashFlags flashFlags0;
        /// <summary>
        /// time of each flash
        /// </summary>
        internal float flashLength0;
        internal Moonfish.Tags.ColourA1R1G1B1 disabledColor0;
        internal short uptimeTicks;
        internal short fadeTicks;
        internal float topOffset;
        internal float bottomOffset;
        internal float leftOffset;
        internal float rightOffset;
        internal byte[] invalidName_4;
        [TagReference("bitm")]
        internal Moonfish.Tags.TagReference arrowBitmap;
        internal HudWaypointArrowBlock[] waypointArrows;
        internal byte[] invalidName_5;
        internal float hudScaleInMultiplayer;
        internal byte[] invalidName_6;
        internal byte[] invalidName_7;
        internal float motionSensorRange;
        /// <summary>
        /// how fast something moves to show up on the motion sensor
        /// </summary>
        internal float motionSensorVelocitySensitivity;
        internal float motionSensorScaleDONTTOUCHEVER;
        internal OpenTK.Vector2 defaultChapterTitleBounds;
        internal byte[] invalidName_8;
        internal short topOffset0;
        internal short bottomOffset0;
        internal short leftOffset0;
        internal short rightOffset0;
        internal byte[] invalidName_9;
        [TagReference("bitm")]
        internal Moonfish.Tags.TagReference indicatorBitmap;
        internal short sequenceIndex;
        internal short multiplayerSequenceIndex;
        internal Moonfish.Tags.ColourA1R1G1B1 color;
        internal byte[] invalidName_10;
        internal Moonfish.Tags.ColourA1R1G1B1 defaultColor1;
        internal Moonfish.Tags.ColourA1R1G1B1 flashingColor1;
        internal float flashPeriod1;
        /// <summary>
        /// time between flashes
        /// </summary>
        internal float flashDelay1;
        internal short numberOfFlashes1;
        internal FlashFlags flashFlags1;
        /// <summary>
        /// time of each flash
        /// </summary>
        internal float flashLength1;
        internal Moonfish.Tags.ColourA1R1G1B1 disabledColor1;
        internal byte[] invalidName_11;
        internal Moonfish.Tags.ColourA1R1G1B1 defaultColor2;
        internal Moonfish.Tags.ColourA1R1G1B1 flashingColor2;
        internal float flashPeriod2;
        /// <summary>
        /// time between flashes
        /// </summary>
        internal float flashDelay2;
        internal short numberOfFlashes2;
        internal FlashFlags flashFlags2;
        /// <summary>
        /// time of each flash
        /// </summary>
        internal float flashLength2;
        internal Moonfish.Tags.ColourA1R1G1B1 disabledColor2;
        internal byte[] invalidName_12;
        internal byte[] invalidName_13;
        [TagReference("bitm")]
        internal Moonfish.Tags.TagReference carnageReportBitmap;
        internal short loadingBeginText;
        internal short loadingEndText;
        internal short checkpointBeginText;
        internal short checkpointEndText;
        [TagReference("snd!")]
        internal Moonfish.Tags.TagReference checkpointSound;
        internal byte[] invalidName_14;
        internal GlobalNewHudGlobalsStructBlock newGlobals;
        public override int SerializedSize { get { return 1160; } }
        public override int Alignment { get { return 4; } }
        public HudGlobalsBlockBase() : base()
        {
        }
        public override Queue<BlamPointer> ReadFields(BinaryReader binaryReader)
        {
            var blamPointers = new Queue<BlamPointer>(base.ReadFields(binaryReader));
            anchor = (Anchor)binaryReader.ReadInt16();
            invalidName_ = binaryReader.ReadBytes(2);
            invalidName_0 = binaryReader.ReadBytes(32);
            anchorOffset = binaryReader.ReadPoint();
            widthScale = binaryReader.ReadSingle();
            heightScale = binaryReader.ReadSingle();
            scalingFlags = (ScalingFlags)binaryReader.ReadInt16();
            invalidName_1 = binaryReader.ReadBytes(2);
            invalidName_2 = binaryReader.ReadBytes(20);
            obsolete1 = binaryReader.ReadTagReference();
            obsolete2 = binaryReader.ReadTagReference();
            upTime = binaryReader.ReadSingle();
            fadeTime = binaryReader.ReadSingle();
            iconColor = binaryReader.ReadVector4();
            textColor = binaryReader.ReadVector4();
            textSpacing = binaryReader.ReadSingle();
            itemMessageText = binaryReader.ReadTagReference();
            iconBitmap = binaryReader.ReadTagReference();
            alternateIconText = binaryReader.ReadTagReference();
            blamPointers.Enqueue(ReadBlockArrayPointer<HudButtonIconBlock>(binaryReader));
            defaultColor = binaryReader.ReadColourA1R1G1B1();
            flashingColor = binaryReader.ReadColourA1R1G1B1();
            flashPeriod = binaryReader.ReadSingle();
            flashDelay = binaryReader.ReadSingle();
            numberOfFlashes = binaryReader.ReadInt16();
            flashFlags = (FlashFlags)binaryReader.ReadInt16();
            flashLength = binaryReader.ReadSingle();
            disabledColor = binaryReader.ReadColourA1R1G1B1();
            invalidName_3 = binaryReader.ReadBytes(4);
            hudMessages = binaryReader.ReadTagReference();
            defaultColor0 = binaryReader.ReadColourA1R1G1B1();
            flashingColor0 = binaryReader.ReadColourA1R1G1B1();
            flashPeriod0 = binaryReader.ReadSingle();
            flashDelay0 = binaryReader.ReadSingle();
            numberOfFlashes0 = binaryReader.ReadInt16();
            flashFlags0 = (FlashFlags)binaryReader.ReadInt16();
            flashLength0 = binaryReader.ReadSingle();
            disabledColor0 = binaryReader.ReadColourA1R1G1B1();
            uptimeTicks = binaryReader.ReadInt16();
            fadeTicks = binaryReader.ReadInt16();
            topOffset = binaryReader.ReadSingle();
            bottomOffset = binaryReader.ReadSingle();
            leftOffset = binaryReader.ReadSingle();
            rightOffset = binaryReader.ReadSingle();
            invalidName_4 = binaryReader.ReadBytes(32);
            arrowBitmap = binaryReader.ReadTagReference();
            blamPointers.Enqueue(ReadBlockArrayPointer<HudWaypointArrowBlock>(binaryReader));
            invalidName_5 = binaryReader.ReadBytes(80);
            hudScaleInMultiplayer = binaryReader.ReadSingle();
            invalidName_6 = binaryReader.ReadBytes(256);
            invalidName_7 = binaryReader.ReadBytes(16);
            motionSensorRange = binaryReader.ReadSingle();
            motionSensorVelocitySensitivity = binaryReader.ReadSingle();
            motionSensorScaleDONTTOUCHEVER = binaryReader.ReadSingle();
            defaultChapterTitleBounds = binaryReader.ReadVector2();
            invalidName_8 = binaryReader.ReadBytes(44);
            topOffset0 = binaryReader.ReadInt16();
            bottomOffset0 = binaryReader.ReadInt16();
            leftOffset0 = binaryReader.ReadInt16();
            rightOffset0 = binaryReader.ReadInt16();
            invalidName_9 = binaryReader.ReadBytes(32);
            indicatorBitmap = binaryReader.ReadTagReference();
            sequenceIndex = binaryReader.ReadInt16();
            multiplayerSequenceIndex = binaryReader.ReadInt16();
            color = binaryReader.ReadColourA1R1G1B1();
            invalidName_10 = binaryReader.ReadBytes(16);
            defaultColor1 = binaryReader.ReadColourA1R1G1B1();
            flashingColor1 = binaryReader.ReadColourA1R1G1B1();
            flashPeriod1 = binaryReader.ReadSingle();
            flashDelay1 = binaryReader.ReadSingle();
            numberOfFlashes1 = binaryReader.ReadInt16();
            flashFlags1 = (FlashFlags)binaryReader.ReadInt16();
            flashLength1 = binaryReader.ReadSingle();
            disabledColor1 = binaryReader.ReadColourA1R1G1B1();
            invalidName_11 = binaryReader.ReadBytes(4);
            defaultColor2 = binaryReader.ReadColourA1R1G1B1();
            flashingColor2 = binaryReader.ReadColourA1R1G1B1();
            flashPeriod2 = binaryReader.ReadSingle();
            flashDelay2 = binaryReader.ReadSingle();
            numberOfFlashes2 = binaryReader.ReadInt16();
            flashFlags2 = (FlashFlags)binaryReader.ReadInt16();
            flashLength2 = binaryReader.ReadSingle();
            disabledColor2 = binaryReader.ReadColourA1R1G1B1();
            invalidName_12 = binaryReader.ReadBytes(4);
            invalidName_13 = binaryReader.ReadBytes(40);
            carnageReportBitmap = binaryReader.ReadTagReference();
            loadingBeginText = binaryReader.ReadInt16();
            loadingEndText = binaryReader.ReadInt16();
            checkpointBeginText = binaryReader.ReadInt16();
            checkpointEndText = binaryReader.ReadInt16();
            checkpointSound = binaryReader.ReadTagReference();
            invalidName_14 = binaryReader.ReadBytes(96);
            newGlobals = new GlobalNewHudGlobalsStructBlock();
            blamPointers.Concat(newGlobals.ReadFields(binaryReader));
            return blamPointers;
        }
        public override void ReadPointers(BinaryReader binaryReader, Queue<BlamPointer> blamPointers)
        {
            base.ReadPointers(binaryReader, blamPointers);
            invalidName_[0].ReadPointers(binaryReader, blamPointers);
            invalidName_[1].ReadPointers(binaryReader, blamPointers);
            invalidName_0[0].ReadPointers(binaryReader, blamPointers);
            invalidName_0[1].ReadPointers(binaryReader, blamPointers);
            invalidName_0[2].ReadPointers(binaryReader, blamPointers);
            invalidName_0[3].ReadPointers(binaryReader, blamPointers);
            invalidName_0[4].ReadPointers(binaryReader, blamPointers);
            invalidName_0[5].ReadPointers(binaryReader, blamPointers);
            invalidName_0[6].ReadPointers(binaryReader, blamPointers);
            invalidName_0[7].ReadPointers(binaryReader, blamPointers);
            invalidName_0[8].ReadPointers(binaryReader, blamPointers);
            invalidName_0[9].ReadPointers(binaryReader, blamPointers);
            invalidName_0[10].ReadPointers(binaryReader, blamPointers);
            invalidName_0[11].ReadPointers(binaryReader, blamPointers);
            invalidName_0[12].ReadPointers(binaryReader, blamPointers);
            invalidName_0[13].ReadPointers(binaryReader, blamPointers);
            invalidName_0[14].ReadPointers(binaryReader, blamPointers);
            invalidName_0[15].ReadPointers(binaryReader, blamPointers);
            invalidName_0[16].ReadPointers(binaryReader, blamPointers);
            invalidName_0[17].ReadPointers(binaryReader, blamPointers);
            invalidName_0[18].ReadPointers(binaryReader, blamPointers);
            invalidName_0[19].ReadPointers(binaryReader, blamPointers);
            invalidName_0[20].ReadPointers(binaryReader, blamPointers);
            invalidName_0[21].ReadPointers(binaryReader, blamPointers);
            invalidName_0[22].ReadPointers(binaryReader, blamPointers);
            invalidName_0[23].ReadPointers(binaryReader, blamPointers);
            invalidName_0[24].ReadPointers(binaryReader, blamPointers);
            invalidName_0[25].ReadPointers(binaryReader, blamPointers);
            invalidName_0[26].ReadPointers(binaryReader, blamPointers);
            invalidName_0[27].ReadPointers(binaryReader, blamPointers);
            invalidName_0[28].ReadPointers(binaryReader, blamPointers);
            invalidName_0[29].ReadPointers(binaryReader, blamPointers);
            invalidName_0[30].ReadPointers(binaryReader, blamPointers);
            invalidName_0[31].ReadPointers(binaryReader, blamPointers);
            invalidName_1[0].ReadPointers(binaryReader, blamPointers);
            invalidName_1[1].ReadPointers(binaryReader, blamPointers);
            invalidName_2[0].ReadPointers(binaryReader, blamPointers);
            invalidName_2[1].ReadPointers(binaryReader, blamPointers);
            invalidName_2[2].ReadPointers(binaryReader, blamPointers);
            invalidName_2[3].ReadPointers(binaryReader, blamPointers);
            invalidName_2[4].ReadPointers(binaryReader, blamPointers);
            invalidName_2[5].ReadPointers(binaryReader, blamPointers);
            invalidName_2[6].ReadPointers(binaryReader, blamPointers);
            invalidName_2[7].ReadPointers(binaryReader, blamPointers);
            invalidName_2[8].ReadPointers(binaryReader, blamPointers);
            invalidName_2[9].ReadPointers(binaryReader, blamPointers);
            invalidName_2[10].ReadPointers(binaryReader, blamPointers);
            invalidName_2[11].ReadPointers(binaryReader, blamPointers);
            invalidName_2[12].ReadPointers(binaryReader, blamPointers);
            invalidName_2[13].ReadPointers(binaryReader, blamPointers);
            invalidName_2[14].ReadPointers(binaryReader, blamPointers);
            invalidName_2[15].ReadPointers(binaryReader, blamPointers);
            invalidName_2[16].ReadPointers(binaryReader, blamPointers);
            invalidName_2[17].ReadPointers(binaryReader, blamPointers);
            invalidName_2[18].ReadPointers(binaryReader, blamPointers);
            invalidName_2[19].ReadPointers(binaryReader, blamPointers);
            buttonIcons = ReadBlockArrayData<HudButtonIconBlock>(binaryReader, blamPointers.Dequeue());
            invalidName_3[0].ReadPointers(binaryReader, blamPointers);
            invalidName_3[1].ReadPointers(binaryReader, blamPointers);
            invalidName_3[2].ReadPointers(binaryReader, blamPointers);
            invalidName_3[3].ReadPointers(binaryReader, blamPointers);
            invalidName_4[0].ReadPointers(binaryReader, blamPointers);
            invalidName_4[1].ReadPointers(binaryReader, blamPointers);
            invalidName_4[2].ReadPointers(binaryReader, blamPointers);
            invalidName_4[3].ReadPointers(binaryReader, blamPointers);
            invalidName_4[4].ReadPointers(binaryReader, blamPointers);
            invalidName_4[5].ReadPointers(binaryReader, blamPointers);
            invalidName_4[6].ReadPointers(binaryReader, blamPointers);
            invalidName_4[7].ReadPointers(binaryReader, blamPointers);
            invalidName_4[8].ReadPointers(binaryReader, blamPointers);
            invalidName_4[9].ReadPointers(binaryReader, blamPointers);
            invalidName_4[10].ReadPointers(binaryReader, blamPointers);
            invalidName_4[11].ReadPointers(binaryReader, blamPointers);
            invalidName_4[12].ReadPointers(binaryReader, blamPointers);
            invalidName_4[13].ReadPointers(binaryReader, blamPointers);
            invalidName_4[14].ReadPointers(binaryReader, blamPointers);
            invalidName_4[15].ReadPointers(binaryReader, blamPointers);
            invalidName_4[16].ReadPointers(binaryReader, blamPointers);
            invalidName_4[17].ReadPointers(binaryReader, blamPointers);
            invalidName_4[18].ReadPointers(binaryReader, blamPointers);
            invalidName_4[19].ReadPointers(binaryReader, blamPointers);
            invalidName_4[20].ReadPointers(binaryReader, blamPointers);
            invalidName_4[21].ReadPointers(binaryReader, blamPointers);
            invalidName_4[22].ReadPointers(binaryReader, blamPointers);
            invalidName_4[23].ReadPointers(binaryReader, blamPointers);
            invalidName_4[24].ReadPointers(binaryReader, blamPointers);
            invalidName_4[25].ReadPointers(binaryReader, blamPointers);
            invalidName_4[26].ReadPointers(binaryReader, blamPointers);
            invalidName_4[27].ReadPointers(binaryReader, blamPointers);
            invalidName_4[28].ReadPointers(binaryReader, blamPointers);
            invalidName_4[29].ReadPointers(binaryReader, blamPointers);
            invalidName_4[30].ReadPointers(binaryReader, blamPointers);
            invalidName_4[31].ReadPointers(binaryReader, blamPointers);
            waypointArrows = ReadBlockArrayData<HudWaypointArrowBlock>(binaryReader, blamPointers.Dequeue());
            invalidName_5[0].ReadPointers(binaryReader, blamPointers);
            invalidName_5[1].ReadPointers(binaryReader, blamPointers);
            invalidName_5[2].ReadPointers(binaryReader, blamPointers);
            invalidName_5[3].ReadPointers(binaryReader, blamPointers);
            invalidName_5[4].ReadPointers(binaryReader, blamPointers);
            invalidName_5[5].ReadPointers(binaryReader, blamPointers);
            invalidName_5[6].ReadPointers(binaryReader, blamPointers);
            invalidName_5[7].ReadPointers(binaryReader, blamPointers);
            invalidName_5[8].ReadPointers(binaryReader, blamPointers);
            invalidName_5[9].ReadPointers(binaryReader, blamPointers);
            invalidName_5[10].ReadPointers(binaryReader, blamPointers);
            invalidName_5[11].ReadPointers(binaryReader, blamPointers);
            invalidName_5[12].ReadPointers(binaryReader, blamPointers);
            invalidName_5[13].ReadPointers(binaryReader, blamPointers);
            invalidName_5[14].ReadPointers(binaryReader, blamPointers);
            invalidName_5[15].ReadPointers(binaryReader, blamPointers);
            invalidName_5[16].ReadPointers(binaryReader, blamPointers);
            invalidName_5[17].ReadPointers(binaryReader, blamPointers);
            invalidName_5[18].ReadPointers(binaryReader, blamPointers);
            invalidName_5[19].ReadPointers(binaryReader, blamPointers);
            invalidName_5[20].ReadPointers(binaryReader, blamPointers);
            invalidName_5[21].ReadPointers(binaryReader, blamPointers);
            invalidName_5[22].ReadPointers(binaryReader, blamPointers);
            invalidName_5[23].ReadPointers(binaryReader, blamPointers);
            invalidName_5[24].ReadPointers(binaryReader, blamPointers);
            invalidName_5[25].ReadPointers(binaryReader, blamPointers);
            invalidName_5[26].ReadPointers(binaryReader, blamPointers);
            invalidName_5[27].ReadPointers(binaryReader, blamPointers);
            invalidName_5[28].ReadPointers(binaryReader, blamPointers);
            invalidName_5[29].ReadPointers(binaryReader, blamPointers);
            invalidName_5[30].ReadPointers(binaryReader, blamPointers);
            invalidName_5[31].ReadPointers(binaryReader, blamPointers);
            invalidName_5[32].ReadPointers(binaryReader, blamPointers);
            invalidName_5[33].ReadPointers(binaryReader, blamPointers);
            invalidName_5[34].ReadPointers(binaryReader, blamPointers);
            invalidName_5[35].ReadPointers(binaryReader, blamPointers);
            invalidName_5[36].ReadPointers(binaryReader, blamPointers);
            invalidName_5[37].ReadPointers(binaryReader, blamPointers);
            invalidName_5[38].ReadPointers(binaryReader, blamPointers);
            invalidName_5[39].ReadPointers(binaryReader, blamPointers);
            invalidName_5[40].ReadPointers(binaryReader, blamPointers);
            invalidName_5[41].ReadPointers(binaryReader, blamPointers);
            invalidName_5[42].ReadPointers(binaryReader, blamPointers);
            invalidName_5[43].ReadPointers(binaryReader, blamPointers);
            invalidName_5[44].ReadPointers(binaryReader, blamPointers);
            invalidName_5[45].ReadPointers(binaryReader, blamPointers);
            invalidName_5[46].ReadPointers(binaryReader, blamPointers);
            invalidName_5[47].ReadPointers(binaryReader, blamPointers);
            invalidName_5[48].ReadPointers(binaryReader, blamPointers);
            invalidName_5[49].ReadPointers(binaryReader, blamPointers);
            invalidName_5[50].ReadPointers(binaryReader, blamPointers);
            invalidName_5[51].ReadPointers(binaryReader, blamPointers);
            invalidName_5[52].ReadPointers(binaryReader, blamPointers);
            invalidName_5[53].ReadPointers(binaryReader, blamPointers);
            invalidName_5[54].ReadPointers(binaryReader, blamPointers);
            invalidName_5[55].ReadPointers(binaryReader, blamPointers);
            invalidName_5[56].ReadPointers(binaryReader, blamPointers);
            invalidName_5[57].ReadPointers(binaryReader, blamPointers);
            invalidName_5[58].ReadPointers(binaryReader, blamPointers);
            invalidName_5[59].ReadPointers(binaryReader, blamPointers);
            invalidName_5[60].ReadPointers(binaryReader, blamPointers);
            invalidName_5[61].ReadPointers(binaryReader, blamPointers);
            invalidName_5[62].ReadPointers(binaryReader, blamPointers);
            invalidName_5[63].ReadPointers(binaryReader, blamPointers);
            invalidName_5[64].ReadPointers(binaryReader, blamPointers);
            invalidName_5[65].ReadPointers(binaryReader, blamPointers);
            invalidName_5[66].ReadPointers(binaryReader, blamPointers);
            invalidName_5[67].ReadPointers(binaryReader, blamPointers);
            invalidName_5[68].ReadPointers(binaryReader, blamPointers);
            invalidName_5[69].ReadPointers(binaryReader, blamPointers);
            invalidName_5[70].ReadPointers(binaryReader, blamPointers);
            invalidName_5[71].ReadPointers(binaryReader, blamPointers);
            invalidName_5[72].ReadPointers(binaryReader, blamPointers);
            invalidName_5[73].ReadPointers(binaryReader, blamPointers);
            invalidName_5[74].ReadPointers(binaryReader, blamPointers);
            invalidName_5[75].ReadPointers(binaryReader, blamPointers);
            invalidName_5[76].ReadPointers(binaryReader, blamPointers);
            invalidName_5[77].ReadPointers(binaryReader, blamPointers);
            invalidName_5[78].ReadPointers(binaryReader, blamPointers);
            invalidName_5[79].ReadPointers(binaryReader, blamPointers);
            invalidName_6[0].ReadPointers(binaryReader, blamPointers);
            invalidName_6[1].ReadPointers(binaryReader, blamPointers);
            invalidName_6[2].ReadPointers(binaryReader, blamPointers);
            invalidName_6[3].ReadPointers(binaryReader, blamPointers);
            invalidName_6[4].ReadPointers(binaryReader, blamPointers);
            invalidName_6[5].ReadPointers(binaryReader, blamPointers);
            invalidName_6[6].ReadPointers(binaryReader, blamPointers);
            invalidName_6[7].ReadPointers(binaryReader, blamPointers);
            invalidName_6[8].ReadPointers(binaryReader, blamPointers);
            invalidName_6[9].ReadPointers(binaryReader, blamPointers);
            invalidName_6[10].ReadPointers(binaryReader, blamPointers);
            invalidName_6[11].ReadPointers(binaryReader, blamPointers);
            invalidName_6[12].ReadPointers(binaryReader, blamPointers);
            invalidName_6[13].ReadPointers(binaryReader, blamPointers);
            invalidName_6[14].ReadPointers(binaryReader, blamPointers);
            invalidName_6[15].ReadPointers(binaryReader, blamPointers);
            invalidName_6[16].ReadPointers(binaryReader, blamPointers);
            invalidName_6[17].ReadPointers(binaryReader, blamPointers);
            invalidName_6[18].ReadPointers(binaryReader, blamPointers);
            invalidName_6[19].ReadPointers(binaryReader, blamPointers);
            invalidName_6[20].ReadPointers(binaryReader, blamPointers);
            invalidName_6[21].ReadPointers(binaryReader, blamPointers);
            invalidName_6[22].ReadPointers(binaryReader, blamPointers);
            invalidName_6[23].ReadPointers(binaryReader, blamPointers);
            invalidName_6[24].ReadPointers(binaryReader, blamPointers);
            invalidName_6[25].ReadPointers(binaryReader, blamPointers);
            invalidName_6[26].ReadPointers(binaryReader, blamPointers);
            invalidName_6[27].ReadPointers(binaryReader, blamPointers);
            invalidName_6[28].ReadPointers(binaryReader, blamPointers);
            invalidName_6[29].ReadPointers(binaryReader, blamPointers);
            invalidName_6[30].ReadPointers(binaryReader, blamPointers);
            invalidName_6[31].ReadPointers(binaryReader, blamPointers);
            invalidName_6[32].ReadPointers(binaryReader, blamPointers);
            invalidName_6[33].ReadPointers(binaryReader, blamPointers);
            invalidName_6[34].ReadPointers(binaryReader, blamPointers);
            invalidName_6[35].ReadPointers(binaryReader, blamPointers);
            invalidName_6[36].ReadPointers(binaryReader, blamPointers);
            invalidName_6[37].ReadPointers(binaryReader, blamPointers);
            invalidName_6[38].ReadPointers(binaryReader, blamPointers);
            invalidName_6[39].ReadPointers(binaryReader, blamPointers);
            invalidName_6[40].ReadPointers(binaryReader, blamPointers);
            invalidName_6[41].ReadPointers(binaryReader, blamPointers);
            invalidName_6[42].ReadPointers(binaryReader, blamPointers);
            invalidName_6[43].ReadPointers(binaryReader, blamPointers);
            invalidName_6[44].ReadPointers(binaryReader, blamPointers);
            invalidName_6[45].ReadPointers(binaryReader, blamPointers);
            invalidName_6[46].ReadPointers(binaryReader, blamPointers);
            invalidName_6[47].ReadPointers(binaryReader, blamPointers);
            invalidName_6[48].ReadPointers(binaryReader, blamPointers);
            invalidName_6[49].ReadPointers(binaryReader, blamPointers);
            invalidName_6[50].ReadPointers(binaryReader, blamPointers);
            invalidName_6[51].ReadPointers(binaryReader, blamPointers);
            invalidName_6[52].ReadPointers(binaryReader, blamPointers);
            invalidName_6[53].ReadPointers(binaryReader, blamPointers);
            invalidName_6[54].ReadPointers(binaryReader, blamPointers);
            invalidName_6[55].ReadPointers(binaryReader, blamPointers);
            invalidName_6[56].ReadPointers(binaryReader, blamPointers);
            invalidName_6[57].ReadPointers(binaryReader, blamPointers);
            invalidName_6[58].ReadPointers(binaryReader, blamPointers);
            invalidName_6[59].ReadPointers(binaryReader, blamPointers);
            invalidName_6[60].ReadPointers(binaryReader, blamPointers);
            invalidName_6[61].ReadPointers(binaryReader, blamPointers);
            invalidName_6[62].ReadPointers(binaryReader, blamPointers);
            invalidName_6[63].ReadPointers(binaryReader, blamPointers);
            invalidName_6[64].ReadPointers(binaryReader, blamPointers);
            invalidName_6[65].ReadPointers(binaryReader, blamPointers);
            invalidName_6[66].ReadPointers(binaryReader, blamPointers);
            invalidName_6[67].ReadPointers(binaryReader, blamPointers);
            invalidName_6[68].ReadPointers(binaryReader, blamPointers);
            invalidName_6[69].ReadPointers(binaryReader, blamPointers);
            invalidName_6[70].ReadPointers(binaryReader, blamPointers);
            invalidName_6[71].ReadPointers(binaryReader, blamPointers);
            invalidName_6[72].ReadPointers(binaryReader, blamPointers);
            invalidName_6[73].ReadPointers(binaryReader, blamPointers);
            invalidName_6[74].ReadPointers(binaryReader, blamPointers);
            invalidName_6[75].ReadPointers(binaryReader, blamPointers);
            invalidName_6[76].ReadPointers(binaryReader, blamPointers);
            invalidName_6[77].ReadPointers(binaryReader, blamPointers);
            invalidName_6[78].ReadPointers(binaryReader, blamPointers);
            invalidName_6[79].ReadPointers(binaryReader, blamPointers);
            invalidName_6[80].ReadPointers(binaryReader, blamPointers);
            invalidName_6[81].ReadPointers(binaryReader, blamPointers);
            invalidName_6[82].ReadPointers(binaryReader, blamPointers);
            invalidName_6[83].ReadPointers(binaryReader, blamPointers);
            invalidName_6[84].ReadPointers(binaryReader, blamPointers);
            invalidName_6[85].ReadPointers(binaryReader, blamPointers);
            invalidName_6[86].ReadPointers(binaryReader, blamPointers);
            invalidName_6[87].ReadPointers(binaryReader, blamPointers);
            invalidName_6[88].ReadPointers(binaryReader, blamPointers);
            invalidName_6[89].ReadPointers(binaryReader, blamPointers);
            invalidName_6[90].ReadPointers(binaryReader, blamPointers);
            invalidName_6[91].ReadPointers(binaryReader, blamPointers);
            invalidName_6[92].ReadPointers(binaryReader, blamPointers);
            invalidName_6[93].ReadPointers(binaryReader, blamPointers);
            invalidName_6[94].ReadPointers(binaryReader, blamPointers);
            invalidName_6[95].ReadPointers(binaryReader, blamPointers);
            invalidName_6[96].ReadPointers(binaryReader, blamPointers);
            invalidName_6[97].ReadPointers(binaryReader, blamPointers);
            invalidName_6[98].ReadPointers(binaryReader, blamPointers);
            invalidName_6[99].ReadPointers(binaryReader, blamPointers);
            invalidName_6[100].ReadPointers(binaryReader, blamPointers);
            invalidName_6[101].ReadPointers(binaryReader, blamPointers);
            invalidName_6[102].ReadPointers(binaryReader, blamPointers);
            invalidName_6[103].ReadPointers(binaryReader, blamPointers);
            invalidName_6[104].ReadPointers(binaryReader, blamPointers);
            invalidName_6[105].ReadPointers(binaryReader, blamPointers);
            invalidName_6[106].ReadPointers(binaryReader, blamPointers);
            invalidName_6[107].ReadPointers(binaryReader, blamPointers);
            invalidName_6[108].ReadPointers(binaryReader, blamPointers);
            invalidName_6[109].ReadPointers(binaryReader, blamPointers);
            invalidName_6[110].ReadPointers(binaryReader, blamPointers);
            invalidName_6[111].ReadPointers(binaryReader, blamPointers);
            invalidName_6[112].ReadPointers(binaryReader, blamPointers);
            invalidName_6[113].ReadPointers(binaryReader, blamPointers);
            invalidName_6[114].ReadPointers(binaryReader, blamPointers);
            invalidName_6[115].ReadPointers(binaryReader, blamPointers);
            invalidName_6[116].ReadPointers(binaryReader, blamPointers);
            invalidName_6[117].ReadPointers(binaryReader, blamPointers);
            invalidName_6[118].ReadPointers(binaryReader, blamPointers);
            invalidName_6[119].ReadPointers(binaryReader, blamPointers);
            invalidName_6[120].ReadPointers(binaryReader, blamPointers);
            invalidName_6[121].ReadPointers(binaryReader, blamPointers);
            invalidName_6[122].ReadPointers(binaryReader, blamPointers);
            invalidName_6[123].ReadPointers(binaryReader, blamPointers);
            invalidName_6[124].ReadPointers(binaryReader, blamPointers);
            invalidName_6[125].ReadPointers(binaryReader, blamPointers);
            invalidName_6[126].ReadPointers(binaryReader, blamPointers);
            invalidName_6[127].ReadPointers(binaryReader, blamPointers);
            invalidName_6[128].ReadPointers(binaryReader, blamPointers);
            invalidName_6[129].ReadPointers(binaryReader, blamPointers);
            invalidName_6[130].ReadPointers(binaryReader, blamPointers);
            invalidName_6[131].ReadPointers(binaryReader, blamPointers);
            invalidName_6[132].ReadPointers(binaryReader, blamPointers);
            invalidName_6[133].ReadPointers(binaryReader, blamPointers);
            invalidName_6[134].ReadPointers(binaryReader, blamPointers);
            invalidName_6[135].ReadPointers(binaryReader, blamPointers);
            invalidName_6[136].ReadPointers(binaryReader, blamPointers);
            invalidName_6[137].ReadPointers(binaryReader, blamPointers);
            invalidName_6[138].ReadPointers(binaryReader, blamPointers);
            invalidName_6[139].ReadPointers(binaryReader, blamPointers);
            invalidName_6[140].ReadPointers(binaryReader, blamPointers);
            invalidName_6[141].ReadPointers(binaryReader, blamPointers);
            invalidName_6[142].ReadPointers(binaryReader, blamPointers);
            invalidName_6[143].ReadPointers(binaryReader, blamPointers);
            invalidName_6[144].ReadPointers(binaryReader, blamPointers);
            invalidName_6[145].ReadPointers(binaryReader, blamPointers);
            invalidName_6[146].ReadPointers(binaryReader, blamPointers);
            invalidName_6[147].ReadPointers(binaryReader, blamPointers);
            invalidName_6[148].ReadPointers(binaryReader, blamPointers);
            invalidName_6[149].ReadPointers(binaryReader, blamPointers);
            invalidName_6[150].ReadPointers(binaryReader, blamPointers);
            invalidName_6[151].ReadPointers(binaryReader, blamPointers);
            invalidName_6[152].ReadPointers(binaryReader, blamPointers);
            invalidName_6[153].ReadPointers(binaryReader, blamPointers);
            invalidName_6[154].ReadPointers(binaryReader, blamPointers);
            invalidName_6[155].ReadPointers(binaryReader, blamPointers);
            invalidName_6[156].ReadPointers(binaryReader, blamPointers);
            invalidName_6[157].ReadPointers(binaryReader, blamPointers);
            invalidName_6[158].ReadPointers(binaryReader, blamPointers);
            invalidName_6[159].ReadPointers(binaryReader, blamPointers);
            invalidName_6[160].ReadPointers(binaryReader, blamPointers);
            invalidName_6[161].ReadPointers(binaryReader, blamPointers);
            invalidName_6[162].ReadPointers(binaryReader, blamPointers);
            invalidName_6[163].ReadPointers(binaryReader, blamPointers);
            invalidName_6[164].ReadPointers(binaryReader, blamPointers);
            invalidName_6[165].ReadPointers(binaryReader, blamPointers);
            invalidName_6[166].ReadPointers(binaryReader, blamPointers);
            invalidName_6[167].ReadPointers(binaryReader, blamPointers);
            invalidName_6[168].ReadPointers(binaryReader, blamPointers);
            invalidName_6[169].ReadPointers(binaryReader, blamPointers);
            invalidName_6[170].ReadPointers(binaryReader, blamPointers);
            invalidName_6[171].ReadPointers(binaryReader, blamPointers);
            invalidName_6[172].ReadPointers(binaryReader, blamPointers);
            invalidName_6[173].ReadPointers(binaryReader, blamPointers);
            invalidName_6[174].ReadPointers(binaryReader, blamPointers);
            invalidName_6[175].ReadPointers(binaryReader, blamPointers);
            invalidName_6[176].ReadPointers(binaryReader, blamPointers);
            invalidName_6[177].ReadPointers(binaryReader, blamPointers);
            invalidName_6[178].ReadPointers(binaryReader, blamPointers);
            invalidName_6[179].ReadPointers(binaryReader, blamPointers);
            invalidName_6[180].ReadPointers(binaryReader, blamPointers);
            invalidName_6[181].ReadPointers(binaryReader, blamPointers);
            invalidName_6[182].ReadPointers(binaryReader, blamPointers);
            invalidName_6[183].ReadPointers(binaryReader, blamPointers);
            invalidName_6[184].ReadPointers(binaryReader, blamPointers);
            invalidName_6[185].ReadPointers(binaryReader, blamPointers);
            invalidName_6[186].ReadPointers(binaryReader, blamPointers);
            invalidName_6[187].ReadPointers(binaryReader, blamPointers);
            invalidName_6[188].ReadPointers(binaryReader, blamPointers);
            invalidName_6[189].ReadPointers(binaryReader, blamPointers);
            invalidName_6[190].ReadPointers(binaryReader, blamPointers);
            invalidName_6[191].ReadPointers(binaryReader, blamPointers);
            invalidName_6[192].ReadPointers(binaryReader, blamPointers);
            invalidName_6[193].ReadPointers(binaryReader, blamPointers);
            invalidName_6[194].ReadPointers(binaryReader, blamPointers);
            invalidName_6[195].ReadPointers(binaryReader, blamPointers);
            invalidName_6[196].ReadPointers(binaryReader, blamPointers);
            invalidName_6[197].ReadPointers(binaryReader, blamPointers);
            invalidName_6[198].ReadPointers(binaryReader, blamPointers);
            invalidName_6[199].ReadPointers(binaryReader, blamPointers);
            invalidName_6[200].ReadPointers(binaryReader, blamPointers);
            invalidName_6[201].ReadPointers(binaryReader, blamPointers);
            invalidName_6[202].ReadPointers(binaryReader, blamPointers);
            invalidName_6[203].ReadPointers(binaryReader, blamPointers);
            invalidName_6[204].ReadPointers(binaryReader, blamPointers);
            invalidName_6[205].ReadPointers(binaryReader, blamPointers);
            invalidName_6[206].ReadPointers(binaryReader, blamPointers);
            invalidName_6[207].ReadPointers(binaryReader, blamPointers);
            invalidName_6[208].ReadPointers(binaryReader, blamPointers);
            invalidName_6[209].ReadPointers(binaryReader, blamPointers);
            invalidName_6[210].ReadPointers(binaryReader, blamPointers);
            invalidName_6[211].ReadPointers(binaryReader, blamPointers);
            invalidName_6[212].ReadPointers(binaryReader, blamPointers);
            invalidName_6[213].ReadPointers(binaryReader, blamPointers);
            invalidName_6[214].ReadPointers(binaryReader, blamPointers);
            invalidName_6[215].ReadPointers(binaryReader, blamPointers);
            invalidName_6[216].ReadPointers(binaryReader, blamPointers);
            invalidName_6[217].ReadPointers(binaryReader, blamPointers);
            invalidName_6[218].ReadPointers(binaryReader, blamPointers);
            invalidName_6[219].ReadPointers(binaryReader, blamPointers);
            invalidName_6[220].ReadPointers(binaryReader, blamPointers);
            invalidName_6[221].ReadPointers(binaryReader, blamPointers);
            invalidName_6[222].ReadPointers(binaryReader, blamPointers);
            invalidName_6[223].ReadPointers(binaryReader, blamPointers);
            invalidName_6[224].ReadPointers(binaryReader, blamPointers);
            invalidName_6[225].ReadPointers(binaryReader, blamPointers);
            invalidName_6[226].ReadPointers(binaryReader, blamPointers);
            invalidName_6[227].ReadPointers(binaryReader, blamPointers);
            invalidName_6[228].ReadPointers(binaryReader, blamPointers);
            invalidName_6[229].ReadPointers(binaryReader, blamPointers);
            invalidName_6[230].ReadPointers(binaryReader, blamPointers);
            invalidName_6[231].ReadPointers(binaryReader, blamPointers);
            invalidName_6[232].ReadPointers(binaryReader, blamPointers);
            invalidName_6[233].ReadPointers(binaryReader, blamPointers);
            invalidName_6[234].ReadPointers(binaryReader, blamPointers);
            invalidName_6[235].ReadPointers(binaryReader, blamPointers);
            invalidName_6[236].ReadPointers(binaryReader, blamPointers);
            invalidName_6[237].ReadPointers(binaryReader, blamPointers);
            invalidName_6[238].ReadPointers(binaryReader, blamPointers);
            invalidName_6[239].ReadPointers(binaryReader, blamPointers);
            invalidName_6[240].ReadPointers(binaryReader, blamPointers);
            invalidName_6[241].ReadPointers(binaryReader, blamPointers);
            invalidName_6[242].ReadPointers(binaryReader, blamPointers);
            invalidName_6[243].ReadPointers(binaryReader, blamPointers);
            invalidName_6[244].ReadPointers(binaryReader, blamPointers);
            invalidName_6[245].ReadPointers(binaryReader, blamPointers);
            invalidName_6[246].ReadPointers(binaryReader, blamPointers);
            invalidName_6[247].ReadPointers(binaryReader, blamPointers);
            invalidName_6[248].ReadPointers(binaryReader, blamPointers);
            invalidName_6[249].ReadPointers(binaryReader, blamPointers);
            invalidName_6[250].ReadPointers(binaryReader, blamPointers);
            invalidName_6[251].ReadPointers(binaryReader, blamPointers);
            invalidName_6[252].ReadPointers(binaryReader, blamPointers);
            invalidName_6[253].ReadPointers(binaryReader, blamPointers);
            invalidName_6[254].ReadPointers(binaryReader, blamPointers);
            invalidName_6[255].ReadPointers(binaryReader, blamPointers);
            invalidName_7[0].ReadPointers(binaryReader, blamPointers);
            invalidName_7[1].ReadPointers(binaryReader, blamPointers);
            invalidName_7[2].ReadPointers(binaryReader, blamPointers);
            invalidName_7[3].ReadPointers(binaryReader, blamPointers);
            invalidName_7[4].ReadPointers(binaryReader, blamPointers);
            invalidName_7[5].ReadPointers(binaryReader, blamPointers);
            invalidName_7[6].ReadPointers(binaryReader, blamPointers);
            invalidName_7[7].ReadPointers(binaryReader, blamPointers);
            invalidName_7[8].ReadPointers(binaryReader, blamPointers);
            invalidName_7[9].ReadPointers(binaryReader, blamPointers);
            invalidName_7[10].ReadPointers(binaryReader, blamPointers);
            invalidName_7[11].ReadPointers(binaryReader, blamPointers);
            invalidName_7[12].ReadPointers(binaryReader, blamPointers);
            invalidName_7[13].ReadPointers(binaryReader, blamPointers);
            invalidName_7[14].ReadPointers(binaryReader, blamPointers);
            invalidName_7[15].ReadPointers(binaryReader, blamPointers);
            invalidName_8[0].ReadPointers(binaryReader, blamPointers);
            invalidName_8[1].ReadPointers(binaryReader, blamPointers);
            invalidName_8[2].ReadPointers(binaryReader, blamPointers);
            invalidName_8[3].ReadPointers(binaryReader, blamPointers);
            invalidName_8[4].ReadPointers(binaryReader, blamPointers);
            invalidName_8[5].ReadPointers(binaryReader, blamPointers);
            invalidName_8[6].ReadPointers(binaryReader, blamPointers);
            invalidName_8[7].ReadPointers(binaryReader, blamPointers);
            invalidName_8[8].ReadPointers(binaryReader, blamPointers);
            invalidName_8[9].ReadPointers(binaryReader, blamPointers);
            invalidName_8[10].ReadPointers(binaryReader, blamPointers);
            invalidName_8[11].ReadPointers(binaryReader, blamPointers);
            invalidName_8[12].ReadPointers(binaryReader, blamPointers);
            invalidName_8[13].ReadPointers(binaryReader, blamPointers);
            invalidName_8[14].ReadPointers(binaryReader, blamPointers);
            invalidName_8[15].ReadPointers(binaryReader, blamPointers);
            invalidName_8[16].ReadPointers(binaryReader, blamPointers);
            invalidName_8[17].ReadPointers(binaryReader, blamPointers);
            invalidName_8[18].ReadPointers(binaryReader, blamPointers);
            invalidName_8[19].ReadPointers(binaryReader, blamPointers);
            invalidName_8[20].ReadPointers(binaryReader, blamPointers);
            invalidName_8[21].ReadPointers(binaryReader, blamPointers);
            invalidName_8[22].ReadPointers(binaryReader, blamPointers);
            invalidName_8[23].ReadPointers(binaryReader, blamPointers);
            invalidName_8[24].ReadPointers(binaryReader, blamPointers);
            invalidName_8[25].ReadPointers(binaryReader, blamPointers);
            invalidName_8[26].ReadPointers(binaryReader, blamPointers);
            invalidName_8[27].ReadPointers(binaryReader, blamPointers);
            invalidName_8[28].ReadPointers(binaryReader, blamPointers);
            invalidName_8[29].ReadPointers(binaryReader, blamPointers);
            invalidName_8[30].ReadPointers(binaryReader, blamPointers);
            invalidName_8[31].ReadPointers(binaryReader, blamPointers);
            invalidName_8[32].ReadPointers(binaryReader, blamPointers);
            invalidName_8[33].ReadPointers(binaryReader, blamPointers);
            invalidName_8[34].ReadPointers(binaryReader, blamPointers);
            invalidName_8[35].ReadPointers(binaryReader, blamPointers);
            invalidName_8[36].ReadPointers(binaryReader, blamPointers);
            invalidName_8[37].ReadPointers(binaryReader, blamPointers);
            invalidName_8[38].ReadPointers(binaryReader, blamPointers);
            invalidName_8[39].ReadPointers(binaryReader, blamPointers);
            invalidName_8[40].ReadPointers(binaryReader, blamPointers);
            invalidName_8[41].ReadPointers(binaryReader, blamPointers);
            invalidName_8[42].ReadPointers(binaryReader, blamPointers);
            invalidName_8[43].ReadPointers(binaryReader, blamPointers);
            invalidName_9[0].ReadPointers(binaryReader, blamPointers);
            invalidName_9[1].ReadPointers(binaryReader, blamPointers);
            invalidName_9[2].ReadPointers(binaryReader, blamPointers);
            invalidName_9[3].ReadPointers(binaryReader, blamPointers);
            invalidName_9[4].ReadPointers(binaryReader, blamPointers);
            invalidName_9[5].ReadPointers(binaryReader, blamPointers);
            invalidName_9[6].ReadPointers(binaryReader, blamPointers);
            invalidName_9[7].ReadPointers(binaryReader, blamPointers);
            invalidName_9[8].ReadPointers(binaryReader, blamPointers);
            invalidName_9[9].ReadPointers(binaryReader, blamPointers);
            invalidName_9[10].ReadPointers(binaryReader, blamPointers);
            invalidName_9[11].ReadPointers(binaryReader, blamPointers);
            invalidName_9[12].ReadPointers(binaryReader, blamPointers);
            invalidName_9[13].ReadPointers(binaryReader, blamPointers);
            invalidName_9[14].ReadPointers(binaryReader, blamPointers);
            invalidName_9[15].ReadPointers(binaryReader, blamPointers);
            invalidName_9[16].ReadPointers(binaryReader, blamPointers);
            invalidName_9[17].ReadPointers(binaryReader, blamPointers);
            invalidName_9[18].ReadPointers(binaryReader, blamPointers);
            invalidName_9[19].ReadPointers(binaryReader, blamPointers);
            invalidName_9[20].ReadPointers(binaryReader, blamPointers);
            invalidName_9[21].ReadPointers(binaryReader, blamPointers);
            invalidName_9[22].ReadPointers(binaryReader, blamPointers);
            invalidName_9[23].ReadPointers(binaryReader, blamPointers);
            invalidName_9[24].ReadPointers(binaryReader, blamPointers);
            invalidName_9[25].ReadPointers(binaryReader, blamPointers);
            invalidName_9[26].ReadPointers(binaryReader, blamPointers);
            invalidName_9[27].ReadPointers(binaryReader, blamPointers);
            invalidName_9[28].ReadPointers(binaryReader, blamPointers);
            invalidName_9[29].ReadPointers(binaryReader, blamPointers);
            invalidName_9[30].ReadPointers(binaryReader, blamPointers);
            invalidName_9[31].ReadPointers(binaryReader, blamPointers);
            invalidName_10[0].ReadPointers(binaryReader, blamPointers);
            invalidName_10[1].ReadPointers(binaryReader, blamPointers);
            invalidName_10[2].ReadPointers(binaryReader, blamPointers);
            invalidName_10[3].ReadPointers(binaryReader, blamPointers);
            invalidName_10[4].ReadPointers(binaryReader, blamPointers);
            invalidName_10[5].ReadPointers(binaryReader, blamPointers);
            invalidName_10[6].ReadPointers(binaryReader, blamPointers);
            invalidName_10[7].ReadPointers(binaryReader, blamPointers);
            invalidName_10[8].ReadPointers(binaryReader, blamPointers);
            invalidName_10[9].ReadPointers(binaryReader, blamPointers);
            invalidName_10[10].ReadPointers(binaryReader, blamPointers);
            invalidName_10[11].ReadPointers(binaryReader, blamPointers);
            invalidName_10[12].ReadPointers(binaryReader, blamPointers);
            invalidName_10[13].ReadPointers(binaryReader, blamPointers);
            invalidName_10[14].ReadPointers(binaryReader, blamPointers);
            invalidName_10[15].ReadPointers(binaryReader, blamPointers);
            invalidName_11[0].ReadPointers(binaryReader, blamPointers);
            invalidName_11[1].ReadPointers(binaryReader, blamPointers);
            invalidName_11[2].ReadPointers(binaryReader, blamPointers);
            invalidName_11[3].ReadPointers(binaryReader, blamPointers);
            invalidName_12[0].ReadPointers(binaryReader, blamPointers);
            invalidName_12[1].ReadPointers(binaryReader, blamPointers);
            invalidName_12[2].ReadPointers(binaryReader, blamPointers);
            invalidName_12[3].ReadPointers(binaryReader, blamPointers);
            invalidName_13[0].ReadPointers(binaryReader, blamPointers);
            invalidName_13[1].ReadPointers(binaryReader, blamPointers);
            invalidName_13[2].ReadPointers(binaryReader, blamPointers);
            invalidName_13[3].ReadPointers(binaryReader, blamPointers);
            invalidName_13[4].ReadPointers(binaryReader, blamPointers);
            invalidName_13[5].ReadPointers(binaryReader, blamPointers);
            invalidName_13[6].ReadPointers(binaryReader, blamPointers);
            invalidName_13[7].ReadPointers(binaryReader, blamPointers);
            invalidName_13[8].ReadPointers(binaryReader, blamPointers);
            invalidName_13[9].ReadPointers(binaryReader, blamPointers);
            invalidName_13[10].ReadPointers(binaryReader, blamPointers);
            invalidName_13[11].ReadPointers(binaryReader, blamPointers);
            invalidName_13[12].ReadPointers(binaryReader, blamPointers);
            invalidName_13[13].ReadPointers(binaryReader, blamPointers);
            invalidName_13[14].ReadPointers(binaryReader, blamPointers);
            invalidName_13[15].ReadPointers(binaryReader, blamPointers);
            invalidName_13[16].ReadPointers(binaryReader, blamPointers);
            invalidName_13[17].ReadPointers(binaryReader, blamPointers);
            invalidName_13[18].ReadPointers(binaryReader, blamPointers);
            invalidName_13[19].ReadPointers(binaryReader, blamPointers);
            invalidName_13[20].ReadPointers(binaryReader, blamPointers);
            invalidName_13[21].ReadPointers(binaryReader, blamPointers);
            invalidName_13[22].ReadPointers(binaryReader, blamPointers);
            invalidName_13[23].ReadPointers(binaryReader, blamPointers);
            invalidName_13[24].ReadPointers(binaryReader, blamPointers);
            invalidName_13[25].ReadPointers(binaryReader, blamPointers);
            invalidName_13[26].ReadPointers(binaryReader, blamPointers);
            invalidName_13[27].ReadPointers(binaryReader, blamPointers);
            invalidName_13[28].ReadPointers(binaryReader, blamPointers);
            invalidName_13[29].ReadPointers(binaryReader, blamPointers);
            invalidName_13[30].ReadPointers(binaryReader, blamPointers);
            invalidName_13[31].ReadPointers(binaryReader, blamPointers);
            invalidName_13[32].ReadPointers(binaryReader, blamPointers);
            invalidName_13[33].ReadPointers(binaryReader, blamPointers);
            invalidName_13[34].ReadPointers(binaryReader, blamPointers);
            invalidName_13[35].ReadPointers(binaryReader, blamPointers);
            invalidName_13[36].ReadPointers(binaryReader, blamPointers);
            invalidName_13[37].ReadPointers(binaryReader, blamPointers);
            invalidName_13[38].ReadPointers(binaryReader, blamPointers);
            invalidName_13[39].ReadPointers(binaryReader, blamPointers);
            invalidName_14[0].ReadPointers(binaryReader, blamPointers);
            invalidName_14[1].ReadPointers(binaryReader, blamPointers);
            invalidName_14[2].ReadPointers(binaryReader, blamPointers);
            invalidName_14[3].ReadPointers(binaryReader, blamPointers);
            invalidName_14[4].ReadPointers(binaryReader, blamPointers);
            invalidName_14[5].ReadPointers(binaryReader, blamPointers);
            invalidName_14[6].ReadPointers(binaryReader, blamPointers);
            invalidName_14[7].ReadPointers(binaryReader, blamPointers);
            invalidName_14[8].ReadPointers(binaryReader, blamPointers);
            invalidName_14[9].ReadPointers(binaryReader, blamPointers);
            invalidName_14[10].ReadPointers(binaryReader, blamPointers);
            invalidName_14[11].ReadPointers(binaryReader, blamPointers);
            invalidName_14[12].ReadPointers(binaryReader, blamPointers);
            invalidName_14[13].ReadPointers(binaryReader, blamPointers);
            invalidName_14[14].ReadPointers(binaryReader, blamPointers);
            invalidName_14[15].ReadPointers(binaryReader, blamPointers);
            invalidName_14[16].ReadPointers(binaryReader, blamPointers);
            invalidName_14[17].ReadPointers(binaryReader, blamPointers);
            invalidName_14[18].ReadPointers(binaryReader, blamPointers);
            invalidName_14[19].ReadPointers(binaryReader, blamPointers);
            invalidName_14[20].ReadPointers(binaryReader, blamPointers);
            invalidName_14[21].ReadPointers(binaryReader, blamPointers);
            invalidName_14[22].ReadPointers(binaryReader, blamPointers);
            invalidName_14[23].ReadPointers(binaryReader, blamPointers);
            invalidName_14[24].ReadPointers(binaryReader, blamPointers);
            invalidName_14[25].ReadPointers(binaryReader, blamPointers);
            invalidName_14[26].ReadPointers(binaryReader, blamPointers);
            invalidName_14[27].ReadPointers(binaryReader, blamPointers);
            invalidName_14[28].ReadPointers(binaryReader, blamPointers);
            invalidName_14[29].ReadPointers(binaryReader, blamPointers);
            invalidName_14[30].ReadPointers(binaryReader, blamPointers);
            invalidName_14[31].ReadPointers(binaryReader, blamPointers);
            invalidName_14[32].ReadPointers(binaryReader, blamPointers);
            invalidName_14[33].ReadPointers(binaryReader, blamPointers);
            invalidName_14[34].ReadPointers(binaryReader, blamPointers);
            invalidName_14[35].ReadPointers(binaryReader, blamPointers);
            invalidName_14[36].ReadPointers(binaryReader, blamPointers);
            invalidName_14[37].ReadPointers(binaryReader, blamPointers);
            invalidName_14[38].ReadPointers(binaryReader, blamPointers);
            invalidName_14[39].ReadPointers(binaryReader, blamPointers);
            invalidName_14[40].ReadPointers(binaryReader, blamPointers);
            invalidName_14[41].ReadPointers(binaryReader, blamPointers);
            invalidName_14[42].ReadPointers(binaryReader, blamPointers);
            invalidName_14[43].ReadPointers(binaryReader, blamPointers);
            invalidName_14[44].ReadPointers(binaryReader, blamPointers);
            invalidName_14[45].ReadPointers(binaryReader, blamPointers);
            invalidName_14[46].ReadPointers(binaryReader, blamPointers);
            invalidName_14[47].ReadPointers(binaryReader, blamPointers);
            invalidName_14[48].ReadPointers(binaryReader, blamPointers);
            invalidName_14[49].ReadPointers(binaryReader, blamPointers);
            invalidName_14[50].ReadPointers(binaryReader, blamPointers);
            invalidName_14[51].ReadPointers(binaryReader, blamPointers);
            invalidName_14[52].ReadPointers(binaryReader, blamPointers);
            invalidName_14[53].ReadPointers(binaryReader, blamPointers);
            invalidName_14[54].ReadPointers(binaryReader, blamPointers);
            invalidName_14[55].ReadPointers(binaryReader, blamPointers);
            invalidName_14[56].ReadPointers(binaryReader, blamPointers);
            invalidName_14[57].ReadPointers(binaryReader, blamPointers);
            invalidName_14[58].ReadPointers(binaryReader, blamPointers);
            invalidName_14[59].ReadPointers(binaryReader, blamPointers);
            invalidName_14[60].ReadPointers(binaryReader, blamPointers);
            invalidName_14[61].ReadPointers(binaryReader, blamPointers);
            invalidName_14[62].ReadPointers(binaryReader, blamPointers);
            invalidName_14[63].ReadPointers(binaryReader, blamPointers);
            invalidName_14[64].ReadPointers(binaryReader, blamPointers);
            invalidName_14[65].ReadPointers(binaryReader, blamPointers);
            invalidName_14[66].ReadPointers(binaryReader, blamPointers);
            invalidName_14[67].ReadPointers(binaryReader, blamPointers);
            invalidName_14[68].ReadPointers(binaryReader, blamPointers);
            invalidName_14[69].ReadPointers(binaryReader, blamPointers);
            invalidName_14[70].ReadPointers(binaryReader, blamPointers);
            invalidName_14[71].ReadPointers(binaryReader, blamPointers);
            invalidName_14[72].ReadPointers(binaryReader, blamPointers);
            invalidName_14[73].ReadPointers(binaryReader, blamPointers);
            invalidName_14[74].ReadPointers(binaryReader, blamPointers);
            invalidName_14[75].ReadPointers(binaryReader, blamPointers);
            invalidName_14[76].ReadPointers(binaryReader, blamPointers);
            invalidName_14[77].ReadPointers(binaryReader, blamPointers);
            invalidName_14[78].ReadPointers(binaryReader, blamPointers);
            invalidName_14[79].ReadPointers(binaryReader, blamPointers);
            invalidName_14[80].ReadPointers(binaryReader, blamPointers);
            invalidName_14[81].ReadPointers(binaryReader, blamPointers);
            invalidName_14[82].ReadPointers(binaryReader, blamPointers);
            invalidName_14[83].ReadPointers(binaryReader, blamPointers);
            invalidName_14[84].ReadPointers(binaryReader, blamPointers);
            invalidName_14[85].ReadPointers(binaryReader, blamPointers);
            invalidName_14[86].ReadPointers(binaryReader, blamPointers);
            invalidName_14[87].ReadPointers(binaryReader, blamPointers);
            invalidName_14[88].ReadPointers(binaryReader, blamPointers);
            invalidName_14[89].ReadPointers(binaryReader, blamPointers);
            invalidName_14[90].ReadPointers(binaryReader, blamPointers);
            invalidName_14[91].ReadPointers(binaryReader, blamPointers);
            invalidName_14[92].ReadPointers(binaryReader, blamPointers);
            invalidName_14[93].ReadPointers(binaryReader, blamPointers);
            invalidName_14[94].ReadPointers(binaryReader, blamPointers);
            invalidName_14[95].ReadPointers(binaryReader, blamPointers);
            newGlobals.ReadPointers(binaryReader, blamPointers);
        }
        public override int Write(BinaryWriter binaryWriter, int nextAddress)
        {
            base.Write(binaryWriter, nextAddress);
using(binaryWriter.BaseStream.Pin())
            {
                binaryWriter.Write((Int16)anchor);
                binaryWriter.Write(invalidName_, 0, 2);
                binaryWriter.Write(invalidName_0, 0, 32);
                binaryWriter.Write(anchorOffset);
                binaryWriter.Write(widthScale);
                binaryWriter.Write(heightScale);
                binaryWriter.Write((Int16)scalingFlags);
                binaryWriter.Write(invalidName_1, 0, 2);
                binaryWriter.Write(invalidName_2, 0, 20);
                binaryWriter.Write(obsolete1);
                binaryWriter.Write(obsolete2);
                binaryWriter.Write(upTime);
                binaryWriter.Write(fadeTime);
                binaryWriter.Write(iconColor);
                binaryWriter.Write(textColor);
                binaryWriter.Write(textSpacing);
                binaryWriter.Write(itemMessageText);
                binaryWriter.Write(iconBitmap);
                binaryWriter.Write(alternateIconText);
                nextAddress = Guerilla.WriteBlockArray<HudButtonIconBlock>(binaryWriter, buttonIcons, nextAddress);
                binaryWriter.Write(defaultColor);
                binaryWriter.Write(flashingColor);
                binaryWriter.Write(flashPeriod);
                binaryWriter.Write(flashDelay);
                binaryWriter.Write(numberOfFlashes);
                binaryWriter.Write((Int16)flashFlags);
                binaryWriter.Write(flashLength);
                binaryWriter.Write(disabledColor);
                binaryWriter.Write(invalidName_3, 0, 4);
                binaryWriter.Write(hudMessages);
                binaryWriter.Write(defaultColor0);
                binaryWriter.Write(flashingColor0);
                binaryWriter.Write(flashPeriod0);
                binaryWriter.Write(flashDelay0);
                binaryWriter.Write(numberOfFlashes0);
                binaryWriter.Write((Int16)flashFlags0);
                binaryWriter.Write(flashLength0);
                binaryWriter.Write(disabledColor0);
                binaryWriter.Write(uptimeTicks);
                binaryWriter.Write(fadeTicks);
                binaryWriter.Write(topOffset);
                binaryWriter.Write(bottomOffset);
                binaryWriter.Write(leftOffset);
                binaryWriter.Write(rightOffset);
                binaryWriter.Write(invalidName_4, 0, 32);
                binaryWriter.Write(arrowBitmap);
                nextAddress = Guerilla.WriteBlockArray<HudWaypointArrowBlock>(binaryWriter, waypointArrows, nextAddress);
                binaryWriter.Write(invalidName_5, 0, 80);
                binaryWriter.Write(hudScaleInMultiplayer);
                binaryWriter.Write(invalidName_6, 0, 256);
                binaryWriter.Write(invalidName_7, 0, 16);
                binaryWriter.Write(motionSensorRange);
                binaryWriter.Write(motionSensorVelocitySensitivity);
                binaryWriter.Write(motionSensorScaleDONTTOUCHEVER);
                binaryWriter.Write(defaultChapterTitleBounds);
                binaryWriter.Write(invalidName_8, 0, 44);
                binaryWriter.Write(topOffset0);
                binaryWriter.Write(bottomOffset0);
                binaryWriter.Write(leftOffset0);
                binaryWriter.Write(rightOffset0);
                binaryWriter.Write(invalidName_9, 0, 32);
                binaryWriter.Write(indicatorBitmap);
                binaryWriter.Write(sequenceIndex);
                binaryWriter.Write(multiplayerSequenceIndex);
                binaryWriter.Write(color);
                binaryWriter.Write(invalidName_10, 0, 16);
                binaryWriter.Write(defaultColor1);
                binaryWriter.Write(flashingColor1);
                binaryWriter.Write(flashPeriod1);
                binaryWriter.Write(flashDelay1);
                binaryWriter.Write(numberOfFlashes1);
                binaryWriter.Write((Int16)flashFlags1);
                binaryWriter.Write(flashLength1);
                binaryWriter.Write(disabledColor1);
                binaryWriter.Write(invalidName_11, 0, 4);
                binaryWriter.Write(defaultColor2);
                binaryWriter.Write(flashingColor2);
                binaryWriter.Write(flashPeriod2);
                binaryWriter.Write(flashDelay2);
                binaryWriter.Write(numberOfFlashes2);
                binaryWriter.Write((Int16)flashFlags2);
                binaryWriter.Write(flashLength2);
                binaryWriter.Write(disabledColor2);
                binaryWriter.Write(invalidName_12, 0, 4);
                binaryWriter.Write(invalidName_13, 0, 40);
                binaryWriter.Write(carnageReportBitmap);
                binaryWriter.Write(loadingBeginText);
                binaryWriter.Write(loadingEndText);
                binaryWriter.Write(checkpointBeginText);
                binaryWriter.Write(checkpointEndText);
                binaryWriter.Write(checkpointSound);
                binaryWriter.Write(invalidName_14, 0, 96);
                newGlobals.Write(binaryWriter);
                return nextAddress;
            }
        }
        internal enum Anchor : short
        {
            TopLeft = 0,
            TopRight = 1,
            BottomLeft = 2,
            BottomRight = 3,
            Center = 4,
            Crosshair = 5,
        };
        [FlagsAttribute]
        internal enum ScalingFlags : short
        {
            DontScaleOffset = 1,
            DontScaleSize = 2,
        };
        [FlagsAttribute]
        internal enum FlashFlags : short
        {
            ReverseDefaultFlashingColors = 1,
        };
        [FlagsAttribute]
        internal enum FlashFlags0 : short
        {
            ReverseDefaultFlashingColors = 1,
        };
        [FlagsAttribute]
        internal enum FlashFlags1 : short
        {
            ReverseDefaultFlashingColors = 1,
        };
        [FlagsAttribute]
        internal enum FlashFlags2 : short
        {
            ReverseDefaultFlashingColors = 1,
        };
    };
}
