//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moonfish.Guerilla.Tags
{
    using Moonfish.Tags;
    using Moonfish.Model;
    using System.IO;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class MoonfishXboxAnimationRawBlock : GuerillaBlock, IWriteQueueable
    {
        public Moonfish.Tags.TagIdent OwnerTag;
        public int BlockSize;
        public int BlockOffset;
        public int Unknown;
        public int Unknown1;
        public override int SerializedSize
        {
            get
            {
                return 20;
            }
        }
        public override int Alignment
        {
            get
            {
                return 4;
            }
        }
        public override System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> ReadFields(System.IO.BinaryReader binaryReader)
        {
            System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue = new System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer>(base.ReadFields(binaryReader));
            this.OwnerTag = binaryReader.ReadTagIdent();
            this.BlockSize = binaryReader.ReadInt32();
            this.BlockLength = binaryReader.ReadInt32();
            this.Unknown = binaryReader.ReadInt32();
            this.Unknown1 = binaryReader.ReadInt32();
            return pointerQueue;
        }
        public override void ReadInstances(System.IO.BinaryReader binaryReader, System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue)
        {
            base.ReadInstances(binaryReader, pointerQueue);
        }
        public override void QueueWrites(Moonfish.Guerilla.QueueableBinaryWriter queueableBinaryWriter)
        {
            base.QueueWrites(queueableBinaryWriter);
        }
        public override void Write_(Moonfish.Guerilla.QueueableBinaryWriter queueableBinaryWriter)
        {
            base.Write_(queueableBinaryWriter);
            queueableBinaryWriter.Write(this.OwnerTag);
            queueableBinaryWriter.Write(this.BlockSize);
            queueableBinaryWriter.Write(this.BlockLength);
            queueableBinaryWriter.Write(this.Unknown);
            queueableBinaryWriter.Write(this.Unknown1);
        }
    }
}
