// ReSharper disable All
using Moonfish.Model;
using Moonfish.Tags.BlamExtension;
using Moonfish.Tags;
using OpenTK;
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;

namespace Moonfish.Guerilla.Tags
{
    public partial class MultiplayerRuntimeBlock : MultiplayerRuntimeBlockBase
    {
        public MultiplayerRuntimeBlock() : base()
        {
        }
    };
    [LayoutAttribute(Size = 1384, Alignment = 4)]
    public class MultiplayerRuntimeBlockBase : GuerillaBlock
    {
        [TagReference("item")]
        internal Moonfish.Tags.TagReference flag;
        [TagReference("item")]
        internal Moonfish.Tags.TagReference ball;
        [TagReference("unit")]
        internal Moonfish.Tags.TagReference unit;
        [TagReference("shad")]
        internal Moonfish.Tags.TagReference flagShader;
        [TagReference("shad")]
        internal Moonfish.Tags.TagReference hillShader;
        [TagReference("item")]
        internal Moonfish.Tags.TagReference head;
        [TagReference("item")]
        internal Moonfish.Tags.TagReference juggernautPowerup;
        [TagReference("item")]
        internal Moonfish.Tags.TagReference daBomb;
        [TagReference("null")]
        internal Moonfish.Tags.TagReference invalidName_;
        [TagReference("null")]
        internal Moonfish.Tags.TagReference invalidName_0;
        [TagReference("null")]
        internal Moonfish.Tags.TagReference invalidName_1;
        [TagReference("null")]
        internal Moonfish.Tags.TagReference invalidName_2;
        [TagReference("null")]
        internal Moonfish.Tags.TagReference invalidName_3;
        internal WeaponsBlock[] weapons;
        internal VehiclesBlock[] vehicles;
        internal GrenadeAndPowerupStructBlock arr;
        [TagReference("unic")]
        internal Moonfish.Tags.TagReference inGameText;
        internal SoundsBlock[] sounds;
        internal GameEngineGeneralEventBlock[] generalEvents;
        internal GameEngineFlavorEventBlock[] flavorEvents;
        internal GameEngineSlayerEventBlock[] slayerEvents;
        internal GameEngineCtfEventBlock[] ctfEvents;
        internal GameEngineOddballEventBlock[] oddballEvents;
        internal GNullBlock[] gNullBlock;
        internal GameEngineKingEventBlock[] kingEvents;
        internal GNullBlock[] gNullBlock0;
        internal GameEngineJuggernautEventBlock[] juggernautEvents;
        internal GameEngineTerritoriesEventBlock[] territoriesEvents;
        internal GameEngineAssaultEventBlock[] invasionEvents;
        internal GNullBlock[] gNullBlock1;
        internal GNullBlock[] gNullBlock2;
        internal GNullBlock[] gNullBlock3;
        internal GNullBlock[] gNullBlock4;
        [TagReference("itmc")]
        internal Moonfish.Tags.TagReference defaultItemCollection1;
        [TagReference("itmc")]
        internal Moonfish.Tags.TagReference defaultItemCollection2;
        internal int defaultFragGrenadeCount;
        internal int defaultPlasmaGrenadeCount;
        internal byte[] invalidName_4;
        internal float dynamicZoneUpperHeight;
        internal float dynamicZoneLowerHeight;
        internal byte[] invalidName_5;
        internal float enemyInnerRadius;
        internal float enemyOuterRadius;
        internal float enemyWeight;
        internal byte[] invalidName_6;
        internal float friendInnerRadius;
        internal float friendOuterRadius;
        internal float friendWeight;
        internal byte[] invalidName_7;
        internal float enemyVehicleInnerRadius;
        internal float enemyVehicleOuterRadius;
        internal float enemyVehicleWeight;
        internal byte[] invalidName_8;
        internal float friendlyVehicleInnerRadius;
        internal float friendlyVehicleOuterRadius;
        internal float friendlyVehicleWeight;
        internal byte[] invalidName_9;
        internal float emptyVehicleInnerRadius;
        internal float emptyVehicleOuterRadius;
        internal float emptyVehicleWeight;
        internal byte[] invalidName_10;
        internal float oddballInclusionInnerRadius;
        internal float oddballInclusionOuterRadius;
        internal float oddballInclusionWeight;
        internal byte[] invalidName_11;
        internal float oddballExclusionInnerRadius;
        internal float oddballExclusionOuterRadius;
        internal float oddballExclusionWeight;
        internal byte[] invalidName_12;
        internal float hillInclusionInnerRadius;
        internal float hillInclusionOuterRadius;
        internal float hillInclusionWeight;
        internal byte[] invalidName_13;
        internal float hillExclusionInnerRadius;
        internal float hillExclusionOuterRadius;
        internal float hillExclusionWeight;
        internal byte[] invalidName_14;
        internal float lastRaceFlagInnerRadius;
        internal float lastRaceFlagOuterRadius;
        internal float lastRaceFlagWeight;
        internal byte[] invalidName_15;
        internal float deadAllyInnerRadius;
        internal float deadAllyOuterRadius;
        internal float deadAllyWeight;
        internal byte[] invalidName_16;
        internal float controlledTerritoryInnerRadius;
        internal float controlledTerritoryOuterRadius;
        internal float controlledTerritoryWeight;
        internal byte[] invalidName_17;
        internal byte[] invalidName_18;
        internal byte[] invalidName_19;
        internal MultiplayerConstantsBlock[] multiplayerConstants;
        internal GameEngineStatusResponseBlock[] stateResponses;
        [TagReference("nhdt")]
        internal Moonfish.Tags.TagReference scoreboardHudDefinition;
        [TagReference("shad")]
        internal Moonfish.Tags.TagReference scoreboardEmblemShader;
        [TagReference("bitm")]
        internal Moonfish.Tags.TagReference scoreboardEmblemBitmap;
        [TagReference("shad")]
        internal Moonfish.Tags.TagReference scoreboardDeadEmblemShader;
        [TagReference("bitm")]
        internal Moonfish.Tags.TagReference scoreboardDeadEmblemBitmap;
        public override int SerializedSize { get { return 1384; } }
        public override int Alignment { get { return 4; } }
        public MultiplayerRuntimeBlockBase() : base()
        {
        }
        public override Queue<BlamPointer> ReadFields(BinaryReader binaryReader)
        {
            var blamPointers = new Queue<BlamPointer>(base.ReadFields(binaryReader));
            flag = binaryReader.ReadTagReference();
            ball = binaryReader.ReadTagReference();
            unit = binaryReader.ReadTagReference();
            flagShader = binaryReader.ReadTagReference();
            hillShader = binaryReader.ReadTagReference();
            head = binaryReader.ReadTagReference();
            juggernautPowerup = binaryReader.ReadTagReference();
            daBomb = binaryReader.ReadTagReference();
            invalidName_ = binaryReader.ReadTagReference();
            invalidName_0 = binaryReader.ReadTagReference();
            invalidName_1 = binaryReader.ReadTagReference();
            invalidName_2 = binaryReader.ReadTagReference();
            invalidName_3 = binaryReader.ReadTagReference();
            blamPointers.Enqueue(ReadBlockArrayPointer<WeaponsBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<VehiclesBlock>(binaryReader));
            arr = new GrenadeAndPowerupStructBlock();
            blamPointers.Concat(arr.ReadFields(binaryReader));
            inGameText = binaryReader.ReadTagReference();
            blamPointers.Enqueue(ReadBlockArrayPointer<SoundsBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<GameEngineGeneralEventBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<GameEngineFlavorEventBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<GameEngineSlayerEventBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<GameEngineCtfEventBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<GameEngineOddballEventBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<GNullBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<GameEngineKingEventBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<GNullBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<GameEngineJuggernautEventBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<GameEngineTerritoriesEventBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<GameEngineAssaultEventBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<GNullBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<GNullBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<GNullBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<GNullBlock>(binaryReader));
            defaultItemCollection1 = binaryReader.ReadTagReference();
            defaultItemCollection2 = binaryReader.ReadTagReference();
            defaultFragGrenadeCount = binaryReader.ReadInt32();
            defaultPlasmaGrenadeCount = binaryReader.ReadInt32();
            invalidName_4 = binaryReader.ReadBytes(40);
            dynamicZoneUpperHeight = binaryReader.ReadSingle();
            dynamicZoneLowerHeight = binaryReader.ReadSingle();
            invalidName_5 = binaryReader.ReadBytes(40);
            enemyInnerRadius = binaryReader.ReadSingle();
            enemyOuterRadius = binaryReader.ReadSingle();
            enemyWeight = binaryReader.ReadSingle();
            invalidName_6 = binaryReader.ReadBytes(16);
            friendInnerRadius = binaryReader.ReadSingle();
            friendOuterRadius = binaryReader.ReadSingle();
            friendWeight = binaryReader.ReadSingle();
            invalidName_7 = binaryReader.ReadBytes(16);
            enemyVehicleInnerRadius = binaryReader.ReadSingle();
            enemyVehicleOuterRadius = binaryReader.ReadSingle();
            enemyVehicleWeight = binaryReader.ReadSingle();
            invalidName_8 = binaryReader.ReadBytes(16);
            friendlyVehicleInnerRadius = binaryReader.ReadSingle();
            friendlyVehicleOuterRadius = binaryReader.ReadSingle();
            friendlyVehicleWeight = binaryReader.ReadSingle();
            invalidName_9 = binaryReader.ReadBytes(16);
            emptyVehicleInnerRadius = binaryReader.ReadSingle();
            emptyVehicleOuterRadius = binaryReader.ReadSingle();
            emptyVehicleWeight = binaryReader.ReadSingle();
            invalidName_10 = binaryReader.ReadBytes(16);
            oddballInclusionInnerRadius = binaryReader.ReadSingle();
            oddballInclusionOuterRadius = binaryReader.ReadSingle();
            oddballInclusionWeight = binaryReader.ReadSingle();
            invalidName_11 = binaryReader.ReadBytes(16);
            oddballExclusionInnerRadius = binaryReader.ReadSingle();
            oddballExclusionOuterRadius = binaryReader.ReadSingle();
            oddballExclusionWeight = binaryReader.ReadSingle();
            invalidName_12 = binaryReader.ReadBytes(16);
            hillInclusionInnerRadius = binaryReader.ReadSingle();
            hillInclusionOuterRadius = binaryReader.ReadSingle();
            hillInclusionWeight = binaryReader.ReadSingle();
            invalidName_13 = binaryReader.ReadBytes(16);
            hillExclusionInnerRadius = binaryReader.ReadSingle();
            hillExclusionOuterRadius = binaryReader.ReadSingle();
            hillExclusionWeight = binaryReader.ReadSingle();
            invalidName_14 = binaryReader.ReadBytes(16);
            lastRaceFlagInnerRadius = binaryReader.ReadSingle();
            lastRaceFlagOuterRadius = binaryReader.ReadSingle();
            lastRaceFlagWeight = binaryReader.ReadSingle();
            invalidName_15 = binaryReader.ReadBytes(16);
            deadAllyInnerRadius = binaryReader.ReadSingle();
            deadAllyOuterRadius = binaryReader.ReadSingle();
            deadAllyWeight = binaryReader.ReadSingle();
            invalidName_16 = binaryReader.ReadBytes(16);
            controlledTerritoryInnerRadius = binaryReader.ReadSingle();
            controlledTerritoryOuterRadius = binaryReader.ReadSingle();
            controlledTerritoryWeight = binaryReader.ReadSingle();
            invalidName_17 = binaryReader.ReadBytes(16);
            invalidName_18 = binaryReader.ReadBytes(560);
            invalidName_19 = binaryReader.ReadBytes(48);
            blamPointers.Enqueue(ReadBlockArrayPointer<MultiplayerConstantsBlock>(binaryReader));
            blamPointers.Enqueue(ReadBlockArrayPointer<GameEngineStatusResponseBlock>(binaryReader));
            scoreboardHudDefinition = binaryReader.ReadTagReference();
            scoreboardEmblemShader = binaryReader.ReadTagReference();
            scoreboardEmblemBitmap = binaryReader.ReadTagReference();
            scoreboardDeadEmblemShader = binaryReader.ReadTagReference();
            scoreboardDeadEmblemBitmap = binaryReader.ReadTagReference();
            return blamPointers;
        }
        public override void ReadPointers(BinaryReader binaryReader, Queue<BlamPointer> blamPointers)
        {
            base.ReadPointers(binaryReader, blamPointers);
            weapons = ReadBlockArrayData<WeaponsBlock>(binaryReader, blamPointers.Dequeue());
            vehicles = ReadBlockArrayData<VehiclesBlock>(binaryReader, blamPointers.Dequeue());
            arr.ReadPointers(binaryReader, blamPointers);
            sounds = ReadBlockArrayData<SoundsBlock>(binaryReader, blamPointers.Dequeue());
            generalEvents = ReadBlockArrayData<GameEngineGeneralEventBlock>(binaryReader, blamPointers.Dequeue());
            flavorEvents = ReadBlockArrayData<GameEngineFlavorEventBlock>(binaryReader, blamPointers.Dequeue());
            slayerEvents = ReadBlockArrayData<GameEngineSlayerEventBlock>(binaryReader, blamPointers.Dequeue());
            ctfEvents = ReadBlockArrayData<GameEngineCtfEventBlock>(binaryReader, blamPointers.Dequeue());
            oddballEvents = ReadBlockArrayData<GameEngineOddballEventBlock>(binaryReader, blamPointers.Dequeue());
            gNullBlock = ReadBlockArrayData<GNullBlock>(binaryReader, blamPointers.Dequeue());
            kingEvents = ReadBlockArrayData<GameEngineKingEventBlock>(binaryReader, blamPointers.Dequeue());
            gNullBlock0 = ReadBlockArrayData<GNullBlock>(binaryReader, blamPointers.Dequeue());
            juggernautEvents = ReadBlockArrayData<GameEngineJuggernautEventBlock>(binaryReader, blamPointers.Dequeue());
            territoriesEvents = ReadBlockArrayData<GameEngineTerritoriesEventBlock>(binaryReader, blamPointers.Dequeue());
            invasionEvents = ReadBlockArrayData<GameEngineAssaultEventBlock>(binaryReader, blamPointers.Dequeue());
            gNullBlock1 = ReadBlockArrayData<GNullBlock>(binaryReader, blamPointers.Dequeue());
            gNullBlock2 = ReadBlockArrayData<GNullBlock>(binaryReader, blamPointers.Dequeue());
            gNullBlock3 = ReadBlockArrayData<GNullBlock>(binaryReader, blamPointers.Dequeue());
            gNullBlock4 = ReadBlockArrayData<GNullBlock>(binaryReader, blamPointers.Dequeue());
            invalidName_4[0].ReadPointers(binaryReader, blamPointers);
            invalidName_4[1].ReadPointers(binaryReader, blamPointers);
            invalidName_4[2].ReadPointers(binaryReader, blamPointers);
            invalidName_4[3].ReadPointers(binaryReader, blamPointers);
            invalidName_4[4].ReadPointers(binaryReader, blamPointers);
            invalidName_4[5].ReadPointers(binaryReader, blamPointers);
            invalidName_4[6].ReadPointers(binaryReader, blamPointers);
            invalidName_4[7].ReadPointers(binaryReader, blamPointers);
            invalidName_4[8].ReadPointers(binaryReader, blamPointers);
            invalidName_4[9].ReadPointers(binaryReader, blamPointers);
            invalidName_4[10].ReadPointers(binaryReader, blamPointers);
            invalidName_4[11].ReadPointers(binaryReader, blamPointers);
            invalidName_4[12].ReadPointers(binaryReader, blamPointers);
            invalidName_4[13].ReadPointers(binaryReader, blamPointers);
            invalidName_4[14].ReadPointers(binaryReader, blamPointers);
            invalidName_4[15].ReadPointers(binaryReader, blamPointers);
            invalidName_4[16].ReadPointers(binaryReader, blamPointers);
            invalidName_4[17].ReadPointers(binaryReader, blamPointers);
            invalidName_4[18].ReadPointers(binaryReader, blamPointers);
            invalidName_4[19].ReadPointers(binaryReader, blamPointers);
            invalidName_4[20].ReadPointers(binaryReader, blamPointers);
            invalidName_4[21].ReadPointers(binaryReader, blamPointers);
            invalidName_4[22].ReadPointers(binaryReader, blamPointers);
            invalidName_4[23].ReadPointers(binaryReader, blamPointers);
            invalidName_4[24].ReadPointers(binaryReader, blamPointers);
            invalidName_4[25].ReadPointers(binaryReader, blamPointers);
            invalidName_4[26].ReadPointers(binaryReader, blamPointers);
            invalidName_4[27].ReadPointers(binaryReader, blamPointers);
            invalidName_4[28].ReadPointers(binaryReader, blamPointers);
            invalidName_4[29].ReadPointers(binaryReader, blamPointers);
            invalidName_4[30].ReadPointers(binaryReader, blamPointers);
            invalidName_4[31].ReadPointers(binaryReader, blamPointers);
            invalidName_4[32].ReadPointers(binaryReader, blamPointers);
            invalidName_4[33].ReadPointers(binaryReader, blamPointers);
            invalidName_4[34].ReadPointers(binaryReader, blamPointers);
            invalidName_4[35].ReadPointers(binaryReader, blamPointers);
            invalidName_4[36].ReadPointers(binaryReader, blamPointers);
            invalidName_4[37].ReadPointers(binaryReader, blamPointers);
            invalidName_4[38].ReadPointers(binaryReader, blamPointers);
            invalidName_4[39].ReadPointers(binaryReader, blamPointers);
            invalidName_5[0].ReadPointers(binaryReader, blamPointers);
            invalidName_5[1].ReadPointers(binaryReader, blamPointers);
            invalidName_5[2].ReadPointers(binaryReader, blamPointers);
            invalidName_5[3].ReadPointers(binaryReader, blamPointers);
            invalidName_5[4].ReadPointers(binaryReader, blamPointers);
            invalidName_5[5].ReadPointers(binaryReader, blamPointers);
            invalidName_5[6].ReadPointers(binaryReader, blamPointers);
            invalidName_5[7].ReadPointers(binaryReader, blamPointers);
            invalidName_5[8].ReadPointers(binaryReader, blamPointers);
            invalidName_5[9].ReadPointers(binaryReader, blamPointers);
            invalidName_5[10].ReadPointers(binaryReader, blamPointers);
            invalidName_5[11].ReadPointers(binaryReader, blamPointers);
            invalidName_5[12].ReadPointers(binaryReader, blamPointers);
            invalidName_5[13].ReadPointers(binaryReader, blamPointers);
            invalidName_5[14].ReadPointers(binaryReader, blamPointers);
            invalidName_5[15].ReadPointers(binaryReader, blamPointers);
            invalidName_5[16].ReadPointers(binaryReader, blamPointers);
            invalidName_5[17].ReadPointers(binaryReader, blamPointers);
            invalidName_5[18].ReadPointers(binaryReader, blamPointers);
            invalidName_5[19].ReadPointers(binaryReader, blamPointers);
            invalidName_5[20].ReadPointers(binaryReader, blamPointers);
            invalidName_5[21].ReadPointers(binaryReader, blamPointers);
            invalidName_5[22].ReadPointers(binaryReader, blamPointers);
            invalidName_5[23].ReadPointers(binaryReader, blamPointers);
            invalidName_5[24].ReadPointers(binaryReader, blamPointers);
            invalidName_5[25].ReadPointers(binaryReader, blamPointers);
            invalidName_5[26].ReadPointers(binaryReader, blamPointers);
            invalidName_5[27].ReadPointers(binaryReader, blamPointers);
            invalidName_5[28].ReadPointers(binaryReader, blamPointers);
            invalidName_5[29].ReadPointers(binaryReader, blamPointers);
            invalidName_5[30].ReadPointers(binaryReader, blamPointers);
            invalidName_5[31].ReadPointers(binaryReader, blamPointers);
            invalidName_5[32].ReadPointers(binaryReader, blamPointers);
            invalidName_5[33].ReadPointers(binaryReader, blamPointers);
            invalidName_5[34].ReadPointers(binaryReader, blamPointers);
            invalidName_5[35].ReadPointers(binaryReader, blamPointers);
            invalidName_5[36].ReadPointers(binaryReader, blamPointers);
            invalidName_5[37].ReadPointers(binaryReader, blamPointers);
            invalidName_5[38].ReadPointers(binaryReader, blamPointers);
            invalidName_5[39].ReadPointers(binaryReader, blamPointers);
            invalidName_6[0].ReadPointers(binaryReader, blamPointers);
            invalidName_6[1].ReadPointers(binaryReader, blamPointers);
            invalidName_6[2].ReadPointers(binaryReader, blamPointers);
            invalidName_6[3].ReadPointers(binaryReader, blamPointers);
            invalidName_6[4].ReadPointers(binaryReader, blamPointers);
            invalidName_6[5].ReadPointers(binaryReader, blamPointers);
            invalidName_6[6].ReadPointers(binaryReader, blamPointers);
            invalidName_6[7].ReadPointers(binaryReader, blamPointers);
            invalidName_6[8].ReadPointers(binaryReader, blamPointers);
            invalidName_6[9].ReadPointers(binaryReader, blamPointers);
            invalidName_6[10].ReadPointers(binaryReader, blamPointers);
            invalidName_6[11].ReadPointers(binaryReader, blamPointers);
            invalidName_6[12].ReadPointers(binaryReader, blamPointers);
            invalidName_6[13].ReadPointers(binaryReader, blamPointers);
            invalidName_6[14].ReadPointers(binaryReader, blamPointers);
            invalidName_6[15].ReadPointers(binaryReader, blamPointers);
            invalidName_7[0].ReadPointers(binaryReader, blamPointers);
            invalidName_7[1].ReadPointers(binaryReader, blamPointers);
            invalidName_7[2].ReadPointers(binaryReader, blamPointers);
            invalidName_7[3].ReadPointers(binaryReader, blamPointers);
            invalidName_7[4].ReadPointers(binaryReader, blamPointers);
            invalidName_7[5].ReadPointers(binaryReader, blamPointers);
            invalidName_7[6].ReadPointers(binaryReader, blamPointers);
            invalidName_7[7].ReadPointers(binaryReader, blamPointers);
            invalidName_7[8].ReadPointers(binaryReader, blamPointers);
            invalidName_7[9].ReadPointers(binaryReader, blamPointers);
            invalidName_7[10].ReadPointers(binaryReader, blamPointers);
            invalidName_7[11].ReadPointers(binaryReader, blamPointers);
            invalidName_7[12].ReadPointers(binaryReader, blamPointers);
            invalidName_7[13].ReadPointers(binaryReader, blamPointers);
            invalidName_7[14].ReadPointers(binaryReader, blamPointers);
            invalidName_7[15].ReadPointers(binaryReader, blamPointers);
            invalidName_8[0].ReadPointers(binaryReader, blamPointers);
            invalidName_8[1].ReadPointers(binaryReader, blamPointers);
            invalidName_8[2].ReadPointers(binaryReader, blamPointers);
            invalidName_8[3].ReadPointers(binaryReader, blamPointers);
            invalidName_8[4].ReadPointers(binaryReader, blamPointers);
            invalidName_8[5].ReadPointers(binaryReader, blamPointers);
            invalidName_8[6].ReadPointers(binaryReader, blamPointers);
            invalidName_8[7].ReadPointers(binaryReader, blamPointers);
            invalidName_8[8].ReadPointers(binaryReader, blamPointers);
            invalidName_8[9].ReadPointers(binaryReader, blamPointers);
            invalidName_8[10].ReadPointers(binaryReader, blamPointers);
            invalidName_8[11].ReadPointers(binaryReader, blamPointers);
            invalidName_8[12].ReadPointers(binaryReader, blamPointers);
            invalidName_8[13].ReadPointers(binaryReader, blamPointers);
            invalidName_8[14].ReadPointers(binaryReader, blamPointers);
            invalidName_8[15].ReadPointers(binaryReader, blamPointers);
            invalidName_9[0].ReadPointers(binaryReader, blamPointers);
            invalidName_9[1].ReadPointers(binaryReader, blamPointers);
            invalidName_9[2].ReadPointers(binaryReader, blamPointers);
            invalidName_9[3].ReadPointers(binaryReader, blamPointers);
            invalidName_9[4].ReadPointers(binaryReader, blamPointers);
            invalidName_9[5].ReadPointers(binaryReader, blamPointers);
            invalidName_9[6].ReadPointers(binaryReader, blamPointers);
            invalidName_9[7].ReadPointers(binaryReader, blamPointers);
            invalidName_9[8].ReadPointers(binaryReader, blamPointers);
            invalidName_9[9].ReadPointers(binaryReader, blamPointers);
            invalidName_9[10].ReadPointers(binaryReader, blamPointers);
            invalidName_9[11].ReadPointers(binaryReader, blamPointers);
            invalidName_9[12].ReadPointers(binaryReader, blamPointers);
            invalidName_9[13].ReadPointers(binaryReader, blamPointers);
            invalidName_9[14].ReadPointers(binaryReader, blamPointers);
            invalidName_9[15].ReadPointers(binaryReader, blamPointers);
            invalidName_10[0].ReadPointers(binaryReader, blamPointers);
            invalidName_10[1].ReadPointers(binaryReader, blamPointers);
            invalidName_10[2].ReadPointers(binaryReader, blamPointers);
            invalidName_10[3].ReadPointers(binaryReader, blamPointers);
            invalidName_10[4].ReadPointers(binaryReader, blamPointers);
            invalidName_10[5].ReadPointers(binaryReader, blamPointers);
            invalidName_10[6].ReadPointers(binaryReader, blamPointers);
            invalidName_10[7].ReadPointers(binaryReader, blamPointers);
            invalidName_10[8].ReadPointers(binaryReader, blamPointers);
            invalidName_10[9].ReadPointers(binaryReader, blamPointers);
            invalidName_10[10].ReadPointers(binaryReader, blamPointers);
            invalidName_10[11].ReadPointers(binaryReader, blamPointers);
            invalidName_10[12].ReadPointers(binaryReader, blamPointers);
            invalidName_10[13].ReadPointers(binaryReader, blamPointers);
            invalidName_10[14].ReadPointers(binaryReader, blamPointers);
            invalidName_10[15].ReadPointers(binaryReader, blamPointers);
            invalidName_11[0].ReadPointers(binaryReader, blamPointers);
            invalidName_11[1].ReadPointers(binaryReader, blamPointers);
            invalidName_11[2].ReadPointers(binaryReader, blamPointers);
            invalidName_11[3].ReadPointers(binaryReader, blamPointers);
            invalidName_11[4].ReadPointers(binaryReader, blamPointers);
            invalidName_11[5].ReadPointers(binaryReader, blamPointers);
            invalidName_11[6].ReadPointers(binaryReader, blamPointers);
            invalidName_11[7].ReadPointers(binaryReader, blamPointers);
            invalidName_11[8].ReadPointers(binaryReader, blamPointers);
            invalidName_11[9].ReadPointers(binaryReader, blamPointers);
            invalidName_11[10].ReadPointers(binaryReader, blamPointers);
            invalidName_11[11].ReadPointers(binaryReader, blamPointers);
            invalidName_11[12].ReadPointers(binaryReader, blamPointers);
            invalidName_11[13].ReadPointers(binaryReader, blamPointers);
            invalidName_11[14].ReadPointers(binaryReader, blamPointers);
            invalidName_11[15].ReadPointers(binaryReader, blamPointers);
            invalidName_12[0].ReadPointers(binaryReader, blamPointers);
            invalidName_12[1].ReadPointers(binaryReader, blamPointers);
            invalidName_12[2].ReadPointers(binaryReader, blamPointers);
            invalidName_12[3].ReadPointers(binaryReader, blamPointers);
            invalidName_12[4].ReadPointers(binaryReader, blamPointers);
            invalidName_12[5].ReadPointers(binaryReader, blamPointers);
            invalidName_12[6].ReadPointers(binaryReader, blamPointers);
            invalidName_12[7].ReadPointers(binaryReader, blamPointers);
            invalidName_12[8].ReadPointers(binaryReader, blamPointers);
            invalidName_12[9].ReadPointers(binaryReader, blamPointers);
            invalidName_12[10].ReadPointers(binaryReader, blamPointers);
            invalidName_12[11].ReadPointers(binaryReader, blamPointers);
            invalidName_12[12].ReadPointers(binaryReader, blamPointers);
            invalidName_12[13].ReadPointers(binaryReader, blamPointers);
            invalidName_12[14].ReadPointers(binaryReader, blamPointers);
            invalidName_12[15].ReadPointers(binaryReader, blamPointers);
            invalidName_13[0].ReadPointers(binaryReader, blamPointers);
            invalidName_13[1].ReadPointers(binaryReader, blamPointers);
            invalidName_13[2].ReadPointers(binaryReader, blamPointers);
            invalidName_13[3].ReadPointers(binaryReader, blamPointers);
            invalidName_13[4].ReadPointers(binaryReader, blamPointers);
            invalidName_13[5].ReadPointers(binaryReader, blamPointers);
            invalidName_13[6].ReadPointers(binaryReader, blamPointers);
            invalidName_13[7].ReadPointers(binaryReader, blamPointers);
            invalidName_13[8].ReadPointers(binaryReader, blamPointers);
            invalidName_13[9].ReadPointers(binaryReader, blamPointers);
            invalidName_13[10].ReadPointers(binaryReader, blamPointers);
            invalidName_13[11].ReadPointers(binaryReader, blamPointers);
            invalidName_13[12].ReadPointers(binaryReader, blamPointers);
            invalidName_13[13].ReadPointers(binaryReader, blamPointers);
            invalidName_13[14].ReadPointers(binaryReader, blamPointers);
            invalidName_13[15].ReadPointers(binaryReader, blamPointers);
            invalidName_14[0].ReadPointers(binaryReader, blamPointers);
            invalidName_14[1].ReadPointers(binaryReader, blamPointers);
            invalidName_14[2].ReadPointers(binaryReader, blamPointers);
            invalidName_14[3].ReadPointers(binaryReader, blamPointers);
            invalidName_14[4].ReadPointers(binaryReader, blamPointers);
            invalidName_14[5].ReadPointers(binaryReader, blamPointers);
            invalidName_14[6].ReadPointers(binaryReader, blamPointers);
            invalidName_14[7].ReadPointers(binaryReader, blamPointers);
            invalidName_14[8].ReadPointers(binaryReader, blamPointers);
            invalidName_14[9].ReadPointers(binaryReader, blamPointers);
            invalidName_14[10].ReadPointers(binaryReader, blamPointers);
            invalidName_14[11].ReadPointers(binaryReader, blamPointers);
            invalidName_14[12].ReadPointers(binaryReader, blamPointers);
            invalidName_14[13].ReadPointers(binaryReader, blamPointers);
            invalidName_14[14].ReadPointers(binaryReader, blamPointers);
            invalidName_14[15].ReadPointers(binaryReader, blamPointers);
            invalidName_15[0].ReadPointers(binaryReader, blamPointers);
            invalidName_15[1].ReadPointers(binaryReader, blamPointers);
            invalidName_15[2].ReadPointers(binaryReader, blamPointers);
            invalidName_15[3].ReadPointers(binaryReader, blamPointers);
            invalidName_15[4].ReadPointers(binaryReader, blamPointers);
            invalidName_15[5].ReadPointers(binaryReader, blamPointers);
            invalidName_15[6].ReadPointers(binaryReader, blamPointers);
            invalidName_15[7].ReadPointers(binaryReader, blamPointers);
            invalidName_15[8].ReadPointers(binaryReader, blamPointers);
            invalidName_15[9].ReadPointers(binaryReader, blamPointers);
            invalidName_15[10].ReadPointers(binaryReader, blamPointers);
            invalidName_15[11].ReadPointers(binaryReader, blamPointers);
            invalidName_15[12].ReadPointers(binaryReader, blamPointers);
            invalidName_15[13].ReadPointers(binaryReader, blamPointers);
            invalidName_15[14].ReadPointers(binaryReader, blamPointers);
            invalidName_15[15].ReadPointers(binaryReader, blamPointers);
            invalidName_16[0].ReadPointers(binaryReader, blamPointers);
            invalidName_16[1].ReadPointers(binaryReader, blamPointers);
            invalidName_16[2].ReadPointers(binaryReader, blamPointers);
            invalidName_16[3].ReadPointers(binaryReader, blamPointers);
            invalidName_16[4].ReadPointers(binaryReader, blamPointers);
            invalidName_16[5].ReadPointers(binaryReader, blamPointers);
            invalidName_16[6].ReadPointers(binaryReader, blamPointers);
            invalidName_16[7].ReadPointers(binaryReader, blamPointers);
            invalidName_16[8].ReadPointers(binaryReader, blamPointers);
            invalidName_16[9].ReadPointers(binaryReader, blamPointers);
            invalidName_16[10].ReadPointers(binaryReader, blamPointers);
            invalidName_16[11].ReadPointers(binaryReader, blamPointers);
            invalidName_16[12].ReadPointers(binaryReader, blamPointers);
            invalidName_16[13].ReadPointers(binaryReader, blamPointers);
            invalidName_16[14].ReadPointers(binaryReader, blamPointers);
            invalidName_16[15].ReadPointers(binaryReader, blamPointers);
            invalidName_17[0].ReadPointers(binaryReader, blamPointers);
            invalidName_17[1].ReadPointers(binaryReader, blamPointers);
            invalidName_17[2].ReadPointers(binaryReader, blamPointers);
            invalidName_17[3].ReadPointers(binaryReader, blamPointers);
            invalidName_17[4].ReadPointers(binaryReader, blamPointers);
            invalidName_17[5].ReadPointers(binaryReader, blamPointers);
            invalidName_17[6].ReadPointers(binaryReader, blamPointers);
            invalidName_17[7].ReadPointers(binaryReader, blamPointers);
            invalidName_17[8].ReadPointers(binaryReader, blamPointers);
            invalidName_17[9].ReadPointers(binaryReader, blamPointers);
            invalidName_17[10].ReadPointers(binaryReader, blamPointers);
            invalidName_17[11].ReadPointers(binaryReader, blamPointers);
            invalidName_17[12].ReadPointers(binaryReader, blamPointers);
            invalidName_17[13].ReadPointers(binaryReader, blamPointers);
            invalidName_17[14].ReadPointers(binaryReader, blamPointers);
            invalidName_17[15].ReadPointers(binaryReader, blamPointers);
            invalidName_18[0].ReadPointers(binaryReader, blamPointers);
            invalidName_18[1].ReadPointers(binaryReader, blamPointers);
            invalidName_18[2].ReadPointers(binaryReader, blamPointers);
            invalidName_18[3].ReadPointers(binaryReader, blamPointers);
            invalidName_18[4].ReadPointers(binaryReader, blamPointers);
            invalidName_18[5].ReadPointers(binaryReader, blamPointers);
            invalidName_18[6].ReadPointers(binaryReader, blamPointers);
            invalidName_18[7].ReadPointers(binaryReader, blamPointers);
            invalidName_18[8].ReadPointers(binaryReader, blamPointers);
            invalidName_18[9].ReadPointers(binaryReader, blamPointers);
            invalidName_18[10].ReadPointers(binaryReader, blamPointers);
            invalidName_18[11].ReadPointers(binaryReader, blamPointers);
            invalidName_18[12].ReadPointers(binaryReader, blamPointers);
            invalidName_18[13].ReadPointers(binaryReader, blamPointers);
            invalidName_18[14].ReadPointers(binaryReader, blamPointers);
            invalidName_18[15].ReadPointers(binaryReader, blamPointers);
            invalidName_18[16].ReadPointers(binaryReader, blamPointers);
            invalidName_18[17].ReadPointers(binaryReader, blamPointers);
            invalidName_18[18].ReadPointers(binaryReader, blamPointers);
            invalidName_18[19].ReadPointers(binaryReader, blamPointers);
            invalidName_18[20].ReadPointers(binaryReader, blamPointers);
            invalidName_18[21].ReadPointers(binaryReader, blamPointers);
            invalidName_18[22].ReadPointers(binaryReader, blamPointers);
            invalidName_18[23].ReadPointers(binaryReader, blamPointers);
            invalidName_18[24].ReadPointers(binaryReader, blamPointers);
            invalidName_18[25].ReadPointers(binaryReader, blamPointers);
            invalidName_18[26].ReadPointers(binaryReader, blamPointers);
            invalidName_18[27].ReadPointers(binaryReader, blamPointers);
            invalidName_18[28].ReadPointers(binaryReader, blamPointers);
            invalidName_18[29].ReadPointers(binaryReader, blamPointers);
            invalidName_18[30].ReadPointers(binaryReader, blamPointers);
            invalidName_18[31].ReadPointers(binaryReader, blamPointers);
            invalidName_18[32].ReadPointers(binaryReader, blamPointers);
            invalidName_18[33].ReadPointers(binaryReader, blamPointers);
            invalidName_18[34].ReadPointers(binaryReader, blamPointers);
            invalidName_18[35].ReadPointers(binaryReader, blamPointers);
            invalidName_18[36].ReadPointers(binaryReader, blamPointers);
            invalidName_18[37].ReadPointers(binaryReader, blamPointers);
            invalidName_18[38].ReadPointers(binaryReader, blamPointers);
            invalidName_18[39].ReadPointers(binaryReader, blamPointers);
            invalidName_18[40].ReadPointers(binaryReader, blamPointers);
            invalidName_18[41].ReadPointers(binaryReader, blamPointers);
            invalidName_18[42].ReadPointers(binaryReader, blamPointers);
            invalidName_18[43].ReadPointers(binaryReader, blamPointers);
            invalidName_18[44].ReadPointers(binaryReader, blamPointers);
            invalidName_18[45].ReadPointers(binaryReader, blamPointers);
            invalidName_18[46].ReadPointers(binaryReader, blamPointers);
            invalidName_18[47].ReadPointers(binaryReader, blamPointers);
            invalidName_18[48].ReadPointers(binaryReader, blamPointers);
            invalidName_18[49].ReadPointers(binaryReader, blamPointers);
            invalidName_18[50].ReadPointers(binaryReader, blamPointers);
            invalidName_18[51].ReadPointers(binaryReader, blamPointers);
            invalidName_18[52].ReadPointers(binaryReader, blamPointers);
            invalidName_18[53].ReadPointers(binaryReader, blamPointers);
            invalidName_18[54].ReadPointers(binaryReader, blamPointers);
            invalidName_18[55].ReadPointers(binaryReader, blamPointers);
            invalidName_18[56].ReadPointers(binaryReader, blamPointers);
            invalidName_18[57].ReadPointers(binaryReader, blamPointers);
            invalidName_18[58].ReadPointers(binaryReader, blamPointers);
            invalidName_18[59].ReadPointers(binaryReader, blamPointers);
            invalidName_18[60].ReadPointers(binaryReader, blamPointers);
            invalidName_18[61].ReadPointers(binaryReader, blamPointers);
            invalidName_18[62].ReadPointers(binaryReader, blamPointers);
            invalidName_18[63].ReadPointers(binaryReader, blamPointers);
            invalidName_18[64].ReadPointers(binaryReader, blamPointers);
            invalidName_18[65].ReadPointers(binaryReader, blamPointers);
            invalidName_18[66].ReadPointers(binaryReader, blamPointers);
            invalidName_18[67].ReadPointers(binaryReader, blamPointers);
            invalidName_18[68].ReadPointers(binaryReader, blamPointers);
            invalidName_18[69].ReadPointers(binaryReader, blamPointers);
            invalidName_18[70].ReadPointers(binaryReader, blamPointers);
            invalidName_18[71].ReadPointers(binaryReader, blamPointers);
            invalidName_18[72].ReadPointers(binaryReader, blamPointers);
            invalidName_18[73].ReadPointers(binaryReader, blamPointers);
            invalidName_18[74].ReadPointers(binaryReader, blamPointers);
            invalidName_18[75].ReadPointers(binaryReader, blamPointers);
            invalidName_18[76].ReadPointers(binaryReader, blamPointers);
            invalidName_18[77].ReadPointers(binaryReader, blamPointers);
            invalidName_18[78].ReadPointers(binaryReader, blamPointers);
            invalidName_18[79].ReadPointers(binaryReader, blamPointers);
            invalidName_18[80].ReadPointers(binaryReader, blamPointers);
            invalidName_18[81].ReadPointers(binaryReader, blamPointers);
            invalidName_18[82].ReadPointers(binaryReader, blamPointers);
            invalidName_18[83].ReadPointers(binaryReader, blamPointers);
            invalidName_18[84].ReadPointers(binaryReader, blamPointers);
            invalidName_18[85].ReadPointers(binaryReader, blamPointers);
            invalidName_18[86].ReadPointers(binaryReader, blamPointers);
            invalidName_18[87].ReadPointers(binaryReader, blamPointers);
            invalidName_18[88].ReadPointers(binaryReader, blamPointers);
            invalidName_18[89].ReadPointers(binaryReader, blamPointers);
            invalidName_18[90].ReadPointers(binaryReader, blamPointers);
            invalidName_18[91].ReadPointers(binaryReader, blamPointers);
            invalidName_18[92].ReadPointers(binaryReader, blamPointers);
            invalidName_18[93].ReadPointers(binaryReader, blamPointers);
            invalidName_18[94].ReadPointers(binaryReader, blamPointers);
            invalidName_18[95].ReadPointers(binaryReader, blamPointers);
            invalidName_18[96].ReadPointers(binaryReader, blamPointers);
            invalidName_18[97].ReadPointers(binaryReader, blamPointers);
            invalidName_18[98].ReadPointers(binaryReader, blamPointers);
            invalidName_18[99].ReadPointers(binaryReader, blamPointers);
            invalidName_18[100].ReadPointers(binaryReader, blamPointers);
            invalidName_18[101].ReadPointers(binaryReader, blamPointers);
            invalidName_18[102].ReadPointers(binaryReader, blamPointers);
            invalidName_18[103].ReadPointers(binaryReader, blamPointers);
            invalidName_18[104].ReadPointers(binaryReader, blamPointers);
            invalidName_18[105].ReadPointers(binaryReader, blamPointers);
            invalidName_18[106].ReadPointers(binaryReader, blamPointers);
            invalidName_18[107].ReadPointers(binaryReader, blamPointers);
            invalidName_18[108].ReadPointers(binaryReader, blamPointers);
            invalidName_18[109].ReadPointers(binaryReader, blamPointers);
            invalidName_18[110].ReadPointers(binaryReader, blamPointers);
            invalidName_18[111].ReadPointers(binaryReader, blamPointers);
            invalidName_18[112].ReadPointers(binaryReader, blamPointers);
            invalidName_18[113].ReadPointers(binaryReader, blamPointers);
            invalidName_18[114].ReadPointers(binaryReader, blamPointers);
            invalidName_18[115].ReadPointers(binaryReader, blamPointers);
            invalidName_18[116].ReadPointers(binaryReader, blamPointers);
            invalidName_18[117].ReadPointers(binaryReader, blamPointers);
            invalidName_18[118].ReadPointers(binaryReader, blamPointers);
            invalidName_18[119].ReadPointers(binaryReader, blamPointers);
            invalidName_18[120].ReadPointers(binaryReader, blamPointers);
            invalidName_18[121].ReadPointers(binaryReader, blamPointers);
            invalidName_18[122].ReadPointers(binaryReader, blamPointers);
            invalidName_18[123].ReadPointers(binaryReader, blamPointers);
            invalidName_18[124].ReadPointers(binaryReader, blamPointers);
            invalidName_18[125].ReadPointers(binaryReader, blamPointers);
            invalidName_18[126].ReadPointers(binaryReader, blamPointers);
            invalidName_18[127].ReadPointers(binaryReader, blamPointers);
            invalidName_18[128].ReadPointers(binaryReader, blamPointers);
            invalidName_18[129].ReadPointers(binaryReader, blamPointers);
            invalidName_18[130].ReadPointers(binaryReader, blamPointers);
            invalidName_18[131].ReadPointers(binaryReader, blamPointers);
            invalidName_18[132].ReadPointers(binaryReader, blamPointers);
            invalidName_18[133].ReadPointers(binaryReader, blamPointers);
            invalidName_18[134].ReadPointers(binaryReader, blamPointers);
            invalidName_18[135].ReadPointers(binaryReader, blamPointers);
            invalidName_18[136].ReadPointers(binaryReader, blamPointers);
            invalidName_18[137].ReadPointers(binaryReader, blamPointers);
            invalidName_18[138].ReadPointers(binaryReader, blamPointers);
            invalidName_18[139].ReadPointers(binaryReader, blamPointers);
            invalidName_18[140].ReadPointers(binaryReader, blamPointers);
            invalidName_18[141].ReadPointers(binaryReader, blamPointers);
            invalidName_18[142].ReadPointers(binaryReader, blamPointers);
            invalidName_18[143].ReadPointers(binaryReader, blamPointers);
            invalidName_18[144].ReadPointers(binaryReader, blamPointers);
            invalidName_18[145].ReadPointers(binaryReader, blamPointers);
            invalidName_18[146].ReadPointers(binaryReader, blamPointers);
            invalidName_18[147].ReadPointers(binaryReader, blamPointers);
            invalidName_18[148].ReadPointers(binaryReader, blamPointers);
            invalidName_18[149].ReadPointers(binaryReader, blamPointers);
            invalidName_18[150].ReadPointers(binaryReader, blamPointers);
            invalidName_18[151].ReadPointers(binaryReader, blamPointers);
            invalidName_18[152].ReadPointers(binaryReader, blamPointers);
            invalidName_18[153].ReadPointers(binaryReader, blamPointers);
            invalidName_18[154].ReadPointers(binaryReader, blamPointers);
            invalidName_18[155].ReadPointers(binaryReader, blamPointers);
            invalidName_18[156].ReadPointers(binaryReader, blamPointers);
            invalidName_18[157].ReadPointers(binaryReader, blamPointers);
            invalidName_18[158].ReadPointers(binaryReader, blamPointers);
            invalidName_18[159].ReadPointers(binaryReader, blamPointers);
            invalidName_18[160].ReadPointers(binaryReader, blamPointers);
            invalidName_18[161].ReadPointers(binaryReader, blamPointers);
            invalidName_18[162].ReadPointers(binaryReader, blamPointers);
            invalidName_18[163].ReadPointers(binaryReader, blamPointers);
            invalidName_18[164].ReadPointers(binaryReader, blamPointers);
            invalidName_18[165].ReadPointers(binaryReader, blamPointers);
            invalidName_18[166].ReadPointers(binaryReader, blamPointers);
            invalidName_18[167].ReadPointers(binaryReader, blamPointers);
            invalidName_18[168].ReadPointers(binaryReader, blamPointers);
            invalidName_18[169].ReadPointers(binaryReader, blamPointers);
            invalidName_18[170].ReadPointers(binaryReader, blamPointers);
            invalidName_18[171].ReadPointers(binaryReader, blamPointers);
            invalidName_18[172].ReadPointers(binaryReader, blamPointers);
            invalidName_18[173].ReadPointers(binaryReader, blamPointers);
            invalidName_18[174].ReadPointers(binaryReader, blamPointers);
            invalidName_18[175].ReadPointers(binaryReader, blamPointers);
            invalidName_18[176].ReadPointers(binaryReader, blamPointers);
            invalidName_18[177].ReadPointers(binaryReader, blamPointers);
            invalidName_18[178].ReadPointers(binaryReader, blamPointers);
            invalidName_18[179].ReadPointers(binaryReader, blamPointers);
            invalidName_18[180].ReadPointers(binaryReader, blamPointers);
            invalidName_18[181].ReadPointers(binaryReader, blamPointers);
            invalidName_18[182].ReadPointers(binaryReader, blamPointers);
            invalidName_18[183].ReadPointers(binaryReader, blamPointers);
            invalidName_18[184].ReadPointers(binaryReader, blamPointers);
            invalidName_18[185].ReadPointers(binaryReader, blamPointers);
            invalidName_18[186].ReadPointers(binaryReader, blamPointers);
            invalidName_18[187].ReadPointers(binaryReader, blamPointers);
            invalidName_18[188].ReadPointers(binaryReader, blamPointers);
            invalidName_18[189].ReadPointers(binaryReader, blamPointers);
            invalidName_18[190].ReadPointers(binaryReader, blamPointers);
            invalidName_18[191].ReadPointers(binaryReader, blamPointers);
            invalidName_18[192].ReadPointers(binaryReader, blamPointers);
            invalidName_18[193].ReadPointers(binaryReader, blamPointers);
            invalidName_18[194].ReadPointers(binaryReader, blamPointers);
            invalidName_18[195].ReadPointers(binaryReader, blamPointers);
            invalidName_18[196].ReadPointers(binaryReader, blamPointers);
            invalidName_18[197].ReadPointers(binaryReader, blamPointers);
            invalidName_18[198].ReadPointers(binaryReader, blamPointers);
            invalidName_18[199].ReadPointers(binaryReader, blamPointers);
            invalidName_18[200].ReadPointers(binaryReader, blamPointers);
            invalidName_18[201].ReadPointers(binaryReader, blamPointers);
            invalidName_18[202].ReadPointers(binaryReader, blamPointers);
            invalidName_18[203].ReadPointers(binaryReader, blamPointers);
            invalidName_18[204].ReadPointers(binaryReader, blamPointers);
            invalidName_18[205].ReadPointers(binaryReader, blamPointers);
            invalidName_18[206].ReadPointers(binaryReader, blamPointers);
            invalidName_18[207].ReadPointers(binaryReader, blamPointers);
            invalidName_18[208].ReadPointers(binaryReader, blamPointers);
            invalidName_18[209].ReadPointers(binaryReader, blamPointers);
            invalidName_18[210].ReadPointers(binaryReader, blamPointers);
            invalidName_18[211].ReadPointers(binaryReader, blamPointers);
            invalidName_18[212].ReadPointers(binaryReader, blamPointers);
            invalidName_18[213].ReadPointers(binaryReader, blamPointers);
            invalidName_18[214].ReadPointers(binaryReader, blamPointers);
            invalidName_18[215].ReadPointers(binaryReader, blamPointers);
            invalidName_18[216].ReadPointers(binaryReader, blamPointers);
            invalidName_18[217].ReadPointers(binaryReader, blamPointers);
            invalidName_18[218].ReadPointers(binaryReader, blamPointers);
            invalidName_18[219].ReadPointers(binaryReader, blamPointers);
            invalidName_18[220].ReadPointers(binaryReader, blamPointers);
            invalidName_18[221].ReadPointers(binaryReader, blamPointers);
            invalidName_18[222].ReadPointers(binaryReader, blamPointers);
            invalidName_18[223].ReadPointers(binaryReader, blamPointers);
            invalidName_18[224].ReadPointers(binaryReader, blamPointers);
            invalidName_18[225].ReadPointers(binaryReader, blamPointers);
            invalidName_18[226].ReadPointers(binaryReader, blamPointers);
            invalidName_18[227].ReadPointers(binaryReader, blamPointers);
            invalidName_18[228].ReadPointers(binaryReader, blamPointers);
            invalidName_18[229].ReadPointers(binaryReader, blamPointers);
            invalidName_18[230].ReadPointers(binaryReader, blamPointers);
            invalidName_18[231].ReadPointers(binaryReader, blamPointers);
            invalidName_18[232].ReadPointers(binaryReader, blamPointers);
            invalidName_18[233].ReadPointers(binaryReader, blamPointers);
            invalidName_18[234].ReadPointers(binaryReader, blamPointers);
            invalidName_18[235].ReadPointers(binaryReader, blamPointers);
            invalidName_18[236].ReadPointers(binaryReader, blamPointers);
            invalidName_18[237].ReadPointers(binaryReader, blamPointers);
            invalidName_18[238].ReadPointers(binaryReader, blamPointers);
            invalidName_18[239].ReadPointers(binaryReader, blamPointers);
            invalidName_18[240].ReadPointers(binaryReader, blamPointers);
            invalidName_18[241].ReadPointers(binaryReader, blamPointers);
            invalidName_18[242].ReadPointers(binaryReader, blamPointers);
            invalidName_18[243].ReadPointers(binaryReader, blamPointers);
            invalidName_18[244].ReadPointers(binaryReader, blamPointers);
            invalidName_18[245].ReadPointers(binaryReader, blamPointers);
            invalidName_18[246].ReadPointers(binaryReader, blamPointers);
            invalidName_18[247].ReadPointers(binaryReader, blamPointers);
            invalidName_18[248].ReadPointers(binaryReader, blamPointers);
            invalidName_18[249].ReadPointers(binaryReader, blamPointers);
            invalidName_18[250].ReadPointers(binaryReader, blamPointers);
            invalidName_18[251].ReadPointers(binaryReader, blamPointers);
            invalidName_18[252].ReadPointers(binaryReader, blamPointers);
            invalidName_18[253].ReadPointers(binaryReader, blamPointers);
            invalidName_18[254].ReadPointers(binaryReader, blamPointers);
            invalidName_18[255].ReadPointers(binaryReader, blamPointers);
            invalidName_18[256].ReadPointers(binaryReader, blamPointers);
            invalidName_18[257].ReadPointers(binaryReader, blamPointers);
            invalidName_18[258].ReadPointers(binaryReader, blamPointers);
            invalidName_18[259].ReadPointers(binaryReader, blamPointers);
            invalidName_18[260].ReadPointers(binaryReader, blamPointers);
            invalidName_18[261].ReadPointers(binaryReader, blamPointers);
            invalidName_18[262].ReadPointers(binaryReader, blamPointers);
            invalidName_18[263].ReadPointers(binaryReader, blamPointers);
            invalidName_18[264].ReadPointers(binaryReader, blamPointers);
            invalidName_18[265].ReadPointers(binaryReader, blamPointers);
            invalidName_18[266].ReadPointers(binaryReader, blamPointers);
            invalidName_18[267].ReadPointers(binaryReader, blamPointers);
            invalidName_18[268].ReadPointers(binaryReader, blamPointers);
            invalidName_18[269].ReadPointers(binaryReader, blamPointers);
            invalidName_18[270].ReadPointers(binaryReader, blamPointers);
            invalidName_18[271].ReadPointers(binaryReader, blamPointers);
            invalidName_18[272].ReadPointers(binaryReader, blamPointers);
            invalidName_18[273].ReadPointers(binaryReader, blamPointers);
            invalidName_18[274].ReadPointers(binaryReader, blamPointers);
            invalidName_18[275].ReadPointers(binaryReader, blamPointers);
            invalidName_18[276].ReadPointers(binaryReader, blamPointers);
            invalidName_18[277].ReadPointers(binaryReader, blamPointers);
            invalidName_18[278].ReadPointers(binaryReader, blamPointers);
            invalidName_18[279].ReadPointers(binaryReader, blamPointers);
            invalidName_18[280].ReadPointers(binaryReader, blamPointers);
            invalidName_18[281].ReadPointers(binaryReader, blamPointers);
            invalidName_18[282].ReadPointers(binaryReader, blamPointers);
            invalidName_18[283].ReadPointers(binaryReader, blamPointers);
            invalidName_18[284].ReadPointers(binaryReader, blamPointers);
            invalidName_18[285].ReadPointers(binaryReader, blamPointers);
            invalidName_18[286].ReadPointers(binaryReader, blamPointers);
            invalidName_18[287].ReadPointers(binaryReader, blamPointers);
            invalidName_18[288].ReadPointers(binaryReader, blamPointers);
            invalidName_18[289].ReadPointers(binaryReader, blamPointers);
            invalidName_18[290].ReadPointers(binaryReader, blamPointers);
            invalidName_18[291].ReadPointers(binaryReader, blamPointers);
            invalidName_18[292].ReadPointers(binaryReader, blamPointers);
            invalidName_18[293].ReadPointers(binaryReader, blamPointers);
            invalidName_18[294].ReadPointers(binaryReader, blamPointers);
            invalidName_18[295].ReadPointers(binaryReader, blamPointers);
            invalidName_18[296].ReadPointers(binaryReader, blamPointers);
            invalidName_18[297].ReadPointers(binaryReader, blamPointers);
            invalidName_18[298].ReadPointers(binaryReader, blamPointers);
            invalidName_18[299].ReadPointers(binaryReader, blamPointers);
            invalidName_18[300].ReadPointers(binaryReader, blamPointers);
            invalidName_18[301].ReadPointers(binaryReader, blamPointers);
            invalidName_18[302].ReadPointers(binaryReader, blamPointers);
            invalidName_18[303].ReadPointers(binaryReader, blamPointers);
            invalidName_18[304].ReadPointers(binaryReader, blamPointers);
            invalidName_18[305].ReadPointers(binaryReader, blamPointers);
            invalidName_18[306].ReadPointers(binaryReader, blamPointers);
            invalidName_18[307].ReadPointers(binaryReader, blamPointers);
            invalidName_18[308].ReadPointers(binaryReader, blamPointers);
            invalidName_18[309].ReadPointers(binaryReader, blamPointers);
            invalidName_18[310].ReadPointers(binaryReader, blamPointers);
            invalidName_18[311].ReadPointers(binaryReader, blamPointers);
            invalidName_18[312].ReadPointers(binaryReader, blamPointers);
            invalidName_18[313].ReadPointers(binaryReader, blamPointers);
            invalidName_18[314].ReadPointers(binaryReader, blamPointers);
            invalidName_18[315].ReadPointers(binaryReader, blamPointers);
            invalidName_18[316].ReadPointers(binaryReader, blamPointers);
            invalidName_18[317].ReadPointers(binaryReader, blamPointers);
            invalidName_18[318].ReadPointers(binaryReader, blamPointers);
            invalidName_18[319].ReadPointers(binaryReader, blamPointers);
            invalidName_18[320].ReadPointers(binaryReader, blamPointers);
            invalidName_18[321].ReadPointers(binaryReader, blamPointers);
            invalidName_18[322].ReadPointers(binaryReader, blamPointers);
            invalidName_18[323].ReadPointers(binaryReader, blamPointers);
            invalidName_18[324].ReadPointers(binaryReader, blamPointers);
            invalidName_18[325].ReadPointers(binaryReader, blamPointers);
            invalidName_18[326].ReadPointers(binaryReader, blamPointers);
            invalidName_18[327].ReadPointers(binaryReader, blamPointers);
            invalidName_18[328].ReadPointers(binaryReader, blamPointers);
            invalidName_18[329].ReadPointers(binaryReader, blamPointers);
            invalidName_18[330].ReadPointers(binaryReader, blamPointers);
            invalidName_18[331].ReadPointers(binaryReader, blamPointers);
            invalidName_18[332].ReadPointers(binaryReader, blamPointers);
            invalidName_18[333].ReadPointers(binaryReader, blamPointers);
            invalidName_18[334].ReadPointers(binaryReader, blamPointers);
            invalidName_18[335].ReadPointers(binaryReader, blamPointers);
            invalidName_18[336].ReadPointers(binaryReader, blamPointers);
            invalidName_18[337].ReadPointers(binaryReader, blamPointers);
            invalidName_18[338].ReadPointers(binaryReader, blamPointers);
            invalidName_18[339].ReadPointers(binaryReader, blamPointers);
            invalidName_18[340].ReadPointers(binaryReader, blamPointers);
            invalidName_18[341].ReadPointers(binaryReader, blamPointers);
            invalidName_18[342].ReadPointers(binaryReader, blamPointers);
            invalidName_18[343].ReadPointers(binaryReader, blamPointers);
            invalidName_18[344].ReadPointers(binaryReader, blamPointers);
            invalidName_18[345].ReadPointers(binaryReader, blamPointers);
            invalidName_18[346].ReadPointers(binaryReader, blamPointers);
            invalidName_18[347].ReadPointers(binaryReader, blamPointers);
            invalidName_18[348].ReadPointers(binaryReader, blamPointers);
            invalidName_18[349].ReadPointers(binaryReader, blamPointers);
            invalidName_18[350].ReadPointers(binaryReader, blamPointers);
            invalidName_18[351].ReadPointers(binaryReader, blamPointers);
            invalidName_18[352].ReadPointers(binaryReader, blamPointers);
            invalidName_18[353].ReadPointers(binaryReader, blamPointers);
            invalidName_18[354].ReadPointers(binaryReader, blamPointers);
            invalidName_18[355].ReadPointers(binaryReader, blamPointers);
            invalidName_18[356].ReadPointers(binaryReader, blamPointers);
            invalidName_18[357].ReadPointers(binaryReader, blamPointers);
            invalidName_18[358].ReadPointers(binaryReader, blamPointers);
            invalidName_18[359].ReadPointers(binaryReader, blamPointers);
            invalidName_18[360].ReadPointers(binaryReader, blamPointers);
            invalidName_18[361].ReadPointers(binaryReader, blamPointers);
            invalidName_18[362].ReadPointers(binaryReader, blamPointers);
            invalidName_18[363].ReadPointers(binaryReader, blamPointers);
            invalidName_18[364].ReadPointers(binaryReader, blamPointers);
            invalidName_18[365].ReadPointers(binaryReader, blamPointers);
            invalidName_18[366].ReadPointers(binaryReader, blamPointers);
            invalidName_18[367].ReadPointers(binaryReader, blamPointers);
            invalidName_18[368].ReadPointers(binaryReader, blamPointers);
            invalidName_18[369].ReadPointers(binaryReader, blamPointers);
            invalidName_18[370].ReadPointers(binaryReader, blamPointers);
            invalidName_18[371].ReadPointers(binaryReader, blamPointers);
            invalidName_18[372].ReadPointers(binaryReader, blamPointers);
            invalidName_18[373].ReadPointers(binaryReader, blamPointers);
            invalidName_18[374].ReadPointers(binaryReader, blamPointers);
            invalidName_18[375].ReadPointers(binaryReader, blamPointers);
            invalidName_18[376].ReadPointers(binaryReader, blamPointers);
            invalidName_18[377].ReadPointers(binaryReader, blamPointers);
            invalidName_18[378].ReadPointers(binaryReader, blamPointers);
            invalidName_18[379].ReadPointers(binaryReader, blamPointers);
            invalidName_18[380].ReadPointers(binaryReader, blamPointers);
            invalidName_18[381].ReadPointers(binaryReader, blamPointers);
            invalidName_18[382].ReadPointers(binaryReader, blamPointers);
            invalidName_18[383].ReadPointers(binaryReader, blamPointers);
            invalidName_18[384].ReadPointers(binaryReader, blamPointers);
            invalidName_18[385].ReadPointers(binaryReader, blamPointers);
            invalidName_18[386].ReadPointers(binaryReader, blamPointers);
            invalidName_18[387].ReadPointers(binaryReader, blamPointers);
            invalidName_18[388].ReadPointers(binaryReader, blamPointers);
            invalidName_18[389].ReadPointers(binaryReader, blamPointers);
            invalidName_18[390].ReadPointers(binaryReader, blamPointers);
            invalidName_18[391].ReadPointers(binaryReader, blamPointers);
            invalidName_18[392].ReadPointers(binaryReader, blamPointers);
            invalidName_18[393].ReadPointers(binaryReader, blamPointers);
            invalidName_18[394].ReadPointers(binaryReader, blamPointers);
            invalidName_18[395].ReadPointers(binaryReader, blamPointers);
            invalidName_18[396].ReadPointers(binaryReader, blamPointers);
            invalidName_18[397].ReadPointers(binaryReader, blamPointers);
            invalidName_18[398].ReadPointers(binaryReader, blamPointers);
            invalidName_18[399].ReadPointers(binaryReader, blamPointers);
            invalidName_18[400].ReadPointers(binaryReader, blamPointers);
            invalidName_18[401].ReadPointers(binaryReader, blamPointers);
            invalidName_18[402].ReadPointers(binaryReader, blamPointers);
            invalidName_18[403].ReadPointers(binaryReader, blamPointers);
            invalidName_18[404].ReadPointers(binaryReader, blamPointers);
            invalidName_18[405].ReadPointers(binaryReader, blamPointers);
            invalidName_18[406].ReadPointers(binaryReader, blamPointers);
            invalidName_18[407].ReadPointers(binaryReader, blamPointers);
            invalidName_18[408].ReadPointers(binaryReader, blamPointers);
            invalidName_18[409].ReadPointers(binaryReader, blamPointers);
            invalidName_18[410].ReadPointers(binaryReader, blamPointers);
            invalidName_18[411].ReadPointers(binaryReader, blamPointers);
            invalidName_18[412].ReadPointers(binaryReader, blamPointers);
            invalidName_18[413].ReadPointers(binaryReader, blamPointers);
            invalidName_18[414].ReadPointers(binaryReader, blamPointers);
            invalidName_18[415].ReadPointers(binaryReader, blamPointers);
            invalidName_18[416].ReadPointers(binaryReader, blamPointers);
            invalidName_18[417].ReadPointers(binaryReader, blamPointers);
            invalidName_18[418].ReadPointers(binaryReader, blamPointers);
            invalidName_18[419].ReadPointers(binaryReader, blamPointers);
            invalidName_18[420].ReadPointers(binaryReader, blamPointers);
            invalidName_18[421].ReadPointers(binaryReader, blamPointers);
            invalidName_18[422].ReadPointers(binaryReader, blamPointers);
            invalidName_18[423].ReadPointers(binaryReader, blamPointers);
            invalidName_18[424].ReadPointers(binaryReader, blamPointers);
            invalidName_18[425].ReadPointers(binaryReader, blamPointers);
            invalidName_18[426].ReadPointers(binaryReader, blamPointers);
            invalidName_18[427].ReadPointers(binaryReader, blamPointers);
            invalidName_18[428].ReadPointers(binaryReader, blamPointers);
            invalidName_18[429].ReadPointers(binaryReader, blamPointers);
            invalidName_18[430].ReadPointers(binaryReader, blamPointers);
            invalidName_18[431].ReadPointers(binaryReader, blamPointers);
            invalidName_18[432].ReadPointers(binaryReader, blamPointers);
            invalidName_18[433].ReadPointers(binaryReader, blamPointers);
            invalidName_18[434].ReadPointers(binaryReader, blamPointers);
            invalidName_18[435].ReadPointers(binaryReader, blamPointers);
            invalidName_18[436].ReadPointers(binaryReader, blamPointers);
            invalidName_18[437].ReadPointers(binaryReader, blamPointers);
            invalidName_18[438].ReadPointers(binaryReader, blamPointers);
            invalidName_18[439].ReadPointers(binaryReader, blamPointers);
            invalidName_18[440].ReadPointers(binaryReader, blamPointers);
            invalidName_18[441].ReadPointers(binaryReader, blamPointers);
            invalidName_18[442].ReadPointers(binaryReader, blamPointers);
            invalidName_18[443].ReadPointers(binaryReader, blamPointers);
            invalidName_18[444].ReadPointers(binaryReader, blamPointers);
            invalidName_18[445].ReadPointers(binaryReader, blamPointers);
            invalidName_18[446].ReadPointers(binaryReader, blamPointers);
            invalidName_18[447].ReadPointers(binaryReader, blamPointers);
            invalidName_18[448].ReadPointers(binaryReader, blamPointers);
            invalidName_18[449].ReadPointers(binaryReader, blamPointers);
            invalidName_18[450].ReadPointers(binaryReader, blamPointers);
            invalidName_18[451].ReadPointers(binaryReader, blamPointers);
            invalidName_18[452].ReadPointers(binaryReader, blamPointers);
            invalidName_18[453].ReadPointers(binaryReader, blamPointers);
            invalidName_18[454].ReadPointers(binaryReader, blamPointers);
            invalidName_18[455].ReadPointers(binaryReader, blamPointers);
            invalidName_18[456].ReadPointers(binaryReader, blamPointers);
            invalidName_18[457].ReadPointers(binaryReader, blamPointers);
            invalidName_18[458].ReadPointers(binaryReader, blamPointers);
            invalidName_18[459].ReadPointers(binaryReader, blamPointers);
            invalidName_18[460].ReadPointers(binaryReader, blamPointers);
            invalidName_18[461].ReadPointers(binaryReader, blamPointers);
            invalidName_18[462].ReadPointers(binaryReader, blamPointers);
            invalidName_18[463].ReadPointers(binaryReader, blamPointers);
            invalidName_18[464].ReadPointers(binaryReader, blamPointers);
            invalidName_18[465].ReadPointers(binaryReader, blamPointers);
            invalidName_18[466].ReadPointers(binaryReader, blamPointers);
            invalidName_18[467].ReadPointers(binaryReader, blamPointers);
            invalidName_18[468].ReadPointers(binaryReader, blamPointers);
            invalidName_18[469].ReadPointers(binaryReader, blamPointers);
            invalidName_18[470].ReadPointers(binaryReader, blamPointers);
            invalidName_18[471].ReadPointers(binaryReader, blamPointers);
            invalidName_18[472].ReadPointers(binaryReader, blamPointers);
            invalidName_18[473].ReadPointers(binaryReader, blamPointers);
            invalidName_18[474].ReadPointers(binaryReader, blamPointers);
            invalidName_18[475].ReadPointers(binaryReader, blamPointers);
            invalidName_18[476].ReadPointers(binaryReader, blamPointers);
            invalidName_18[477].ReadPointers(binaryReader, blamPointers);
            invalidName_18[478].ReadPointers(binaryReader, blamPointers);
            invalidName_18[479].ReadPointers(binaryReader, blamPointers);
            invalidName_18[480].ReadPointers(binaryReader, blamPointers);
            invalidName_18[481].ReadPointers(binaryReader, blamPointers);
            invalidName_18[482].ReadPointers(binaryReader, blamPointers);
            invalidName_18[483].ReadPointers(binaryReader, blamPointers);
            invalidName_18[484].ReadPointers(binaryReader, blamPointers);
            invalidName_18[485].ReadPointers(binaryReader, blamPointers);
            invalidName_18[486].ReadPointers(binaryReader, blamPointers);
            invalidName_18[487].ReadPointers(binaryReader, blamPointers);
            invalidName_18[488].ReadPointers(binaryReader, blamPointers);
            invalidName_18[489].ReadPointers(binaryReader, blamPointers);
            invalidName_18[490].ReadPointers(binaryReader, blamPointers);
            invalidName_18[491].ReadPointers(binaryReader, blamPointers);
            invalidName_18[492].ReadPointers(binaryReader, blamPointers);
            invalidName_18[493].ReadPointers(binaryReader, blamPointers);
            invalidName_18[494].ReadPointers(binaryReader, blamPointers);
            invalidName_18[495].ReadPointers(binaryReader, blamPointers);
            invalidName_18[496].ReadPointers(binaryReader, blamPointers);
            invalidName_18[497].ReadPointers(binaryReader, blamPointers);
            invalidName_18[498].ReadPointers(binaryReader, blamPointers);
            invalidName_18[499].ReadPointers(binaryReader, blamPointers);
            invalidName_18[500].ReadPointers(binaryReader, blamPointers);
            invalidName_18[501].ReadPointers(binaryReader, blamPointers);
            invalidName_18[502].ReadPointers(binaryReader, blamPointers);
            invalidName_18[503].ReadPointers(binaryReader, blamPointers);
            invalidName_18[504].ReadPointers(binaryReader, blamPointers);
            invalidName_18[505].ReadPointers(binaryReader, blamPointers);
            invalidName_18[506].ReadPointers(binaryReader, blamPointers);
            invalidName_18[507].ReadPointers(binaryReader, blamPointers);
            invalidName_18[508].ReadPointers(binaryReader, blamPointers);
            invalidName_18[509].ReadPointers(binaryReader, blamPointers);
            invalidName_18[510].ReadPointers(binaryReader, blamPointers);
            invalidName_18[511].ReadPointers(binaryReader, blamPointers);
            invalidName_18[512].ReadPointers(binaryReader, blamPointers);
            invalidName_18[513].ReadPointers(binaryReader, blamPointers);
            invalidName_18[514].ReadPointers(binaryReader, blamPointers);
            invalidName_18[515].ReadPointers(binaryReader, blamPointers);
            invalidName_18[516].ReadPointers(binaryReader, blamPointers);
            invalidName_18[517].ReadPointers(binaryReader, blamPointers);
            invalidName_18[518].ReadPointers(binaryReader, blamPointers);
            invalidName_18[519].ReadPointers(binaryReader, blamPointers);
            invalidName_18[520].ReadPointers(binaryReader, blamPointers);
            invalidName_18[521].ReadPointers(binaryReader, blamPointers);
            invalidName_18[522].ReadPointers(binaryReader, blamPointers);
            invalidName_18[523].ReadPointers(binaryReader, blamPointers);
            invalidName_18[524].ReadPointers(binaryReader, blamPointers);
            invalidName_18[525].ReadPointers(binaryReader, blamPointers);
            invalidName_18[526].ReadPointers(binaryReader, blamPointers);
            invalidName_18[527].ReadPointers(binaryReader, blamPointers);
            invalidName_18[528].ReadPointers(binaryReader, blamPointers);
            invalidName_18[529].ReadPointers(binaryReader, blamPointers);
            invalidName_18[530].ReadPointers(binaryReader, blamPointers);
            invalidName_18[531].ReadPointers(binaryReader, blamPointers);
            invalidName_18[532].ReadPointers(binaryReader, blamPointers);
            invalidName_18[533].ReadPointers(binaryReader, blamPointers);
            invalidName_18[534].ReadPointers(binaryReader, blamPointers);
            invalidName_18[535].ReadPointers(binaryReader, blamPointers);
            invalidName_18[536].ReadPointers(binaryReader, blamPointers);
            invalidName_18[537].ReadPointers(binaryReader, blamPointers);
            invalidName_18[538].ReadPointers(binaryReader, blamPointers);
            invalidName_18[539].ReadPointers(binaryReader, blamPointers);
            invalidName_18[540].ReadPointers(binaryReader, blamPointers);
            invalidName_18[541].ReadPointers(binaryReader, blamPointers);
            invalidName_18[542].ReadPointers(binaryReader, blamPointers);
            invalidName_18[543].ReadPointers(binaryReader, blamPointers);
            invalidName_18[544].ReadPointers(binaryReader, blamPointers);
            invalidName_18[545].ReadPointers(binaryReader, blamPointers);
            invalidName_18[546].ReadPointers(binaryReader, blamPointers);
            invalidName_18[547].ReadPointers(binaryReader, blamPointers);
            invalidName_18[548].ReadPointers(binaryReader, blamPointers);
            invalidName_18[549].ReadPointers(binaryReader, blamPointers);
            invalidName_18[550].ReadPointers(binaryReader, blamPointers);
            invalidName_18[551].ReadPointers(binaryReader, blamPointers);
            invalidName_18[552].ReadPointers(binaryReader, blamPointers);
            invalidName_18[553].ReadPointers(binaryReader, blamPointers);
            invalidName_18[554].ReadPointers(binaryReader, blamPointers);
            invalidName_18[555].ReadPointers(binaryReader, blamPointers);
            invalidName_18[556].ReadPointers(binaryReader, blamPointers);
            invalidName_18[557].ReadPointers(binaryReader, blamPointers);
            invalidName_18[558].ReadPointers(binaryReader, blamPointers);
            invalidName_18[559].ReadPointers(binaryReader, blamPointers);
            invalidName_19[0].ReadPointers(binaryReader, blamPointers);
            invalidName_19[1].ReadPointers(binaryReader, blamPointers);
            invalidName_19[2].ReadPointers(binaryReader, blamPointers);
            invalidName_19[3].ReadPointers(binaryReader, blamPointers);
            invalidName_19[4].ReadPointers(binaryReader, blamPointers);
            invalidName_19[5].ReadPointers(binaryReader, blamPointers);
            invalidName_19[6].ReadPointers(binaryReader, blamPointers);
            invalidName_19[7].ReadPointers(binaryReader, blamPointers);
            invalidName_19[8].ReadPointers(binaryReader, blamPointers);
            invalidName_19[9].ReadPointers(binaryReader, blamPointers);
            invalidName_19[10].ReadPointers(binaryReader, blamPointers);
            invalidName_19[11].ReadPointers(binaryReader, blamPointers);
            invalidName_19[12].ReadPointers(binaryReader, blamPointers);
            invalidName_19[13].ReadPointers(binaryReader, blamPointers);
            invalidName_19[14].ReadPointers(binaryReader, blamPointers);
            invalidName_19[15].ReadPointers(binaryReader, blamPointers);
            invalidName_19[16].ReadPointers(binaryReader, blamPointers);
            invalidName_19[17].ReadPointers(binaryReader, blamPointers);
            invalidName_19[18].ReadPointers(binaryReader, blamPointers);
            invalidName_19[19].ReadPointers(binaryReader, blamPointers);
            invalidName_19[20].ReadPointers(binaryReader, blamPointers);
            invalidName_19[21].ReadPointers(binaryReader, blamPointers);
            invalidName_19[22].ReadPointers(binaryReader, blamPointers);
            invalidName_19[23].ReadPointers(binaryReader, blamPointers);
            invalidName_19[24].ReadPointers(binaryReader, blamPointers);
            invalidName_19[25].ReadPointers(binaryReader, blamPointers);
            invalidName_19[26].ReadPointers(binaryReader, blamPointers);
            invalidName_19[27].ReadPointers(binaryReader, blamPointers);
            invalidName_19[28].ReadPointers(binaryReader, blamPointers);
            invalidName_19[29].ReadPointers(binaryReader, blamPointers);
            invalidName_19[30].ReadPointers(binaryReader, blamPointers);
            invalidName_19[31].ReadPointers(binaryReader, blamPointers);
            invalidName_19[32].ReadPointers(binaryReader, blamPointers);
            invalidName_19[33].ReadPointers(binaryReader, blamPointers);
            invalidName_19[34].ReadPointers(binaryReader, blamPointers);
            invalidName_19[35].ReadPointers(binaryReader, blamPointers);
            invalidName_19[36].ReadPointers(binaryReader, blamPointers);
            invalidName_19[37].ReadPointers(binaryReader, blamPointers);
            invalidName_19[38].ReadPointers(binaryReader, blamPointers);
            invalidName_19[39].ReadPointers(binaryReader, blamPointers);
            invalidName_19[40].ReadPointers(binaryReader, blamPointers);
            invalidName_19[41].ReadPointers(binaryReader, blamPointers);
            invalidName_19[42].ReadPointers(binaryReader, blamPointers);
            invalidName_19[43].ReadPointers(binaryReader, blamPointers);
            invalidName_19[44].ReadPointers(binaryReader, blamPointers);
            invalidName_19[45].ReadPointers(binaryReader, blamPointers);
            invalidName_19[46].ReadPointers(binaryReader, blamPointers);
            invalidName_19[47].ReadPointers(binaryReader, blamPointers);
            multiplayerConstants = ReadBlockArrayData<MultiplayerConstantsBlock>(binaryReader, blamPointers.Dequeue());
            stateResponses = ReadBlockArrayData<GameEngineStatusResponseBlock>(binaryReader, blamPointers.Dequeue());
        }
        public override int Write(BinaryWriter binaryWriter, int nextAddress)
        {
            base.Write(binaryWriter, nextAddress);
using(binaryWriter.BaseStream.Pin())
            {
                binaryWriter.Write(flag);
                binaryWriter.Write(ball);
                binaryWriter.Write(unit);
                binaryWriter.Write(flagShader);
                binaryWriter.Write(hillShader);
                binaryWriter.Write(head);
                binaryWriter.Write(juggernautPowerup);
                binaryWriter.Write(daBomb);
                binaryWriter.Write(invalidName_);
                binaryWriter.Write(invalidName_0);
                binaryWriter.Write(invalidName_1);
                binaryWriter.Write(invalidName_2);
                binaryWriter.Write(invalidName_3);
                nextAddress = Guerilla.WriteBlockArray<WeaponsBlock>(binaryWriter, weapons, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<VehiclesBlock>(binaryWriter, vehicles, nextAddress);
                arr.Write(binaryWriter);
                binaryWriter.Write(inGameText);
                nextAddress = Guerilla.WriteBlockArray<SoundsBlock>(binaryWriter, sounds, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<GameEngineGeneralEventBlock>(binaryWriter, generalEvents, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<GameEngineFlavorEventBlock>(binaryWriter, flavorEvents, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<GameEngineSlayerEventBlock>(binaryWriter, slayerEvents, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<GameEngineCtfEventBlock>(binaryWriter, ctfEvents, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<GameEngineOddballEventBlock>(binaryWriter, oddballEvents, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<GNullBlock>(binaryWriter, gNullBlock, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<GameEngineKingEventBlock>(binaryWriter, kingEvents, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<GNullBlock>(binaryWriter, gNullBlock0, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<GameEngineJuggernautEventBlock>(binaryWriter, juggernautEvents, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<GameEngineTerritoriesEventBlock>(binaryWriter, territoriesEvents, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<GameEngineAssaultEventBlock>(binaryWriter, invasionEvents, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<GNullBlock>(binaryWriter, gNullBlock1, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<GNullBlock>(binaryWriter, gNullBlock2, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<GNullBlock>(binaryWriter, gNullBlock3, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<GNullBlock>(binaryWriter, gNullBlock4, nextAddress);
                binaryWriter.Write(defaultItemCollection1);
                binaryWriter.Write(defaultItemCollection2);
                binaryWriter.Write(defaultFragGrenadeCount);
                binaryWriter.Write(defaultPlasmaGrenadeCount);
                binaryWriter.Write(invalidName_4, 0, 40);
                binaryWriter.Write(dynamicZoneUpperHeight);
                binaryWriter.Write(dynamicZoneLowerHeight);
                binaryWriter.Write(invalidName_5, 0, 40);
                binaryWriter.Write(enemyInnerRadius);
                binaryWriter.Write(enemyOuterRadius);
                binaryWriter.Write(enemyWeight);
                binaryWriter.Write(invalidName_6, 0, 16);
                binaryWriter.Write(friendInnerRadius);
                binaryWriter.Write(friendOuterRadius);
                binaryWriter.Write(friendWeight);
                binaryWriter.Write(invalidName_7, 0, 16);
                binaryWriter.Write(enemyVehicleInnerRadius);
                binaryWriter.Write(enemyVehicleOuterRadius);
                binaryWriter.Write(enemyVehicleWeight);
                binaryWriter.Write(invalidName_8, 0, 16);
                binaryWriter.Write(friendlyVehicleInnerRadius);
                binaryWriter.Write(friendlyVehicleOuterRadius);
                binaryWriter.Write(friendlyVehicleWeight);
                binaryWriter.Write(invalidName_9, 0, 16);
                binaryWriter.Write(emptyVehicleInnerRadius);
                binaryWriter.Write(emptyVehicleOuterRadius);
                binaryWriter.Write(emptyVehicleWeight);
                binaryWriter.Write(invalidName_10, 0, 16);
                binaryWriter.Write(oddballInclusionInnerRadius);
                binaryWriter.Write(oddballInclusionOuterRadius);
                binaryWriter.Write(oddballInclusionWeight);
                binaryWriter.Write(invalidName_11, 0, 16);
                binaryWriter.Write(oddballExclusionInnerRadius);
                binaryWriter.Write(oddballExclusionOuterRadius);
                binaryWriter.Write(oddballExclusionWeight);
                binaryWriter.Write(invalidName_12, 0, 16);
                binaryWriter.Write(hillInclusionInnerRadius);
                binaryWriter.Write(hillInclusionOuterRadius);
                binaryWriter.Write(hillInclusionWeight);
                binaryWriter.Write(invalidName_13, 0, 16);
                binaryWriter.Write(hillExclusionInnerRadius);
                binaryWriter.Write(hillExclusionOuterRadius);
                binaryWriter.Write(hillExclusionWeight);
                binaryWriter.Write(invalidName_14, 0, 16);
                binaryWriter.Write(lastRaceFlagInnerRadius);
                binaryWriter.Write(lastRaceFlagOuterRadius);
                binaryWriter.Write(lastRaceFlagWeight);
                binaryWriter.Write(invalidName_15, 0, 16);
                binaryWriter.Write(deadAllyInnerRadius);
                binaryWriter.Write(deadAllyOuterRadius);
                binaryWriter.Write(deadAllyWeight);
                binaryWriter.Write(invalidName_16, 0, 16);
                binaryWriter.Write(controlledTerritoryInnerRadius);
                binaryWriter.Write(controlledTerritoryOuterRadius);
                binaryWriter.Write(controlledTerritoryWeight);
                binaryWriter.Write(invalidName_17, 0, 16);
                binaryWriter.Write(invalidName_18, 0, 560);
                binaryWriter.Write(invalidName_19, 0, 48);
                nextAddress = Guerilla.WriteBlockArray<MultiplayerConstantsBlock>(binaryWriter, multiplayerConstants, nextAddress);
                nextAddress = Guerilla.WriteBlockArray<GameEngineStatusResponseBlock>(binaryWriter, stateResponses, nextAddress);
                binaryWriter.Write(scoreboardHudDefinition);
                binaryWriter.Write(scoreboardEmblemShader);
                binaryWriter.Write(scoreboardEmblemBitmap);
                binaryWriter.Write(scoreboardDeadEmblemShader);
                binaryWriter.Write(scoreboardDeadEmblemBitmap);
                return nextAddress;
            }
        }
    };
}
