//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moonfish.Guerilla.Tags
{
    using JetBrains.Annotations;
    using Moonfish.Tags;
    using Moonfish.Model;
    using Moonfish.Guerilla;
    using System.IO;
    using System.Collections.Generic;
    using System.Linq;
    
    [JetBrains.Annotations.UsedImplicitlyAttribute(ImplicitUseTargetFlags.WithMembers)]
    [TagBlockOriginalNameAttribute("character_physics_flying_struct_block")]
    public partial class CharacterPhysicsFlyingStructBlock : GuerillaBlock, IWriteDeferrable
    {
        public float BankAngle;
        public float BankApplyTime;
        public float BankDecayTime;
        public float PitchRatio;
        public float MaxVelocity;
        public float MaxSidestepVelocity;
        public float Acceleration;
        public float Deceleration;
        public float AngularVelocityMaximum;
        public float AngularAccelerationMaximum;
        public float CrouchVelocityModifier;
        public override int SerializedSize
        {
            get
            {
                return 44;
            }
        }
        public override int Alignment
        {
            get
            {
                return 4;
            }
        }
        public override System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> ReadFields(Moonfish.Guerilla.BlamBinaryReader binaryReader)
        {
            System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue = new System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer>(base.ReadFields(binaryReader));
            this.BankAngle = binaryReader.ReadSingle();
            this.BankApplyTime = binaryReader.ReadSingle();
            this.BankDecayTime = binaryReader.ReadSingle();
            this.PitchRatio = binaryReader.ReadSingle();
            this.MaxVelocity = binaryReader.ReadSingle();
            this.MaxSidestepVelocity = binaryReader.ReadSingle();
            this.Acceleration = binaryReader.ReadSingle();
            this.Deceleration = binaryReader.ReadSingle();
            this.AngularVelocityMaximum = binaryReader.ReadSingle();
            this.AngularAccelerationMaximum = binaryReader.ReadSingle();
            this.CrouchVelocityModifier = binaryReader.ReadSingle();
            return pointerQueue;
        }
        public override void ReadInstances(Moonfish.Guerilla.BlamBinaryReader binaryReader, System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue)
        {
            base.ReadInstances(binaryReader, pointerQueue);
        }
        public override void DeferReferences(Moonfish.Guerilla.LinearBinaryWriter writer)
        {
            base.DeferReferences(writer);
        }
        public override void Write(Moonfish.Guerilla.LinearBinaryWriter writer)
        {
            base.Write(writer);
            writer.Write(this.BankAngle);
            writer.Write(this.BankApplyTime);
            writer.Write(this.BankDecayTime);
            writer.Write(this.PitchRatio);
            writer.Write(this.MaxVelocity);
            writer.Write(this.MaxSidestepVelocity);
            writer.Write(this.Acceleration);
            writer.Write(this.Deceleration);
            writer.Write(this.AngularVelocityMaximum);
            writer.Write(this.AngularAccelerationMaximum);
            writer.Write(this.CrouchVelocityModifier);
        }
    }
}
