//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moonfish.Guerilla.Tags
{
    using JetBrains.Annotations;
    using Moonfish.Tags;
    using Moonfish.Model;
    using Moonfish.Guerilla;
    using System.IO;
    using System.Collections.Generic;
    using System.Linq;
    
    [JetBrains.Annotations.UsedImplicitlyAttribute(ImplicitUseTargetFlags.WithMembers)]
    [TagBlockOriginalNameAttribute("gear_block")]
    public partial class GearBlock : GuerillaBlock, IWriteDeferrable
    {
        public TorqueCurveStructBlock LoadedTorqueCurve = new TorqueCurveStructBlock();
        public TorqueCurveStructBlock CruisingTorqueCurve = new TorqueCurveStructBlock();
        public float MinTimeToUpshift;
        public float EngineUpshiftScale;
        public float GearRatio;
        public float MinTimeToDownshift;
        public float EngineDownshiftScale;
        public override int SerializedSize
        {
            get
            {
                return 68;
            }
        }
        public override int Alignment
        {
            get
            {
                return 4;
            }
        }
        public override System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> ReadFields(Moonfish.Guerilla.BlamBinaryReader binaryReader)
        {
            System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue = new System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer>(base.ReadFields(binaryReader));
            pointerQueue = new System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer>(pointerQueue.Concat(this.LoadedTorqueCurve.ReadFields(binaryReader)));
            pointerQueue = new System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer>(pointerQueue.Concat(this.CruisingTorqueCurve.ReadFields(binaryReader)));
            this.MinTimeToUpshift = binaryReader.ReadSingle();
            this.EngineUpshiftScale = binaryReader.ReadSingle();
            this.GearRatio = binaryReader.ReadSingle();
            this.MinTimeToDownshift = binaryReader.ReadSingle();
            this.EngineDownshiftScale = binaryReader.ReadSingle();
            return pointerQueue;
        }
        public override void ReadInstances(Moonfish.Guerilla.BlamBinaryReader binaryReader, System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue)
        {
            base.ReadInstances(binaryReader, pointerQueue);
            this.LoadedTorqueCurve.ReadInstances(binaryReader, pointerQueue);
            this.CruisingTorqueCurve.ReadInstances(binaryReader, pointerQueue);
        }
        public override void DeferReferences(Moonfish.Guerilla.LinearBinaryWriter writer)
        {
            base.DeferReferences(writer);
            this.LoadedTorqueCurve.DeferReferences(writer);
            this.CruisingTorqueCurve.DeferReferences(writer);
        }
        public override void Write(Moonfish.Guerilla.LinearBinaryWriter writer)
        {
            base.Write(writer);
            this.LoadedTorqueCurve.Write(writer);
            this.CruisingTorqueCurve.Write(writer);
            writer.Write(this.MinTimeToUpshift);
            writer.Write(this.EngineUpshiftScale);
            writer.Write(this.GearRatio);
            writer.Write(this.MinTimeToDownshift);
            writer.Write(this.EngineDownshiftScale);
        }
    }
}
