//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moonfish.Guerilla.Tags
{
    using JetBrains.Annotations;
    using Moonfish.Tags;
    using Moonfish.Model;
    using Moonfish.Guerilla;
    using System.IO;
    using System.Collections.Generic;
    using System.Linq;
    
    [JetBrains.Annotations.UsedImplicitlyAttribute(ImplicitUseTargetFlags.WithMembers)]
    [TagBlockOriginalNameAttribute("global_detail_object_cells_block")]
    public partial class GlobalDetailObjectCellsBlock : GuerillaBlock, IWriteDeferrable
    {
        public short FieldShortInteger;
        public short FieldShortInteger0;
        public short FieldShortInteger1;
        public short FieldShortInteger2;
        public int FieldLongInteger;
        public int FieldLongInteger0;
        public int FieldLongInteger1;
        private byte[] fieldpad = new byte[12];
        public override int SerializedSize
        {
            get
            {
                return 32;
            }
        }
        public override int Alignment
        {
            get
            {
                return 4;
            }
        }
        public override System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> ReadFields(Moonfish.Guerilla.BlamBinaryReader binaryReader)
        {
            System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue = new System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer>(base.ReadFields(binaryReader));
            this.FieldShortInteger = binaryReader.ReadInt16();
            this.FieldShortInteger0 = binaryReader.ReadInt16();
            this.FieldShortInteger1 = binaryReader.ReadInt16();
            this.FieldShortInteger2 = binaryReader.ReadInt16();
            this.FieldLongInteger = binaryReader.ReadInt32();
            this.FieldLongInteger0 = binaryReader.ReadInt32();
            this.FieldLongInteger1 = binaryReader.ReadInt32();
            this.fieldpad = binaryReader.ReadBytes(12);
            return pointerQueue;
        }
        public override void ReadInstances(Moonfish.Guerilla.BlamBinaryReader binaryReader, System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue)
        {
            base.ReadInstances(binaryReader, pointerQueue);
        }
        public override void DeferReferences(Moonfish.Guerilla.LinearBinaryWriter writer)
        {
            base.DeferReferences(writer);
        }
        public override void Write(Moonfish.Guerilla.LinearBinaryWriter writer)
        {
            base.Write(writer);
            writer.Write(this.FieldShortInteger);
            writer.Write(this.FieldShortInteger0);
            writer.Write(this.FieldShortInteger1);
            writer.Write(this.FieldShortInteger2);
            writer.Write(this.FieldLongInteger);
            writer.Write(this.FieldLongInteger0);
            writer.Write(this.FieldLongInteger1);
            writer.Write(this.fieldpad);
        }
    }
}
