//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moonfish.Guerilla.Tags
{
    using JetBrains.Annotations;
    using Moonfish.Tags;
    using Moonfish.Model;
    using Moonfish.Guerilla;
    using System.IO;
    using System.Collections.Generic;
    using System.Linq;
    
    [JetBrains.Annotations.UsedImplicitlyAttribute(ImplicitUseTargetFlags.WithMembers)]
    [TagBlockOriginalNameAttribute("model_variant_state_block")]
    public partial class ModelVariantStateBlock : GuerillaBlock, IWriteDeferrable
    {
        public Moonfish.Tags.StringIdent PermutationName;
        private byte[] fieldpad = new byte[1];
        public PropertyFlags ModelVariantStatePropertyFlags;
        public StateEnum State;
        [Moonfish.Tags.TagReferenceAttribute("effe")]
        public Moonfish.Tags.TagReference LoopingEffect;
        public Moonfish.Tags.StringIdent LoopingEffectMarkerName;
        public float InitialProbability;
        public override int SerializedSize
        {
            get
            {
                return 24;
            }
        }
        public override int Alignment
        {
            get
            {
                return 4;
            }
        }
        public override System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> ReadFields(Moonfish.Guerilla.BlamBinaryReader binaryReader)
        {
            System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue = new System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer>(base.ReadFields(binaryReader));
            this.PermutationName = binaryReader.ReadStringIdent();
            this.fieldpad = binaryReader.ReadBytes(1);
            this.ModelVariantStatePropertyFlags = ((PropertyFlags)(binaryReader.ReadByte()));
            this.State = ((StateEnum)(binaryReader.ReadInt16()));
            this.LoopingEffect = binaryReader.ReadTagReference();
            this.LoopingEffectMarkerName = binaryReader.ReadStringIdent();
            this.InitialProbability = binaryReader.ReadSingle();
            return pointerQueue;
        }
        public override void ReadInstances(Moonfish.Guerilla.BlamBinaryReader binaryReader, System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue)
        {
            base.ReadInstances(binaryReader, pointerQueue);
        }
        public override void DeferReferences(Moonfish.Guerilla.LinearBinaryWriter writer)
        {
            base.DeferReferences(writer);
        }
        public override void Write(Moonfish.Guerilla.LinearBinaryWriter writer)
        {
            base.Write(writer);
            writer.Write(this.PermutationName);
            writer.Write(this.fieldpad);
            writer.Write(((byte)(this.ModelVariantStatePropertyFlags)));
            writer.Write(((short)(this.State)));
            writer.Write(this.LoopingEffect);
            writer.Write(this.LoopingEffectMarkerName);
            writer.Write(this.InitialProbability);
        }
        [System.FlagsAttribute()]
        public enum PropertyFlags : byte
        {
            None = 0,
            Blurred = 1,
            HellaBlurred = 2,
            Shielded = 4,
        }
        public enum StateEnum : short
        {
            Default = 0,
            MinorDamage = 1,
            MediumDamage = 2,
            MajorDamage = 3,
            Destroyed = 4,
        }
    }
}
