//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moonfish.Guerilla.Tags
{
    using JetBrains.Annotations;
    using Moonfish.Tags;
    using Moonfish.Model;
    using System.IO;
    using System.Collections.Generic;
    using System.Linq;
    
    [JetBrains.Annotations.UsedImplicitlyAttribute(ImplicitUseTargetFlags.WithMembers)]
    [TagBlockOriginalNameAttribute("model_animation_runtime_data_struct_block")]
    public partial class ModelAnimationRuntimeDataStructBlock : GuerillaBlock, IWriteQueueable
    {
        public InheritedAnimationBlock[] InheritenceListBBAAAA = new InheritedAnimationBlock[0];
        public WeaponClassLookupBlock[] WeaponListBBAAAA = new WeaponClassLookupBlock[0];
        private byte[] fieldpad = new byte[32];
        private byte[] fieldpad0 = new byte[32];
        public override int SerializedSize
        {
            get
            {
                return 80;
            }
        }
        public override int Alignment
        {
            get
            {
                return 4;
            }
        }
        public override System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> ReadFields(Moonfish.Guerilla.BlamBinaryReader binaryReader)
        {
            System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue = new System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer>(base.ReadFields(binaryReader));
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(32));
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(8));
            this.fieldpad = binaryReader.ReadBytes(32);
            this.fieldpad0 = binaryReader.ReadBytes(32);
            return pointerQueue;
        }
        public override void ReadInstances(Moonfish.Guerilla.BlamBinaryReader binaryReader, System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue)
        {
            base.ReadInstances(binaryReader, pointerQueue);
            this.InheritenceListBBAAAA = base.ReadBlockArrayData<InheritedAnimationBlock>(binaryReader, pointerQueue.Dequeue());
            this.WeaponListBBAAAA = base.ReadBlockArrayData<WeaponClassLookupBlock>(binaryReader, pointerQueue.Dequeue());
        }
        public override void Defer(Moonfish.Guerilla.QueueableBlamBinaryWriter queueableBinaryWriter)
        {
            base.Defer(queueableBinaryWriter);
            queueableBinaryWriter.Defer(this.InheritenceListBBAAAA);
            queueableBinaryWriter.Defer(this.WeaponListBBAAAA);
        }
        public override void Write(Moonfish.Guerilla.QueueableBlamBinaryWriter queueableBinaryWriter)
        {
            base.Write(queueableBinaryWriter);
            queueableBinaryWriter.WritePointer(this.InheritenceListBBAAAA);
            queueableBinaryWriter.WritePointer(this.WeaponListBBAAAA);
            queueableBinaryWriter.Write(this.fieldpad);
            queueableBinaryWriter.Write(this.fieldpad0);
        }
    }
}
