//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moonfish.Guerilla.Tags
{
    using Moonfish.Tags;
    using Moonfish.Model;
    using System.IO;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class MultiplayerRuntimeBlock : GuerillaBlock, IWriteQueueable
    {
        [Moonfish.Tags.TagReferenceAttribute("item")]
        public Moonfish.Tags.TagReference Flag;
        [Moonfish.Tags.TagReferenceAttribute("item")]
        public Moonfish.Tags.TagReference Ball;
        [Moonfish.Tags.TagReferenceAttribute("unit")]
        public Moonfish.Tags.TagReference Unit;
        [Moonfish.Tags.TagReferenceAttribute("shad")]
        public Moonfish.Tags.TagReference FlagShader;
        [Moonfish.Tags.TagReferenceAttribute("shad")]
        public Moonfish.Tags.TagReference HillShader;
        [Moonfish.Tags.TagReferenceAttribute("item")]
        public Moonfish.Tags.TagReference Head;
        [Moonfish.Tags.TagReferenceAttribute("item")]
        public Moonfish.Tags.TagReference JuggernautPowerup;
        [Moonfish.Tags.TagReferenceAttribute("item")]
        public Moonfish.Tags.TagReference DaBomb;
        [Moonfish.Tags.TagReferenceAttribute("null")]
        public Moonfish.Tags.TagReference TagReference;
        [Moonfish.Tags.TagReferenceAttribute("null")]
        public Moonfish.Tags.TagReference TagReference0;
        [Moonfish.Tags.TagReferenceAttribute("null")]
        public Moonfish.Tags.TagReference TagReference1;
        [Moonfish.Tags.TagReferenceAttribute("null")]
        public Moonfish.Tags.TagReference TagReference2;
        [Moonfish.Tags.TagReferenceAttribute("null")]
        public Moonfish.Tags.TagReference TagReference3;
        public WeaponsBlock[] Weapons = new WeaponsBlock[0];
        public VehiclesBlock[] Vehicles = new VehiclesBlock[0];
        public GrenadeAndPowerupStructBlock Arr = new GrenadeAndPowerupStructBlock();
        [Moonfish.Tags.TagReferenceAttribute("unic")]
        public Moonfish.Tags.TagReference InGameText;
        public SoundsBlock[] Sounds = new SoundsBlock[0];
        public GameEngineGeneralEventBlock[] GeneralEvents = new GameEngineGeneralEventBlock[0];
        public GameEngineFlavorEventBlock[] FlavorEvents = new GameEngineFlavorEventBlock[0];
        public GameEngineSlayerEventBlock[] SlayerEvents = new GameEngineSlayerEventBlock[0];
        public GameEngineCtfEventBlock[] CtfEvents = new GameEngineCtfEventBlock[0];
        public GameEngineOddballEventBlock[] OddballEvents = new GameEngineOddballEventBlock[0];
        public GNullBlock[] GNullBlock = new GNullBlock[0];
        public GameEngineKingEventBlock[] KingEvents = new GameEngineKingEventBlock[0];
        public GNullBlock[] GNullBlock0 = new GNullBlock[0];
        public GameEngineJuggernautEventBlock[] JuggernautEvents = new GameEngineJuggernautEventBlock[0];
        public GameEngineTerritoriesEventBlock[] TerritoriesEvents = new GameEngineTerritoriesEventBlock[0];
        public GameEngineAssaultEventBlock[] InvasionEvents = new GameEngineAssaultEventBlock[0];
        public GNullBlock[] GNullBlock1 = new GNullBlock[0];
        public GNullBlock[] GNullBlock2 = new GNullBlock[0];
        public GNullBlock[] GNullBlock3 = new GNullBlock[0];
        public GNullBlock[] GNullBlock4 = new GNullBlock[0];
        [Moonfish.Tags.TagReferenceAttribute("itmc")]
        public Moonfish.Tags.TagReference DefaultItemCollection1;
        [Moonfish.Tags.TagReferenceAttribute("itmc")]
        public Moonfish.Tags.TagReference DefaultItemCollection2;
        public int DefaultFragGrenadeCount;
        public int DefaultPlasmaGrenadeCount;
        private byte[] fieldpad = new byte[40];
        public float DynamicZoneUpperHeight;
        public float DynamicZoneLowerHeight;
        private byte[] fieldpad0 = new byte[40];
        public float EnemyInnerRadius;
        public float EnemyOuterRadius;
        public float EnemyWeight;
        private byte[] fieldpad1 = new byte[16];
        public float FriendInnerRadius;
        public float FriendOuterRadius;
        public float FriendWeight;
        private byte[] fieldpad2 = new byte[16];
        public float EnemyVehicleInnerRadius;
        public float EnemyVehicleOuterRadius;
        public float EnemyVehicleWeight;
        private byte[] fieldpad3 = new byte[16];
        public float FriendlyVehicleInnerRadius;
        public float FriendlyVehicleOuterRadius;
        public float FriendlyVehicleWeight;
        private byte[] fieldpad4 = new byte[16];
        public float EmptyVehicleInnerRadius;
        public float EmptyVehicleOuterRadius;
        public float EmptyVehicleWeight;
        private byte[] fieldpad5 = new byte[16];
        public float OddballInclusionInnerRadius;
        public float OddballInclusionOuterRadius;
        public float OddballInclusionWeight;
        private byte[] fieldpad6 = new byte[16];
        public float OddballExclusionInnerRadius;
        public float OddballExclusionOuterRadius;
        public float OddballExclusionWeight;
        private byte[] fieldpad7 = new byte[16];
        public float HillInclusionInnerRadius;
        public float HillInclusionOuterRadius;
        public float HillInclusionWeight;
        private byte[] fieldpad8 = new byte[16];
        public float HillExclusionInnerRadius;
        public float HillExclusionOuterRadius;
        public float HillExclusionWeight;
        private byte[] fieldpad9 = new byte[16];
        public float LastRaceFlagInnerRadius;
        public float LastRaceFlagOuterRadius;
        public float LastRaceFlagWeight;
        private byte[] fieldpad10 = new byte[16];
        public float DeadAllyInnerRadius;
        public float DeadAllyOuterRadius;
        public float DeadAllyWeight;
        private byte[] fieldpad11 = new byte[16];
        public float ControlledTerritoryInnerRadius;
        public float ControlledTerritoryOuterRadius;
        public float ControlledTerritoryWeight;
        private byte[] fieldpad12 = new byte[16];
        private byte[] fieldpad13 = new byte[560];
        private byte[] fieldpad14 = new byte[48];
        public MultiplayerConstantsBlock[] MultiplayerConstants = new MultiplayerConstantsBlock[0];
        public GameEngineStatusResponseBlock[] StateResponses = new GameEngineStatusResponseBlock[0];
        [Moonfish.Tags.TagReferenceAttribute("nhdt")]
        public Moonfish.Tags.TagReference ScoreboardHudDefinition;
        [Moonfish.Tags.TagReferenceAttribute("shad")]
        public Moonfish.Tags.TagReference ScoreboardEmblemShader;
        [Moonfish.Tags.TagReferenceAttribute("bitm")]
        public Moonfish.Tags.TagReference ScoreboardEmblemBitmap;
        [Moonfish.Tags.TagReferenceAttribute("shad")]
        public Moonfish.Tags.TagReference ScoreboardDeadEmblemShader;
        [Moonfish.Tags.TagReferenceAttribute("bitm")]
        public Moonfish.Tags.TagReference ScoreboardDeadEmblemBitmap;
        public override int SerializedSize
        {
            get
            {
                return 1384;
            }
        }
        public override int Alignment
        {
            get
            {
                return 4;
            }
        }
        public override System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> ReadFields(System.IO.BinaryReader binaryReader)
        {
            System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue = new System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer>(base.ReadFields(binaryReader));
            this.Flag = binaryReader.ReadTagReference();
            this.Ball = binaryReader.ReadTagReference();
            this.Unit = binaryReader.ReadTagReference();
            this.FlagShader = binaryReader.ReadTagReference();
            this.HillShader = binaryReader.ReadTagReference();
            this.Head = binaryReader.ReadTagReference();
            this.JuggernautPowerup = binaryReader.ReadTagReference();
            this.DaBomb = binaryReader.ReadTagReference();
            this.TagReference = binaryReader.ReadTagReference();
            this.TagReference0 = binaryReader.ReadTagReference();
            this.TagReference1 = binaryReader.ReadTagReference();
            this.TagReference2 = binaryReader.ReadTagReference();
            this.TagReference3 = binaryReader.ReadTagReference();
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(8));
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(8));
            pointerQueue = new System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer>(pointerQueue.Concat(this.Arr.ReadFields(binaryReader)));
            this.InGameText = binaryReader.ReadTagReference();
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(8));
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(168));
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(168));
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(168));
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(168));
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(168));
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(0));
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(168));
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(0));
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(168));
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(168));
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(168));
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(0));
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(0));
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(0));
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(0));
            this.DefaultItemCollection1 = binaryReader.ReadTagReference();
            this.DefaultItemCollection2 = binaryReader.ReadTagReference();
            this.DefaultFragGrenadeCount = binaryReader.ReadInt32();
            this.DefaultPlasmaGrenadeCount = binaryReader.ReadInt32();
            this.fieldpad = binaryReader.ReadBytes(40);
            this.DynamicZoneUpperHeight = binaryReader.ReadSingle();
            this.DynamicZoneLowerHeight = binaryReader.ReadSingle();
            this.fieldpad0 = binaryReader.ReadBytes(40);
            this.EnemyInnerRadius = binaryReader.ReadSingle();
            this.EnemyOuterRadius = binaryReader.ReadSingle();
            this.EnemyWeight = binaryReader.ReadSingle();
            this.fieldpad1 = binaryReader.ReadBytes(16);
            this.FriendInnerRadius = binaryReader.ReadSingle();
            this.FriendOuterRadius = binaryReader.ReadSingle();
            this.FriendWeight = binaryReader.ReadSingle();
            this.fieldpad2 = binaryReader.ReadBytes(16);
            this.EnemyVehicleInnerRadius = binaryReader.ReadSingle();
            this.EnemyVehicleOuterRadius = binaryReader.ReadSingle();
            this.EnemyVehicleWeight = binaryReader.ReadSingle();
            this.fieldpad3 = binaryReader.ReadBytes(16);
            this.FriendlyVehicleInnerRadius = binaryReader.ReadSingle();
            this.FriendlyVehicleOuterRadius = binaryReader.ReadSingle();
            this.FriendlyVehicleWeight = binaryReader.ReadSingle();
            this.fieldpad4 = binaryReader.ReadBytes(16);
            this.EmptyVehicleInnerRadius = binaryReader.ReadSingle();
            this.EmptyVehicleOuterRadius = binaryReader.ReadSingle();
            this.EmptyVehicleWeight = binaryReader.ReadSingle();
            this.fieldpad5 = binaryReader.ReadBytes(16);
            this.OddballInclusionInnerRadius = binaryReader.ReadSingle();
            this.OddballInclusionOuterRadius = binaryReader.ReadSingle();
            this.OddballInclusionWeight = binaryReader.ReadSingle();
            this.fieldpad6 = binaryReader.ReadBytes(16);
            this.OddballExclusionInnerRadius = binaryReader.ReadSingle();
            this.OddballExclusionOuterRadius = binaryReader.ReadSingle();
            this.OddballExclusionWeight = binaryReader.ReadSingle();
            this.fieldpad7 = binaryReader.ReadBytes(16);
            this.HillInclusionInnerRadius = binaryReader.ReadSingle();
            this.HillInclusionOuterRadius = binaryReader.ReadSingle();
            this.HillInclusionWeight = binaryReader.ReadSingle();
            this.fieldpad8 = binaryReader.ReadBytes(16);
            this.HillExclusionInnerRadius = binaryReader.ReadSingle();
            this.HillExclusionOuterRadius = binaryReader.ReadSingle();
            this.HillExclusionWeight = binaryReader.ReadSingle();
            this.fieldpad9 = binaryReader.ReadBytes(16);
            this.LastRaceFlagInnerRadius = binaryReader.ReadSingle();
            this.LastRaceFlagOuterRadius = binaryReader.ReadSingle();
            this.LastRaceFlagWeight = binaryReader.ReadSingle();
            this.fieldpad10 = binaryReader.ReadBytes(16);
            this.DeadAllyInnerRadius = binaryReader.ReadSingle();
            this.DeadAllyOuterRadius = binaryReader.ReadSingle();
            this.DeadAllyWeight = binaryReader.ReadSingle();
            this.fieldpad11 = binaryReader.ReadBytes(16);
            this.ControlledTerritoryInnerRadius = binaryReader.ReadSingle();
            this.ControlledTerritoryOuterRadius = binaryReader.ReadSingle();
            this.ControlledTerritoryWeight = binaryReader.ReadSingle();
            this.fieldpad12 = binaryReader.ReadBytes(16);
            this.fieldpad13 = binaryReader.ReadBytes(560);
            this.fieldpad14 = binaryReader.ReadBytes(48);
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(352));
            pointerQueue.Enqueue(binaryReader.ReadBlamPointer(28));
            this.ScoreboardHudDefinition = binaryReader.ReadTagReference();
            this.ScoreboardEmblemShader = binaryReader.ReadTagReference();
            this.ScoreboardEmblemBitmap = binaryReader.ReadTagReference();
            this.ScoreboardDeadEmblemShader = binaryReader.ReadTagReference();
            this.ScoreboardDeadEmblemBitmap = binaryReader.ReadTagReference();
            return pointerQueue;
        }
        public override void ReadInstances(System.IO.BinaryReader binaryReader, System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue)
        {
            base.ReadInstances(binaryReader, pointerQueue);
            this.Weapons = base.ReadBlockArrayData<WeaponsBlock>(binaryReader, pointerQueue.Dequeue());
            this.Vehicles = base.ReadBlockArrayData<VehiclesBlock>(binaryReader, pointerQueue.Dequeue());
            this.Arr.ReadInstances(binaryReader, pointerQueue);
            this.Sounds = base.ReadBlockArrayData<SoundsBlock>(binaryReader, pointerQueue.Dequeue());
            this.GeneralEvents = base.ReadBlockArrayData<GameEngineGeneralEventBlock>(binaryReader, pointerQueue.Dequeue());
            this.FlavorEvents = base.ReadBlockArrayData<GameEngineFlavorEventBlock>(binaryReader, pointerQueue.Dequeue());
            this.SlayerEvents = base.ReadBlockArrayData<GameEngineSlayerEventBlock>(binaryReader, pointerQueue.Dequeue());
            this.CtfEvents = base.ReadBlockArrayData<GameEngineCtfEventBlock>(binaryReader, pointerQueue.Dequeue());
            this.OddballEvents = base.ReadBlockArrayData<GameEngineOddballEventBlock>(binaryReader, pointerQueue.Dequeue());
            this.GNullBlock = base.ReadBlockArrayData<GNullBlock>(binaryReader, pointerQueue.Dequeue());
            this.KingEvents = base.ReadBlockArrayData<GameEngineKingEventBlock>(binaryReader, pointerQueue.Dequeue());
            this.GNullBlock0 = base.ReadBlockArrayData<GNullBlock>(binaryReader, pointerQueue.Dequeue());
            this.JuggernautEvents = base.ReadBlockArrayData<GameEngineJuggernautEventBlock>(binaryReader, pointerQueue.Dequeue());
            this.TerritoriesEvents = base.ReadBlockArrayData<GameEngineTerritoriesEventBlock>(binaryReader, pointerQueue.Dequeue());
            this.InvasionEvents = base.ReadBlockArrayData<GameEngineAssaultEventBlock>(binaryReader, pointerQueue.Dequeue());
            this.GNullBlock1 = base.ReadBlockArrayData<GNullBlock>(binaryReader, pointerQueue.Dequeue());
            this.GNullBlock2 = base.ReadBlockArrayData<GNullBlock>(binaryReader, pointerQueue.Dequeue());
            this.GNullBlock3 = base.ReadBlockArrayData<GNullBlock>(binaryReader, pointerQueue.Dequeue());
            this.GNullBlock4 = base.ReadBlockArrayData<GNullBlock>(binaryReader, pointerQueue.Dequeue());
            this.MultiplayerConstants = base.ReadBlockArrayData<MultiplayerConstantsBlock>(binaryReader, pointerQueue.Dequeue());
            this.StateResponses = base.ReadBlockArrayData<GameEngineStatusResponseBlock>(binaryReader, pointerQueue.Dequeue());
        }
        public override void QueueWrites(Moonfish.Guerilla.QueueableBlamBinaryWriter queueableBlamBinaryWriter)
        {
            base.QueueWrites(queueableBlamBinaryWriter);
            queueableBlamBinaryWriter.QueueWrite(this.Weapons);
            queueableBlamBinaryWriter.QueueWrite(this.Vehicles);
            this.Arr.QueueWrites(queueableBlamBinaryWriter);
            queueableBlamBinaryWriter.QueueWrite(this.Sounds);
            queueableBlamBinaryWriter.QueueWrite(this.GeneralEvents);
            queueableBlamBinaryWriter.QueueWrite(this.FlavorEvents);
            queueableBlamBinaryWriter.QueueWrite(this.SlayerEvents);
            queueableBlamBinaryWriter.QueueWrite(this.CtfEvents);
            queueableBlamBinaryWriter.QueueWrite(this.OddballEvents);
            queueableBlamBinaryWriter.QueueWrite(this.GNullBlock);
            queueableBlamBinaryWriter.QueueWrite(this.KingEvents);
            queueableBlamBinaryWriter.QueueWrite(this.GNullBlock0);
            queueableBlamBinaryWriter.QueueWrite(this.JuggernautEvents);
            queueableBlamBinaryWriter.QueueWrite(this.TerritoriesEvents);
            queueableBlamBinaryWriter.QueueWrite(this.InvasionEvents);
            queueableBlamBinaryWriter.QueueWrite(this.GNullBlock1);
            queueableBlamBinaryWriter.QueueWrite(this.GNullBlock2);
            queueableBlamBinaryWriter.QueueWrite(this.GNullBlock3);
            queueableBlamBinaryWriter.QueueWrite(this.GNullBlock4);
            queueableBlamBinaryWriter.QueueWrite(this.MultiplayerConstants);
            queueableBlamBinaryWriter.QueueWrite(this.StateResponses);
        }
        public override void Write_(Moonfish.Guerilla.QueueableBlamBinaryWriter queueableBlamBinaryWriter)
        {
            base.Write_(queueableBlamBinaryWriter);
            queueableBlamBinaryWriter.Write(this.Flag);
            queueableBlamBinaryWriter.Write(this.Ball);
            queueableBlamBinaryWriter.Write(this.Unit);
            queueableBlamBinaryWriter.Write(this.FlagShader);
            queueableBlamBinaryWriter.Write(this.HillShader);
            queueableBlamBinaryWriter.Write(this.Head);
            queueableBlamBinaryWriter.Write(this.JuggernautPowerup);
            queueableBlamBinaryWriter.Write(this.DaBomb);
            queueableBlamBinaryWriter.Write(this.TagReference);
            queueableBlamBinaryWriter.Write(this.TagReference0);
            queueableBlamBinaryWriter.Write(this.TagReference1);
            queueableBlamBinaryWriter.Write(this.TagReference2);
            queueableBlamBinaryWriter.Write(this.TagReference3);
            queueableBlamBinaryWriter.WritePointer(this.Weapons);
            queueableBlamBinaryWriter.WritePointer(this.Vehicles);
            this.Arr.Write_(queueableBlamBinaryWriter);
            queueableBlamBinaryWriter.Write(this.InGameText);
            queueableBlamBinaryWriter.WritePointer(this.Sounds);
            queueableBlamBinaryWriter.WritePointer(this.GeneralEvents);
            queueableBlamBinaryWriter.WritePointer(this.FlavorEvents);
            queueableBlamBinaryWriter.WritePointer(this.SlayerEvents);
            queueableBlamBinaryWriter.WritePointer(this.CtfEvents);
            queueableBlamBinaryWriter.WritePointer(this.OddballEvents);
            queueableBlamBinaryWriter.WritePointer(this.GNullBlock);
            queueableBlamBinaryWriter.WritePointer(this.KingEvents);
            queueableBlamBinaryWriter.WritePointer(this.GNullBlock0);
            queueableBlamBinaryWriter.WritePointer(this.JuggernautEvents);
            queueableBlamBinaryWriter.WritePointer(this.TerritoriesEvents);
            queueableBlamBinaryWriter.WritePointer(this.InvasionEvents);
            queueableBlamBinaryWriter.WritePointer(this.GNullBlock1);
            queueableBlamBinaryWriter.WritePointer(this.GNullBlock2);
            queueableBlamBinaryWriter.WritePointer(this.GNullBlock3);
            queueableBlamBinaryWriter.WritePointer(this.GNullBlock4);
            queueableBlamBinaryWriter.Write(this.DefaultItemCollection1);
            queueableBlamBinaryWriter.Write(this.DefaultItemCollection2);
            queueableBlamBinaryWriter.Write(this.DefaultFragGrenadeCount);
            queueableBlamBinaryWriter.Write(this.DefaultPlasmaGrenadeCount);
            queueableBlamBinaryWriter.Write(this.fieldpad);
            queueableBlamBinaryWriter.Write(this.DynamicZoneUpperHeight);
            queueableBlamBinaryWriter.Write(this.DynamicZoneLowerHeight);
            queueableBlamBinaryWriter.Write(this.fieldpad0);
            queueableBlamBinaryWriter.Write(this.EnemyInnerRadius);
            queueableBlamBinaryWriter.Write(this.EnemyOuterRadius);
            queueableBlamBinaryWriter.Write(this.EnemyWeight);
            queueableBlamBinaryWriter.Write(this.fieldpad1);
            queueableBlamBinaryWriter.Write(this.FriendInnerRadius);
            queueableBlamBinaryWriter.Write(this.FriendOuterRadius);
            queueableBlamBinaryWriter.Write(this.FriendWeight);
            queueableBlamBinaryWriter.Write(this.fieldpad2);
            queueableBlamBinaryWriter.Write(this.EnemyVehicleInnerRadius);
            queueableBlamBinaryWriter.Write(this.EnemyVehicleOuterRadius);
            queueableBlamBinaryWriter.Write(this.EnemyVehicleWeight);
            queueableBlamBinaryWriter.Write(this.fieldpad3);
            queueableBlamBinaryWriter.Write(this.FriendlyVehicleInnerRadius);
            queueableBlamBinaryWriter.Write(this.FriendlyVehicleOuterRadius);
            queueableBlamBinaryWriter.Write(this.FriendlyVehicleWeight);
            queueableBlamBinaryWriter.Write(this.fieldpad4);
            queueableBlamBinaryWriter.Write(this.EmptyVehicleInnerRadius);
            queueableBlamBinaryWriter.Write(this.EmptyVehicleOuterRadius);
            queueableBlamBinaryWriter.Write(this.EmptyVehicleWeight);
            queueableBlamBinaryWriter.Write(this.fieldpad5);
            queueableBlamBinaryWriter.Write(this.OddballInclusionInnerRadius);
            queueableBlamBinaryWriter.Write(this.OddballInclusionOuterRadius);
            queueableBlamBinaryWriter.Write(this.OddballInclusionWeight);
            queueableBlamBinaryWriter.Write(this.fieldpad6);
            queueableBlamBinaryWriter.Write(this.OddballExclusionInnerRadius);
            queueableBlamBinaryWriter.Write(this.OddballExclusionOuterRadius);
            queueableBlamBinaryWriter.Write(this.OddballExclusionWeight);
            queueableBlamBinaryWriter.Write(this.fieldpad7);
            queueableBlamBinaryWriter.Write(this.HillInclusionInnerRadius);
            queueableBlamBinaryWriter.Write(this.HillInclusionOuterRadius);
            queueableBlamBinaryWriter.Write(this.HillInclusionWeight);
            queueableBlamBinaryWriter.Write(this.fieldpad8);
            queueableBlamBinaryWriter.Write(this.HillExclusionInnerRadius);
            queueableBlamBinaryWriter.Write(this.HillExclusionOuterRadius);
            queueableBlamBinaryWriter.Write(this.HillExclusionWeight);
            queueableBlamBinaryWriter.Write(this.fieldpad9);
            queueableBlamBinaryWriter.Write(this.LastRaceFlagInnerRadius);
            queueableBlamBinaryWriter.Write(this.LastRaceFlagOuterRadius);
            queueableBlamBinaryWriter.Write(this.LastRaceFlagWeight);
            queueableBlamBinaryWriter.Write(this.fieldpad10);
            queueableBlamBinaryWriter.Write(this.DeadAllyInnerRadius);
            queueableBlamBinaryWriter.Write(this.DeadAllyOuterRadius);
            queueableBlamBinaryWriter.Write(this.DeadAllyWeight);
            queueableBlamBinaryWriter.Write(this.fieldpad11);
            queueableBlamBinaryWriter.Write(this.ControlledTerritoryInnerRadius);
            queueableBlamBinaryWriter.Write(this.ControlledTerritoryOuterRadius);
            queueableBlamBinaryWriter.Write(this.ControlledTerritoryWeight);
            queueableBlamBinaryWriter.Write(this.fieldpad12);
            queueableBlamBinaryWriter.Write(this.fieldpad13);
            queueableBlamBinaryWriter.Write(this.fieldpad14);
            queueableBlamBinaryWriter.WritePointer(this.MultiplayerConstants);
            queueableBlamBinaryWriter.WritePointer(this.StateResponses);
            queueableBlamBinaryWriter.Write(this.ScoreboardHudDefinition);
            queueableBlamBinaryWriter.Write(this.ScoreboardEmblemShader);
            queueableBlamBinaryWriter.Write(this.ScoreboardEmblemBitmap);
            queueableBlamBinaryWriter.Write(this.ScoreboardDeadEmblemShader);
            queueableBlamBinaryWriter.Write(this.ScoreboardDeadEmblemBitmap);
        }
    }
}
