//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moonfish.Guerilla.Tags
{
    using JetBrains.Annotations;
    using Moonfish.Tags;
    using Moonfish.Model;
    using System.IO;
    using System.Collections.Generic;
    using System.Linq;
    
    [JetBrains.Annotations.UsedImplicitlyAttribute(ImplicitUseTargetFlags.WithMembers)]
    [TagBlockOriginalNameAttribute("ragdoll_constraints_block")]
    public partial class RagdollConstraintsBlock : GuerillaBlock, IWriteQueueable
    {
        public ConstraintBodiesStructBlock ConstraintBodies = new ConstraintBodiesStructBlock();
        private byte[] fieldpad = new byte[4];
        public float MinTwist;
        public float MaxTwist;
        public float MinCone;
        public float MaxCone;
        public float MinPlane;
        public float MaxPlane;
        public float MaxFricitonTorque;
        public override int SerializedSize
        {
            get
            {
                return 148;
            }
        }
        public override int Alignment
        {
            get
            {
                return 4;
            }
        }
        public override System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> ReadFields(Moonfish.Guerilla.BlamBinaryReader binaryReader)
        {
            System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue = new System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer>(base.ReadFields(binaryReader));
            pointerQueue = new System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer>(pointerQueue.Concat(this.ConstraintBodies.ReadFields(binaryReader)));
            this.fieldpad = binaryReader.ReadBytes(4);
            this.MinTwist = binaryReader.ReadSingle();
            this.MaxTwist = binaryReader.ReadSingle();
            this.MinCone = binaryReader.ReadSingle();
            this.MaxCone = binaryReader.ReadSingle();
            this.MinPlane = binaryReader.ReadSingle();
            this.MaxPlane = binaryReader.ReadSingle();
            this.MaxFricitonTorque = binaryReader.ReadSingle();
            return pointerQueue;
        }
        public override void ReadInstances(Moonfish.Guerilla.BlamBinaryReader binaryReader, System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue)
        {
            base.ReadInstances(binaryReader, pointerQueue);
            this.ConstraintBodies.ReadInstances(binaryReader, pointerQueue);
        }
        public override void Defer(Moonfish.Guerilla.QueueableBlamBinaryWriter queueableBinaryWriter)
        {
            base.Defer(queueableBinaryWriter);
            this.ConstraintBodies.Defer(queueableBinaryWriter);
        }
        public override void Write(Moonfish.Guerilla.QueueableBlamBinaryWriter queueableBinaryWriter)
        {
            base.Write(queueableBinaryWriter);
            this.ConstraintBodies.Write(queueableBinaryWriter);
            queueableBinaryWriter.Write(this.fieldpad);
            queueableBinaryWriter.Write(this.MinTwist);
            queueableBinaryWriter.Write(this.MaxTwist);
            queueableBinaryWriter.Write(this.MinCone);
            queueableBinaryWriter.Write(this.MaxCone);
            queueableBinaryWriter.Write(this.MinPlane);
            queueableBinaryWriter.Write(this.MaxPlane);
            queueableBinaryWriter.Write(this.MaxFricitonTorque);
        }
    }
}
