//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moonfish.Guerilla.Tags
{
    using JetBrains.Annotations;
    using Moonfish.Tags;
    using Moonfish.Model;
    using Moonfish.Guerilla;
    using System.IO;
    using System.Collections.Generic;
    using System.Linq;
    
    [JetBrains.Annotations.UsedImplicitlyAttribute(ImplicitUseTargetFlags.WithMembers)]
    [TagBlockOriginalNameAttribute("shader_texture_state_filter_state_block")]
    public partial class ShaderTextureStateFilterStateBlock : GuerillaBlock, IWriteDeferrable
    {
        public MagFilterEnum MagFilter;
        public MinFilterEnum MinFilter;
        public MipFilterEnum MipFilter;
        private byte[] fieldpad = new byte[2];
        public float MipmapBias;
        public short MaxMipmapIndex;
        public AnisotropyEnum Anisotropy;
        public override int SerializedSize
        {
            get
            {
                return 16;
            }
        }
        public override int Alignment
        {
            get
            {
                return 4;
            }
        }
        public override System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> ReadFields(Moonfish.Guerilla.BlamBinaryReader binaryReader)
        {
            System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue = new System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer>(base.ReadFields(binaryReader));
            this.MagFilter = ((MagFilterEnum)(binaryReader.ReadInt16()));
            this.MinFilter = ((MinFilterEnum)(binaryReader.ReadInt16()));
            this.MipFilter = ((MipFilterEnum)(binaryReader.ReadInt16()));
            this.fieldpad = binaryReader.ReadBytes(2);
            this.MipmapBias = binaryReader.ReadSingle();
            this.MaxMipmapIndex = binaryReader.ReadInt16();
            this.Anisotropy = ((AnisotropyEnum)(binaryReader.ReadInt16()));
            return pointerQueue;
        }
        public override void ReadInstances(Moonfish.Guerilla.BlamBinaryReader binaryReader, System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue)
        {
            base.ReadInstances(binaryReader, pointerQueue);
        }
        public override void DeferReferences(Moonfish.Guerilla.LinearBinaryWriter writer)
        {
            base.DeferReferences(writer);
        }
        public override void Write(Moonfish.Guerilla.LinearBinaryWriter writer)
        {
            base.Write(writer);
            writer.Write(((short)(this.MagFilter)));
            writer.Write(((short)(this.MinFilter)));
            writer.Write(((short)(this.MipFilter)));
            writer.Write(this.fieldpad);
            writer.Write(this.MipmapBias);
            writer.Write(this.MaxMipmapIndex);
            writer.Write(((short)(this.Anisotropy)));
        }
        public enum MagFilterEnum : short
        {
            None = 0,
            PointSampled = 1,
            Linear = 2,
            Anisotropic = 3,
            Quincunx = 4,
            GaussianCubic = 5,
        }
        public enum MinFilterEnum : short
        {
            None = 0,
            PointSampled = 1,
            Linear = 2,
            Anisotropic = 3,
            Quincunx = 4,
            GaussianCubic = 5,
        }
        public enum MipFilterEnum : short
        {
            None = 0,
            PointSampled = 1,
            Linear = 2,
            Anisotropic = 3,
            Quincunx = 4,
            GaussianCubic = 5,
        }
        public enum AnisotropyEnum : short
        {
            NonAnisotropic = 0,
            _2tap = 1,
            _3tap = 2,
            _4tap = 3,
        }
    }
}
