//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moonfish.Guerilla.Tags
{
    using JetBrains.Annotations;
    using Moonfish.Tags;
    using Moonfish.Model;
    using Moonfish.Guerilla;
    using System.IO;
    using System.Collections.Generic;
    using System.Linq;
    
    [JetBrains.Annotations.UsedImplicitlyAttribute(ImplicitUseTargetFlags.WithMembers)]
    [TagBlockOriginalNameAttribute("s_text_value_pair_reference_block_UNUSED")]
    public partial class STextValuePairReferenceBlockUNUSED : GuerillaBlock, IWriteDeferrable
    {
        public ValueTypeEnum ValueType;
        public BooleanValueEnum BooleanValue;
        public int IntegerValue;
        public float FpValue;
        public Moonfish.Tags.StringIdent TextValueStringId;
        /// <summary>
        /// This is text string associated with data when it has the value specified above.
        ///The string comes from the screen's string list tag.
        /// </summary>
        public Moonfish.Tags.StringIdent TextLabelStringId;
        public override int SerializedSize
        {
            get
            {
                return 20;
            }
        }
        public override int Alignment
        {
            get
            {
                return 4;
            }
        }
        public override System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> ReadFields(Moonfish.Guerilla.BlamBinaryReader binaryReader)
        {
            System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue = new System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer>(base.ReadFields(binaryReader));
            this.ValueType = ((ValueTypeEnum)(binaryReader.ReadInt16()));
            this.BooleanValue = ((BooleanValueEnum)(binaryReader.ReadInt16()));
            this.IntegerValue = binaryReader.ReadInt32();
            this.FpValue = binaryReader.ReadSingle();
            this.TextValueStringId = binaryReader.ReadStringIdent();
            this.TextLabelStringId = binaryReader.ReadStringIdent();
            return pointerQueue;
        }
        public override void ReadInstances(Moonfish.Guerilla.BlamBinaryReader binaryReader, System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue)
        {
            base.ReadInstances(binaryReader, pointerQueue);
        }
        public override void DeferReferences(Moonfish.Guerilla.LinearBinaryWriter writer)
        {
            base.DeferReferences(writer);
        }
        public override void Write(Moonfish.Guerilla.LinearBinaryWriter writer)
        {
            base.Write(writer);
            writer.Write(((short)(this.ValueType)));
            writer.Write(((short)(this.BooleanValue)));
            writer.Write(this.IntegerValue);
            writer.Write(this.FpValue);
            writer.Write(this.TextValueStringId);
            writer.Write(this.TextLabelStringId);
        }
        /// <summary>
        /// this is all obsolete
        /// </summary>
        public enum ValueTypeEnum : short
        {
            IntegerNumber = 0,
            FloatingPointNumber = 1,
            Boolean = 2,
            TextString = 3,
        }
        /// <summary>
        /// Enter the value in the box corresponding to the value type you specified above
        /// </summary>
        public enum BooleanValueEnum : short
        {
            FALSE = 0,
            TRUE = 1,
        }
    }
}
