//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moonfish.Guerilla.Tags
{
    using JetBrains.Annotations;
    using Moonfish.Tags;
    using Moonfish.Model;
    using System.IO;
    using System.Collections.Generic;
    using System.Linq;
    
    [JetBrains.Annotations.UsedImplicitlyAttribute(ImplicitUseTargetFlags.WithMembers)]
    [TagBlockOriginalNameAttribute("table_view_list_item_reference_block")]
    public partial class TableViewListItemReferenceBlock : GuerillaBlock, IWriteDeferrable
    {
        public TextFlags TableViewListItemReferenceTextFlags;
        public short CellWidth;
        private byte[] fieldpad = new byte[2];
        public Moonfish.Tags.Point BitmapTopleft;
        [Moonfish.Tags.TagReferenceAttribute("bitm")]
        public Moonfish.Tags.TagReference BitmapTag;
        public Moonfish.Tags.StringIdent StringId;
        public short RenderDepthBias;
        private byte[] fieldpad0 = new byte[2];
        public override int SerializedSize
        {
            get
            {
                return 28;
            }
        }
        public override int Alignment
        {
            get
            {
                return 4;
            }
        }
        public override System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> ReadFields(Moonfish.Guerilla.BlamBinaryReader binaryReader)
        {
            System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue = new System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer>(base.ReadFields(binaryReader));
            this.TableViewListItemReferenceTextFlags = ((TextFlags)(binaryReader.ReadInt32()));
            this.CellWidth = binaryReader.ReadInt16();
            this.fieldpad = binaryReader.ReadBytes(2);
            this.BitmapTopleft = binaryReader.ReadPoint();
            this.BitmapTag = binaryReader.ReadTagReference();
            this.StringId = binaryReader.ReadStringIdent();
            this.RenderDepthBias = binaryReader.ReadInt16();
            this.fieldpad0 = binaryReader.ReadBytes(2);
            return pointerQueue;
        }
        public override void ReadInstances(Moonfish.Guerilla.BlamBinaryReader binaryReader, System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue)
        {
            base.ReadInstances(binaryReader, pointerQueue);
        }
        public override void DeferReferences(Moonfish.Guerilla.LinearBinaryWriter queueableBinaryWriter)
        {
            base.DeferReferences(queueableBinaryWriter);
        }
        public override void Write(Moonfish.Guerilla.LinearBinaryWriter queueableBinaryWriter)
        {
            base.Write(queueableBinaryWriter);
            queueableBinaryWriter.Write(((int)(this.TableViewListItemReferenceTextFlags)));
            queueableBinaryWriter.Write(this.CellWidth);
            queueableBinaryWriter.Write(this.fieldpad);
            queueableBinaryWriter.Write(this.BitmapTopleft);
            queueableBinaryWriter.Write(this.BitmapTag);
            queueableBinaryWriter.Write(this.StringId);
            queueableBinaryWriter.Write(this.RenderDepthBias);
            queueableBinaryWriter.Write(this.fieldpad0);
        }
        [System.FlagsAttribute()]
        public enum TextFlags : int
        {
            None = 0,
            LeftJustifyText = 1,
            RightJustifyText = 2,
            PulsatingText = 4,
            CalloutText = 8,
            Small31CharBuffer = 16,
        }
    }
}
