//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moonfish.Guerilla.Tags
{
    using JetBrains.Annotations;
    using Moonfish.Tags;
    using Moonfish.Model;
    using System.IO;
    using System.Collections.Generic;
    using System.Linq;
    
    [JetBrains.Annotations.UsedImplicitlyAttribute(ImplicitUseTargetFlags.WithMembers)]
    [TagBlockOriginalNameAttribute("user_hint_jump_block")]
    public partial class UserHintJumpBlock : GuerillaBlock, IWriteQueueable
    {
        public Flags UserHintJumpFlags;
        public Moonfish.Tags.ShortBlockIndex1 GeometryIndex;
        public ForceJumpHeightEnum ForceJumpHeight;
        public ControlFlags UserHintJumpControlFlags;
        public override int SerializedSize
        {
            get
            {
                return 8;
            }
        }
        public override int Alignment
        {
            get
            {
                return 4;
            }
        }
        public override System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> ReadFields(Moonfish.Guerilla.BlamBinaryReader binaryReader)
        {
            System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue = new System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer>(base.ReadFields(binaryReader));
            this.UserHintJumpFlags = ((Flags)(binaryReader.ReadInt16()));
            this.GeometryIndex = binaryReader.ReadShortBlockIndex1();
            this.ForceJumpHeight = ((ForceJumpHeightEnum)(binaryReader.ReadInt16()));
            this.UserHintJumpControlFlags = ((ControlFlags)(binaryReader.ReadInt16()));
            return pointerQueue;
        }
        public override void ReadInstances(Moonfish.Guerilla.BlamBinaryReader binaryReader, System.Collections.Generic.Queue<Moonfish.Tags.BlamPointer> pointerQueue)
        {
            base.ReadInstances(binaryReader, pointerQueue);
        }
        public override void Defer(Moonfish.Guerilla.QueueableBlamBinaryWriter queueableBinaryWriter)
        {
            base.Defer(queueableBinaryWriter);
        }
        public override void Write(Moonfish.Guerilla.QueueableBlamBinaryWriter queueableBinaryWriter)
        {
            base.Write(queueableBinaryWriter);
            queueableBinaryWriter.Write(((short)(this.UserHintJumpFlags)));
            queueableBinaryWriter.Write(this.GeometryIndex);
            queueableBinaryWriter.Write(((short)(this.ForceJumpHeight)));
            queueableBinaryWriter.Write(((short)(this.UserHintJumpControlFlags)));
        }
        [System.FlagsAttribute()]
        public enum Flags : short
        {
            None = 0,
            Bidirectional = 1,
            Closed = 2,
        }
        public enum ForceJumpHeightEnum : short
        {
            NONE = 0,
            Down = 1,
            Step = 2,
            Crouch = 3,
            Stand = 4,
            Storey = 5,
            Tower = 6,
            Infinite = 7,
        }
        [System.FlagsAttribute()]
        public enum ControlFlags : short
        {
            None = 0,
            MagicLift = 1,
        }
    }
}
